### ISSUE TITLE
Add clippy integration test for aarch64

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1007]

**Comment by andreeaflorescu** [comment]
I cannot install clippy on aarch64. Apparently it didn't land in stable yet: https://github.com/rust-lang/rust-clippy/issues/3682

**Comment by dianpopa** [comment]
Seems like we can use `cargo clippy --target aarch64-unknown-linux-musl` on x86_64.

**Comment by dianpopa** [comment]
Raising priority on this one since more build warnings are now displayed after upgrade to 1.38 for aarch64.
