### ISSUE TITLE
Run integration & unit tests on AMD

### ISSUE THREAD

**Issue by ochescc** [firecracker-microvm/firecracker#1012]
List of tests that are currently failing on AMD:
- [x] #1016 
- [x] #1017
- [x] #1011

**Comment by serban300** [comment]
Here is the integration tests output on AMD:

[output.txt](https://github.com/firecracker-microvm/firecracker/files/2976719/output.txt)

**Comment by dianpopa** [comment]
All encompassing issues are fixed.
