### ISSUE TITLE
Install docker in the microVM/launch lambda function

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker#1028]
Has anyone tried installing docker in the microVM? I am following this guide: [here](https://wiki.alpinelinux.org/wiki/Docker) but I am getting a lot of error. I want to run the lambda function using SAM(serverlesss application model) but it needs docker as a pre-requisite.

This is the list of errors:
![docker](https://user-images.githubusercontent.com/8316863/54708854-4162cf80-4b12-11e9-851b-4fa1164044d6.png)

**Comment by andreeaflorescu** [comment]
Can you also provide the content of `/etc/apk/repositories` file? It looks like it cannot fetch docker from the repository that you added.

**Comment by Anjali05** [comment]
@andreeaflorescu 
localhost:~# cat /etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/v3.8/main
http://dl-cdn.alpinelinux.org/alpine/v3.8/community
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community

**Comment by niketagrawal** [comment]
What is the kernel and rootfs you used to create the microVM? Looks like docker failed to install in the first place due to insufficient size. The example rootfs given on the firecracker get started github page is too small in size to support installation of most software packages let alone docker. if you can share the disk usage of your microVM, that'll help. I guess I have understood the issue as I could just now reproduce a similar screenshot on my system because I already experienced it once before.

**Comment by Anjali05** [comment]
@niketagrawal 
![disk](https://user-images.githubusercontent.com/8316863/54711986-2ba4d880-4b19-11e9-8413-e22eb6763231.png)


Did you increase the RAM when starting the instance? I am using the  hello-vmlinux.bin kernel and xenial.rootfs.ext4(from the demo repo).

**Comment by niketagrawal** [comment]
@Anjali05 Yes, I did but that is different from rootfs where the applications get installed. The xenial.rootfs.ext4 too seems to have insufficient size. This isn't an issue exactly but more of a 'use the right configuration' case. This https://github.com/alpinelinux/alpine-make-rootfs might help to create a customized rootfs for alpine which may come handy. I haven't been able to try it yet myself though as I couldn't quite get the procedure. Maybe someone can further add to this if they have any alternatives?

**Comment by dhrgit** [comment]
You might run into some issues when trying to boot a microvm from a Docker image, since Docker images are not meant to be bootable (i.e. they lack an init system).

We have [a guide](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md) for creating rootfs and kernel images, where we are converting an Alpine Docker image into a bootable rootfs. That guide creates a 50 MiB rootfs image, so you'll need to increase that number to something that can accommodate everything you need to install on your rootfs.

**Comment by Anjali05** [comment]
@dhrgit 
I am not trying to boot a microvm from a docker image. I am trying to install docker inside an already running microVM. I want to run this, https://hub.docker.com/r/lambci/lambda-base  after that so that I can emulate lambda function locally inside the microVM.

**Comment by dhrgit** [comment]
@Anjali05 Apologies - I thought the guide @niketagrawal linked was about creating an Alpine-based container image.

As far as I understand, the problem was not having enough disk space on your rootfs. If you use a large enough rootfs, are you still unable to run Docker inside the microvm?

**Comment by Anjali05** [comment]
@dhrgit 
I was trying to build my own image from rootfs to increase the default size. I am getting read-only error in this step: for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done.

I tried changing the permission of the image after coping an empty file system on the file by running.
chmod 777 custom.xenial.rootfs.etx4

This is the error:

![rootfs](https://user-images.githubusercontent.com/8316863/54775757-9ff48000-4bdc-11e9-860f-1c3b3ab70566.png)

**Comment by oraoto** [comment]
I am running docker and k8s in firecracker with a custom kernel and rootfs based archlinux, [archlinux-firecracker](https://github.com/oraoto/archlinux-firecracker).

To increase the size of rootfs, you can use `resize2fs` in the host with the vm shutdowned.

**Comment by dhrgit** [comment]
@Anjali05 Looks like your fs image is mounted read-only. You need to mount the fs image read/write (the default for `mount`), then run the Alpine container with the directory where you mounted the fs image passed as a bind-mount. I.e.:

```bash
# Mount the fs image to /tmp/my-rootfs
mkdir /tmp/my-rootfs
sudo mount my-rootfs.ext4 /tmp/my-rootfs

# Pass the /tmp/my-rootfs dir to the container, as /my-rootfs
docker run -it --rm -v /tmp/my-rootfs:/my-rootfs alpine
```

**Comment by Anjali05** [comment]
@dhrgit 
I think what you are suggesting is the same in the guide [here](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md).

I followed it exactly but still got the error.

**Comment by Anjali05** [comment]
@dhrgit 
What will be the login for the new built image?

**Comment by dhrgit** [comment]
You should be able to login as root at the console (i.e. the stdin/stdout of the `firecracker` process), without a password. If that isn't working, you might have skipped the `securetty` setup:

```bash
echo ttyS0 > /etc/securetty
```

Our guide doesn't set up a root password. You can set one up by running `passwd` before copying the image files (the `tar c ... | tar x ...` step).

**Comment by Anjali05** [comment]
@dhrgit 
I tried all that but didn't work so I used the resize2fs tool. But even after increasing the size docker is not getting installed. I am getting the same error.

**Comment by Anjali05** [comment]
I was able to install docker but it seems to crash and I am not able to start it again. It also gave segmentation fault while running the hello-world image. Has anyone encountered such an issue?

**Comment by Anjali05** [comment]
This is the full error:

time="2019-03-31T20:02:17.356307093Z" level=warning msg="Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior" dir=/var/lib/docker error="error writing file to signal mount cleanup on shutdown: open /var/run/docker/unmount-on-shutdown: no such file or directory"
time="2019-03-31T20:02:17.357639411Z" level=info msg="libcontainerd: started new containerd process" pid=1225
time="2019-03-31T20:02:17.357797498Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-03-31T20:02:17.357811042Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-03-31T20:02:17.357945954Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-03-31T20:02:17.358034142Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-03-31T20:02:17.358203377Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001205b0, CONNECTING" module=grpc
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x559c47d43df6, 0x16)
	/usr/lib/go/src/runtime/panic.go:608 +0x74 fp=0x7fffbbac2b10 sp=0x7fffbbac2ae0 pc=0x559c4705d2c4
runtime.sysMap(0xc000000000, 0x4000000, 0x559c48e6f238)
	/usr/lib/go/src/runtime/mem_linux.go:156 +0xc9 fp=0x7fffbbac2b50 sp=0x7fffbbac2b10 pc=0x559c47048019
runtime.(*mheap).sysAlloc(0x559c48e55700, 0x4000000, 0x0, 0x0)
	/usr/lib/go/src/runtime/malloc.go:619 +0x1c9 fp=0x7fffbbac2bd8 sp=0x7fffbbac2b50 pc=0x559c4703bc89
runtime.(*mheap).grow(0x559c48e55700, 0x1, 0x0)
	/usr/lib/go/src/runtime/mheap.go:920 +0x44 fp=0x7fffbbac2c30 sp=0x7fffbbac2bd8 pc=0x559c47054514
runtime.(*mheap).allocSpanLocked(0x559c48e55700, 0x1, 0x559c48e6f248, 0x0)
	/usr/lib/go/src/runtime/mheap.go:848 +0x339 fp=0x7fffbbac2c70 sp=0x7fffbbac2c30 pc=0x559c47054399
runtime.(*mheap).alloc_m(0x559c48e55700, 0x1, 0x2a, 0x0)
	/usr/lib/go/src/runtime/mheap.go:692 +0x11d fp=0x7fffbbac2cb0 sp=0x7fffbbac2c70 pc=0x559c47053b9d
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:759 +0x4e fp=0x7fffbbac2ce8 sp=0x7fffbbac2cb0 pc=0x559c4708a1fe
runtime.(*mheap).alloc(0x559c48e55700, 0x1, 0x559c4701002a, 0x7fffbbac2d50)
	/usr/lib/go/src/runtime/mheap.go:758 +0x8c fp=0x7fffbbac2d38 sp=0x7fffbbac2ce8 pc=0x559c47053e3c
runtime.(*mcentral).grow(0x559c48e574b8, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:232 +0x96 fp=0x7fffbbac2d80 sp=0x7fffbbac2d38 pc=0x559c47047a06
runtime.(*mcentral).cacheSpan(0x559c48e574b8, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:106 +0x2fa fp=0x7fffbbac2dc8 sp=0x7fffbbac2d80 pc=0x559c4704755a
runtime.(*mcache).refill(0x7f42903e7000, 0x220000002a)
	/usr/lib/go/src/runtime/mcache.go:122 +0x99 fp=0x7fffbbac2df8 sp=0x7fffbbac2dc8 pc=0x559c47047119
runtime.(*mcache).nextFree.func1()
	/usr/lib/go/src/runtime/malloc.go:749 +0x34 fp=0x7fffbbac2e18 sp=0x7fffbbac2df8 pc=0x559c470895e4
runtime.(*mcache).nextFree(0x7f42903e7000, 0x559c48e6f22a, 0x4000, 0x7f42903e7000, 0x7fffbbac2ed8)
	/usr/lib/go/src/runtime/malloc.go:748 +0xb8 fp=0x7fffbbac2e70 sp=0x7fffbbac2e18 pc=0x559c4703c338
runtime.mallocgc(0x180, 0x559c48396ea0, 0x7fffbbac2f01, 0x7f42903eb000)
	/usr/lib/go/src/runtime/malloc.go:903 +0x7a5 fp=0x7fffbbac2f10 sp=0x7fffbbac2e70 pc=0x559c4703cc95
runtime.newobject(0x559c48396ea0, 0x559c48e6f2a0)
	/usr/lib/go/src/runtime/malloc.go:1032 +0x3a fp=0x7fffbbac2f40 sp=0x7fffbbac2f10 pc=0x559c4703d08a
runtime.malg(0x7f4200008000, 0x7f42903e7000)
	/usr/lib/go/src/runtime/proc.go:3285 +0x33 fp=0x7fffbbac2f80 sp=0x7fffbbac2f40 pc=0x559c47067783
runtime.mpreinit(0x559c48e4f9e0)
	/usr/lib/go/src/runtime/os_linux.go:311 +0x2b fp=0x7fffbbac2fa0 sp=0x7fffbbac2f80 pc=0x559c4705b6ab
runtime.mcommoninit(0x559c48e4f9e0)
	/usr/lib/go/src/runtime/proc.go:624 +0xc5 fp=0x7fffbbac2fd8 sp=0x7fffbbac2fa0 pc=0x559c47060f15
runtime.schedinit()
	/usr/lib/go/src/runtime/proc.go:546 +0x8d fp=0x7fffbbac3040 sp=0x7fffbbac2fd8 pc=0x559c47060bdd
runtime.rt0_go(0x7fffbbac30b8, 0x5, 0x7fffbbac30b8, 0x0, 0x7f42901b7ad6, 0x0, 0x7fffbbac30b0, 0x0, 0x7f429042ab88, 0x0, ...)
	/usr/lib/go/src/runtime/asm_amd64.s:195 +0x11e fp=0x7fffbbac3048 sp=0x7fffbbac3040 pc=0x559c4708c3de
time="2019-03-31T20:02:17.389673681Z" level=error msg="containerd did not exit successfully" error="exit status 2" module=libcontainerd
time="2019-03-31T20:02:27.358095802Z" level=error msg="failed connecting to containerd" error="failed to dial \"/var/run/docker/containerd/containerd.sock\": context deadline exceeded" module=libcontainerd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55563f4c2970]

goroutine 37 [running]:
github.com/docker/docker/vendor/github.com/containerd/containerd.(*Client).Close(0x0, 0x0, 0x0)
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/containerd/containerd/client.go:536 +0x30
github.com/docker/docker/libcontainerd/supervisor.(*remote).monitorDaemon(0xc00064e9c0, 0x55564057ebc0, 0xc000130040)
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:321 +0x24f
created by github.com/docker/docker/libcontainerd/supervisor.Start
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:90 +0x3b5
time="2019-03-31T20:04:16.528164026Z" level=info msg="libcontainerd: started new containerd process" pid=1374
time="2019-03-31T20:04:16.528406488Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-03-31T20:04:16.528417588Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-03-31T20:04:16.528536666Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-03-31T20:04:16.528557534Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-03-31T20:04:16.528597360Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001223d0, CONNECTING" module=grpc
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x55a9fc73bdf6, 0x16)
	/usr/lib/go/src/runtime/panic.go:608 +0x74 fp=0x7ffc62efdf30 sp=0x7ffc62efdf00 pc=0x55a9fba552c4
runtime.sysMap(0xc000000000, 0x4000000, 0x55a9fd867238)
	/usr/lib/go/src/runtime/mem_linux.go:156 +0xc9 fp=0x7ffc62efdf70 sp=0x7ffc62efdf30 pc=0x55a9fba40019
runtime.(*mheap).sysAlloc(0x55a9fd84d700, 0x4000000, 0x0, 0x0)
	/usr/lib/go/src/runtime/malloc.go:619 +0x1c9 fp=0x7ffc62efdff8 sp=0x7ffc62efdf70 pc=0x55a9fba33c89
runtime.(*mheap).grow(0x55a9fd84d700, 0x1, 0x0)
	/usr/lib/go/src/runtime/mheap.go:920 +0x44 fp=0x7ffc62efe050 sp=0x7ffc62efdff8 pc=0x55a9fba4c514
runtime.(*mheap).allocSpanLocked(0x55a9fd84d700, 0x1, 0x55a9fd867248, 0x0)
	/usr/lib/go/src/runtime/mheap.go:848 +0x339 fp=0x7ffc62efe090 sp=0x7ffc62efe050 pc=0x55a9fba4c399
runtime.(*mheap).alloc_m(0x55a9fd84d700, 0x1, 0x2a, 0x0)
	/usr/lib/go/src/runtime/mheap.go:692 +0x11d fp=0x7ffc62efe0d0 sp=0x7ffc62efe090 pc=0x55a9fba4bb9d
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:759 +0x4e fp=0x7ffc62efe108 sp=0x7ffc62efe0d0 pc=0x55a9fba821fe
runtime.(*mheap).alloc(0x55a9fd84d700, 0x1, 0x55a9fb01002a, 0x7ffc62efe170)
	/usr/lib/go/src/runtime/mheap.go:758 +0x8c fp=0x7ffc62efe158 sp=0x7ffc62efe108 pc=0x55a9fba4be3c
runtime.(*mcentral).grow(0x55a9fd84f4b8, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:232 +0x96 fp=0x7ffc62efe1a0 sp=0x7ffc62efe158 pc=0x55a9fba3fa06
runtime.(*mcentral).cacheSpan(0x55a9fd84f4b8, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:106 +0x2fa fp=0x7ffc62efe1e8 sp=0x7ffc62efe1a0 pc=0x55a9fba3f55a
runtime.(*mcache).refill(0x7f96c0127000, 0x220000002a)
	/usr/lib/go/src/runtime/mcache.go:122 +0x99 fp=0x7ffc62efe218 sp=0x7ffc62efe1e8 pc=0x55a9fba3f119
runtime.(*mcache).nextFree.func1()
	/usr/lib/go/src/runtime/malloc.go:749 +0x34 fp=0x7ffc62efe238 sp=0x7ffc62efe218 pc=0x55a9fba815e4
runtime.(*mcache).nextFree(0x7f96c0127000, 0x55a9fd86722a, 0x4000, 0x7f96c0127000, 0x7ffc62efe2f8)
	/usr/lib/go/src/runtime/malloc.go:748 +0xb8 fp=0x7ffc62efe290 sp=0x7ffc62efe238 pc=0x55a9fba34338
runtime.mallocgc(0x180, 0x55a9fcd8eea0, 0x7ffc62efe301, 0x7f96c012b000)
	/usr/lib/go/src/runtime/malloc.go:903 +0x7a5 fp=0x7ffc62efe330 sp=0x7ffc62efe290 pc=0x55a9fba34c95
runtime.newobject(0x55a9fcd8eea0, 0x55a9fd8672a0)
	/usr/lib/go/src/runtime/malloc.go:1032 +0x3a fp=0x7ffc62efe360 sp=0x7ffc62efe330 pc=0x55a9fba3508a
runtime.malg(0x7f9600008000, 0x7f96c0127000)
	/usr/lib/go/src/runtime/proc.go:3285 +0x33 fp=0x7ffc62efe3a0 sp=0x7ffc62efe360 pc=0x55a9fba5f783
runtime.mpreinit(0x55a9fd8479e0)
	/usr/lib/go/src/runtime/os_linux.go:311 +0x2b fp=0x7ffc62efe3c0 sp=0x7ffc62efe3a0 pc=0x55a9fba536ab
runtime.mcommoninit(0x55a9fd8479e0)
	/usr/lib/go/src/runtime/proc.go:624 +0xc5 fp=0x7ffc62efe3f8 sp=0x7ffc62efe3c0 pc=0x55a9fba58f15
runtime.schedinit()
	/usr/lib/go/src/runtime/proc.go:546 +0x8d fp=0x7ffc62efe460 sp=0x7ffc62efe3f8 pc=0x55a9fba58bdd
runtime.rt0_go(0x7ffc62efe4d8, 0x5, 0x7ffc62efe4d8, 0x0, 0x7f96bfef7ad6, 0x0, 0x7ffc62efe4d0, 0x0, 0x7f96c016ab88, 0x0, ...)
	/usr/lib/go/src/runtime/asm_amd64.s:195 +0x11e fp=0x7ffc62efe468 sp=0x7ffc62efe460 pc=0x55a9fba843de
time="2019-03-31T20:04:16.566690185Z" level=error msg="containerd did not exit successfully" error="exit status 2" module=libcontainerd
time="2019-03-31T20:04:26.529202400Z" level=error msg="failed connecting to containerd" error="failed to dial \"/var/run/docker/containerd/containerd.sock\": context deadline exceeded" module=libcontainerd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55d8a5c3f970]

goroutine 37 [running]:
github.com/docker/docker/vendor/github.com/containerd/containerd.(*Client).Close(0x0, 0x0, 0x0)
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/containerd/containerd/client.go:536 +0x30
github.com/docker/docker/libcontainerd/supervisor.(*remote).monitorDaemon(0xc0008d29c0, 0x55d8a6cfbbc0, 0xc00060a000)
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:321 +0x24f
created by github.com/docker/docker/libcontainerd/supervisor.Start
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:90 +0x3b5
time="2019-03-31T20:09:42.813825390Z" level=info msg="libcontainerd: started new containerd process" pid=1616
time="2019-03-31T20:09:42.814062353Z" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-03-31T20:09:42.814074707Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-03-31T20:09:42.816197177Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-03-31T20:09:42.816366960Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-03-31T20:09:42.817784036Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00091eef0, CONNECTING" module=grpc
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5588fa1b0df6, 0x16)
	/usr/lib/go/src/runtime/panic.go:608 +0x74 fp=0x7fffbc504340 sp=0x7fffbc504310 pc=0x5588f94ca2c4
runtime.sysMap(0xc000000000, 0x4000000, 0x5588fb2dc238)
	/usr/lib/go/src/runtime/mem_linux.go:156 +0xc9 fp=0x7fffbc504380 sp=0x7fffbc504340 pc=0x5588f94b5019
runtime.(*mheap).sysAlloc(0x5588fb2c2700, 0x4000000, 0x0, 0x0)
	/usr/lib/go/src/runtime/malloc.go:619 +0x1c9 fp=0x7fffbc504408 sp=0x7fffbc504380 pc=0x5588f94a8c89
runtime.(*mheap).grow(0x5588fb2c2700, 0x1, 0x0)
	/usr/lib/go/src/runtime/mheap.go:920 +0x44 fp=0x7fffbc504460 sp=0x7fffbc504408 pc=0x5588f94c1514
runtime.(*mheap).allocSpanLocked(0x5588fb2c2700, 0x1, 0x5588fb2dc248, 0x0)
	/usr/lib/go/src/runtime/mheap.go:848 +0x339 fp=0x7fffbc5044a0 sp=0x7fffbc504460 pc=0x5588f94c1399
runtime.(*mheap).alloc_m(0x5588fb2c2700, 0x1, 0x2a, 0x0)
	/usr/lib/go/src/runtime/mheap.go:692 +0x11d fp=0x7fffbc5044e0 sp=0x7fffbc5044a0 pc=0x5588f94c0b9d
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:759 +0x4e fp=0x7fffbc504518 sp=0x7fffbc5044e0 pc=0x5588f94f71fe
runtime.(*mheap).alloc(0x5588fb2c2700, 0x1, 0x5588f901002a, 0x7fffbc504580)
	/usr/lib/go/src/runtime/mheap.go:758 +0x8c fp=0x7fffbc504568 sp=0x7fffbc504518 pc=0x5588f94c0e3c
runtime.(*mcentral).grow(0x5588fb2c44b8, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:232 +0x96 fp=0x7fffbc5045b0 sp=0x7fffbc504568 pc=0x5588f94b4a06
runtime.(*mcentral).cacheSpan(0x5588fb2c44b8, 0x0)
	/usr/lib/go/src/runtime/mcentral.go:106 +0x2fa fp=0x7fffbc5045f8 sp=0x7fffbc5045b0 pc=0x5588f94b455a
runtime.(*mcache).refill(0x7ff33bf98000, 0x220000002a)
	/usr/lib/go/src/runtime/mcache.go:122 +0x99 fp=0x7fffbc504628 sp=0x7fffbc5045f8 pc=0x5588f94b4119
runtime.(*mcache).nextFree.func1()
	/usr/lib/go/src/runtime/malloc.go:749 +0x34 fp=0x7fffbc504648 sp=0x7fffbc504628 pc=0x5588f94f65e4
runtime.(*mcache).nextFree(0x7ff33bf98000, 0x5588fb2dc22a, 0x4000, 0x7ff33bf98000, 0x7fffbc504708)
	/usr/lib/go/src/runtime/malloc.go:748 +0xb8 fp=0x7fffbc5046a0 sp=0x7fffbc504648 pc=0x5588f94a9338
runtime.mallocgc(0x180, 0x5588fa803ea0, 0x7fffbc504701, 0x7ff33bf9c000)
	/usr/lib/go/src/runtime/malloc.go:903 +0x7a5 fp=0x7fffbc504740 sp=0x7fffbc5046a0 pc=0x5588f94a9c95
runtime.newobject(0x5588fa803ea0, 0x5588fb2dc2a0)
	/usr/lib/go/src/runtime/malloc.go:1032 +0x3a fp=0x7fffbc504770 sp=0x7fffbc504740 pc=0x5588f94aa08a
runtime.malg(0x7ff300008000, 0x7ff33bf98000)
	/usr/lib/go/src/runtime/proc.go:3285 +0x33 fp=0x7fffbc5047b0 sp=0x7fffbc504770 pc=0x5588f94d4783
runtime.mpreinit(0x5588fb2bc9e0)
	/usr/lib/go/src/runtime/os_linux.go:311 +0x2b fp=0x7fffbc5047d0 sp=0x7fffbc5047b0 pc=0x5588f94c86ab
runtime.mcommoninit(0x5588fb2bc9e0)
	/usr/lib/go/src/runtime/proc.go:624 +0xc5 fp=0x7fffbc504808 sp=0x7fffbc5047d0 pc=0x5588f94cdf15
runtime.schedinit()
	/usr/lib/go/src/runtime/proc.go:546 +0x8d fp=0x7fffbc504870 sp=0x7fffbc504808 pc=0x5588f94cdbdd
runtime.rt0_go(0x7fffbc5048e8, 0x5, 0x7fffbc5048e8, 0x0, 0x7ff33bd68ad6, 0x0, 0x7fffbc5048e0, 0x0, 0x7ff33bfdbb88, 0x0, ...)
	/usr/lib/go/src/runtime/asm_amd64.s:195 +0x11e fp=0x7fffbc504878 sp=0x7fffbc504870 pc=0x5588f94f93de
time="2019-03-31T20:09:42.844001759Z" level=error msg="containerd did not exit successfully" error="exit status 2" module=libcontainerd
time="2019-03-31T20:09:52.814409309Z" level=error msg="failed connecting to containerd" error="failed to dial \"/var/run/docker/containerd/containerd.sock\": context deadline exceeded" module=libcontainerd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55c55fae6970]

goroutine 37 [running]:
github.com/docker/docker/vendor/github.com/containerd/containerd.(*Client).Close(0x0, 0x0, 0x0)
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/vendor/github.com/containerd/containerd/client.go:536 +0x30
github.com/docker/docker/libcontainerd/supervisor.(*remote).monitorDaemon(0xc0008f29c0, 0x55c560ba2bc0, 0xc000907b00)
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:321 +0x24f
created by github.com/docker/docker/libcontainerd/supervisor.Start
	/home/buildozer/aports/community/docker/src/docker-18.09.1-ce/components/engine/.gopath/src/github.com/docker/docker/libcontainerd/supervisor/remote_daemon.go:90 +0x3b5

**Comment by aghecenco** [comment]
Hi @Anjali05, we haven't come across the kind of behavior you're describing; what's the latest status? Have you managed to get things running? If not, what exactly isn't working?

>  it seems to crash and I am not able to start it again

What crashes? Does something fail on the host or in the guest? Have you managed to log in on the guest after all?

> segmentation fault while running the hello-world image

Who gets the seg fault? Docker? Something else?

To make this issue easy to replicate, can you:
* share the rootfs you're using
* share the exact sequence of API calls into Firecracker you're using

**Comment by Anjali05** [comment]
@aghecenco 
You can close the issue.

**Comment by MadhavChoudhary** [comment]
Did anybody find a way to do this?
@Anjali05 I am working on a similar thing to benchmark firecracker and to test lambda functions.
Did you figure out something? Some help will be very much appreciated.

**Comment by Anjali05** [comment]
@MadhavChoudhary I found a docker image that runs lambda locally(https://github.com/lambci/docker-lambda). However, my docker keeps crashing in the microVM. I was able to install and run docker successfully the first time but on subsequent runs, it crashes.

**Comment by Aceysx** [comment]
It's there any update?
If i use the kernel and rootfs readme provide, install docker in firecracker will not work, right?

Did anybody  running docker in firecracker with a custom kernel and rootfs based on x86_64?

**Comment by serban300** [comment]
@Aceysx @Anjali05 @MadhavChoudhary 

`hello-rootfs.ext4` and `xenial.rootfs.ext4` are minimized images and are missing some things needed in order to install new packages. But if you create a new rootfs you should be able to install docker inside. You can create a new rootfs using roughly the following commands:

```
wget -c http://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/ubuntu-base-20.04-base-amd64.tar.gz

fallocate -l 1G rootfs.ext4
sudo mkfs.ext4 rootfs.ext4

mkdir /tmp/my-rootfs
sudo mount rootfs.ext4 /tmp/my-rootfs
sudo tar -xzvf ubuntu-base-20.04-base-amd64.tar.gz -C /tmp/my-rootfs
sudo umount /tmp/my-rootfs
```

I don't think you need a custom kernel. `hello-vmlinux.bin` should work.

**Comment by Anjali05** [comment]
Install http://www.issihosts.com/haveged/ on alpine and then try installing docker. Alpine does not generate enough entropy on start-up and docker needs randomness for some crypto stuff.

**Comment by MadhavChoudhary** [comment]
>  Install http://www.issihosts.com/haveged/ on alpine and then try installing docker. 
> 
> 
> 
> Refer to this issue: https://github.com/firecracker-microvm/firecracker-demo/issues/13

Thanks, that is exactly the problem.

**Comment by ashwin31** [comment]
> I am running docker and k8s in firecracker with a custom kernel and rootfs based on archlinux, [archlinux-firecracker](https://github.com/oraoto/archlinux-firecracker).
> 
> To increase the size of rootfs, you can use `resize2fs` in the host with the vm shutdowned.

do we have any such kernel for ubuntu?
