### ISSUE TITLE
Support Checkpoint/Restore in Firecracker

### ISSUE THREAD

**Issue by jtestard** [firecracker-microvm/firecracker#1035]
Checkpoint/Restore functionality exists in [Docker](https://github.com/docker/cli/blob/master/experimental/checkpoint-restore.md) and other container runtimes. 

It does not exist yet for [kata-containers](https://github.com/kata-containers/documentation/blob/master/Limitations.md#checkpoint-and-restore), but is planned.

Is there any plan to implement such functionality in firecracker?

**Comment by jtestard** [comment]
And as a follow up, could it be done using [KVM's own migration tools](https://www.linux-kvm.org/page/Migration#savevm.2Floadvm_to_an_external_state_file_.28using_pseudo-migration.29)

**Comment by iggy** [comment]
A docker runtime running inside firecracker could do that. I'll let one of the devs speak to whether it's a planned feature (I think the answer is very long from now if ever).

Regarding using KVM support for that, there's a lot of userspace code required for migration/save/restore. Qemu spent a long time getting that right (and it's still not perfect).

**Comment by raduweiss** [comment]
Added to the roadmap, see #1184.

**Comment by dianpopa** [comment]
Hi @jtestard ,

Firecracker added support for creating a snapshot of a microVM and later start a new one from that. This is still in developer preview but if you are interested you can read the details [here](https://github.com/firecracker-microvm/firecracker/blob/master/docs/snapshotting/snapshot-support.md#snapshotting-in-firecracker).
