### ISSUE TITLE
rootfs creation documentation is inaccurate

### ISSUE THREAD

**Issue by jeromegn** [firecracker-microvm/firecracker#1048]
Following [the guide](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md), I've not been to create a rootfs with the same configuration as the hello-rootfs.ext4 provided by the documentation.

There are a few things that are very different.

- The line `mkdir /my-rootfs/{dev,proc,run,sys,var}` only works with a shell that will expand these curly braces (like bash), but the default one in alpine is `sh`
- The alpine version used to create hello-rootfs.ext4 appears to be 3.8, that's a small documentation change but since 3.9 is out, that's the latest on docker hub.
- Missing a few packages, at least curl, iptables, openssh. These are present in hello-rootfs.ext4, but not in the instructions. Likely more packages I haven't tracked down yet.
- Lots of files are different, here's a gist with the diff between 2 mounted filesystems: https://gist.github.com/jeromegn/dd2fcfe5b2b8c439ac39e3054cb091d7 (I have installed curl in this case, but it was also missing curl and all the ca-certificates.) Some notable differences:

```
Files hello/etc/inittab and tmp/etc/inittab differ
# ...
Only in hello/etc/runlevels/boot: hostname
Only in hello/etc/runlevels/boot: sysfs
Only in hello/etc/runlevels/nonetwork: agetty.ttyS0
# ...
Only in hello/dev: console
Only in hello/dev: pts
Only in hello/dev: shm
# ...
Only in hello/: home
# ...
Only in hello/var: cache
Only in hello/var: empty
Only in hello/var: lib
Only in hello/var: local
Only in hello/var: lock
Only in hello/var: log
Only in hello/var: opt
Only in hello/var: run
Only in hello/var: spool
Only in hello/var: tmp
```

The lack of `/var/cache` (and others in `/var`) is preventing `apk` usage, I believe. It might also be a permissions thing.

I can try working on a PR to fix most of the issues, but it's hard to work backwards from a pre-built rootfs.

I think it'd be useful to be able to programmatically create the hello-rootfs.ext4 from scratch in a reproducible manner.

**Comment by MalteJ** [comment]
I'm currently working with those two scripts:

**alpine-make-rootfs.sh**
```
#!/bin/sh

apk add openrc
apk add util-linux

# Set up a login terminal on the serial console (ttyS0):
ln -s agetty /etc/init.d/agetty.ttyS0
echo ttyS0 > /etc/securetty
rc-update add agetty.ttyS0 default

# Make sure special file systems are mounted on boot:
rc-update add devfs boot
rc-update add procfs boot

# Then, copy the newly configured system to the rootfs image:
for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /new-rootfs; done
cd /new-rootfs
mkdir dev proc run sys var

# All done, exit docker shell
exit
```

**make.sh**
```
#!/bin/bash
set -e
set -x

TARGET=$1
SIZE_MB=$2

rm -f $TARGET
dd if=/dev/zero of=$TARGET bs=1M count=$SIZE_MB
mkfs.ext4 $TARGET

TEMPDIR=`mktemp -d`
mount $TARGET $TEMPDIR

docker pull alpine:latest
docker run -it --rm -v `pwd`:/tmp -v $TEMPDIR:/new-rootfs alpine:latest /tmp/alpine-make-rootfs.sh

umount $TEMPDIR
rm -rf $TEMPDIR
```

To build an image you need docker installed and then simply do:

    export TARGET_FILE=rootfs.ext4
    export FILESYSTEM_SIZE_MB=256
    sudo ./make.sh $TARGET_FILE $FILESYSTEM_SIZE_MB

I am no firecracker expert, but this works for me.
Feel free to use those two scripts to enhance the docs :)

**Comment by acatangiu** [comment]
I believe `hello-rootfs.ext4` was manually created and manually edited (incremental adds) over time and not automatically script-generated.

[This guide](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md) is just an example on how to create a rootfs.

I do like the idea of changing that script or adding another that would be used to generate each of the `rootfs`s used in the firecracker CI (integration tests). @jeromegn any contribution in this area is greatly appreciated.

**Comment by jeromegn** [comment]
@acatangiu Yes, that makes sense. I've been chatting on slack and people we're telling me that this guide was all there was to it.

I don't care as much anymore though. I thought my file structure was wrong, or my mounts or something like that. Turns out it's all about the [extremely low entropy available at boot time](https://github.com/firecracker-microvm/firecracker/issues/663).

**Comment by bbros-dev** [comment]
>  I've been chatting on slack and people we're telling me that this guide was all there was to it.

That was the impression I got from reading the docs.  Better to remove the docs rather than have misleading ones that turn your day into a time vacuum.

For others looking for more substantial guides that work:

1. Weaveworks Ignite project has:
    - [kernel builds](https://github.com/weaveworks/ignite/tree/master/images/kernel) by reading the code you can see exactly what is involved, and can run their code too.
   - [rootfs builds](https://github.com/weaveworks/ignite/tree/master/images)

**Comment by HQ01** [comment]
Interested to help out!

**Comment by serban300** [comment]
Hi @HQ01 ! Thanks for the interest in Firecracker ! I saw you posted on multiple issues. All seem available. I would recommend to chose one that is marked with the "Good first issue" tag as a starting point. Please let us know which one you prefer and depending on the issue we can discuss next steps.

**Comment by HQ01** [comment]
Hi @serban300, thanks for the reply! To provide you with more context, we are 4 students in UT Austin's virtualization class, and look forward to contributing to an open-source project as part of our coursework -- Firecracker really attracts us as an exciting project to work on :) We will start from relatively simple issues, but hopefully we can fix them all one by one. Any pointer to documentation/guide for new contributors will be really appreciated!

**Comment by HQ01** [comment]
Hi @serban300! I read through the discussion but not sure what are expected to be fixed here. Is the issue the rootfs created in the current guide cannot be used by Firecracker, or it's different from the example hello-rootfs?  I agreed that if hello-rootfs.ext4 was manually created, it's not sustainable to create a script to generate it.

**Comment by alindima** [comment]
We now have scripts that automate rootfs creation in devtool: https://github.com/firecracker-microvm/firecracker/blob/ded133601265d0f15f0d461c63b89d83c509e428/tools/devtool#L2040
