### ISSUE TITLE
Replace deprecated std::mem::zeroed

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1060]
`std::mem::zeroed` has a deprecation tag that shows up in the IDE.

[Source](https://github.com/rust-lang/rust/blob/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/mem.rs#L503):
```rust
#[rustc_deprecated(since = "2.0.0", reason = "use `mem::MaybeUninit::zeroed` instead")]
#[stable(feature = "rust1", since = "1.0.0")]
pub unsafe fn zeroed<T>() -> T {
```

Firecracker should switch to the suggested `std::mem::MaybeUninit::zeroed` instead of `std::mem::zeroed`, used in several places.

**Comment by hermesespinola** [comment]
Can I take this? This seems like a great first contribution to the project 😄.

**Comment by andreeaflorescu** [comment]
@hermesespinola I believe MaybeUnit is not yet in Rust stable, we might want to wait a bit before doing the switch. We can guide you to other good first issues if you're interested in a PR :) let us know!

**Comment by hermesespinola** [comment]
@andreeaflorescu Yes, that would be great!

**Comment by aghecenco** [comment]
Closing until `MaybeUninit` is stable and `zeroed` is *actually* deprecated.
