### ISSUE TITLE
The `kernel` crate doesn't need a dependency to the `memory_model` crate

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1067]

**Comment by aghecenco** [comment]
I half disagree. To elaborate:
* I think the `kernel` crate is logically tied to a memory-related crate. What else are you supposed to load it in? I don't see a use case where someone would need the `kernel` crate without underlying memory support.
* Regarding the memory-related crate: `memory_model` might indeed not be the ideal one. I think it would make sense for `kernel` to depend on the "front-end" memory model implemented in https://github.com/rust-vmm/vm-memory - it would pull in (as dependencies) the light crate that defines memory accessor traits, leaving the heavy lifting to whichever back-end we want to plug in it.
