### ISSUE TITLE
Create utils method for checking guest cmd output in the integration tests

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1068]
In the integration tests there are multiple functions that execute a command on the guest and then compare the output with some expected values. Like [this one](https://github.com/firecracker-microvm/firecracker/blob/b8550cc749227565ad1e13ae4b99821c98239e94/tests/integration_tests/functional/test_cpu_features.py#L37)

Create one `utils` method that does this and call it when needed instead of having a couple of similar methods scattered throughout the integration tests.

See the comment [here](https://github.com/firecracker-microvm/firecracker/pull/1052#discussion_r277235971)

**Comment by andreeaflorescu** [comment]
@serban300 your link goes to "We went looking everywhere, but couldn’t find those commits.". Please add a proper description for this issue.

**Comment by sri-srikanth** [comment]
Hey!
I am a Computer Science student at the University of Texas at Austin taking a Virtualization course. Myself and my two groupmates were wondering if we could contribute to resolving this issue. Please let me know if this would be possible and we can get started.

**Comment by dhriti-rajan** [comment]
Hello! My name's Dhriti, I'm currently taking the CS 360V Virtualization course at UT Austin. One of our projects for the class is to work on an issue in an open-source repository, and this repository looked pretty cool. Would it be alright if I worked on this issue?
