### ISSUE TITLE
Remove arm cross compilation test from CI

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1078]
Once the CI is sucessfully run on arm instances, we need to remove any cross compilation tests taking place right now.
This also implies removing any dependencies from Dockerfile and docker image/tag (i.e libfdt).

**Comment by andreeaflorescu** [comment]
If we remove the cross compilation test, we should also remove the linker options from .cargo/config and aarch64-linux-gnu-gcc from the Dockerfile.

**Comment by dianpopa** [comment]
This issue refers to removing anything that was related to cross compiling arm on x86_64.

**Comment by andreeaflorescu** [comment]
@dianpopa I agree, I just added the comment so we don't forget about it.
