### ISSUE TITLE
SendCtrlAltDel command not working as expected

### ISSUE THREAD

**Issue by vitcozzolino** [firecracker-microvm/firecracker#1081]
I have compiled a custom kernel (I followed this tutorial [link](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md)) with the required options to enable the `SendCtrlAltDel` command but it doesn't work, the command is not recognized. I just receive back the following:

`"fault_message": "unknown variant FlushMetrics, expected BlockDeviceRescan or InstanceStart at line 2 column 42"`

Support for atkbd and i8042 is added to the kernel image during the compilation stage, as I can see from these stdout lines:

`CC      drivers/input/keyboard/atkbd.o`
`CC      drivers/input/serio/i8042.o`

But when I boot the microVM I see in dmesg the following:

`[    0.770500] i8042: Can't read CTR while initializing i8042`
`[    0.771174] i8042: probe of i8042 failed with error -5`

and the output from `dmesg | grep -i atkbd` is blank.

I attached my edited .config file [config.txt](https://github.com/firecracker-microvm/firecracker/files/3142368/config.txt)

**Comment by dianpopa** [comment]
@vitcozzolino are you still experiencing this issue?
If yes, can you please copy paste the exact API requests that you are using for starting the microVM?

**Comment by dhrgit** [comment]
Closing as not reproducible. Please reopen if necessary.
