### ISSUE TITLE
Firecracker scheduler

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker#1084]
How does scheduling work in firecracker? Is there anyway to pin a firecracker instance to a particular core? If so, how?

**Comment by petreeftime** [comment]
I believe this could be done via the jailer, which uses cgroups to set affinity, however, at the moment it only seems capable of pinning the vCPUs to a specific NUMA node.

**Comment by aghecenco** [comment]
Hi @Anjali05, @petreeftime 's answer pretty much wraps it up - you can pin to a NUMA node (see [the jailer documentation](https://github.com/firecracker-microvm/firecracker/blob/master/docs/jailer.md) and the [cgroups-related code](https://github.com/firecracker-microvm/firecracker/blob/master/jailer/src/cgroup.rs) for details). This is done the same way as using [`numactl`](https://linux.die.net/man/8/numactl).
