### ISSUE TITLE
Firecracker does not load 32bit kernels

### ISSUE THREAD

**Issue by petreeftime** [firecracker-microvm/firecracker#1092]
When trying to load a 32bit kernel I am getting the following message: `"fault_message": "Cannot load kernel due to invalid memory configuration or invalid kernel image. Invalid ELF program header size"`.

32bit kernels are generally quite a bit smaller than 64bit kernels (and so is the userspace), so using a 32bit kernel could reduce memory usage when you don't need more than 4GB of memory for a VM. (eg. 4,5M vs 16M kernel binary size for an equivalent configuration).

**Comment by raduweiss** [comment]
Until we see a clear use case come along, I looks like the combination between 64bit Linux kernels and the various uni-kernels that work with Firecracker meets users' needs.

**Comment by iMilnb** [comment]
I doubt this use case will bring a lot of attention, but being able to run _i386_ kernels would permit to launch NetBSD with Firecracker, as NetBSD/amd64 doesn't support the multiboot 1 protocol and as such will not start with the `-kernel` parameter.
