### ISSUE TITLE
Enforce timeouts on API request durations in vsock builds

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1096]
As of #1091, API requests are no longer timed in vsock-enabled Firecracker builds (the test itself will time out if an API takes more than the default timeout value though). This can make it harder to detect regressions with vsock. Once vsock is stable, API requests should be timed again.

**Comment by dianpopa** [comment]
Vsock is now stable and the [`untime`](https://github.com/firecracker-microvm/firecracker/pull/1176/commits/b5052635cf2b4a5ade88752742ea1215da90e8f0#diff-ea89e5a5223068896a61a847ef21314eL252) does not apply for vsock anymore.
