### ISSUE TITLE
FAQ: document  "Resource busy" (errno 16) error when another hypervisor locks /dev/kvm

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1109]
If another hypervisor (e.g. Virtualbox / VMWare) locks `/dev/kvm`, Firecracker will fail to start with:

```
Firecracker panicked at 'Cannot create VMM: Error opening VM fd: VmFd(Os { code: 16, kind: Other, message: "Resource busy" })', src/libcore/result.rs:1009:5
```

Terminating the other hypervisor allows Firecracker to start.

This problem has popped up before (see [this issue with qemu](https://github.com/CanonicalLtd/multipass/issues/6) among others) and should be documented in the FAQ.

**Comment by Akasurde** [comment]
resolved_by_pr #1483
