### ISSUE TITLE
Set /sys/hypervisor/uuid?

### ISSUE THREAD

**Issue by luxas** [firecracker-microvm/firecracker#1120]
It seems like `/sys/hypervisor/uuid` is not set by Firecracker. Is this expected or not?

Thank you for your answer!

**Comment by andreeaflorescu** [comment]
@luxas we didn't really think about this so far. Do you have a usecase for which you need the hypervisor uuid to be set?

**Comment by luxas** [comment]
@andreeaflorescu some software seem to read it to keep track of machines

**Comment by andreeaflorescu** [comment]
@luxas Is the expected value there KVM?

**Comment by luxas** [comment]
I think the KVM implementation can populate it?

**Comment by andreeaflorescu** [comment]
@luxas I looked a bit at the kernel code and it doesn't look like the appropriate entries are populated by KVM. I also found [this patch](https://patchwork.kernel.org/patch/10632185/) which should add support for populating `/sys/hypervisor/uuid` with KVM, but it doesn't look like it was merged.

What other hypervisors are you using that properly set `/sys/hypervisor/uuid`? I am trying to understand if we can work around this issue.

**Comment by luxas** [comment]
> I also found this patch which should add support for populating /sys/hypervisor/uuid with KVM, but it doesn't look like it was merged.

Yeah, saw that too...

> What other hypervisors are you using that properly set /sys/hypervisor/uuid?

I don't remember all places I've seen it, but a couple.
However, this is not a big issue for me, I worked around it in other ways on my side.
Thanks for your time!
