### ISSUE TITLE
Remove json-patch dependency

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1122]
We are using the json-patch crate for the mmds functionality to merge two jsons. However, we can avoid this dependency as per  [suggestion](https://stackoverflow.com/questions/47070876/how-can-i-merge-two-json-objects-with-rust).

**Comment by hermesespinola** [comment]
Can I take this issue?
I get the idea is to remove the `json-patch` dependency and instead implement a utility function to perform a merge patch, while still being [RFC 7396](https://tools.ietf.org/html/rfc7396) compliant. There's a reference to the `json-patch` dependency in  the [docs/mmds.md](https://github.com/firecracker-microvm/firecracker/blob/87c46e34b12efdcd1aaa7b38fae15cae2d8dd93d/docs/mmds.md#L48), maybe that doc will need to be updated as well.

**Comment by raduweiss** [comment]
Sure, go ahead!

**Comment by andreeaflorescu** [comment]
Fixed by #1151
