### ISSUE TITLE
Remove chrono crate dependency

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1123]
We are using the `chrono` crate to get `chrono::Utc::now()` and then transform the result to `timestamp_nanos()` that will later be used to calculate a duration. 
We can do that with `time::get_time()` which will return a `Timespec` containing seconds and nanoseconds. So no further processing will be required. Investigate also if SteadyTIme::now` may be a better option.

The nice thing about this is that we will be removing 3-4 crate dependencies.

**Comment by andreeaflorescu** [comment]
This seems related to: https://github.com/firecracker-microvm/firecracker/issues/537. Maybe we can do it both in one go.
