### ISSUE TITLE
[CI] Deny warnings on build & unit tests

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1129]
We should update the build tests to not allow warnings as they are very easy to miss. This can be done by using `cargo rustc -- -D warnings` instead of `cargo build`.

**Comment by dianpopa** [comment]
Currently clippy integration test will fail if warnings are found inside build code.
However, due to a misuse of its parameters, clippy will not run on unit tests.
#1131 should fix this.

**Comment by dianpopa** [comment]
Fixed by #1131.
