### ISSUE TITLE
Use `KVM_CAP_MANUAL_DIRTY_LOG_PROTECT` when getting dirty log

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1132]
It looks like `KVM_CAP_MANUAL_DIRTY_LOG_PROTECT` was introduced in the Linux Kernel version 5.0. In Firecracker we currently use `KVM_GET_DIRTY_LOG` which has two problems as described in the [patch](https://lkml.org/lkml/2018/11/28/738) that introduces manual dirty log:
- it can report false positives
- it has a performance impact

For kernel versions > 5.0 we should use `KVM_CAP_MANUAL_DIRTY_LOG_PROTECT` instead.

**Comment by aghecenco** [comment]
From my understanding, `KVM_GET_DIRTY_LOG` will no longer reset the dirty bitmap with this cap enabled, but we'd need to manually call the newly introduced `KVM_CLEAR_DIRTY_LOG`. I don't understand the benefit this would bring...? We'd need a new ioctl to solve a problem I'm not sure we have:
```
Second, in some cases a large amount of time can pass between a call to
KVM_GET_DIRTY_LOG and userspace actually using the data in the page.
```
This doesn't affect Firecracker, we only retrieve the dirty log to count the dirtied pages and don't care about the contents.

*(Also, we'd need to check how a Firecracker built on kernel 5.0+ handles capabilities not present in kernels <5.0 at runtime - I expect the iotctl will fail, check should it out).*

**Comment by andreeaflorescu** [comment]
@aghecenco as you pointed out we will need to do a manual reset. From my understanding the problem we do have is the false positives (aka the report of the dirty bits is not necessarily accurate). The scenario in which this happens is detailed in the patch as well:
```
  1. KVM_GET_DIRTY_LOG returns a set of dirty pages and write protects
     them.
  2. The guest modifies the pages, causing them to be marked ditry.
  3. Userspace actually copies the pages.
  4. KVM_GET_DIRTY_LOG returns those pages as dirty again, even though
     they were not written to since (3).
```

There are also reports that kvm_get_dirty_log has a significant performance impact, so we should at least check if this new approach is more efficient. I couldn't find numbers for kvm guest with vs without dirty log enabled and probably we need to have our own numbers before we decide if this is an optimization we want to have. There are some numbers for dirty log with write protection vs with PML: https://www.spinics.net/lists/kvm/msg112904.html and https://os.itec.kit.edu/downloads/ba_2016_sch%c3%b6tterl-glausch_PML_for_Lightweight_Continuous_Checkpointing.pdf

A bit more context: I started looking into this because we actually used `KVM_GET_DIRTY_LOG` as we didn't find a better mechanism to measure the working set of a VM as per this PR description: https://github.com/firecracker-microvm/firecracker/pull/541.

For these reasons I think this is something worth investigating. After the investigation we can decide if we want to switch to it or not.

**Comment by aghecenco** [comment]
Firecracker doesn't adhere to that scenario because it doesn't do `3.`. The pages aren't touched by userspace (clarification for posterity, in the patch description, `userspace` refers to *host* userspace, while the guest is referred to as `guest`). So false positives because of userspace tampering don't happen.

I agree on the second point, we should compare performance numbers for "vanilla" `KVM_GET_DIRTY_LOG` vs `KVM_CAP_MANUAL_DIRTY_LOG_PROTECT + KVM_GET_DIRTY_LOG + KVM_CLEAR_DIRTY_LOG` and pick the winner. I'd say it's low priority because the metric isn't used all that much afaik.

**Comment by aghecenco** [comment]
#1531 deprecates this issue.
