### ISSUE TITLE
Fix `test_signal_handler`

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1141]
We should find a method to check that the SIGBUS handler left the process alive.
```vmm/src/signal_handler.rs:193:9```

**Comment by andreeaflorescu** [comment]
One idea is to add a metric on SIGBUS similar to `METRICS.seccomp.num_faults` and check the value of it. With `#[cfg(test)]` the SIGBUS handler does not exit because all `vmm` unit tests run in one process  and it would cause `cargo test` to exit abruptly.

**Comment by aghecenco** [comment]
As the signal handling functionality cannot be fully tested from unit tests, this will need a new integration test instead.

**Comment by alindima** [comment]
We now have integration tests for all handled signals, including SIGBUS, checking the metrics and logs
