### ISSUE TITLE
Investigate if we can optimize memory ocupied by enums

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1142]
As per clippy: "Enum size is bounded by the largest variant. Having a large variant can penalize the memory layout of that enum."

We have a few of these enums:
- ParsedRequest
- VmmAction

**Comment by acatangiu** [comment]
Each instantiated enum object has the size of its largest variant. Inefficiencies occur when enum variants considerably differ in size.

The only remaining `allow(clippy::large_enum_variant)` in the Firecracker codebase is on `ParsedRequest`, everything else looks good.
