### ISSUE TITLE
Improve aarch64 filesystem image hygene

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1144]
The following lines are printed by dmesg when booting on aarch64 with the ubuntu_with_ssh image:
```
[    0.865342] fff
[    0.865346] aaaa 0
[    0.873568] aaaa 0
[    0.883017] aaaa 0
[    0.892489] aaaa 0
[    0.901964] aaaa 0
[    0.912685] aaaa 0
[    0.922161] aaaa 0
[    0.931688] bbb 0 irq 9
[    0.941138] cc 0 irq 9 name 
[    0.952661] lll
[    0.966234] fffi 0
```
These look like they were somehow added when creating the filesystem image.

Also these ones:
```
[    1.845193] tun: Universal TUN/TAP device driver, 1.6
[    1.879417] probe
[    1.879447] adada
```

**Comment by sandreim** [comment]
These are debug prints from previous kernel debugging sessions. Somehow that kernel image was uploaded to S3 before removing these. I'll update the kernel image with PR #1233.

**Comment by sandreim** [comment]
Updated S3 images.
