### ISSUE TITLE
Compile zbud into the kernel used for running aarch64 tests

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1145]
Missing module causes the following warnings when booting on aarch64:
```
[    2.353087] zswap: default zpool zbud not available
[    2.386900] zswap: pool creation failed
```

**Comment by petreeftime** [comment]
This indicates zswap is already compiled, but the default pool is not created. This likely means zbud is not compiled or zswap needs some additional boot parameters. Removing zswap completely for the tests is likely a better option IMO.

**Comment by andreeaflorescu** [comment]
Indeed, zbud is not compiled. I'll also update the issue name.
@petreeftime Why do you say we should disable it?

**Comment by petreeftime** [comment]
swap/zswap are not completely deterministic and might influence performance. The effect from zswap will likely be small, but the small variations might cause performance tests to be flaky if they're set very ambitiously.
