### ISSUE TITLE
Serial Console does not show login on aarch64

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1147]
The serial console on aarch64 does not show the login prompt. It seems like it gets stuck before that. I am using the root filesystem, kernel image and boot arguments specified in [getting started](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-firecracker) for aarch64.

[dmesg_aarch64.txt](https://github.com/firecracker-microvm/firecracker/files/3311395/dmesg_aarch64.txt)

**Comment by sandreim** [comment]
So far I've got the login prompt to show after boot, but serial input is not working yet. Below is the list of changes:

The 8250 port is not detected by the guest. I've recompiled the guest kernel with CONFIG_SERIAL_OF_PLATFORM=y and the port is now initialized at boot:
```
[    0.093862] console [ttyS0] disabled
[    0.093903] 40003000.serial: ttyS0 at MMIO 0x40003000 (irq = 7, base_baud = 230400) is a 8250
[    0.756726] console [ttyS0] enabled
```

Changed the earlycon cmd line parameters to: `uart8250,mmio8,0x{:08x}`.
Changed the uart irq trigger to IRQ_TYPE_EDGE_RISING.

The guest is receiving interrupts only for the TX side:
```
root@fadfdd4af58a:~# cat /proc/interrupts
           CPU0
  4:       1413     GICv3  27 Level     arch_timer
  6:        886     GICv3  64 Edge      virtio0
  7:        666     GICv3  66 Edge      ttyS0
  8:        238     GICv3  65 Edge      virtio1
  9:          0     GICv3  67 Level     rtc-pl031
IPI0:         0       Rescheduling interrupts
IPI1:         0       Function call interrupts
IPI2:         0       CPU stop interrupts
IPI3:         0       CPU stop (for crash dump) interrupts
IPI4:         0       Timer broadcast interrupts
IPI5:         0       IRQ work interrupts
IPI6:         0       CPU wake-up interrupts
Err:          0
```

The host stdin is pumping input into the emulated uart buffer, but the IER_RECV_BIT is not set in the interrupt enable register by the guest driver, so it never gets an interrupt and read any data.

Next steps: Further debug the kernel 8250 driver and firecracker emulation.
