### ISSUE TITLE
Remove deserialize macro from `TokenBucket`

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1166]
The rate limiter is configured using `TokenBucketConfig` structures. From these structures we create `TokenBucket` objects which contain the so called "live" objects which can be modified as the VMM is running. Since TokenBucket cannot and should not be updated via the API, we should remove the `Deserialize` derive as well as all the other serde related macros.

**Comment by tamionv** [comment]
PR #1170 fixed this issue.
