### ISSUE TITLE
Use separate structures for API and VMM

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1167]
We currently use one structure for both the API and the VMM. The structures are defined in [vmm_config](). The problem associated with this design is that we have multiple configuration structures that are not really holding just the configuration, but also live objects like files, tap devices and others. Live objects cannot be automatically serialized/deserialized so we end up implementing custom ser-de or skip the fields that hold live objects. This further complicates things because besides the `..Config` structures we also have `Virtio..` structures, but there is no (easy) way of mapping a `..Config` object to the `Virtio..` object that was created from the specific configuration.

To better understand the separation between static and live objects, let's take as an example the [`TokenBucket`](https://github.com/firecracker-microvm/firecracker/blob/de058a6fa9dc1b5eb45d3a4e9d4d98743536ee84/rate_limiter/src/lib.rs#L92). The Rate Limiter already uses two structures: one configuration structure (part of the public interface of the VMM) and one live structure (part of the implementation of the VMM and should not be  publicly exported):
- `TokenBucketConfig` with fields that can be configured via the API (either the HTTP server or something else). The `..Config` structures would have a 1:1 mapping to the [swagger definition](https://github.com/firecracker-microvm/firecracker/blob/de058a6fa9dc1b5eb45d3a4e9d4d98743536ee84/api_server/swagger/firecracker.yaml#L584).
```rust
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TokenBucketConfig {
    // Bucket defining traits.
    size: u64,
    // Initial burst size (number of free initial tokens, that can be consumed at no cost)
    one_time_burst: Option<u64>,
    // Complete refill time in milliseconds.
    refill_time: u64,
}
```
- `TokenBucketConfig` created by the VMM using the `TokenBucketConfig`:
```rust
pub struct TokenBucket {
    config: TokenBucketConfig,
    // Internal state descriptors.
    budget: u64,
    last_update: u64,

    // Fields used for pre-processing optimizations.
    processed_capacity: u64,
    processed_refill_time: u64,
}
```

P.S. The TokenBucket does not look exactly like in this example at the moment as we have some left over serde macros which should be removed when fixing https://github.com/firecracker-microvm/firecracker/issues/1166

For `..Config` objects that are used for creating `Virtio..` structures the design is a bit more complicated and should be properly scoped.

**Comment by tamionv** [comment]
The configurations currently no longer hold any live objects (due to PR #1284); still we do not have the separation that is mentioned here. We should discuss about whether this is still something we want to do.

**Comment by georgepisaltu** [comment]
We'll pick this up if/when we do an API revamp for v2.0.0.

**Comment by ShadowCurse** [comment]
Closing as this issues no longer exists.
