### ISSUE TITLE
[Hardening] Seccomp improvements

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#1177]
The current way our seccomp filters are set up can be improved.

Issues included in this bundle:
- [x] #1178
- [x] #1088
- [x] #485
- [x] #1366 
- [x] #1475

**Comment by alindima** [comment]
Improvements are being developed on the `feature/file_based_seccomp` branch. This issue will be closed once we merge it into mainline

**Comment by alindima** [comment]
The feature branch was merged in main and will be released in v0.25.0. Will close this issue once we release it

**Comment by dianpopa** [comment]
v0.25.0 was released.
