### ISSUE TITLE
Seccomp: apply different filters depending on thread

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1178]
We currently apply the same filters on all threads. We should have separate filters based on the purpose of threads:
- VMM thread
- API thread
- vCPU threads

**Comment by mi-yu** [comment]
Hi @andreeaflorescu, thanks for your response on #1366! Could @pyrito and I get assigned to this one as well?

**Comment by andreeaflorescu** [comment]
@mi-yu are you still interested in this issue?

**Comment by mi-yu** [comment]
I have an implementation that is based on the changes in #1431 but of course those changes are very tentative. Feel free to assign to others!

**Comment by alindima** [comment]
Implemented by: https://github.com/firecracker-microvm/firecracker/pull/2557
