### ISSUE TITLE
Support running the Jailer inside of a container

### ISSUE THREAD

**Issue by luxas** [firecracker-microvm/firecracker#1185]
As written in https://github.com/firecracker-microvm/firecracker/issues/813#issuecomment-511434917:

> It'd be very nice to make it possible for the jailer to not do a specific set of things (e.g. the chroot, cgroups, maybe the numa node stuff), to let higher-level tools like Ignite run Firecracker in a container (like we do), but also run the jailer there to filter syscalls, reassign uid/gid, etc. Letting the container runtime take care of the cgroups, chroot, netns and similar and the jailer take care of syscall filtering would be a very good split of responsibilities IMO.

xref related Ignite issue weaveworks/ignite#68 (comment)

cc @raduweiss

**Comment by andreeaflorescu** [comment]
Hey @luxas the Firecracker code has changed a bit in the meantime and now the seccomp filters are applied in firecracker and not in jailer.

The current responsibilities of the jailer are:
1. numa node assignment
2. GID & UID assignment
3. network namespaces
4. create chroot
5. create cgroups
6. drop privileges and exec into firecracker

From what I understand you would like the ability to opt-out from some of these. Which ones specifically are you referring to? I am trying to understand if it makes sense to provide "simplified" jailer in the case where most of these are already done by high-level tools like Ignite.

**Comment by andreeaflorescu** [comment]
cc: @alexandruag

**Comment by luxas** [comment]
> seccomp filters are applied in firecracker

Awesome! Is that included in v0.17.0?

> network namespaces
> create chroot
> create cgroups

These three are done by any container runtime, right?

> numa node assignment

Why do you assign it to a numa node?

> GID & UID assignment

This _could_ be useful when/if the container must have `uid=0` for e.g. calling `mount`, but we want to change uid/gid later before spawning FC.

> drop privileges and exec into firecracker

What privileges are you dropping?

**Comment by andreeaflorescu** [comment]
> > seccomp filters are applied in firecracker
> 
> Awesome! Is that included in v0.17.0?

Yes. The seccomp filters can be specified with ```--secomp-level```. By default the advanced filtering is used.

> > network namespaces
> > create chroot
> > create cgroups
> 
> These three are done by any container runtime, right?

I don't really know how container runtimes work, but I would assume that's what they do.

> > numa node assignment
> 
> Why do you assign it to a numa node?

On large machines you have multiple numa nodes. When you are running Firecracker you want to force that both memory and the CPUs end up on the same numa node for performance reasons. The memory access time is relative to the distance between the processor and the memory. 

> > GID & UID assignment
> 
> This _could_ be useful when/if the container must have `uid=0` for e.g. calling `mount`, but we want to change uid/gid later before spawning FC.
> > drop privileges and exec into firecracker
> 
> What privileges are you dropping?

This code that changes the uid and guid is rather trivial, so I would not have a special jailer just to handle it. It is basically just calling chown and when executing firecracker, it is setting the UID and GUID of the process. Nothing fancy there.

Regarding the privileges: the jailer needs elevated privileges to create the chroot, cgroups and others. After doing all the setup, the jailer execs into firecracker, but firecracker runs as the user specified in `--uid```. That's what I meant with "drop privileges".

**Comment by luxas** [comment]
> Yes. The seccomp filters can be specified with --secomp-level. By default the advanced filtering is used.

Awesome!

> On large machines you have multiple numa nodes. When you are running Firecracker you want to force that both memory and the CPUs end up on the same numa node for performance reasons. The memory access time is relative to the distance between the processor and the memory.

Thanks for the explanation. It's something we could consider implementing in the future (loadbalancing between numa nodes etc.) but not something I'd consider at the moment (we'll prioritize other feature requests instead)

> This code that changes the uid and guid is rather trivial, so I would not have a special jailer just to handle it. 

Yes, we can totally implement that on our own in our `ignite-spawn` component which starts Firecracker.

All in all, as I now learned that seccomp filtering is done in Firecracker, we're all set to keep on going isolating the process in a container instead of using the Jailer.

Thanks all!
