### ISSUE TITLE
Running jailer in Docker causes no such device error

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#1199]
We have a [Docker image](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/tools/docker/Dockerfile) that we use to run our e2e tests. When enabling the jailer, the error `VhostOpen(VhostOpen(Os { code: 19, kind: Other, message: No such device }))` is returned.

When running the Docker image
```
docker run --rm \                                                                                               
                --privileged \                                                                                          
                --ipc=host \                                                                                            
                --volume /dev:/dev \                                                                                    
                --volume /run/udev/control:/run/udev/control \                                                          
                --volume $(PWD)/logs:/var/log/firecracker-containerd-test \                                             
                --device=/dev/vhost-vsock:/dev/vhost-vsock \                                                            
                --device=/dev/vsock:/dev/vsock \                                                                        
                --device=/dev/kvm:/dev/kvm \                                                                            
                --device=/dev/loop-control:/dev/loop-control \                                                          
                --workdir="/firecracker-containerd/runtime" \                                                           
                localhost/firecracker-containerd-e2etest-naive:latest \                                              
                "go test -run TestShimExitsUponContainerDelete_Isolated ./... -v"
```

I've also ran a simpler test, instead of `TestShimExitsUponContainerDelete_Isolated`, that only tests the jailer and still returns the same error.

We are using v0.17.0 of Firecracker and the jailer.

**Comment by dhrgit** [comment]
The error seems to indicate that `/dev/vhost-vsock` doesn't make it to the jailed mount space. The jailer manually creates a `/dev/vhost-vsock` node inside the jail, though. Also, the CI runs all tests inside a jail, inside a docker container, so this looks a bit tricky.

Can you confirm your test works without the jailer, and only fails when applying the jailer?

**Comment by xibz** [comment]
@dhrgit - Yes, it works fine without the jailer and only fails when applying the jailer.

**Comment by xibz** [comment]
Looks like the AMI I am using mounts the device with a different major and minor number

```
> ls -l /dev/vhost-vsock
crw-rw---- 1 root kvm 10, 57 Aug  2 04:48 /dev/vhost-vsock
```

I have since spun up a new instance with the original Ubuntu AMI and that works properly. Going to go ahead and close this.
