### ISSUE TITLE
Links from Docker Hub should be updated

### ISSUE THREAD

**Issue by montao** [firecracker-microvm/firecracker#1214]
It looks like the links from Docker Hub are outdated for this project

https://hub.docker.com/r/fcuvm/dev

If you try and follow the links to the Dockerfile and to the repo it seems like you should land somewhere else. The Dockerfile link is https://github.com/firecracker-microvm/firecracker/blob/master/tools/devctr/Dockerfile but that is not found and supposedly should be one of the files to build the docker image

https://github.com/firecracker-microvm/firecracker/blob/master/tools/devctr/Dockerfile.x86_64

https://github.com/firecracker-microvm/firecracker/blob/master/tools/devctr/Dockerfile.aarch64

Also the link to this repository is not leading here. It says https://github.io/firecracker-microvm/firecracker but that redirects somewhere else, maybe you can set up a redirect to this repository or directly link here (https://github.com/firecracker-microvm/firecracker)

**Comment by serban300** [comment]
Thank you for reporting this ! I fixed the links.
