### ISSUE TITLE
PROPOSAL - widen firecracker omnipresence

### ISSUE THREAD

**Issue by cherusk** [firecracker-microvm/firecracker#1219]
**Based on**: https://github.com/karmab/kcli/issues/153

**Gist**: Include firecracker as "backend" into kcli

**Comment by serban300** [comment]
I'm not sure we would have a business case for this, but it would be nice to have a better understanding of the issue.

Could you expand a bit please ? What exactly would be required on our side ?

**Comment by cherusk** [comment]
Nothing is required and no issue, it was more about communicating that there's a common abstraction layer forming holding many virtualization providers like libvirt and kubevirt, yet not firecracker.

General "consumer" interest is of course to wield as many of those provider thinkable in a seamless way. Since  firecracker e.g. holds promise to more efficient in aspects as let's say kubevirt. Having all in one place for others might helped dispersing your technology out of the initial realms.

**Comment by raduweiss** [comment]
Got it. We're definitely supportive of any initiative for including Firecracker as a runtime layer in the container ecosystem (this is very much part of our mission). Do you plan to use  Firecracker as is?

**Comment by cherusk** [comment]
>  Do you plan to use Firecracker as is?
>
Viably, most seems in place to do so. Haven't assessed thoroughly,
mostly was on my mind.

To some level, it'd compete with libvirt|KVM as is. Especially since
firecracker comes with its own VMM, as far as I introspected the logic.
Nigh, few aspects would render firecracker more outstanding: e.g.
Kubevirt comes with container-disks, therefore allowing for use of a
container image as a system core. Something similar would render
Firecracker more "seamless" also.
