### ISSUE TITLE
Technical debt: `allocate_virtio_tokens` rename/refactor

### ISSUE THREAD

**Issue by tamionv** [firecracker-microvm/firecracker#1225]
The function name ```allocate_virtio_tokens``` is misleading, since this function also has as a side effects. The name implies that it only allocates tokens, whereas it also creates a device handler. We should either rename this function, or refactor it out somehow.

**Comment by dianpopa** [comment]
`allocate_virtio_tokens` is now named `allocate_tokens_for_virtio_device`. Still creates a device handler inside too.

**Comment by dianpopa** [comment]
Issue won't apply anymore once #1404 is done.

**Comment by sandreim** [comment]
Fixed in #1618
