### ISSUE TITLE
Improve documentation on MMDS usage

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1226]
Make it obvious in the [mmds doc](https://github.com/firecracker-microvm/firecracker/blob/master/docs/mmds.md) that you need network connectivity for being able to interrogate the data store set up inside the guest. Furthermore, we could provide the explicit workflow for configuring the guest  before doing a curl to `169.254.169.254`.

**Comment by iulianbarbu** [comment]
Closed by #1800 .
