### ISSUE TITLE
CI should check that commits are signed

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1231]
Ensure that commits that make up a PR are signed (`-s`) .
Use as [inspiration](https://github.com/firecracker-microvm/firecracker-containerd/blob/2905f8dbab16c6847c99dd6384a90b462bffe206/.buildkite/logcheck.sh#L31).

**Comment by andreeaflorescu** [comment]
There is an app for this as well: https://github.com/apps/dco

Might be worth looking at it. We might be using it in rust-vmm as well.
