### ISSUE TITLE
HttpConnection: move Request parsing logic into separate class

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1239]
The HttpConnection class contains Request Parsing logic. It would be better to decouple this logic from HttpConnection and move it in a separate class `RequestParser`.

See [this](https://github.com/firecracker-microvm/firecracker/pull/1211#issuecomment-524203275) comment.

**Comment by georgepisaltu** [comment]
I have experimented around a bit with this issue and it seems the cost of doing this would outweigh the benefits.

However, we can use the parsing logic in `HttpConnection` in dumbo + MMDS, where `Request::try_from` is currently used. This change would mean instantiating an `HttpConnection` and calling `try_read` on the byte slice that was passed in `Request::try_from`, as it satisfies the constraints.

**Comment by serban300** [comment]
Probably it's not worth doing this. I will close this issue.
