### ISSUE TITLE
vsocks: firecracker terminates the host connection before starting the init process

### ISSUE THREAD

**Issue by devimc** [firecracker-microvm/firecracker#1253]
# Description of problem

firecracker terminates the host connection before starting the init process (systemd or kata-agent)  in the guest OS. This issue happens when the `CONNECT <port>` command is sent immediately after `InstanceStart`. To mitigate this issue in kata containers the runtime (host) tries to connect with the agent (guest) several times until the connection succeed, we see this approach more like a workaround than a real solution, since we consider this is prone to failures in slow systems where the number of tries can be bigger.

# Proposal 1

Firecracker should never terminate the host connection (like virtio-vsocks implementation.. ?)

# Proposal 2

Add a timeout parameter in the json request that creates the vsock

`{"vsock_id": "root","guest_cid": 3,"uds_path": "/vsock","timeout": 120}`

where `timeout` is in seconds

---

cc @sboeuf @sandreim @dhrgit  @stefanha

**Comment by dhrgit** [comment]
@devimc When you connect to the Firecracker unix socket and write a `CONNECT <port>` command, a vsock connection request packet is queued by Firecracker. That request packet will reach the guest only after the guest vsock driver has had a chance to initialize and make some RX buffers available (the connection request packet is sent to the guest via an RX buffer).

So, if you send the `CONNECT <port>` command before the guest is fully booted up, chances are that the connection request packet sent by Firecracker will reach the guest socket layer sometime between vsock driver initialization and the guest userspace app binding/listening to the AF_VSOCK `<port>`. This means your connection will be refused, causing Firecracker to sever the host unix connection, leading to an `EOF` (0-length) read on your connected unix socket.

I don't fully understand the flow you are describing that leads to `EOT`. I'm guessing this behavior is implemented by some higher level software (above the socket layer).

If you want to connect to an uninitialized guest (though I would advise against it), my suggestion is to use a nonblocking socket on the host side and have your guest (listening) agent ack client connections via some kind of message. Then, at the host end, immediately after `connect <port>`, you could poll your socket for read events (EPOLLIN) to check on the success status of your connection (i.e. a 0-length read means your connection was refused, while an ack message from your agent indicates a successful connection).

**Comment by devimc** [comment]
@dhrgit thanks for explaining.
Closing issue since we found a solution that may work for kata, thanks again. :+1:
