### ISSUE TITLE
Remove epoll dependency

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1259]
The rust-vmm [vmm-sys-util](https://github.com/rust-vmm/vmm-sys-util/) crate exports wrappers over epoll. Use [this](https://github.com/rust-vmm/vmm-sys-util/blob/master/src/poll.rs) module instead of the epoll crate.

**Blockers**:
- publish vmm-sys-util to crates.io

**Sub-tasks**:
- [ ] Check if the poll module in rust-vmm has the functionality needed by Firecracker. If functionality is missing from this module, it should be added directly in rust-vmm.
- [ ] Update Firecracker to use vmm-sys-util instead of epoll.

**Comment by lauralt** [comment]
Closing this issue since epoll crate dependency is now replaced with our own implementation of epoll wrapper. Once we have our event manager and epoll wrapper in rust-vmm, we will use that crate instead.
