### ISSUE TITLE
virtio-mmio: insert device nodes into fdt in order on AArch64

### ISSUE THREAD

**Issue by Pennyzct** [firecracker-microvm/firecracker#1264]
Hi~ guys
I, and my colleague @xiaobo55x are working on enabling firecracker with Kata Containers. 
For now, the launching error is as follows:
```
time="2019-09-11T17:52:11.579833941+08:00" level=error msg="rpc error: code = Internal 
desc = Could not mount /dev/vdb to /run/kata-containers/shared/containers/99bd85d0e97b41b617c721958a7a6ee4f54f72eb1a848a53de6327f902310935: input/output error" 
arch=arm64 command=create container=99bd85d0e97b417c721958a7a6ee4f54f72eb1a848a53de6327f902310935 name=kata-runtime pid=72762 source=runtime
```
It is because that Before launching the VM, kata will create 9 block devices as Device Pool. It creates a empty, temporary file as a placeholder backend for the drive at the beginning, and using the `patch` command to modify the host-backend at runtime. This is how they convey the container rootfs. 
On aarch64, we use HashMap to store all 9 virtio-mmio device nodes. But when we iterate whole HashMap to insert device nodes into fdt, it can't be guaranteed that the sequence in fdt is the same order in which we inserted the nodes into the HashMap. 
That's because that HashMap is iterated in an agnostic way.
You could see that all device nodes are in random order.
```
root@penny:/# ls /sys/bus/platform/devices/40001000.virtio_mmio
driver  driver_override  modalias  of_node  power  subsystem  uevent  virtio0
root@penny:/# ls /sys/bus/platform/devices/40002000.virtio_mmio
driver  driver_override  modalias  of_node  power  subsystem  uevent  virtio3
root@penny:/# ls /sys/bus/platform/devices/40003000.virtio_mmio
driver  driver_override  modalias  of_node  power  subsystem  uevent  virtio5
root@penny:/# ls /sys/bus/platform/devices/40004000.virtio_mmio
driver  driver_override  modalias  of_node  power  subsystem  uevent  virtio2

```
The fixed PR is on the way. ;)

**Comment by dianpopa** [comment]
Fixed by #1265.
