### ISSUE TITLE
Deploying docker swarm cluster on Firecracker VM

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker#1271]
Hi,

I have a setup where I need to deploy multiple containers on different VMs and I am using firecracker VMs to measure these workloads(https://github.com/parsa-epfl/cloudsuite). I am trying to setup an overlay network, the setup runs fine with normal host machines but I am not able to get it working on firecracker VMs, when I do` docker service create ` to launch a container on one of the microVMs it fails with `1/1: network sandbox join failed: subnet sandbox join failed for "10.0.0.0/24":… `. I have checked firecracker networking and its able to ping properly. I am not sure if this is related to firecrakcer specifically or docker. Docker creates a new network interface and I am not sure if firecracker will automatically connect to this interface through docker CLI  or whether I can even attach two network interfaces to the microVM . If someone has run into this issue or give me some direction on how to debug this please let me know. I would really appreciate any help.

Thanks,
Anjali

**Comment by dhrgit** [comment]
This looks like a Docker / guest userspace specific problem. You don't need to attach multiple interfaces to the vm, just like you wouldn't need multiple network cards on a bare metal host. Whatever network interface Docker creates is fully handled by the guest-side software.

Googling the error you are getting will yield some results from people who have run into the same issue with Docker, without Firecracker.
