### ISSUE TITLE
Refactor MMDS data_store

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1293]
The MMDS data_store uses names for functions that are mapping to HTTP API. As the data_store is not necessarily tied to an API and it is rather a backend for MMDS, we should refactor the code to reflect its actual purpose.

For example, we have functions like `put_data` and `patch_data`.

**Comment by serban300** [comment]
We don't need the data_store to be generic and in the current context names like `put_data` or `patch_data` can be more intuitive. Resolving for now. We'll revisit this issue if we decide we need to make the data_store more generic.
