### ISSUE TITLE
Potential Off-by-one Error In The Virtio Queue Checking Logic

### ISSUE THREAD

**Issue by dpeckett** [firecracker-microvm/firecracker#1296]
If the descriptor chain includes a memory region that ends at the guests highest memory address (but not exceeding), the descriptor chain is incorrectly marked as invalid. I believe this stems from a potential off-by-one issue in the virtio queue bounds checking logic:

https://github.com/firecracker-microvm/firecracker/blob/6713662ade763dc7b82bb1ee4fdf16285ce9e1ac/devices/src/virtio/queue.rs#L111

The issue appears we are passing a length, instead of an offset, to the checked_offset method. This appears to fail thankfully in a safe manner (but can lead to guest os panics).

**Comment by acatangiu** [comment]
Thanks for the report @dpeckett 👍 .

We'll look into it, but PR's are also welcome 😄 .

**Comment by dpeckett** [comment]
My main concern around supplying a merge request for this fix, is that I am concerned by the implication of this bug, that there may be other parts of the code base which could have potentially misused the checked_offset validator for length parameters. I'm not familiar enough with the codebase to perform the necessary project wide checks.

The initial bug was identified by investigating intermittent block device failures on a custom kernel build. I can recreate the issue if we need to confirm a fix.

**Comment by iulianbarbu** [comment]
> My main concern around supplying a merge request for this fix, is that I am concerned by the implication of this bug, that there may be other parts of the code base which could have potentially misused the checked_offset validator for length parameters. I'm not familiar enough with the codebase to perform the necessary project wide checks.
> 
> The initial bug was identified by investigating intermittent block device failures on a custom kernel build. I can recreate the issue if we need to confirm a fix.

@dpeckett, can you please try to build firecracker from https://github.com/iulianbarbu/firecracker/tree/potential_off_by_one_virtio_queue_checking, and then, work through the steps necessary to reproduce the bug?
I am curious if the provided change is enough for your issue.
