### ISSUE TITLE
Expose kcov run results as HTML

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#1301]
At this time coverage failures investigation require manually copying the files locally. 
This would reduce the time required to investigate a coverage failure and would easily highlight the code that requires testing. 

Options that I can think of right now are:

- zip the output and upload it and provide URL for download
- upload and provide URL.

**Comment by serban300** [comment]
We're continuing to track this as a nice to have.

**Comment by dianpopa** [comment]
After discussions, we decided to make use of buildkite's artifact capability to store the zipped HTML results that kcov leaves behind after a coverage run.

**Comment by roypat** [comment]
We have switching from kcov to using grcov, and decided that instead of having our CI generate html artifacts and store them, we use codecov.io for coverage visualization: https://app.codecov.io/gh/firecracker-microvm/firecracker
