### ISSUE TITLE
Mounting block devices as virtio devices doesn't work correctly

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker#1316]
While investigating https://github.com/firecracker-microvm/firecracker-containerd/issues/253, we have found a small gap regarding virtio block device support on Firecracker.

Currently Firecracker is using `std::fs::metadata()` to [check the size of a virtio block device](https://github.com/firecracker-microvm/firecracker/blob/4fea9ad1cc9eb15776b5880bfc67296f9bb036ca/vmm/src/lib.rs#L1910), which ultimately calls [stat() on Unix](https://github.com/rust-lang/rust/blob/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/sys/unix/fs.rs#L522).

However firecracker-containerd is using a loopback device as the backing file for a virtio block device. On a lookback device, the size from stat() is always zero.

Can Firecracker support our usecase by inspecting the size of the file more deeply? You probably can use [BLKGETSIZE64 ioctl](http://www.microhowto.info/howto/get_the_size_of_a_linux_block_special_device_in_c.html).

Thanks,

**Comment by aghecenco** [comment]
Hi @kzys, thank you for the report and investigation! This looks like a bug, and will be addressed as soon as possible. However, if in the meantime you have a fix ready, PRs are welcome!
