### ISSUE TITLE
Add integration test for binary size

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#1337]
Keeping the memory footprint low requires tracking the Firecracker binary size increase for each merged PR. The integration test should fail if the current size of the binary versus history is greater than a configurable threshold. 

Sometimes it might be required for this test to be bypassed or the baseline adjusted so legit size increases are allowed. Mainly we want this test to allow us to catch accidental increases in size and decide after that what the next steps are. 

We could keep the size history in a DynamoDB table.

**Comment by dianpopa** [comment]
Fixed by #1465
