### ISSUE TITLE
Patching drives write permissions

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#1338]
We currently have a use case where we need to dynamically attach drives, we do this by creating stub drives and later using patch to replace the stub drive with an actual drive. However, we've found that we want to give the option to our users to allow them to specify the rate limiter and write permissions during patching. We can work around this by doing it all in the beginning when we create the initial drives. However, this requires our users to know upfront what rate limiting and write permissions they need. While implementing this work around isn't too much work, having the ability to specify the rate limiters and write permissions during patch would really simplify things.

**Comment by mprey** [comment]
Hello, I am interested in working on this issue. Do you have any tips for getting started?

**Comment by andreeaflorescu** [comment]
Hey @mprey. This issue has two parts. We need to provide two actions:
- update block device permissions  
- update rate limiter for block device

The block device permission is set when doing the device feature negotiation. Once the device is live, you can only update the block device permission only if you are reseting the device. You can take a look at the specification, section 2.2: http://docs.oasis-open.org/virtio/virtio/v1.0/cs04/virtio-v1.0-cs04.html#x1-490001. We don't support block device reset in Firecracker right now. We need to discuss whether this is something that we want to support.

For patching the rate limiter, we already have a patch on Rate Limiter for network devices. The work should be similar. You can take a look at this PR that introduced the patch as an example: https://github.com/firecracker-microvm/firecracker/pull/928

We are currently re-working the devices in Firecracker so the code that is handling devices might change quite a lot. CC: @firecracker-microvm/compute-capsule do you think it makes sense to add this feature now or should we wait for the rework of devices to get merged?

**Comment by mprey** [comment]
Ok, well let me know if you decide to pursue this feature now. I can start working on this issue.

**Comment by acatangiu** [comment]
Hi @mprey! We are now in a state where our code is no longer in massive flux. If you are interested in picking this up, we'd be happy for the contribution.

Like @andreeaflorescu said, this should be broken down in (at least) two PRs:
- _update block device permissions_ (involves virtio renegociation/reactivation)
- _update rate limiter for block device_ (fairly straightforward)

> We don't support block device reset in Firecracker right now. We need to discuss whether this is something that we want to support.

I vote yes here. As long as it doesn't over-complicate our device management (it shouldn't), I believe the benefits outweigh the cost.

@xibz from a prioritization point of view, which of the two (patch drive permissions/rate-limiters) would help you most?

**Comment by xibz** [comment]
@acatangiu - Both are probably equally as important, but if I had to choose one, probably drive permissions.

**Comment by acatangiu** [comment]
Patching block device support added in #2278.

**Comment by acatangiu** [comment]
Rate limiter updating is now available, renaming this issue to adding support for updating driver permissions.

**Comment by MalteJ** [comment]
is the pre-provisioned drive strategy, like described in the opening comment by @xibz, the way to go when you want to attach/disattach drives during runtime of the VM?

**Comment by sandreim** [comment]
@MalteJ this is mostly the gist of it. Take a look at the Firecracker [patch block docs](https://github.com/firecracker-microvm/firecracker/blob/master/docs/api_requests/patch-block.md). Also, what @acatangiu is something we would also do, but currently we have no plans for it.

**Comment by alindima** [comment]
@xibz @kzys is this feature still relevant for you?

**Comment by alindima** [comment]
As pointed out by @serban300, the linux virtio driver does not implement `VIRTIO_CONFIG_S_NEEDS_RESET`, so there is not really a way for Firecracker to initiate the renegotiation process for the block device. It is therefore impossible to patch the write permission after the device is live.

Resolving this issue

https://github.com/torvalds/linux/commit/c00bbcf8628969e103d4a7b351a53746f1025576
