### ISSUE TITLE
Firecracker slack link no longer valid

### ISSUE THREAD

**Issue by VanillaBrooks** [firecracker-microvm/firecracker#1344]
The ["Chat about firecracker on slack"](https://tinyurl.com/firecracker-microvm) link at https://firecracker-microvm.github.io/ is no longer valid. I don't see a repo for the github.io page so i'm filing this issue here.

**Comment by aghecenco** [comment]
Hey @VanillaBrooks, thanks for reporting this! The invite link should be pointing to the Slack workspace now.

**Comment by aaglenn** [comment]
it is broken again. is there a current, active Slack workspace?

**Comment by acatangiu** [comment]
Thanks for the heads up! Renewed link here: https://github.com/firecracker-microvm/firecracker-microvm.github.io/pull/17 (pending merge to actual site).
