### ISSUE TITLE
Use vmm-sys-util from rust-vmm

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1346]
vmm-sys-util is now published to crates.io: https://crates.io/crates/vmm-sys-util

We can use it to get rid of a few external dependencies (like tempfile). What we could do is unify the utilities crates in Firecracker under one and this crate can have a dependency on vmm-sys-util. Specifically we can have just one `utils` crate which has all modules from net_util, sys_util and fc_util. The previous crates can be mapped to modules so we can still have them separated. The new `utils` crate depends on vmm-sys-utils and re-exports only the modules that are used by Firecracker.

**Comment by acatangiu** [comment]
Big :+1:

**Comment by iulianbarbu** [comment]
In the current implementation [1] of `register_signal_handler`, from `vmm-sys-util`, we can see that a signal handler is registered without specifying any mask for blocked signals.

In the current Firecracker implementation for `register_signal_handler` [2], from `sys_util`, we can see that we block all other signals, while the signal handler for the registered signal is running.

These two behaviors are conflicting. Should we drive some discussions on the rust-vmm about the reasons for ignoring blocking other signals? 

[1] https://github.com/rust-vmm/vmm-sys-util/blob/472614c3a21231f6a0c3696fab83fb34d6592ade/src/signal.rs#L191
[2] https://github.com/firecracker-microvm/firecracker/blob/87eb6eace8a77826b29182f3bd16921eb145c2ba/sys_util/src/signal.rs#L150

**Comment by acatangiu** [comment]
Bumped priority since it's blocking #1386

**Comment by acatangiu** [comment]
Fixed by 1413
