### ISSUE TITLE
Regression in KVM error prints

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1353]
If there are problems with the KVM setup on the host, we now return a non-formatted error which was the cause of many confusions when we open source Firecracker. We need to re-add the pretty prints of KVM errors (the common ones).

The errors affected by this regression are:
- **Cannot open `/dev/kvm`**. Previously the panic message was: "Cannot create VMM: Cannot open /dev/kvm. Error: Permission denied (os error 13)". This regression was introduced by fc75ec711b1ebcb1042b59cfaf7c3c9ae7b14931. `Kvm::new()` returns an `io::Error` and not a custom Firecracker error as it used to when the Kvm object was created inside the KvmContext.
- **Invalid KVM API version**. Previously the panic message was: "Bad KVM API version: 42". This regression was introduced by 5a84e2cfb59a2812c801717fabae6bc34ddba363. Vstate errors don't do pretty print on debugs. The easy fix is to introduce pretty prints only for errors that are used often and for the rest to just use the default debug print.
- **Unsupported KVM capability**. Previously the panic message was: "Missing KVM capability: Hlt". Regression introduced by 5a84e2cfb59a2812c801717fabae6bc34ddba363.

**Comment by dianpopa** [comment]
These issues should get solved by #1343.
