### ISSUE TITLE
Seccomp - allow syscalls list to be passed by caller

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1366]
During our presentation at KVM Forum about Firecracker we got a suggestion for an improvement that we could do to our seccomp filters. Instead of having a static list of syscalls that are allowed, we can let the users of Firecracker to pass a list of syscalls that it wants to allow. This feature can help in two cases:
- If you miss to add a syscall to the allow list, instead of needing to create a new Firecracker binary, you can just update the file containing the syscalls
- If you don't use statically linked binaries (i.e. the musl build of Firecracker), it is hard to have a minimal list of all syscalls because it is highly dependent on the dependencies versions. In this case the Firecracker user can provide the list that is targeted for the workload, platform and other possible dependencies.

**Comment by pyrito** [comment]
Hi, I'm at student at UT Austin and am looking to contribute to container-related project as part of my virtualization course. I'm interested in picking this issue up for our project. @mi-yu is also part of my group.

**Comment by aghecenco** [comment]
Hey @pyrito, @mi-yu, thanks for the interest! Some pointers to get you started:
- syscalls are dependent on: architecture (`x86_64` + `aarch64`) and build toolchain (`musl` + `gnu`). You should need to take this into consideration; we don't want to whitelist any more than strictly necessary (i.e. don't whitelist in the `musl` build a syscall that only glibc emits).
- the recommended way to run Firecracker is [jailed](https://github.com/firecracker-microvm/firecracker/blob/master/docs/prod-host-setup.md) so make sure the paths are relative to the chroot'ed root.
- also side effect of the jailer - the command line parameters need to be passed to the jailer first and propagated to Firecracker, where the filters are actually installed.
- the filters are installed in the last moment before starting to execute guest code (right before the vCPUs start running); if you move the filter installation to any moment prior to that, you'll need to whitelist more syscalls, including some potentially dangerous ones (think: `SYS_clone`)
- I think this feature can go nicely with #1178 - it'd be nice to see a separation between syscalls that come from the API thread, the emulation thread and the vCPUs.
Reach out any time if you need more pointers :slightly_smiling_face: Looking forward to the PRs :+1:

**Comment by pyrito** [comment]
Thanks Alexandra! I have a few questions:

- How do we run firecracker in general? I've been looking around and although I've made a successful build, I haven't found anything that has told me how to run firecracker on a host system (in this case, I'm running a linux VM on my Mac). Do you have any pointers to how to create a jailed instance (some external documentation)?

- How is the whitelist going to be inputted ideally? Are we looking at something that will be defined in a config file or will it be a list of arguments passed through by the user?

Thanks!

**Comment by mi-yu** [comment]
To follow up a Slack conversation with @aghecenco, we are looking for more input on how exactly users should specify syscalls to whitelist. For example, would they configure a custom whitelist as part of the config file:

```
{
  ...

  "syscall_whitelist": ["connect", "read", etc...]
}
```

And do we want to support allowing users to configure each individual syscall in terms of allowed arguments and conditionals?

Finally, how should we approach configuration options for different architectures? Would it be better to have something like this:

```
{
  ...

  "syscall_whitelist": {
    "x86": [ <list of syscalls for x86> ],
    "aarch64": [ <list of syscalls for aarch64> ]
  }
}
```

as opposed to the first code snippet. The first option seems easier for the user, but would complicate the parsing logic quite a bit. Not sure what a good tradeoff is.

**Comment by aghecenco** [comment]
After giving this issue some more thought, we've come up with a base set of requirements, and some ideas:

## Key points to address

1. **Architecture:**
    1. **Whitelist structure:** the whitelist differs between `x86_64` and `aarch64`, as certain syscalls are only called on one of the 2 architectures.
    2. **Syscall numbers**: even where the whitelist is identical, the syscall numbers can differ. This is relevant as it would impede users from specifying syscall numbers in the filter file.
1. **Toolchain:** GNU libc issues different syscalls than musl libc.
1. **Thread:** the whitelist should be specific to the thread on which it’s applied. This is not yet implemented. See https://github.com/firecracker-microvm/firecracker/issues/1178, part of the larger seccomp improvements bundle https://github.com/firecracker-microvm/firecracker/issues/1177.
1. **Security by default:** Firecracker’s default behavior should remain unchanged, i.e. unless the user explicitly relaxes the seccomp filters, the process should run as restricted as possible. Analogous to the current default setting of `seccomp-level=2`, we will need to convert the hardcoded filters into default filter files.
5. **VMM flexibility:** as of https://github.com/firecracker-microvm/firecracker/pull/1474, the filters are built before the VMM is instantiated, and passed to the VMM thread. This functionality needs to stay in place.
6. **User experience:**  We do not want to complicate things for users and should aim for the opposite. The filter file must be clear and concise.

## Proposal idea

A new `seccomp-level=file` is introduced, working in tandem with a new command line parameter `filters`. The `filters` parameter does not make sense without `seccomp-level=file` and is ignored in combination with anything else. `seccomp-level=file` requires the `filters` parameter to be specified and exits the Firecracker process if it is not.
The existing options for `seccomp-level` are kept for usability and backwards compatibility, but can be obsoleted and deprecated later.

The `filters` parameter takes a JSON file containing rules. If `seccomp-level=file` is specified and the default rules overridden, the user assumes full responsibility for the correctness of the filters.

The currently hardcoded filters need to be converted or autogenerated from the Rust code. The corresponding files will be included in the Firecracker source tree. We can explore the possibility of bundling them in the binary, to simplify deployment UX.

```bash
--seccomp-level=
    0   # seccomp disabled
    1   # filters loaded from /path/to/basic/filters.json
    2   # filters loaded from /path/to/advanced/filters.json
    file --filters=/path/to/custom.filters.json
```

Rule file format:

```
{
  thread:
  {
    syscall_name:
    [
      # Rule 0
      [ 
        { "arg_idx": $idx0, "arg_type": $type0, "op": $op0, "val": $val0 },
        ...
        { "arg_idx": $idxN, "arg_type": $typeN, "op": $opN, "val": $valN }
      ],
      ...
      # Rule K
      [ 
        { "arg_idx": $idx0, "arg_type": $type0, "op": $op0, "val": $val0 },
        ...
        { "arg_idx": $idxM, "arg_type": $typeM, "op": $opM, "val": $valM }
      ]
    ]
  }
}
```

Rules `0` to `K` are logically `OR`-bound (only one of the rules needs to hold for the filter to match). All the conditions that comprise a rule are logically `AND`-bound (all of a rule’s conditions must be met for the rule to hold).

Neither the architecture, nor the libc implementation are mentioned in the file.

`thread` can be one of `api`, `vmm` or `vcpu`.

Syscalls are specified by name, not by number. The translation needs to be implemented in Firecracker (an autogenerated, toolchain-dependent, hardcoded map `syscall name → syscall number`). The same applies to named parameters imported from libc, which can also have different values.

### Simplifying assumptions and restrictions

* Neither integrity checks, nor validations, nor conflict resolution are performed on rules loaded from user-specified files.
* The filters can only be specified at process startup time, through the command line arguments. There is no API call for seccomp configurations, nor has there been the need for one.
* The filters cannot be updated at runtime.
* The filter is expressed as a map, so the syscalls are not sorted by relevance. Having the most frequently used syscalls earlier in the filter is an optimization heuristic based on the idea that the kernel will have fewer rules to go through for each syscall.
* The JSON file does not make it obvious to the user that rules are `OR`-bound and conditions within a rule are `AND`-bound. The format could be extended with explicit operators (i.e. rules and conditions within a rule could be expressed as dicts `"OR": [ <rules> ]` / `"AND": [ <conditions> ]`).

Example

```json
{
  "fc_vmm":
  {
    "SYS_accept4": [],
    "SYS_futex":
    [
      [
        {"arg_idx": 1, "arg_type": "DWORD", "op": "Eq", "val": "FUTEX_WAIT_PRIVATE"}
      ],
      [
        {"arg_idx": 1, "arg_type": "DWORD", "op": "Eq", "val": "FUTEX_WAKE_PRIVATE"}
      ]
    ]
  },
  "fc_vcpu*":
  {
    "SYS_ioctl":
    [
      [
        {"arg_idx": 1, "arg_type": "DWORD", "op": "Eq", "val": "KVM_SET_REGS"}
      ],
      [
        {"arg_idx": 1, "arg_type": "DWORD", "op": "Eq", "val": "KVM_SET_SREGS"}
      ]
    ]
  }
}
```

**Comment by mi-yu** [comment]
This all looks very reasonable to me! Just one point:

Is the idea for the `thread` property to act as a regex-like string? The proposal mentions `thread` should be one of `vmm, vcpu, api`, but in the example config file, I see `fc_vcpu*` as one of the thread names. Do we want to support different filters for different `vcpu` threads? It seems to make more sense to have the same filters for all `vcpu` threads.

**Comment by aghecenco** [comment]
Good callout! I had that idea at one point but after bouncing it off the team I think it's better to keep things simple and not bring regexes into the matter. We can stick with `vmm`, `vcpu` and `api` categories. I updated the example.

**Comment by alindima** [comment]
Implemented by: https://github.com/firecracker-microvm/firecracker/pull/2557
