### ISSUE TITLE
Question: How to force-stop an uncooperative Firecracker VM?

### ISSUE THREAD

**Issue by andrew-d** [firecracker-microvm/firecracker#1370]
Hello folks,

I've been doing some reading, and I haven't found a single answer: what is the current recommended way of force-stopping a Firecracker VM? Here's what I've found:
* #673 mentions `SIGTERM`/`SIGKILL`, but didn't really mention whether this was safe.
* #1095 has a bunch of debugging where the kernel doesn't have the correct module(s) to handle the Ctrl-Alt-Delete signal, but doesn't appear to talk about forced shutdowns.

As such: a collection of three related questions:
1. What is the current recommended way of forcefully terminating a Firecracker VM where the guest kernel isn't cooperating with a shutdown request?
2. Is it safe to `SIGKILL`/`SIGTERM` the Firecracker process, or will that leave the host kernel's KVM structures in a strange state?
3. If using the jailer process, is it recommended to kill the Firecracker process inside the "jail"? I assume so, to allow the jailer to "clean up" any resources, but the docs mention that it expects to be spawned in a new PID namespace, which (presumably) makes it harder to obtain the PID of the Firecracker process to kill.

Any recommendations here are appreciated!

**Comment by aghecenco** [comment]
Hey @andrew-d,

The recommended way to stop a microVM is to send it CTRL+ALT+DEL which initiates a clean shutdown from inside the guest; if the guest is unresponsive, uncooperative, or doesn't handle CTRL+ALT+DEL, the Firecracker process must be `SIGKILL`ed.

To answer your questions:

1. `kill -KILL $(pidof firecracker)`
1. If the Firecracker process is killed, there is no guarantee of immediate cleanup. Furthermore, there is the risk of corrupting mounted drives if the guest had pending IO.
1. The jailer `exec`s into Firecracker so there is no external entity that performs cleanup. It's up to the user to monitor the jail and do the cleanup.
