### ISSUE TITLE
set logger with null options will crash firecracker

### ISSUE THREAD

**Issue by lifupan** [firecracker-microvm/firecracker#1375]
The following logger configure would crash firecracker:
```
 curl --unix-socket /tmp/firecracker.socket  -i     -X PUT "http://localh
ost/logger"     -H "accept: application/json"     -H "Content-Type: application/json"     -d "{
             \"log_fifo\": \"/logs.fifo\",
             \"metrics_fifo\": \"/metrics.fifo\", \"level\": \"Debug\", \"options\":null
    }"
```

Firecracker will crashed with the following backtrace:

2019-11-08T14:24:57.361247895 [anonymous-instance] Firecracker panicked at 'called `Option::unwrap()` on a `None` value', /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libcore/macros.rs:41:40
2019-11-08T14:24:57.510482482 [anonymous-instance] stack backtrace:
   0: backtrace::backtrace::libunwind::trace::h952205ac5c19428a (0x8a16ad)
             at /home/fupan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::hdd58e47a2f7fc4c0
             at /home/fupan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace::hf08ff4662e0235f8 (0x8a1665)
             at /home/fupan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:53
Aborted

**Comment by aghecenco** [comment]
Hi @lifupan, thanks for reporting this! We'll come up with a fix asap.
