### ISSUE TITLE
Update to kvm-ioctls v0.4.0 to access the vm and vcpu serialization ioctls

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1386]
`kvm-ioctls` v0.4.0 will contain support for (previously missing):

Vcpu serialization and deserialization:
- KVM_GET_CPUID2
- KVM_GET_MP_STATE
- KVM_SET_MP_STATE
- KVM_GET_VCPU_EVENTS
- KVM_SET_VCPU_EVENTS
- KVM_GET_DEBUGREGS
- KVM_SET_DEBUGREGS
- KVM_GET_XSAVE
- KVM_SET_XSAVE
- KVM_GET_XCRS
- KVM_SET_XCRS

Vm serialization and deserialization:
- KVM_GET_IRQCHIP
- KVM_SET_IRQCHIP
- KVM_GET_PIT2
- KVM_SET_PIT2
- KVM_GET_CLOCK
- KVM_SET_CLOCK

**Comment by acatangiu** [comment]
Currently blocked on creating a new `kvm-ioctls` release https://github.com/rust-vmm/kvm-ioctls/issues/59

**Comment by acatangiu** [comment]
**Also blocked** on https://github.com/firecracker-microvm/firecracker/issues/1346
New `kvm-ioctls` uses `vmm_sys_util::EventFd` from while firecracker uses `sys_util::EventFd`.

**Comment by andreeaflorescu** [comment]
@acatangiu can you please expand on why is this work blocked on #1346?
My understanding was that you can still use the newer version of kvm-ioctls and just replace the occurrence of sys_util::EventFd with vmm-sys-util::Eventfd. With this approach we can unblock the work on this issue and at the same time make sure we take the time that we need for switching to vmm-sys-util.

**Comment by acatangiu** [comment]
> just replace the occurrence of sys_util::EventFd with vmm-sys-util::Eventfd

easier said than done. It's also throwaway work.

> make sure we take the time that we need for switching to vmm-sys-util

definitely take the **required** time, but I consider #1346 to now be higher priority because it's blocking using the new `kvm-ioctls`. It's just a matter of prioritization not about quality or rash decisions.
