### ISSUE TITLE
Add serialization to kvm-bindings structs

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1387]
`kvm-bindings` offers us FFI-structs used by the KVM api.
We need to implement (de)serialization mechanisms for said structs.

**Comment by aghecenco** [comment]
Since `kvm-bindings` is consumed by multiple projects, I touched base with the rust-vmm community on this topic in today's syncup. I will follow up with a doc proposal in the `kvm-bindings` repo (as a PR so folks can comment).

**Comment by acatangiu** [comment]
Fixed in https://github.com/firecracker-microvm/kvm-bindings/pull/2

**Comment by andreeaflorescu** [comment]
@acatangiu how about we keep this open to track the work for merging it upstream? It looks like it is done in firecracker-microvm/kvm-bindings.

**Comment by acatangiu** [comment]
> track the work for merging it upstream

I agree, but is `https://github.com/firecracker-microvm/firecracker` the right repo to track that?

I think both https://github.com/firecracker-microvm/kvm-bindings and https://github.com/rust-vmm/kvm-bindings are better locations to keep a tracking issue. WDYT?

**Comment by andreeaflorescu** [comment]
Hmm, it looks like the action item is on Firecracker side, not on rust-vmm. I would prefer to track this on the Firecracker side until we switch back to using the upstream version. We can also track this in firecracker-microvm/kvm-bindings. My impression was this is a temporary state, and we want to still consume kvm-ioctls from upstream.
