### ISSUE TITLE
Enhance GuestMemory to support file-mapped memory

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1394]
We want to be able to accelerate certain snapshot usecases where the Guest Memory is host-file `mmap`ed.

Implement support for this in the `GuestMemory` crate.
An alternative option is to use https://github.com/rust-vmm/vm-memory which already provides this support.

**Comment by serban300** [comment]
This is already done in `rust-vmm/vm-memory`. We should switch to that crate very soon.

**Comment by dianpopa** [comment]
This was solved by switching to rust-vmm/vm-memory which happened in #1562.
