### ISSUE TITLE
Examine the rust-vmm/vm-memory crate

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1399]
We have to check the following:

- the overall architecture is ok
- the crate is safe to use
- there are no methods that can generate undefined behavior
- all the unsafe blocks are absolutely necessary
- all the unsafe methods and traits are marked as unsafe

**Comment by aghecenco** [comment]
https://github.com/firecracker-microvm/firecracker/pull/1562 makes the switch to `vm-memory`, so it's safe to say the crate has been examined.
