### ISSUE TITLE
With the use of vmm-sys-util, signal handling is again using the sa_sigaction instead of sa_handler

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1420]
Firecracker signal.rs code was refactored, do the same in vmm-sys-util to consume the new version from there.

**Comment by iulianbarbu** [comment]
Fixed with this PR: https://github.com/rust-vmm/vmm-sys-util/pull/54 and contained by 0.3.1 version, used currently in Firecracker.
