### ISSUE TITLE
Move SyscallReturnCode struct from utils/src/lib.rs

### ISSUE THREAD

**Issue by iulianbarbu** [firecracker-microvm/firecracker#1422]
As we try to make things decoupled, it is best to move the `SyscallReturnCode` struct from utils/src/lib.rs, inherited from the Firecracker sys_util crate, which was removed when we merged #1413 , and keep utils/src/lib.rs clean, without any unnecessary logic or structs definition.

As a suggestion, I would make a separate file, `utils/src/syscall.rs`, which will contain logic belonging to how we handle syscall exit codes in a rustacean way.

**Comment by dianpopa** [comment]
Yes, yes I agree with your suggestion.

**Comment by iulianbarbu** [comment]
> Yes, yes I agree with your suggestion.

Ok, then. I will get a PR with this soon.
