### ISSUE TITLE
hybrid vsock lost the first package when it was just created

### ISSUE THREAD

**Issue by teawater** [firecracker-microvm/firecracker#1432]
We meet the issue with firecracker in https://github.com/kata-containers/kata-containers/issues/79.
And I found that hybrid vsock will drop or truncate the first package and qemu doesn't have this issue.
I add code that send an empty package and wait the first package arrive from client to handle this issue in https://github.com/alipay/grpc/commit/811660d28e3771a162cd5ece0d1e950168476ac8.

**Comment by sandreim** [comment]
Thanks for logging this @teawater. We will look into it and update.

**Comment by sandreim** [comment]
@teawater We need more context into the problem as our integration tests pass without requiring the workaround that you implemented.  Can you please provide steps and some more information on the setup that reproduces this issue ? Ideally that would be the most simple scenario that triggers the bug.

**Comment by teawater** [comment]
@sandreim Thanks for your comments.
I found that this is an issue of kata.  I just post a PR to fix this issue in https://github.com/kata-containers/agent/pull/696
