### ISSUE TITLE
question: is cpu hot remove supported?

### ISSUE THREAD

**Issue by devimc** [firecracker-microvm/firecracker#1448]
Kata Containers supports several VMMs, one of them is firecracker. Is possible to hot remove a CPU from a running instance?  thanks

**Comment by sandreim** [comment]
Hi @devimc! Unfortunately Firecracker does not support vCPU hotplug. 
You can however disable or enable the cpus from the guest, but I am not sure if this helps with your usecase:
```bash
# Enable:
echo 0 | tee /sys/devices/system/cpu/cpuX/online
# Disable:
echo 1 | tee /sys/devices/system/cpu/cpuX/online
```

**Comment by devimc** [comment]
thanks @sandreim , unfortunately this workaround won't help

closing issue/question, thanks again :+1:
