### ISSUE TITLE
Not able to mount 32GB rootfs

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker#1449]
Hi, 

I am trying to mount a 32GB rootfs but firecracker is not able to start the microVM with this message:

[    0.112967] VFS: Disk quotas dquot_6.6.0
[    0.113693] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.118837] NET: Registered protocol family 2
[    0.120299] TCP established hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.123251] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    0.125935] TCP: Hash tables configured (established 131072 bind 65536)
[    0.127665] UDP hash table entries: 8192 (order: 6, 262144 bytes)
[    0.129462] UDP-Lite hash table entries: 8192 (order: 6, 262144 bytes)
[    0.131373] NET: Registered protocol family 1
[    0.132180] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.133171] software IO TLB [mem 0xcc000000-0xd0000000] (64MB) mapped at [ffff8800cc000000-ffff8800cfffffff]
[    0.134532] virtio-mmio: Registering device virtio-mmio.0 at 0xd0000000-0xd0000fff, IRQ 5.
[    0.135717] virtio-mmio: Registering device virtio-mmio.1 at 0xd0001000-0xd0001fff, IRQ 6.
[    0.137054] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    0.141578] Scanning for low memory corruption every 60 seconds
[    0.144402] audit: initializing netlink subsys (disabled)
[    0.146445] audit: type=2000 audit(1575481149.510:1): state=initialized audit_enabled=0 res=1
[    0.146683] Initialise system trusted keyrings
[    0.146689] Key type blacklist registered
[    0.146840] workingset: timestamp_bits=36 max_order=22 bucket_order=0
[    0.150004] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.156047] Key type asymmetric registered
[    0.156844] Asymmetric key parser 'x509' registered
[    0.157829] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
[    0.159331] io scheduler noop registered (default)
[    0.161207] io scheduler cfq registered
[    0.162851] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.166430] virtio-mmio virtio-mmio.1: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.168524] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.193031] serial8250: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a U6_16550A
[    0.199789] loop: module loaded
[    0.201323] tun: Universal TUN/TAP device driver, 1.6
[    0.203341] hidraw: raw HID events driver (C) Jiri Kosina
[    0.204778] nf_conntrack version 0.5.0 (65536 buckets, 262144 max)
[    0.206172] ip_tables: (C) 2000-2006 Netfilter Core Team
[    0.207985] Initializing XFRM netlink socket
[    0.208930] NET: Registered protocol family 10
[    0.211076] Segment Routing with IPv6
[    0.211637] NET: Registered protocol family 17
[    0.212429] Bridge firewalling registered
[    0.213244] sched_clock: Marking stable (213129916, 0)->(605566486, -392436570)
[    0.215020] registered taskstats version 1
[    0.215660] Loading compiled-in X.509 certificates
[    0.217644] Loaded X.509 cert 'Build time autogenerated kernel key: 3472798b31ba23b86c1c5c7236c9c91723ae5ee9'
[    0.219155] zswap: default zpool zbud not available
[    0.219820] zswap: pool creation failed
[    0.221326] Key type encrypted registered
[    0.240113] IP-Config: Complete:
[    0.241035]      device=eth0, hwaddr=02:fc:00:00:00:00, ipaddr=169.254.0.1, mask=255.255.255.252, gw=169.254.0.2
[    0.243931]      host=169.254.0.1, domain=, nis-domain=(none)
[    0.245738]      bootserver=255.255.255.255, rootserver=255.255.255.255, rootpath=
[    0.250685] EXT4-fs (vda): ext4_check_descriptors: Block bitmap for group 0 overlaps block group descriptors
[    0.253975] EXT4-fs (vda): group descriptors corrupted!
[    0.255695] VFS: Cannot open root device "vda" or unknown-block(254,0): error -117
[    0.257740] Please append a correct "root=" boot option; here are the available partitions:
[    0.259988] fe00        32536576 vda 
[    0.259989]  driver: virtio_blk
[    0.261849] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(254,0)
[    0.264120] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.14.55-84.37.amzn2.x86_64 #1
[    0.266162] Call Trace:
[    0.266864]  dump_stack+0x63/0x89
[    0.267395]  panic+0xdf/0x239
[    0.267889]  mount_block_root+0x1f8/0x2af
[    0.268496]  ? set_debug_rodata+0x12/0x12
[    0.269062]  mount_root+0x65/0x68
[    0.269533]  prepare_namespace+0x12f/0x167
[    0.270111]  kernel_init_freeable+0x21a/0x247
[    0.270746]  ? rest_init+0xb0/0xb0
[    0.271254]  kernel_init+0x9/0x100
[    0.271781]  ret_from_fork+0x35/0x40
[    0.272485] Kernel Offset: disabled
[    0.273064] Rebooting in 1 seconds..

Is there any upper limit on the rootfs size?

Thanks

**Comment by dianpopa** [comment]
Hi @Anjali05 ,

There is no upper limit on the rootfs size. From the kernel messages you receive (i.e:
```
[ 0.250685] EXT4-fs (vda): ext4_check_descriptors: Block bitmap for group 0 overlaps block group descriptors
[ 0.253975] EXT4-fs (vda): group descriptors corrupted!
[ 0.255695] VFS: Cannot open root device "vda" or unknown-block(254,0): error -117
[ 0.257740] Please append a correct "root=" boot option; here are the available partitions:
```
seems that it might me something wrong with the ext4 that you are trying to mount.
What does **fsck.ext4** report for your rootfs?
