### ISSUE TITLE
Use public SIGRTMIN() and SIGRTMAX() from rust-vmm/vmm-sys-util

### ISSUE THREAD

**Issue by iulianbarbu** [firecracker-microvm/firecracker#1467]
In #1434 we've added support for `sigrtmin()` and `sigrtmax()` (base signums for real-time signals) inside Firecracker. I've raised https://github.com/rust-vmm/vmm-sys-util/issues/63  which asks for exporting these methods, which would ideally dissolve the support for these methods from within Firecracker. Raised this issue here for visibility.

**Comment by andreeaflorescu** [comment]
This is already merged and published in vmm-sys-util version 0.3.1. We just need to update the version and use them from there.
