### ISSUE TITLE
Broken link for firecracker binaries in getting started

### ISSUE THREAD

**Issue by mziyabo** [firecracker-microvm/firecracker#1469]
Small update required for:
Link for the firecracker binary in [Getting Started](../blob/master/docs/getting-started.md) under [Getting the binary section](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#getting-the-firecracker-binary) - link leaves out the binary's architecture

- Download will work fine but a `Command Not Found` exception occurs when you later try to run the binary

Suggest a **note** perhaps OR including the architecture in the  link, e.g.:
curl -LOJ https://github.com/firecracker-microvm/firecracker/releases/download/${latest}/firecracker-${latest}-$(uname -m)

**Comment by dianpopa** [comment]
Hi @mziyabo ,

Indeed, the link to the binary is outdated. Including the architecture in the link, just like you suggested, solves the `not found` issue. 
Would you mind posting a PR with this?
