### ISSUE TITLE
Seccomp compiles bpf many times

### ISSUE THREAD

**Issue by petreeftime** [firecracker-microvm/firecracker#1475]
Each `SeccompFilter::apply` operation ends up creating a new BPF program from the filter definition and only then applying it. Since the same filter is applied to multiple vCPU threads, the BPF program should be compiled once and re-used.

**Comment by andreeaflorescu** [comment]
We don't actually want to apply the same seccomp filter to all threads. See issue: https://github.com/firecracker-microvm/firecracker/issues/1178

We can probably still do some optimizations there.

**Comment by petreeftime** [comment]
vCPU threads would still get the same filter, and there's many of those.

**Comment by andreeaflorescu** [comment]
We should update the description to make sure we mention "vCPU" threads. There are other threads in Firecracker and it is confusing when you say we want to apply the same filters on all threads.

**Comment by andreeaflorescu** [comment]
We can prioritize this as part of #1177
