### ISSUE TITLE
Unable to start firecracker using jailer with the --config-file option

### ISSUE THREAD

**Issue by Athinivas** [firecracker-microvm/firecracker#1477]
We have been trying to start firecracker using jailer binary. 

We are facing the following issue, only while passing the config-file option as extra argument for the jailer.

**Command used:**
`sudo ./jailer --id 157 --node 0 --exec-file "firecracker" --uid 1000 --gid 1000 --chroot-base-dir /home/test/jailer_home -- --config-file "/home/test/config.json"`

PS: Attached the config.json file used for booting the firecracker.

> We are getting the following error:
> 2019-12-26T13:42:56.951411667 [anonymous-instance:ERROR:src/main.rs:62] Firecracker panicked at 'Unable to open or read from the configuration file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
> 2019-12-26T13:42:56.952144082 [anonymous-instance:ERROR:src/main.rs:72] stack backtrace:
>    0: <no info> (0x40333e)
>    1: <no info> (0x560a37)
>    2: <no info> (0x5607de)
>    3: <no info> (0x56b416)
>    4: <no info> (0x57552c)
>    5: <no info> (0x577f26)
>    6: <no info> (0x40250e)
>    7: <no info> (0x57ff53)
>    8: <no info> (0x40e1aa)

**Note:** We are using the firecracker & jailer 0.19.1 release

### Could anyone share some information on what's wrong with the supplied command.

Thanks,
Athi
[vm_config.txt](https://github.com/firecracker-microvm/firecracker/files/4002838/vm_config.txt)

**Comment by christian7007** [comment]
The config file must be inside `chroot_dir` in your case something like `/home/test/jailer_home/firecracker/<id>/root` as the jailer isolate the firecracker process before starting it. You can find more info here: https://github.com/firecracker-microvm/firecracker/blob/777e366329c48764db51325eda241943ca485d97/docs/jailer.md#jailer-operation.

Also note that kernel image and file system should be in the same directory (`chroot_dir`) in order that the firecracker process can find them.

I used this script to test the microVMs deployment, maybe it's useful to you.
```
#!/bin/bash

VM_ID=$1
CHROOT_PATH=/srv/jailer/firecracker/$VM_ID/root

# Create chroot path
mkdir -p $CHROOT_PATH

# Copy deployment file + kernel + fs (hard link will also works)
cp hello-* config.file $CHROOT_PATH

#Check permissions (maybe is better changing the owner)
chmod o+x $CHROOT_PATH/hello-vmlinux.bin
chmod o+w $CHROOT_PATH/hello-rootfs.ext4

jailer --id $VM_ID --node 0 --exec-file $(which firecracker) --uid 1000 --gid 1000 -- --config-file config.file
```

**Comment by Athinivas** [comment]
@christian7007 Thanks a lot.
