### ISSUE TITLE
Fix rescan_block_device() to update disk_nsectors.

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1511]
The `rescan_block_device` function (which can only be triggered after the guest has booted up) does not update `disk_nsectors` field. This field is used in the `process_queue` so it is vital to the good functioning of the block's transport requests.
The change fixing this bug should also make sure this duplicated warning ([here](https://github.com/firecracker-microvm/firecracker/blob/refactoring/epoll_handler/src/devices/src/virtio/block.rs#L509) and [here](https://github.com/firecracker-microvm/firecracker/blob/refactoring/epoll_handler/src/vmm/src/controller.rs#L88)) gets deduplicated and is used both when `Block::new` is created and also at `rescan_block_device`.

**Comment by ioanachirca** [comment]
Rescanning a block device can be done through a PATCH /drives API call.
More details can be found at `docs/api_requests/patch-block.md`.
