### ISSUE TITLE
Measuring perf counters inside microVM

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker#1519]
Hi,

I have a C program that runs 10x slower when I fix the memory size of the microVM to 2GB in comparison to 8GB. The program itself uses 1MB of memory. I tried to use perf events inside the microVM but it seems like not every event is supported in alpine. What would be a good tool/way to measure the performance counters in the microVM? 

Thanks,
Anjali

**Comment by serban300** [comment]
@Anjali05 you could try profiling both the guest and the host using `perf kvm`. Please take a look on this [issue](https://github.com/firecracker-microvm/firecracker/issues/1153) for more details.

**Comment by iulianbarbu** [comment]
Hi, @Anjali05 ! Have you managed to profile your program on guest and host using `perf kvm`?

**Comment by aghecenco** [comment]
Closing as inactive, @Anjali05 please reopen if any new info is available.
