### ISSUE TITLE
Investigate block device performance.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#1529]
Previous benchmarks showed low performance when running a 4K random read test with fio.

We need to measure current I/O performance with different block sizes on the refactoring/epoll branch, identify possible bottlenecks and  options for improving performance.

**Comment by dianpopa** [comment]
We should keep in mind that these tests also need to be exercised on aarch64.

**Comment by sandreim** [comment]
There are multiple issues which bring down the overall performance of our block device emulation. I am listing them below sorted by their impact (from high to low):
- Serial block file I/O
- Guest interrupt rate
- Double processing of virtio descriptors (in parse() and execute())

1. Serializing the block file I/O also serializes the latencies of each IO request resulting in very low throughput (4-5k IOPS) on nvme SSDs. This also temporarly blocks our emulation thread, meaning increased latency in all other emulated devices.

Possible solutions:
- Implement AIO (io_submit) which is available since Linux 2.5.x
- Implement io_uring (Linux 5.1+) - https://lwn.net/Articles/776703/

2. An increased guest interrupt rate adds significant overhead in the guest due to frequent context switches.  
Possible solutions: driver and device event suppression / Interrupt mitigation

**Comment by andreeaflorescu** [comment]
@sandreim do we already have an issue for improving block performance?

**Comment by sandreim** [comment]
@andreeaflorescu Yes we do have #1600.
