### ISSUE TITLE
[GuestMemory] add guard pages to mmaped regions

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1533]
Add guard pages to mmaped regions in order to prevent read/write ops outside of the regions

We should implement this in `rust-vmm/vm-memory` if possible.

**Comment by andreeaflorescu** [comment]
@serban300 can you please open an issue in vm-memory as well to check with the maintainers if this is something they want tot do?

**Comment by serban300** [comment]
> @serban300 can you please open an issue in vm-memory as well to check with the maintainers if this is something they want tot do?

I opened an issue in `rust-vmm/vm-memory`

**Comment by serban300** [comment]
I created a draft PR in `rust-vmm/vm-memory` : https://github.com/rust-vmm/vm-memory/pull/77

**Comment by berciuliviu** [comment]
Merged in PR #2377.
