### ISSUE TITLE
Add documentation for running Firecracker with gnu build

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1535]
The seccomp filters are tailored for the Firecracker musl build. We should specify how to run Firecracker when building it with gnu as well.

Requested by @rbrasga in https://github.com/firecracker-microvm/firecracker/issues/1515#issuecomment-576463657

**Comment by alindima** [comment]
See: https://github.com/firecracker-microvm/firecracker/blob/main/docs/seccomp.md

> On experimental GNU targets, there are no default seccomp filters installed, since they are not intended for production use.

Alternatively, one may use seccompiler and the --seccomp-filter parameter to supply a custom filter to Firecracker, that can be tailored for glibc
