### ISSUE TITLE
micro_http: missed to remove dead fds from epoll target list.

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [firecracker-microvm/firecracker#1541]
Hi team, in this line https://github.com/firecracker-microvm/firecracker/blob/ebc15f2eacaa4c26782a05f8e0cebe4c47512553/src/micro_http/src/server.rs#L369 we have removed dead connections but we have not removed the dead connections fds from epoll targets list.

**Comment by iulianbarbu** [comment]
@KarthikNedunchezhiyan, I do not think this is necessary. When dead connections are removed from the connections vector, these connections, which are wrappers over `UnixStream`, will get out of scope and will be destroyed. Having so, the data pertaining to these connections will get destroyed also, which means the `UnixStream` (wrapper over `Socket`, which is wrapper over `FileDesc`), that gets registered to the epoll, will be closed. When a file descriptor is closed, and there is no other file descriptor opened for that specific opened file, the event for the specified file descriptor will be removed from epoll. You can find a related explanation in the [epoll man page](http://man7.org/linux/man-pages/man7/epoll.7.html), at _Questions and answers_ chapter, question 6.
