### ISSUE TITLE
[GuestMemory] use the GuestMemory traits instead of the GuestMemoryMmap struct where possible

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1544]
Right now we're always using the `GuestMemoryMmap` concrete implementation. Try to use the `GuestMemory` interface instead where possible.

This is not needed for the migration to `rust-vmm/vm-memory`.

**Comment by AlexandruCihodaru** [comment]
Our implementation is still dependent on our custom crate and we can not easily do this.
