### ISSUE TITLE
FAQ fix: initrd issue resolved

### ISSUE THREAD

**Issue by tidux** [firecracker-microvm/firecracker#1554]
Closing https://github.com/firecracker-microvm/firecracker/issues/208 indicates the FAQ should be updated to confirm that initrds are supported now.

**Comment by dianpopa** [comment]
Thanks @tidux for the issue! Indeed [this part of the FAQ](https://github.com/firecracker-microvm/firecracker/blob/master/FAQ.md#i-tried-using-an-initrd-for-boot-but-it-doesnt-seem-to-be-used-is-initrd-supported) is outdated.

**Comment by tidux** [comment]
https://github.com/firecracker-microvm/firecracker/pull/1561
