### ISSUE TITLE
DescriptorChainTooShort and silent virtio block device data corruption

### ISSUE THREAD

**Issue by smira** [firecracker-microvm/firecracker#1560]
This issue appears to be fixed in `master` branch with PR #1497, not sure if that was intentional (bug not mentioned) or just happened by coincidence. But as this bug existed as of yesterday and in the current release, I thought I should share the details.

In VM logs, this bug looks like the following:

```
instance:ERROR:src/devices/src/virtio/block.rs:374] Failed to parse available descriptor chain: DescriptorChainTooShort
```

tl;dr is that `checked_range_offset` function has off-by-one comparison bug which discards valid buffers and drops some read (or) write requests which eventually leads to filesystem corruption (if write requests are dropped).

Long version:

There are three places in `parse` function which might return `DescriptorChainTooShort` error, I found out it was returned from:

```rust
        let data_desc;
        let status_desc;
        let desc = avail_desc
            .next_descriptor()
            .ok_or(Error::DescriptorChainTooShort)
```

So the next buffer after the header doesn't have next. 

Function `next_descriptor` depends on `has_next()`:

```rust
    /// Gets if this descriptor chain has another descriptor chain linked after it.
    pub fn has_next(&self) -> bool {
        self.flags & VIRTQ_DESC_F_NEXT != 0 && self.ttl > 1
    }
```

But this descriptor has next flag set and ttl was always pretty high.

Next thing `next_descriptor()` depends on is `chained_new()` which itself returns `None` is built descriptor chain is `!is_valid()`.

`is_valid()` was defined as:

```rust
    fn is_valid(&self) -> bool {
        !(self
            .mem
            .checked_range_offset(self.addr, self.len as usize)
            .is_none()
            || (self.has_next() && self.next >= self.queue_size))
    }
```

Condition `(self.has_next() && self.next >= self.queue_size)` was fine, so looked like `checked_range_offset(self.addr, self.len as usize)` returned `None.

I inspected the actual buffer address and length and noticed that all of the problematic buffers laid exactly at the guest address space boundary (1536MB or 0x60000000):

E.g.:

```python
>>> hex(1609826304 + 786432)
'0x60000000'
```

Function `checked_range_offset` had following source code:

```rust
    /// Returns the address plus the offset if base and the result belong to the same memory
    /// region (Firecracker currently does not use adjacent memory regions, so distinct regions
    /// always have a gap in-between).
    pub fn checked_range_offset(&self, base: GuestAddress, offset: usize) -> Option<GuestAddress> {
        if let Some(addr) = base.checked_add(offset as u64) {
            for region in self.regions.iter() {
                let last_addr = region.last_addr();
                if base >= region.guest_base
                    && base <= last_addr
                    && addr >= region.guest_base
                    && addr <= last_addr
                {
                    return Some(addr);
                }
            }
        }
        None
    }
```

Code looks fine at the first glance, but if you look how `region.last_addr()` is defined:

```rust
    fn last_addr(&self) -> GuestAddress {
        // unchecked_add is safe as the region bounds were checked when it was created.
        self.guest_base
            .unchecked_add((self.mapping.size() - 1) as u64)
    }
```

It returns address of the last bye of the region, which is off by one with `start + offset`. So check `addr <= last_addr` discarded perfectly valid buffers, as `addr == start + size`, while `last_addr = start + size - 1` basically.

In our case, this error leads to xfs data corruption during periods of high I/O.

**Comment by dianpopa** [comment]
Hi @smira,

Thanks for the deep insight and please, accept my apology for such a late answer. Indeed, this issue was fixed by #1497 came as a fix to issue https://github.com/firecracker-microvm/firecracker/issues/1296 which was discovered in a similar situation as this one: "investigating intermittent block device failures on a custom kernel build". 
Hopefully, everything works good now. Feel free to open this issue if other clarifications are needed.
