### ISSUE TITLE
Some of our example guests incorrectly shut down

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1564]
Some of the guests `rootfs`s that we use (for example the Alpine one) do not correctly flush guest disks on shut-down leading to sporadic file-system inconsistencies for RW drives.

We need to fix/replace them with correct ones.

**Comment by rpaul98** [comment]
Hi, @edengarza, @amaniduncker, and I are students at UT and are looking to contribute to an open source project for our virtualization class. We were wondering if we could get assigned to this issue.

Thanks!

**Comment by serban300** [comment]
Hi ! Sure, I assigned you to the issue. Please let us know if you need any help here.

**Comment by acatangiu** [comment]
Looks like this issue is stale, none of the currently used rootfs images surfaced this behavior. Closing.
