### ISSUE TITLE
Enable unit tests to run in parallel

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1569]
This is a milestone-like issue for tracking the fixes we need to do to in order to run the unit tests in parallel:
- [ ] #1568 
- [x] #4412
- TBD

**Comment by roypat** [comment]
I'm closing this as subsumed by https://github.com/firecracker-microvm/firecracker/issues/4709, which is a more up-to-date list of which tests prevent parallel unittests execution
