### ISSUE TITLE
[Devices] virtio memory balloon

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1571]
Adding support for a memory balloon device will allow Firecracker users to reclaim memory unused by their guests.

We should emulate a `virtio-balloon` device as described in the `VIRTIO` spec.

More details on memory ballooning concept [here](https://en.wikipedia.org/wiki/Memory_ballooning).

Related issues: #1570

**Comment by aghecenco** [comment]
Previously prototyped in #1198

**Comment by dianpopa** [comment]
Memory ballooning is in production as of [release v0.24.0](https://github.com/firecracker-microvm/firecracker/releases/tag/v0.24.0).
