### ISSUE TITLE
vsock: Connection broken when EPOLLHUP or EPOLLERR happens

### ISSUE THREAD

**Issue by sboeuf** [firecracker-microvm/firecracker#1572]
I have been debugging an issue pretty hard to reproduce on Kata Containers + Cloud-Hypervisor. The reason why I'm filing a bug here is because I think the culprit is the `vsock` device from Firecracker, which had been previously ported over to Cloud-Hypervisor.

Whenever an event is triggered on the `epoll::wait()` loop, if it is related to the backend, the muxer will get notified [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/epoll_handler.rs#L192), with the corresponding `evset`. The muxer then waits onto its own epoll loop [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/unix/muxer.rs#L277), and handle the events accordingly. The problem comes from the case of an `EPOLLHUP` and/or `EPOLLERR` event coming up from one of the registered `fd`s. In these cases, the muxer still tries to handle the event, but I think it shouldn't.

To give a bit more details, from `strace` I can see the event being `EPOLLIN|EPOLLHUP|EPOLLERR`, and right after I can see a `recvfrom()` failing badly with the following log:
```
epoll_wait(24, [{EPOLLIN|EPOLLERR|EPOLLHUP, {u32=12, u64=12}}], 32, 0) = 1
recvfrom(12, 0x7f2a27ed0000, 4096, 0, NULL, NULL) = -1 ECONNRESET (Connection reset by peer)
```
The `epoll_wait` is the one from [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/unix/muxer.rs#L277), and the `recv_from()` is the result from [conn.notify()](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/unix/muxer.rs#L346) calling into [this](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/csm/connection.rs#L417). So basically, the code registers a new pending rx from this event, which will imply the code to try to read from this chain of calls: [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/epoll_handler.rs#L200) ==> [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/epoll_handler.rs#L84) ==> [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/unix/muxer.rs#L155) ==> [here](https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/vsock/csm/connection.rs#L220).
Once the read happens, the `recv_from()` is triggered and fails because the connection has been previously reset. Because of this error, the thread gets killed and this leads to an unrecoverable situation.

With the following patch (probably not the right way to handle properly the issue), I never run into the issue again:
```diff
diff --git a/vm-virtio/src/vsock/unix/muxer.rs b/vm-virtio/src/vsock/unix/muxer.rs
index 2e6f894..b3c3eea 100644
--- a/vm-virtio/src/vsock/unix/muxer.rs
+++ b/vm-virtio/src/vsock/unix/muxer.rs
@@ -288,6 +288,10 @@ impl VsockEpollListener for VsockMuxer {
             Ok(ev_cnt) => {
                 #[allow(clippy::needless_range_loop)]
                 for i in 0..ev_cnt {
+                    if epoll_events[i].events & epoll::Events::EPOLLHUP.bits() == epoll::Events::EPOLLHUP.bits() ||
+                        epoll_events[i].events & epoll::Events::EPOLLERR.bits() == epoll::Events::EPOLLERR.bits() {
+                            continue;
+                    }
                     self.handle_event(
                         epoll_events[i].data as RawFd,
                         // It's ok to unwrap here, since the `epoll_events[i].events` is filled
```

I'm looking for some guidance here on what might be the best way to fix this problem :)

**Comment by dhrgit** [comment]
@sboeuf thanks for the thorough analysis!

A failing `recvfrom` shouldn't kill the thread, though. The error should be handled [here](https://github.com/firecracker-microvm/firecracker/blob/1eb80f8d1bbe9287cafdedebaee3fb604095fac6/src/devices/src/virtio/vsock/csm/connection.rs#L239), leading to an immediate forceful termination of the connection (i.e. send an `RST` to the guest and then remove it from `Muxer::conn_map`).

What's the final outcome? Does the Firecracker process crash? If so, is there any more interesting info showing up in the trace?

**Comment by sboeuf** [comment]
@dhrgit after more investigation with @rbradford, we realized the problem was coming from the [error!()](https://github.com/firecracker-microvm/firecracker/blob/1eb80f8d1bbe9287cafdedebaee3fb604095fac6/src/devices/src/virtio/vsock/csm/connection.rs#L242-L245) as this was printing to Kata-Containers stderr, but it was hitting a broken pipe (`-EPIPE`). And because this was ending up on an `expect!()` call, the whole vsock thread was destroyed.

That being said, it's still kind of weird that we read from the stream even if we got `EPOLLHUP` and `EPOLLERR` alongside with `EPOLLIN`, don't you think?

**Comment by dhrgit** [comment]
My reasoning for not handling `EPOLLERR` and `EPOLLHUP` specifically was that these two events don't bring any new information, per se. I.e. the condition that would have caused an `EPOLLERR` is handled as part of the `read` / `write` failures. Similarly, for `EPOLLHUP`, we handle 0-length reads.

So, handling `EPOLLERR` / `EPOLLHUP` specifically would lead to having two code paths for the same condition.

**Comment by sboeuf** [comment]
Ok I understand, thanks for the explanation :)
