### ISSUE TITLE
Networking support is limited to using TUN/TAP host-side

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#158]
Most likely we will need to support using 'generic' interfaces on the host as backing devices for our guest emulated network interfaces.

This means being able to use physical interfaces (ethX) as well as virtual interfaces;

Currently supported list:

- [ ] physical (ethx)
- [x] tun/tap
- [ ] IPsec, PPPoE, GRE
- [ ] VLANs

**Comment by weixiao-huang** [comment]
Now it seems firecracker only support tuntap, so is there a plan to support other network like vlan/vxlan ?

**Comment by acatangiu** [comment]
@weixiao-huang no plan to support other network devices. If we find a customer need for that, we will revisit our decision.

**Comment by casibbald** [comment]
@acatangiu Adrian, has there been any update on the IO Virtualisaton supported list?

[ ] physical (ethx)
[x] tun/tap
[ ] IPsec, PPPoE, GRE
[ ] VLANs

**Comment by acatangiu** [comment]
@casibbald no changes, we haven't heard of a strong customer usecase that needs something else here.

There is an RFC #2217 for also supporting _macvtap_ that we're currently evaluating.
