### ISSUE TITLE
Promethium - Lightweight self contained manager for Firecracker

### ISSUE THREAD

**Issue by spuddleziz** [firecracker-microvm/firecracker#1582]
WARNING! Very very alpha and needs significant work but it will boot and manage VMs, images.

Tested it with OSv as well. Please see below, thought I would post here in case anyone is interested in playing with it.

Inspired heavily by Libvirt and Proxmox but designed to be as lightweight as possible.

Firecracker and Jailer v0.20.0 embedded in binary.

https://github.com/768bit/promethium/releases/tag/v0.2.0

I hope to get a number of things resolved in the next month and hopefully get a usable beta out very soon.

**Comment by raduweiss** [comment]
Very cool! We're glad that Firecracker is useful to other open source projects 👍 💯.

**Comment by alindima** [comment]
> Let us know if there's anything we can help with!

Thank you and let us know if anything comes up
