### ISSUE TITLE
Investigate random failures during PR tests

### ISSUE THREAD

**Issue by gc-plp** [firecracker-microvm/firecracker#1596]
Occasionally we see that the PR tests fail due to reasons that are not related to the changed code itself.

We should investigate and fix this.

**Comment by dianpopa** [comment]
We are currently investigating frequent failures seen in `test_multiple_microvm_boottime_no_network` and/or `test_multiple_microvm_boottime_with_network`. @gc-plp please post here the results of the invstigation.

**Comment by acatangiu** [comment]
#1669 fixed most of the failures, but I think there still are some elusive ones.

Closing this for now, we can reopen when someone sights Bigfoot again.
