### ISSUE TITLE
Research performance impact of different VM topologies

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1599]
Our setup of cache topology (at least on x86_64) is kinda dummy.

At the end of the [Automated Performance TestingFor Virtualization with MMTests](https://fosdem.org/2020/schedule/event/testing_automated_performance_testing_virtualization/attachments/slides/3926/export/events/attachments/testing_automated_performance_testing_virtualization/slides/3926/Automated_Performance_Testing_for_Virtualization_with_MMTests.pdf) there are some slides with performance benchmarks where they show the difference between host, VM with no topology, VM with topology and VM with a tuned topology.

We should measure this in Firecracker as well and see if we should also tweak our cache topology.

**Comment by sandreim** [comment]
The benchmarks are pretty useful here just to get some head start into what to expect. We can try similar benchmarks these in high density environments (1000+ uVMs) where the main focus should be CPU oversubscription.

**Comment by zulinx86** [comment]
FYI: stress-ng has `cpu-cache` class, which might be available to measure the performance impact.
https://manpages.ubuntu.com/manpages/xenial/man1/stress-ng.1.html
