### ISSUE TITLE
Fircracker will crash when receving a signal

### ISSUE THREAD

**Issue by raduiliescu** [firecracker-microvm/firecracker#1604]
Send any signal to a running Firecracker and it will crash with epoll interrupted error.
Epoll can be interrupted by signals and returns -EINTR. This should be not treated as error.

One related issue is that you are unable to do gdb attach.

**Comment by dianpopa** [comment]
This seems to be a duplicate of a very old issue: #197. Since Firecracker has undergone massive refactoring since then, I will leave this one open as latest reference.

**Comment by acatangiu** [comment]
Duplicate of #197
