### ISSUE TITLE
CI failures - Error accessing Docker

### ISSUE THREAD

**Issue by raduiliescu** [firecracker-microvm/firecracker#1615]
There is a high number of CI failures with following error - currently from 13 PR 4 are affected by this.
_[Firecracker devtool] Error accessing Docker. Please make sure the Docker daemon is running and that you are part of the docker group. For more information, see https://docs.docker.com/install/linux/linux-postinstall/_

Happens mostly on X86

**Comment by dianpopa** [comment]
Issue was solved by changes in the CI framework.
