### ISSUE TITLE
Add tests for vmm::lib.rs

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1624]
The Vmm now exposes a crisp and simple programmatic interface for microVm runtime operations.
We should add unit tests for those functions where it makes sense (some might be better tested with integration tests).

**Comment by iulianbarbu** [comment]
The units from `vmm::lib.rs` are tested through integration tests. I've identified the following units, and I think we have thorough integration tests which test the functionality:

- `pub fn get_bus_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<dyn BusDevice>>` which is a wrapper over `MmioDeviceManager::get_bus_device`, which is tested as a unit inside tests for `device_manager/mmio.rs`.

- `pub fn start_vcpus(
        &mut self,
        mut vcpus: Vec<Vcpu>,
        vmm_seccomp_filter: BpfProgram,
        vcpu_seccomp_filter: BpfProgramRef,
    ) -> Result<()>` which is used every time we build and start a microVM, basically in every integration test which boots a kernel.

- `pub fn resume_vcpus(&mut self) -> Result<()>` used inside `Vmm::start_vcpus`.

- `pub fn configure_system(&self, vcpus: &[Vcpu], initrd: &Option<InitrdConfig>) -> Result<()>` used every time we build and start a microVM, for x86_64 and aarch64 respectively.

- `pub fn send_ctrl_alt_del(&mut self) -> Result<()>` tested by `functional/test_api::test_send_ctrl_alt_del`.

- `pub fn stop(&mut self, exit_code: i32)` tested by `functional/test_api::test_send_ctrl_alt_del`, when rebooting.

- `fn log_boot_time(t0_ts: &TimestampUs)` tested by `performance/test_bootime`.
