### ISSUE TITLE
Add --license command line argument

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1628]

**Comment by Zyqsempai** [comment]
Hey, I would love to try to work on this one, can you provide some more details?

**Comment by andreeaflorescu** [comment]
Hey @Zyqsempai. We are not yet decided how we want to implement this and it might require changes to our CI pipelines. Are you interested in contributing to another issue? If you ping me on Slack/email we can find something else.

**Comment by Zyqsempai** [comment]
@andreeaflorescu Got it, thanks, i will try to find something in issues.

**Comment by alindima** [comment]
We now release binaries in an archive containing the associated license
