### ISSUE TITLE
Guest kernel hangs during architected timer initialization on aarch64

### ISSUE THREAD

**Issue by nspin** [firecracker-microvm/firecracker#1634]
For certain platforms and host kernel configurations on aarch64, the guest kernel hangs during [`arch_timer_of_init`](https://elixir.bootlin.com/linux/v5.6-rc3/source/drivers/clocksource/arm_arch_timer.c#L1246). I encountered this issue using the pre-built Firecracker 0.21.0 binary distributed from this repository.

Here is an example log: [log.txt](https://github.com/firecracker-microvm/firecracker/files/4258703/log.txt). That includes both Firecracker log output with `"level": "Debug"` and guest kernel output with `loglevel=8`. Using GDB, I've determined that the guest kernel hangs during `arch_timer_of_init`, but I haven't figured out why. The point during that function at which the guest kernel hangs varies, and seems to depend on the timing of some asynchronous event.

I've encountered this issue with a variety of platform/host kernel configuration pairs, all resulting in a log similar to the above. First, on `qemu-system-aarch64 -machine virt` with host Linux at `5.6.0-rc3` built with `defconfig`, and then on a Raspberry Pi 4 with host Linux at `rpi-5.6.y` built with `bcm2711_defconfig` (augmented with some KVM-related options). After hearing that Firecracker works on aarch64 on Ubuntu 19.10 for the Raspberry Pi 4, I built a host kernel similar to that which ships with Ubuntu 19.10 for the Raspberry Pi 4. The guest did not hang under this host. I then built a very similar kernel to run on `qemu-system-aarch64 -machine virt` (only adding some virtio-related options, and building the same version from mainline instead of the Raspberry Pi tree). A guest running under this host on `qemu-system-aarch64 -machine virt` hung during `arch_timer_of_init` just as before.

For guest kernels, I've tried both `5.6.0-rc3` built with `defconfig` and `4.14.0` built with the recommended configuration provided by this repository.

The details of the conditions of these failures can be found in this repository: [nspin/firecracker-repro](https://github.com/nspin/firecracker-repro). It includes all kernel versions and configurations, along with QEMU invocations, Firecracker invocations, and userlands.

I can spend more time in GDB to narrow in on the issue here. Does anyone more familiar with the Firecracker on aarch64 effort so far have ideas on what might be the cause? Has anyone successfully booted a microvm with `qemu-system-aarch64 -machine virt` as the host platform?

**Comment by andreeaflorescu** [comment]
Hey @nspin. We haven't try running on `qemu-system-aarch64 -machine virt`.
We will start investigate this most likely on Monday and post our findings here.

**Comment by nspin** [comment]
Thanks @andreeaflorescu! I'll be available on Slack to take part in the investigation.

**Comment by aghecenco** [comment]
Hey @nspin, thanks for the extensive info! Just to clarify - are you encountering the error when:
a) trying to run nested (firecracker guest over qemu guest over metal) or
b) comparing a firecracker guest with a qemu guest?

**Comment by nspin** [comment]
Hi @aghecenco, I'm encountering this issue in case (a) (firecracker host + guest running in an virtual machine emulated by `qemu-system-aarch64 -machine virt` on an x86 host). I'm also encountering this same issue directly on the Raspberry Pi 4 (no QEMU) with certain host kernel configurations.

**Comment by aghecenco** [comment]
For the nested use case, we don't officially support running nested - it's been attempted several times and successful on a few platforms, but Firecracker is only qualified on baremetal. On the RPi, do you mean you see this issue when the host boots or when the Firecracker guest on the metal RPi boots? It sounds like a kernel issue nonetheless; could you please post detailed repro steps for this use case?
* host kernel config
* guest kernel config
* rootfs resources, if available
* build steps starting from the nix scripts

**Comment by nspin** [comment]
I observed this issue while the Firecracker guest was booting.

I've messed around a bit more and found that Firecracker works fine on the Raspberry Pi 4 with _mainline_ `5.6.0-rc3` and `defconfig`. Furthermore, I'm having trouble reproducing this issue on the Raspberry Pi 4 at all. It's possible that the time I observed this issue on the Raspberry Pi 4 was under some mistaken conditions not recorded in my repository, such as a kernel/Kconfig mismatch. My focus was on QEMU and I was more treating the Raspberry Pi 4 more as a baseline.

The issue under QEMU remains, but it seems that's out of scope. I may investigate further anyways, and will report back if I find anything interesting. Also, I'll try a bit more to figure out under what conditions I observed this issue on the Raspberry Pi 4.

Sorry for the bother!

**Comment by aghecenco** [comment]
Thanks @nspin! We'll close this for now as there's nothing needed from our side - if you find anything that we can help with, please feel free to reopen this issue. And if you come across something interesting in your investigation, it would be great if you'd consider a PR to update one of the docs [[1]](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md), [[2]](https://github.com/firecracker-microvm/firecracker/blob/master/FAQ.md) :beer:
