### ISSUE TITLE
Add support for starting VMs with more than 32 vCPUs

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1640]
Currently we support at most 32 vCPUs. Increase the limit to at least 128 vCPUs .

**Comment by alindima** [comment]
Closing it for now, as we don't have a clear need for it

**Comment by alexellis** [comment]
Hi @serban300 @alindima is there anything required to go beyond the soft limit of 32 vCPU?

The Q80 model of Ampere Altra aarch64 servers have 80 Cores available, and any workload such as compiling a Kernel gets artificially limited to < 50% of the potential build speed.

**Comment by sudanl0** [comment]
> Hi @serban300 @alindima is there anything required to go beyond the soft limit of 32 vCPU?
> 
> The Q80 model of Ampere Altra aarch64 servers have 80 Cores available, and any workload such as compiling a Kernel gets artificially limited to < 50% of the potential build speed.

Hi @alexellis,
I think [this](https://github.com/firecracker-microvm/firecracker/discussions/3092#discussioncomment-6966073) answers your question.
