### ISSUE TITLE
Investigate possibilities for VM unique identifier

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1643]
In the context of snapshotting, Firecracker needs to provide a mechanism to let the guest know if it's been resumed from a previous snapshot.

Such a mechanism is required so that guests can:
- reseed their randomness sources
- invalidate/refresh any crypto-sensitive workloads
- take any required action around network connections

**Comment by dianpopa** [comment]
This is related to snapsafe story and we already have issues that detail the support: https://github.com/firecracker-microvm/firecracker/issues/2546 and https://github.com/firecracker-microvm/firecracker/issues/2476.
