### ISSUE TITLE
strip firecracker release binary

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1652]
Looks like simply calling `strip` on the firecracker release binary reduces the size from 2.5 MB to 1.4 MB. Investigate if this affects in any way the functionality.

**Comment by sandreim** [comment]
IMO this will affect debugability by less detailed or useless backtraces, but it should not affect any functionality. I am not sure if it is possible with rust, but if it's done at compile time it can boost performance.

**Comment by raduweiss** [comment]
Yeah, according to the `strip` command's description, the ability to interpret back/stack traces is affected. But, what do we gain? Does the binary size reduction also result in memory usage reduction? If not, does the binary size reduction help in any other way?

**Comment by petreeftime** [comment]
Probably `strip --strip-debug --discard-locals` is a better option than what `strip` does by default for production builds. You can still get some useful information from stack traces that way.

**Comment by serban300** [comment]
@raduweiss in this case the binary size reduction doesn't result in a memory usage reduction. It's only a disk size optimization. Does this bring any value ? If not, we can close the issue.

**Comment by acatangiu** [comment]
Closing this issue as we yet have no indicators for relevant positive gains which would result from stripping the firecracker release binary.

We can reopen if later needed.

**Comment by iulianbarbu** [comment]
Reopening this.

**Comment by iulianbarbu** [comment]
The PR was merged.
