### ISSUE TITLE
Add `at least one root block device` check in firecracker

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [firecracker-microvm/firecracker#1659]
In the firecracker, we need to check whether the user has supplied at least one root block device and throw an appropriate error message if not provided.

In current flow, if the user has not supplied any root block device he will end up in kernel panic like below.

> [    0.145223] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
> [    0.146475] Please append a correct "root=" boot option; here are the available partitions:
> [    0.147855] fe00           30720 vda 
> [    0.147857]  driver: virtio_blk
> [    0.149050] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

But recent versions of firecracker support initrd. Users may handle rootfs mounting logic there 😕. Need to find a way to handle this elegantly.

**Comment by acatangiu** [comment]
@KarthikNedunchezhiyan are you interested in contributing with a fix to this issue? We can discuss a strategy together if that's the case.

**Comment by acatangiu** [comment]
Actually, thinking about this more, I think we don't even need such a check. Having a root device or not is an optional use-case-specific choice.

For example users of Firecracker which boot unikernels might not want any block device.

I believe the current Firecracker behavior of not enforcing such requirements is actually the correct one.

**Comment by acatangiu** [comment]
Closing this. Anyone, feel free to open if needed.
