### ISSUE TITLE
Test performance when spawning a high number of microVMs

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#1665]
Find a way to ensure that boot time, process start up etc stays within a desired range even when a high number of microVMs (>1000) are spawned on a metal machine.
The current method of doing this has proven to be unreliable and not very helpful since we only spawn 10 microVMs. See https://github.com/firecracker-microvm/firecracker/pull/1664.

**Comment by luminitavoicu** [comment]
We already have other pipelines for ensuring concurrency related tests for Firecracker.
