### ISSUE TITLE
use micro-http from firecracker-microvm/micro-http

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1670]
We have a few PRs touching the micro-http code that were merged to Firecracker. We should first port those PRs and then use it as a crate from firecracker-microvm/micro-http.

To avoid breaking the build, we should either use a specific commit from the micro-http repository, or create a tag and use that. After we publish it to crates.io we will not have that problem any more.

**Comment by andreeaflorescu** [comment]
We need to add epoll to vmm-sys-util before the switch.

**Comment by iulianbarbu** [comment]
> We need to add epoll to vmm-sys-util before the switch.

Is there an issue to track this?

**Comment by lauralt** [comment]
It is already added to vmm-sys-util (https://github.com/rust-vmm/vmm-sys-util/pull/79), but we must wait for a new release to be able to use it.

**Comment by andreeaflorescu** [comment]
Yap, we need a release of vmm-sys-util.

**Comment by aghecenco** [comment]
Coming up.

**Comment by aghecenco** [comment]
`vmm-sys-util` v0.5.0 is released and available on crates.io.

**Comment by lyuyuan** [comment]
Hi, I'd like to help with this issue. To clarify, are the action items basically,
1) remove [firecracker/src/micro_http](https://github.com/firecracker-microvm/firecracker/tree/master/src/micro_http) from firecracker repo, and
2) add [main branch of firecracker-microvm/micro-http](https://github.com/firecracker-microvm/micro-http) in [here](https://github.com/firecracker-microvm/firecracker/blob/5603def16abe3ad0907c94639fa878faee3dd1a8/Cargo.toml#L12-L13)?

**Comment by acatangiu** [comment]
@lyuyuan that's right. You should also make sure to backport any missing commits from Firecracker to the [firecracker-microvm/micro-http](https://github.com/firecracker-microvm/micro-http).

**Comment by lyuyuan** [comment]
There are two dependencies in the micro-http source,
* [`logger::error`](https://github.com/firecracker-microvm/firecracker/blob/d151f7ec2dc577a3efa9962e6a94e94ff763dc2f/src/micro_http/src/server.rs#L4)
* [`utils::epoll`](https://github.com/firecracker-microvm/firecracker/blob/d151f7ec2dc577a3efa9962e6a94e94ff763dc2f/src/micro_http/src/server.rs#L18)

Any suggestions how to make them independent in the micro-http repo?

**Comment by acatangiu** [comment]
Hi @lyuyuan,

- `utils::epoll` is actually a re-export of [vmm-sys-util::epoll](https://github.com/rust-vmm/vmm-sys-util/blob/master/src/linux/epoll.rs) as you can see [here](https://github.com/firecracker-microvm/firecracker/blob/d151f7ec2dc577a3efa9962e6a94e94ff763dc2f/src/utils/src/lib.rs#L9). So you can just use the `vmm-sys-util::epoll`.
- I see `logger::error` is only used in `fn flush_outgoing_writes()`. I suggest we just drop that logger line for now and remove the dependency altogether.
