### ISSUE TITLE
Make the Logger more modular

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#1675]
We should at least decouple the record formatting logic into a different module (e.g. `LogFormatter`). Check if there's anything else that we can do to make the logger more modular.

**Comment by JonathanWoollett-Light** [comment]
A recent refactor in https://github.com/firecracker-microvm/firecracker/pull/4047 significantly simplified the logger, which I believe should address this issue.

Please re-open the issue if you still have outstanding concerns.
