### ISSUE TITLE
Upgrade to vm-memory v0.2.0

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1683]
- [x] Simplify the vsock code. More details here: https://github.com/firecracker-microvm/firecracker/pull/1562/files#r381161195
- [x] Replace struct_util with `BytedValue`. For an example, you can check the PR that introduced this change: https://github.com/rust-vmm/vm-memory/pull/83/files

**Comment by dianpopa** [comment]
Firecracker now uses `vm-memory = { version = ">=0.2.0", features = ["backend-mmap"] }`.

**Comment by andreeaflorescu** [comment]
@dianpopa we still need to do the replacement of BytedValue. We can also open a new issue with that if you think ti makes more sense. What do you say?

**Comment by dianpopa** [comment]
Uh ok I missed the `BytedValue` part. IMO we need more visibility for it, it kind of got lost in this issue so yes, I think it would be better to open a separate issue for this. Thanks!

**Comment by HQ01** [comment]
Interested to help out!

**Comment by yichen-zhang-dev** [comment]
@andreeaflorescu @dianpopa I'm with HQ01. Could you provide any instructions or hints on what needs to be done for the replacement? Thanks.

**Comment by serban300** [comment]
Resolving this issue since #2331 was merged
