### ISSUE TITLE
Remove the `configure` workaround in the logger

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1686]
Once #1361 is merged, we will have the possibility for adding logging from the start of the Firecracker process. With this new feature, we can remove the previous workaround by which the logging would be printed at stdout before the logging is initialized. The workaround was added so that we can have logging from startup which can now be achieved by simply configuring the logger from the start.

One problem that we might face is that when installing the panic hook we don't know if the logger was configured or not. We can workaround this issue, by checking if the logger is configured. If it is not configured, we can just use `println` instead of `error` to print the error message from the panic hook.

**Comment by iulianbarbu** [comment]
I remember that we had some discussions in which it was unclear if checking if the logger is initialized will also initialize it. Just wanted to put this here, because I am unsure if it still stands.

**Comment by serban300** [comment]
I strongly agree that we have to rethink our strategy here, but IMO we should find a solution that involves setting the logger right at the beginning of `main()`. Using `println()` until the logger is initialized still feels like a workaround to me and I think it can turn into a burden in the long run. We'll have to pay attention to this special case whenever we add a piece of code in `main()` . We'll have to be very aware whether the code is added before configuring the logger or after and we'll have to use `println` or `info, warn, error, etc` accordingly. This seems very error prone to me.

As I see it, we need 2 phases anyway:

1. Right at the beginning of `main()` we should set the actual logger (one way or another we have to end up calling `set_logger()`). This logger should be used for the entire lifetime of the application.
2. We should be able to reconfigure some of the parameters of the logger during execution. For example the destination, the format, etc. Which is what we'll also do when we receive the API call.

I don't think that `configure()` is the main issue here. The main issue is the number of `if` branches and special cases. For example:

```
    fn write_log(&self, msg: String, msg_level: Level) {
        if STATE.load(Ordering::Relaxed) == INITIALIZED {
            if let Some(guard) = buf_guard(&self.log_buf).as_mut() {
                // No need to explicitly call flush because the underlying LineWriter flushes
                // automatically whenever a newline is detected (and we always end with a
                // newline the current write).
                if guard.write(&(format!("{}\n", msg)).as_bytes()).is_err() {
                    // No reason to log the error to stderr here, just increment the metric.
                    METRICS.logger.missed_log_count.inc();
                }
            } else {
                METRICS.logger.missed_log_count.inc();
                panic!("Failed to write to the provided log destination due to poisoned lock");
            }
        } else if msg_level <= Level::Warn {
            eprintln!("{}", msg);
        } else {
            println!("{}", msg);
        }
    }
```

This logic should definitely be more generic.

I am trying to address this while working on #1675 . I will assign myself to this issue for the moment.

**Comment by serban300** [comment]
@andreeaflorescu we reduced the number of `if` branches as part of #1701 and  I'm not sure if there's much more we can do here. As I mentioned in the previous comment, from what I understand removing the logger configuration step would generate a lot of special cases and that could turn into a burden in the long run. Is it ok if we close this issue ?

**Comment by andreeaflorescu** [comment]
Sounds good.
