### ISSUE TITLE
Fix unit test coverage for the cpuid crate.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#1705]
The coverage is reported incorrectly as the unit tests are implemented in a `mod test` block instead of `mod tests`. Please see #1704.

src/cpuid/src/transformer/intel.rs
src/cpuid/src/transformer/mod.rs
src/cpuid/src/transformer/amd.rs
src/cpuid/src/transformer/common.rs

**Comment by lauralt** [comment]
Fixed by: #1832.
