### ISSUE TITLE
Decouple Vmm from its Firecracker-specific RPC interface

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1713]
This issue is part of a story that tracks a state where the `vmm` crate is no longer Firecracker-specific.

### Benefits:

- swapping out `Vmm` implementations in Firecracker - the `vmm` crate used in Firecracker could be one from [rust-vmm](https://github.com/rust-vmm).
- upstreaming/outsourcing the current `Vmm` implementation in Firecracker to other projects.
- reducing the barrier-to-entry in Firecracker code-base by having much more contained components.
- clear language-enforced dependencies in the form of crates helps keeping the code clean by forcing contributors to work at the right level with the right resources.

### Scope:

`vmm_config`, `VmResources`, `Pre-boot and Runtime Controllers` and `rpc_interface` to be moved to an external `rpc_interface` crate that depend on `Vmm`. Dependency graph will be:

```
+---------------+     Dependencies
|  Firecracker  |           |
+---------------+           |
|  API Server   |           |
+---------------+           |
| RPC Interface |           |
+---------------+           |
|      Vmm      |           |
+---------------+           V
```

With `Vmm` decoupled from all Firecracker-specific configuration primitives and logic.

**Comment by acatangiu** [comment]
Depends on:

- [ ] #1776 
- [ ] #1777 
- [ ] #1778

**Comment by luminitavoicu** [comment]
We don't have an immediate plan for this. Will reopen in the future if necessary.
