### ISSUE TITLE
use abstract UNIX socket names for api server connection

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [firecracker-microvm/firecracker#1716]
In the current firecracker model, binding socket address for the API server creates a file object in the host machine. This object will not be cleared even after the firecracker instance lifetime. If the user starts the firecracker instance without removing the old object then the user will face `AddrInUse` error. 

To solve this can we use `abstract UNIX socket names` which will be cleared by the kernel as soon as the firecracker instance is killed. WDYT?

Note: We cannot apply `acl` on this method like before.

**Comment by alindima** [comment]
> Note: We cannot apply acl on this method like before.

As you mentioned, permissions handling are indeed an issue in this case. There may be use cases where API socket access needs to be restricted to only certain users.

Another issue with abstract sockets are network namespaces. Firecracker's jailer can be used to create a new network namespace and join it. Creating a net namespace also creates a new abstract socket namespace, so in order for another process to be able to send requests to Firecracker, a host process would need CAP_SYS_ADMIN to join the jailer net namespace.

Even if we were to somehow work around all those issues, this would also be a pretty significant breaking change.

I believe this adds too much trouble for the little added benefit, so I'll close the issue.
