### ISSUE TITLE
Use vmm-sys-util  v0.5.0

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#1734]
As vmm-sys-util v0.5.0 is now released, we can use the epoll wrapper from there and remove the one from our repo.

**Comment by andreeaflorescu** [comment]
I am trying to post a new version of vmm-sys-util soon-ish (in a couple of days) because there are some derives needed by vmm-epoll (see PR: https://github.com/rust-vmm/vmm-sys-util/pull/83). Can we hold off to this switch before the new version is published?

**Comment by lauralt** [comment]
Sure.
