### ISSUE TITLE
Separate Rate Limiter from core virtio implementation

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1758]
Right now the virtio device implementation is tightly coupled with the rate limiter. We should have the rate limiter functionality as a plugin for Virtio Devices for two reasons:
- Separation of concerns. Separate the core emulation from the rate limiter. This should also reduce the duplication of code in Block Devices for example where we parse requests twice.
- Consuming the virtio implementation from rust-vmm (when it is available).

**Comment by alsrdn** [comment]
This would nice to have. Setting low priority right now.

**Comment by roypat** [comment]
Marking this as 'not planned' for now, as we do not really see how this could be done easily, and the benefits of this as a stand-alone change are low. Should a future task require this, we can revisit this issue.
