### ISSUE TITLE
[devices] Use GuestMemory trait instead of the GuestMemoryMmap

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1762]
This has a slight overlap with https://github.com/firecracker-microvm/firecracker/issues/1544.
Created as a separate issue as it is needed when consuming devices from rust-vmm.

We should use the trait instead of the mmap implementation here. Better yet, devices should not depend on vm-memory's mmap backend feature. That feature should only be used as a `dev-dependency`.

**Comment by alexandruag** [comment]
Maybe it's a good idea to wait for discussions around topics such as [this one](https://github.com/rust-vmm/vm-virtio/pull/15) to settle before proceeding with a particular course of action here, if that makes sense.

**Comment by roypat** [comment]
For now, we are not planning to do this, as we do not see benefits from this as a stand-alone change. Should a change like this become necessary for any specific task in the future, we can track doing it as part of that task.
