### ISSUE TITLE
Create composite device IDs

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1763]
In order to uniquely identify a device, Firecracker currently uses the `device_type` from the `VirtioDevice` trait and another separate device ID. This second identifier only makes sense for a device that's plugged into something (in our case, the Firecracker VMM) so it could be abstractized as a separate trait, representing devices that are in use. See https://github.com/firecracker-microvm/firecracker/pull/1737#discussion_r405509819.

**Comment by alindima** [comment]
Not planning to work on this in the foreseeable future
