### ISSUE TITLE
move vmm_config under rpc_interface

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1777]
The `vmm_config` module contains the configuration definitions used as part of the Vmm RPC interface. Flattened the two modules in a single 'rpc_interface' module.

The `rpc_interface` module should contain the API/RPC actions, the pre-boot and runtime controllers to apply those actions to the Vmm, and the resources configuration definitions.

The target is to completely isolate/contain the API/RPC interface so it could be enabled/disabled using features for example.

**Comment by luminitavoicu** [comment]
This is no more relevant to the current code design. Closing this.
