### ISSUE TITLE
move resources under rpc_interface

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1778]
Depends on/Continuation of https://github.com/firecracker-microvm/firecracker/issues/1777.

The VmResources is only used through the RPC interface, move it in the rpc_interface module.

The target is to completely isolate/contain the API/RPC interface so it could be enabled/disabled using features for example.

**Comment by alicelambda** [comment]
Hello, I would like to work on this

**Comment by serban300** [comment]
Hi @alicelambda ! This issue is available. Should I assign you to it ?

**Comment by alicelambda** [comment]
ye

**Comment by alicelambda** [comment]
Hello is VmResourceStore still being used? I'm having trouble finding it in the codebase

**Comment by acatangiu** [comment]
The gist of this issue/code-base-improvement is to decouple the core `vmm` from the `rpc` driver.

There would be a `rpc_interface` crate which contains resources and logic for configuring a `vmm` using RPCs/commands.

`vmm_config`, `vm_resources` and `rpc_interface` should move from `vmm` crate to the new `rpc_interface` crate.

**Comment by luminitavoicu** [comment]
This is no more relevant to the current code design. Closing this.
