### ISSUE TITLE
Versionize for unit variant enum not supported

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#1787]
Currently, we do not support versionizing an enum variant with no fields (also known as unit variant).

Example:
```rust
#[derive(Versionize)]
pub enum X {
    One,
    Two(u8, u16),
    #[version(start = 2, default_fn = "default_state_three")]
    Three,
}
```
This will fail with `expected tuple struct or tuple variant, found unit variant Self::Three`.

**Comment by ioanachirca** [comment]
Fixed by firecracker-microvm/versionize_derive#6

**Comment by acatangiu** [comment]
Ideally we should close `firecracker` issues when the fixed code reaches `firecracker`. For this fix to go in I believe we still need to publish a new version of https://github.com/firecracker-microvm/versionize_derive, right?

**Comment by ioanachirca** [comment]
Yup, that's right. We'll close it once the fix is in Firecracker.

**Comment by dianpopa** [comment]
The fix is in Firecracker by upgrading to the latest `versionize_derive`.
