### ISSUE TITLE
Versionize for tuple variant with more than one field not supported

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#1788]
Currently, we do not support versionizing an enum tuple variant with more than one field.

Example:

```rust
#[derive(Versionize)]
pub enum X {
    One,
    Two(u8, u16),
    #[version(start = 2, default_fn = "default_state_three")]
    Three(u32, u64),
}
```
This will fail with `this pattern has 1 field, but the corresponding tuple variant has 2 fields`.

**Comment by ioanachirca** [comment]
Open until the fix reaches Firecracker.

**Comment by dianpopa** [comment]
The fix reached Firecracker by upgrading the versionize_derive crate.
