### ISSUE TITLE
Document Header Autogeneration Using rust bindgen

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#179]
This is the process we use to re-generate headers. Some info already exists in:
- https://github.com/aws/PRIVATE-firecracker/pull/178
- https://github.com/aws/PRIVATE-firecracker/pull/114

**Comment by andreeaflorescu** [comment]
The generation is documented in the separate crate [kvm_wrapper](https://crates.io/crates/kvm_wrapper) under the [CONTRIBUTORS.md](https://github.com/rust-vmm/kvm_wrapper/blob/master/CONTRIBUTING.md) file. As we remove autogenerated code from Firecracker, we should make sure we document them in their respective crates.
