### ISSUE TITLE
test_sanitize_process does not appear to create the required test condition

### ISSUE THREAD

**Issue by tnotw** [firecracker-microvm/firecracker#1804]
The jailer test for the sanitize_process function attempts to create 100 open fd's for the sanitize_process to close: 
```
#[test]
    fn test_sanitize_process() {
        let n = 100;

        let tmp_dir_path = "/tmp/jailer/tests/sanitize_process";
        assert!(fs::create_dir_all(tmp_dir_path).is_ok());

        let mut fds = Vec::new();
        for i in 0..n {
            let maybe_file = File::create(format!("{}/{}", tmp_dir_path, i));
            assert!(maybe_file.is_ok());
            fds.push(maybe_file.unwrap().as_raw_fd());
        }

        sanitize_process();
```
However,  debug statements inserted into the sanitize_process function suggest it only sees 4 fd's,  rather than the expected 104. 

The docs for [as_raw_fd](https://doc.rust-lang.org/std/os/unix/io/trait.AsRawFd.html#tymethod.as_raw_fd) suggest that the function does not pass ownership of the fd to the vector, and the file is therefore dropped on each iteration of the iterator.  Would [into_raw_fd](https://doc.rust-lang.org/std/os/unix/io/trait.IntoRawFd.html#tymethod.into_raw_fd) be better,  since the docs suggest it does pass ownership.

**Comment by serban300** [comment]
fixed by #1805 1805
