### ISSUE TITLE
Save full state of MmdsNetworkStack 

### ISSUE THREAD

**Issue by ioanachirca** [firecracker-microvm/firecracker#1814]
The way `Persist` is implemented for `MmdsNetworkStack` in #1773, we only save the fields necessary for restoring `MmdsNetworkStack` and `TcpIPv4Handler` using their respective constructors. 
A better approach would be to also save the connection states from the handler, this way we would be able to fully restore them.

**Comment by alindima** [comment]
This behaviour is currently documented: https://github.com/firecracker-microvm/firecracker/blob/main/docs/mmds/mmds-user-guide.md#snapshotting-considerations
We don't see a need for this at the moment, so closing this issue for now
