### ISSUE TITLE
False positives on VMM Rust integration tests

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1834]
The integration tests that exercise full VMM functionalities introduced by #1791 issue a `vmm.stop(0)` to gracefully stop the vcpu loops. This exits the integration test process with a success code and interferes with `cargo kcov` and `cargo test` normal functioning. This is why new tests that do this do not account for test coverage.

The `vmm.stop()` can be removed because the process exits anyway **but**
1. the vcpu threads will not exit gracefully
1. this plus the CPU pinning `kcov` does to serialize instructions for coverage computation breaks the VMM seccomp integration test.

We should:
1. remove the `vmm.stop()` in the Rust VMM integ tests; let the test harness (`cargo`) control how the test process exits
1. figure out how to gracefully stop the vcpu threads before letting `cargo` force-end the test process, bringing them down or panicking them;. the cleanest way is to have the test guest kernel exit and let them go through the `exited` state
1. figure out why the `seccomp` integ test doesn't work

**Comment by acatangiu** [comment]
I think we can get everything working nicely with different `vmm.stop()` implementations for tests and release.
`Vcpu` cleanup can be done like we did in https://github.com/firecracker-microvm/firecracker/pull/1753

**Comment by aghecenco** [comment]
The integration tests don't compile the `#[cfg(test)]`-marked code. The VMM crate it uses is exactly the same as for release.

**Comment by acatangiu** [comment]
> The integration tests don't compile the #[cfg(test)]-marked code.

That's right..

I wonder if coverage reporting would work fine if we `fork` during tests. We could run the actual test in the child and the parent would only report the status.

**Comment by andreeaflorescu** [comment]
We could also whitelist sysprocmask and let the vcpu threads exit cleanly.

**Comment by aghecenco** [comment]
This isn't a seccomp issue in the unit tests. The problem with the vmm exiting is that it takes down the integration test process with it. Also, there's no way to force the vcpus to exit but leave the process running using just the public facing programmatic api.

**Comment by aghecenco** [comment]
Another fun thing I discovered is that the seccomp test I added in the new integration tests is broken. The signal handler never gets called in the Rust integ tests when running under kcov.
* `cargo test` -> integ tests are run, signal handler is called, seccomp test works
* `cargo kcov` -> integ tests are run, signal handler **not** called, seccomp test broken

**Comment by acatangiu** [comment]
> Also, there's no way to force the vcpus to exit but leave the process running using just the public facing programmatic api.

Originally, `VcpuEvents` also contained an `Exit` command so the `vmm` can request `vcpus` to cleanly exit. We removed it as it wasn't used, but I think we should bring it back. It would be a clean flow. In that case, however this
> We could also whitelist sysprocmask and let the vcpu threads exit cleanly.

would also be needed.

**However**, if we go the `fork` way, then we really don't need anything extra.

**Comment by aghecenco** [comment]
We've hit the latter before with the unit tests which is why the unit tests don't assert on the signal handler having been called when running under kcov. https://github.com/firecracker-microvm/firecracker/blob/15b3fe3496ad95d6ee59943622bf01517068fa9a/src/vmm/src/signal_handler.rs#L201

I will let the signal + kcov issue go for now and focus on the other 2. As for the corresponding rust integ test, I'll try to tweak it same as the unit test above, and if it doesn't work I'll remove it (we already have coverage on seccomp).

As for the other issues: instead of `vmm.stop()`, we can `sleep` a bit to give the guest kernel(s) a chance to run and and exit. The elf we use to test right now says hello world then exits. We can sleep a bit in the integ test, give the vcpu threads their chance to run the state machine, then end the test. It won't always do the trick and sometimes the test (and hence the vmm thread) will end first, potentially causing the vcpu threads to panic. But as long as `cargo test` and `cargo kcov` aren't affected, we shouldn't care.

The elf I built to test the dirty bitmap runs forever and keeps dirtying. I'll rebuild it so that it dies after an adequate amount of time.

**Comment by andreeaflorescu** [comment]
> Originally, `VcpuEvents` also contained an `Exit` command so the `vmm` can request `vcpus` to cleanly exit. We removed it as it wasn't used, but I think we should bring it back. It would be a clean flow. In that case, however this
> 
> > We could also whitelist sysprocmask and let the vcpu threads exit cleanly.
> 
> would also be needed.

That's what I was basically proposing, Adi put in better words :))

**Comment by aghecenco** [comment]
I like this approach better than what I suggested (relying on empirical `sleep`s here and there). I'll
1. revive the `VcpuEvents::Exit` enum variant and adjust filters accordingly
1. port the seccomp/kcov workaround from the unit tests to the integration tests as it manifests the same way
1. dig some more into kcov and why it hates signal handlers so much
