### ISSUE TITLE
Implement FC version to snapshot version mapping

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1854]

**Comment by sandreim** [comment]
Used benchmark in PR #1878 to determine how the performance degradation scales with the number of new versions added in the version map:

- 4 versions -  serialize 239.57 us, deserialize 79.859 us
- 100 versions -  serialize 477.26  us, deserialize 315.40  us
- 1000 versions - serialize 2.5948 ms, deserialize 2.4318 ms 

Closing the issue and now tracking possible performance optimizations in issue #1879
