### ISSUE TITLE
Look into notifying the guest when vcpus are paused

### ISSUE THREAD

**Issue by alxiord** [firecracker-microvm/firecracker#1859]
According to the [documentation](https://www.kernel.org/doc/Documentation/virtual/kvm/api.txt):

```
KVM_KVMCLOCK_CTRL

This signals to the host kernel that the specified guest is being paused by
userspace.  The host will set a flag in the pvclock structure that is checked
from the soft lockup watchdog.  [...] This ioctl can be called any time
after pausing the vcpu, but before it is resumed.
```

KVM uses this ioctl to notify the guest that it's being paused([code](https://elixir.bootlin.com/linux/latest/source/arch/x86/kvm/x86.c#L4493)):

```c
case KVM_KVMCLOCK_CTRL: {
    r = kvm_set_guest_paused(vcpu);
    goto out;
}
```

```c
/*
 * kvm_set_guest_paused() indicates to the guest kernel that it has been
 * stopped by the hypervisor.  This function will be called from the host only.
 * EINVAL is returned when the host attempts to set the flag for a guest that
 * does not support pv clocks.
 */
static int kvm_set_guest_paused(struct kvm_vcpu *vcpu)
{
	if (!vcpu->arch.pv_time_enabled)
		return -EINVAL;
	vcpu->arch.pvclock_set_guest_stopped_request = true;
	kvm_make_request(KVM_REQ_CLOCK_UPDATE, vcpu);
	return 0;
}
```

In the context of snapshotting a microVM and resuming it later, this ioctl needs to be evaluated to assess its benefits & costs and whether it should be called immediately after pausing or between deserialization and resuming.

**Comment by acatangiu** [comment]
Adding a bit more detail here:

In a case where the guest is paused by the hypervisor for a non-negligible period of time, that blackout period is seen by the guest as frozen/non-ticking CPUs. On resuming the VM, the guest soft-lockup watchdog might panic.

This ioctl makes KVM on the host set a special flag on the emulated/paravirtualized pv-clock. This flag is seen by the guest and tells the guest that the vCPUs haven't ticked in a while on purpose.

**Comment by alindima** [comment]
> On resuming the VM, the guest soft-lockup watchdog might panic.

Remember seeing any such panics?

**Comment by sudanl0** [comment]
Reference to this in our code https://github.com/firecracker-microvm/firecracker/blob/cb2ea9203da579c2a473f8538815a1e4eb4420d4/src/vmm/src/vstate/vcpu/mod.rs#L299

**Comment by shomilj** [comment]
Hi! We are seeing cases of soft lockup even when running Firecracker 1.12 on amazonlinux/guest kernel 6.1 - see https://gist.github.com/shomilj/e31dfcca7046db3508f2724cd29c77ea for a dmesg. Have you all seen this show up again at all after you made these changes? Do we need to add a call to KVMCLOCK_CTRL on the resume path as well possibly?

Firecracker version: 1.12.0
Host kernel: 6.8.0-1031-aws
Rootfs info ->
Description: Debian GNU/Linux 12 (bookworm)
Release: 12
Codename: bookworm
Architecture: x86_64
