### ISSUE TITLE
Consume linux-loader from rust-vmm

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1860]
Once there's a release of https://github.com/rust-vmm/linux-loader/ on crates.io, replace the `kernel` crate with it. Some bits of the `arch` crate will also be replace-able.

**Comment by aghecenco** [comment]
Blocked by https://github.com/rust-vmm/linux-loader/issues/18

**Comment by aghecenco** [comment]
Note to self: measure the performance impact, if any, of replacing the embedded `kernel` crate with `linux-loader`.

**Comment by aghecenco** [comment]
2nd note to self: investigate impact on binary size

**Comment by dianpopa** [comment]
Fixed by https://github.com/firecracker-microvm/firecracker/pull/2470.
