### ISSUE TITLE
Create a simple mmio device to support logging the guest boot-time

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1865]
Right now Firecracker has some hardcoded logic for a `PIO` address on `x86_64` and a `MMIO` address on `aarch64` to trigger logging of elapsed time since `InstanceStart` command.
See https://github.com/firecracker-microvm/firecracker/blob/76dfe3af573f6fa641efc192896c6b42bc15b60d/src/vmm/src/vstate.rs#L1032 and https://github.com/firecracker-microvm/firecracker/blob/76dfe3af573f6fa641efc192896c6b42bc15b60d/src/vmm/src/vstate.rs#L1048

This is both inefficient (check against this magic address and value happens on every `MmioWrite` and `IoWrite`) and hacky (this mmio address space is not managed in any way).

We should unify this mechanism to work over `Mmio` for both `aarch64` and `x86_64` and provide it through a "device" that implements `trait BusDevice` so it can be properly managed by a device manager.

**Comment by lauralt** [comment]
#1921
