### ISSUE TITLE
Move functions marked with `#[cfg(test)]` to test modules

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#1868]
We have a few functions in our codebase that are marked with `#[cfg(test)]` (only used by tests), but are not implemented in test modules (`mod tests`). These functions are not excluded by `kcov`, when calculating the coverage, and they should be. We can easily move them to the corresponding test modules.

From what I've seen, these are the files which contain such functions:
https://github.com/firecracker-microvm/firecracker/blob/22f5293ca05f94d9fae28c350af72dd591e36f42/src/vmm/src/vmm_config/net.rs#L191
https://github.com/firecracker-microvm/firecracker/blob/22f5293ca05f94d9fae28c350af72dd591e36f42/src/dumbo/src/tcp/handler.rs#L183
https://github.com/firecracker-microvm/firecracker/blob/22f5293ca05f94d9fae28c350af72dd591e36f42/src/vmm/src/vstate.rs#L1238
The last one might not be worth moving/can complicate things, but the others should require just the expand of the implementation for the structs in which those functions are defined, into test modules (adding `impl NetBuilder`, `impl TcpIPv4Handler` also in `mod tests`).

It is also worth double-checking if I didn't miss other `#[cfg(test)]`  function.

**Comment by acatangiu** [comment]
**Subjective opinion**: in some cases it might be worth to keep them next to one another to improve readability (for example the vstate.rs occurrence you mentioned).

**Comment by lauralt** [comment]
That one yes, but the others would fit better I guess in test modules if they are only used by tests :-??.
