### ISSUE TITLE
VMM rust integ tests: add "fixture" for the fork&run paradigm

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#1887]
See also https://github.com/firecracker-microvm/firecracker/pull/1693#discussion_r423601425
The VMM integ tests run the VMM in a child process, while the parent waits and `assert`s on its exit status. This is common for all scenarios where the VMM is expected to exit. To avoid repeating the
```rust
match fork() {
    0 => { // run VMM... },
    child_pid => { // wait & check... },
}
```
snippet in every such test, we should add a shorthand for it.

**Comment by acatangiu** [comment]
Name it anything else than `fixture` please, my PTSD kicks in at the sound of the word 😆
