### ISSUE TITLE
CI platform independent tests to run once

### ISSUE THREAD

**Issue by iulianbarbu** [firecracker-microvm/firecracker#1894]
We run `test_ensure_mod_tests.py` and `test_style.py` only on `x86_64`. These tests do static source code analysis. We need to extend these tests to run on `aarch64`. We also need to incorporate CI logic which run these platform independent tests once, when the CI is triggered by a push on a PR.

**Comment by andreeaflorescu** [comment]
Besides `cargo clippy`, it looks like all the other style tests don't need to be run on all platforms.
