### ISSUE TITLE
Provide a tool for merging diff snapshots

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#1895]
Input parameters:
- incremental snapshot layer list - ordered from base to top
- output file

**Comment by lauralt** [comment]
The [documentation](https://github.com/firecracker-microvm/firecracker/blob/master/docs/snapshotting/snapshot-support.md#snapshot-tools) should be updated to point to this tool. Reopening this.

**Comment by sandreim** [comment]
> The [documentation](https://github.com/firecracker-microvm/firecracker/blob/master/docs/snapshotting/snapshot-support.md#snapshot-tools) should be updated to point to this tool. Reopening this.

Good call, I guess we can just link the docs to `tests/host_tools/snapshot_helper.py` and add an example of a flow where we use it to rebase incremental snapshots on top of a base.

**Comment by dianpopa** [comment]
The documentation offers details on how to merge diff snapshots: https://github.com/firecracker-microvm/firecracker/blob/master/docs/snapshotting/snapshot-support.md#creating-snapshots. Closing this.
