### ISSUE TITLE
Network: UFO of offload is deprecated

### ISSUE THREAD

**Issue by xiekeyang** [firecracker-microvm/firecracker#1902]
Accoeding to [kernel document](https://www.kernel.org/doc/html/latest/networking/segmentation-offloads.html#udp-fragmentation-offload), `udp fragmentation offload(ufo)` in offloa
ds has been deprecated.

However this is still executed in firecracker code `pub fn new_with_tap`:

https://github.com/firecracker-microvm/firecracker/blob/master/src/devices/src/virtio/net/device.rs#L127

I set up a host tap for vm and run firecracker on `ec2 z1d.metal`, with ubuntu 18.04 and kernel version `5.3.0-1017-aws`. Network config is as below:
```json
"network-interfaces": [
  {   
    "iface_id": "eth0",
    "guest_mac": "02:FC:00:00:00:00",
    "host_dev_name": "vmtap0"
  }   
]
```

Guest network works well while ufo is still off:
```
$ sudo ethtool -k vmtap0 |grep udp-fragmentation-offload
udp-fragmentation-offload: off 
```

I then run on another host with ubuntu 18.04 and kernel version `4.14.1-041401-generic`(firecracker allows kernel version 4.14+ or later), and encounter the panic when vm bootup:
```
[anonymous-instance:ERROR] Configuration for VMM from one single json failed: NetDevice(CreateNetworkDevice(TapSetOffload(IoctlError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))))
```
This seems to because ufo setting is forbidden strictly.

I remove `ufo` from offload set in firecracker code and both of above machines work well.

I've made a commit [here](https://github.com/xiekeyang/firecracker/commit/b4dfe5ea0a172d196dff21e00ebd599324c33be7) with integration tests passed, but not sure if this should be landed to firecracker code. So I would like to discuss here.

**Comment by acatangiu** [comment]
> This seems to because ufo setting is forbidden strictly.

This is weird, I run firecracker on Linux kernel 5.3.0-51-generic Network Devices work fine.

**Comment by xiekeyang** [comment]
> This is weird, I run firecracker on Linux kernel 5.3.0-51-generic Network Devices work fine.

Me too, but I'm still not sure if kernel forbid it deliberately or not.
