### ISSUE TITLE
API: Integrate OpenAPI validation/linter checks into acceptance test suite

### ISSUE THREAD

**Issue by bbros-dev** [firecracker-microvm/firecracker#1905]
To address OpenAPI change requests in a consistent manner it will be necessary for the project to:

1. select a [linter/validator](https://nordicapis.com/8-openapi-linters/) 
1. settle on the rules to be applied

This addresses the [change requests made](https://github.com/firecracker-microvm/firecracker/pull/1882#pullrequestreview-412484508) as part of PR #1881.

**Comment by andreeaflorescu** [comment]
We've been trying to do that before, but failed :(
We ended up having only this test: https://github.com/firecracker-microvm/firecracker/blob/d85cc8341ad98b24e05b4f253b995ef8352aae26/tests/integration_tests/build/test_style.py#L79 which is not super useful.

What would be nice instead is to be able to generate the API and use it throughout the integration tests in python. This way we could get rid of [resources.py](https://github.com/firecracker-microvm/firecracker/blob/master/tests/framework/resources.py) and at the same time test that the swagger definition is what we expect it to be.

**Comment by bbros-dev** [comment]
Useful context.  Items 1. and 2. in the OP liely are jointly decided.  That needs to happen first. Likely a project Lead or their delegate.

I'm flat out working on a generic, reproducible, kernel build infrastructure so can't volunteer for this.

**Comment by alindima** [comment]
We are now using swagger-cli for validation. See `test_swagger.py`
