### ISSUE TITLE
Shared memory between host and guests?

### ISSUE THREAD

**Issue by timvisee** [firecracker-microvm/firecracker#1909]
After reading the documentation, the following wasn't quite clear to me:

Is it possible to set up a block of shared memory between the host and a guest, or between two guests? I've read that the virtio implementation uses MMIO, but don't see a way to use MMIO myself.

If this isn't possible, is this something Firecracker could support in the future?

I'd like to resort to shared memory for 1Gbps+ communication between environments, where networking might not be fast enough.

**Comment by serban300** [comment]
@timvisee 

There is no API for doing this, but it can probably be done from the code. Firecracker uses the `rust-vmm/vm-memory` crate. You can translate a guest address into a host address using [get_host_address()](https://github.com/rust-vmm/vm-memory/blob/257d7c76ec4072e7cc6d73fce2c4ef38b8975bf3/src/guest_memory.rs#L600). You can take a block of memory, find out the guest address and the host address, and use it as shared memory. Or you can create an additional memory region that will be shared between host and guest (you can take a look on the [from_regions()](https://github.com/rust-vmm/vm-memory/blob/257d7c76ec4072e7cc6d73fce2c4ef38b8975bf3/src/mmap.rs#L445) method).

It might also be worth it to take a look on:
[set_kvm_memory_regions()](https://github.com/firecracker-microvm/firecracker/blob/be8b2bae3e6213a020047ad3d2c9ff69eced0e36/src/vmm/src/vstate.rs#L542)
[MmapRegion::build()](https://github.com/rust-vmm/vm-memory/blob/257d7c76ec4072e7cc6d73fce2c4ef38b8975bf3/src/mmap_unix.rs#L130)

**Comment by serban300** [comment]
Closing this issue for the moment. Please feel free to reopen it if you have more questions.
