### ISSUE TITLE
Reduce number of Python linters

### ISSUE THREAD

**Issue by gc-plp** [firecracker-microvm/firecracker#1914]
Currently we are using 3 Python linters to check for styling issues: `pylint`, `pycodestyle` and `pydocstyle`.

It would be good if we only use on one of them, preferably `pylint` or switch to a different one such as `flake8`.

One thing that I noticed is that `flake8` seems to find more styling issues than `pylint` does - for example import ordering.

**Comment by luminitavoicu** [comment]
We have no plans for this.
