### ISSUE TITLE
More flexible interaction with cgroups

### ISSUE THREAD

**Issue by christian7007** [firecracker-microvm/firecracker#1937]
When deploying microVMs using Jailer + config-file, it would be useful to have a way of specifying which cgroups are going to be set, to avoid having to create them manually before starting the VM or modifying them later once the microVM have started. This will add much more flexibility on how the microVMs are isolated (https://github.com/firecracker-microvm/firecracker/issues/1617) and also will allow to set resource limitations (e.g setting the value of `cpu.shares`).

Maybe some new parameters can be added like `--cpu_share` or `--cpuset_cpus` or maybe we can think in a more generic interface like `--cgroup <path>=<value>`.

This way the only one modifying the microVM cgroups would be the jailer and when using it with a third part integration the only command which will need sudo permissions will be the jailer and not the command/script needed for creating the corresponding cgroups.

**Comment by raduweiss** [comment]
Hi @christian7007, thanks for this idea.

We've booked some time in the maintainer team to chat about it next week, and then we'll get back to you. Sorry for the delay, but we want to consider your proposal carefully.

**Comment by raduweiss** [comment]
We've chatted about this in the maintainer team, and this sounds like something that makes sense to add in Firecracker. Something like a `jailer` argument along the lines of `--cgroup [...]` is a useful expansion of the current capabilities.

@christian7007 , we can't deliver this ourselves right now as we're pretty booked in the summer months, but if you want to contribute it, we'll work with you here. If that makes sense to you, we can sync up and dive deeper on the topic. Let us know.

Just to be extra cautions, the solution space here does *not* in any way mitigate SMT security issues. Regardless of how cgroups are set up, to ensure the security of Firecracker guests, all production setups will continue to require disabling SMT (where that feature is available).

**Comment by christian7007** [comment]
Hello @raduweiss nice to hear that!

Sure, I can block some time to work on this and contribute it. Just let me know how can we sync up and define the final behavior.

**Comment by raduweiss** [comment]
Let's get in touch on slack to set up a sync-up.

**Comment by christian7007** [comment]
Hello @raduweiss, @andreeaflorescu and @acatangiu,

Here you have the design draft for the feature:

### Design
The aim of this feature is to add more flexibility to the cgroups defined by Jailer when a microVM is deployed. This will allow to better isolate and limit the access of the microVMs to the different resources.
​
**NOTE**: This do not solve any SMT security issues.
​
Currently when a microVM is deployed the following cgroups are created/written automatically by the Jailer (assuming that every controller is mounted in `/sys/fs/cgroup`) :
```
- /sys/fs/cgroup/cpu/firecracker/<id>/tasks  
- /sys/fs/cgroup/cpuset/firecracker/<id>/tasks  
- /sys/fs/cgroup/pids/firecracker/<id>/tasks  
- /sys/fs/cgroup/cpuset/firecracker/<id>/cpuset.mems (= numa_node)
- /sys/fs/cgroup/cpuset/firecracker/<vm-id>/cpuset.cpus (= /sys/devices/system/node/node<numa_node>/cpulist)
```
With this new feature the user will have total freedom to define the cgroups as needed for each specific use case.
#### Interface​
A new `--cgroups` argument will be added to the Jailer allowing to define an specific cgroup value like this:
```
--cgroups <cgroup_controller>.<cgroup_property>=<value>,<cgroup_controller>.<cgroup_property>=<value>
```
Assuming that `<cgroup_controler>` is mounted at `/sys/fs/cgroup/` the corresponding value will be written into: `/sys/fs/cgroup/<cgroup_controller/firecracker/<id>/<cgroup_property>`
​
For example in order to set the `cpuset.mems` and `cpuset.cpus` values (which are currently set automatically by the Jailer) the following command should be addressed:
```
jailer --id <id> --exec-file /usr/bin/firecracker --uid 1000 --gid 1000 --cgroups cpuset.mems=0,cpuset.cpus=0-7 -- --config-file deployment.file
```
#### Error management
Due to the wide variety of `cgroups` the value passed won't be checked by the Jailer. The Jailer will write the value, and after that it will read the corresponding cgroup to make sure that the value have been set as expected.
​
If one of the values cannot be set the Jailer will fails and the microVM wont be deployed to avoid deploying a microVM without the user expected configuration.
#### Examples
 - **CPU pinning**
 The microVM will only have access to the memory of the NUMA node 0 (`cpuset.mems=0`) and the cpu 1 of that node (`cpuset.cpus=1`)
```
jailer --id <id> --exec-file /usr/bin/firecracker --uid 1000 --gid 1000 --cgroups cpuset.mems=0,cpuset.cpus=1 -- --config-file deployment.file
```
-  **Limiting CPU access**
`cpu.shares` can be used to limit the CPU access for some microVMs. In the example below, `microvm1` will have half of CPU time that `microvm2`
​
```
jailer --id microvm1 --exec-file /usr/bin/firecracker --uid 1000 --gid 1000 --cgroups cpu.shares=1024 -- --config-file deployment.file
jailer --id microvm2 --exec-file /usr/bin/firecracker --uid 1000 --gid 1000 --cgroups cpu.shares=2048 -- --config-file deployment.file
```
#### TBD
- How should be treated the `--node` argument? should it be deprecated in favor of `--cgroups`? At least it will need to be marked as optional to allow full flexibility.

**Comment by acatangiu** [comment]
High-level design looks good to me 👍 

> How should be treated the --node argument? should it be deprecated in favor of --cgroups? At least it will need to be marked as optional to allow full flexibility.

I would deprecate the `--node` argument in favor of `--cgroups`, based on our `Minimalist in Features` [tenet](https://github.com/firecracker-microvm/firecracker/blob/master/CHARTER.md#tenets-unless-you-know-better-ones).

**Comment by christian7007** [comment]
Thanks for the feedback @acatangiu, I'll try to start with the implementation next week.
