### ISSUE TITLE
Rootfs files created by alpine-make-vm-image hang mid-boot

### ISSUE THREAD

**Issue by space55** [firecracker-microvm/firecracker#1948]
Hi, all!

I'm opening this at the recommendation of @iulianbarbu  on slack. Essentially, if one creates a rootfs with [alpine-make-vm-image](https://github.com/alpinelinux/alpine-make-vm-image), then boots it, the new VM will hang on startup.

## Reproduction Steps
1. Install Firecracker v0.21.1 (tested on Debian and CentOS on GCP, with nested virtualization enabled)
2. Download alpine-make-vm-image
3. Create an image to your liking
4. Download the hello-vmlinux.bin kernel, as from the Getting Started guide
5. Set the kernel, as per the Getting Started guide
6. Set the rootfs, as per the Getting Started guide, except refer to your shiny new ext4 file generated by alpine-make-vm-image
7. Start the VM, in the typical Firecracker style (Start firecracker, as per the Getting Started guide, then set InstanceStart)
8. It should boot for about three seconds, then freeze and not progress

## Tested Systems

- Centos 8 with Firecracker v0.21.1
- Debian 10 with Firecracker v0.21.1
- Scratch-compiled Linux 5.4
- Scratch-compiled Linux 4.14
- hello-vmlinux.bin file, as downloaded from the Getting Started guide

Any combination of the above seems to fail. I'm hard-pressed to believe it's related to the OS, and most likely due to some quirk of either OpenRC in Alpine, or some way the system is started. This issue _is_ reproducible (at least, for me it is). If there's any further info, please, feel free to let me know.

Thanks in advance!

**Comment by AlexandruCihodaru** [comment]
Hello @space55 we never managed to take a look at this, let us know if this is still a current issue.

**Comment by alindima** [comment]
I've taken a look at this issue. The guest boots normally, but the output of the serial console seems to "hang", because the `alpine-make-vm-image` tool does not set up a `getty` service on `ttyS0`.
So the OS appears to hang because we don't actually output anything on the serial console, once the OS finishes writing the boot logs.

I'm closing this issue per the above reasoning, since this isn't a Firecracker issue.
