### ISSUE TITLE
Is aarch64 DRAM_MEM_END defined to the correct value?

### ISSUE THREAD

**Issue by weiyang-linux** [firecracker-microvm/firecracker#1949]
pub const DRAM_MEM_END: u64 = 0x00FF_8000_0000; // 1024 - 2 = 1022 GB.

According to the chart in the layout.rs, the dram memory end is 1024G, while the value here is 1022G.

Do we mixed this definition?

**Comment by dianpopa** [comment]
Hi @weixiao-huang ,

The chart in layout.rs also represents the memory from 0 to 2 GB (the reserved memory area, the one that does not is included in the DRAM), that is why the end offset points to 1024. Let me know if it is clearer now.

**Comment by weiyang-linux** [comment]
Hi, @dianpopa 

Thanks for your response, while I am still not clear.

The simplified layout looks like this. 

```
  0       2G          1024G
   |------|-------------|
```

With DRAM_MEM_START defined to be 2G, I suppose **DRAM_MEM_END** to be 1024G, so the total size is 1024 - 2 = 1022G.

But in current definition, the END is 1022G instead of 1024G, and SIZE is 1020G instead of 1022G.

Besides, in your reply, "the end offset points to 1024", but the code show it is 1022. I am not sure which one is correct.

**Comment by andreeaflorescu** [comment]
I think it's a mistake in the code. It should be 1024 G. The value that is written as `DRAM_MEM_END` seems to actually be the `DRAM_MEM_MAX_SIZE`.

**Comment by weiyang-linux** [comment]
@andreeaflorescu 

Agree with you.

**Comment by andreeaflorescu** [comment]
@weiyang-linux do you want to also open a PR to fix the problem once @dianpopa also confirms this?

**Comment by weiyang-linux** [comment]
I think it is ok

**Comment by dianpopa** [comment]
@weiyang-linux now I understand your question. Indeed, `DREM_MEM_MAX_SIZE` is erroneous, `DRAM_MEM_END` is  the maximum length of the DRAM size. I suggest deleting the current DRAM_MEM_MAX_SIZE and rename DRAM_MEM_END to DRAM_MEM_MAX_SIZE. 
Thanks for uncovering this!

**Comment by weiyang-linux** [comment]
ok, as you wish.
