### ISSUE TITLE
Any straightforward way to start multiple VMs (<5) at once?

### ISSUE THREAD

**Issue by sominwadhwa** [firecracker-microvm/firecracker#1955]
Need to do some network benchmarking, so all of them must have network access.

**Comment by iulianbarbu** [comment]
Hi, @sominwadhwa! To start <5 VMs at once you would need to configure/start each VM (mandatory with a network interface, if you want to bench the network) in parallel. This would not necessary mean that these <5 VMs will be up at the exact same time. You would need to poll the userspace to understand when a VM is responsive. 

If you're looking for a specific tool which does exactly this, you might also want to ask a question on the [Firecracker slack channel](https://app.slack.com/client/TDKHXBXA5/CDL3FUR8B). There is a `firecracker-demo` repo, with necessary setup to spawn 4000 VMs with network configuration as well, which you might find useful. Please take a look [here](https://github.com/firecracker-microvm/firecracker-demo)

Note: `firecracker-demo` uses Firecracker v0.19.0. It might need an update to v0.21.1, if you plan to use the latest (which we also recommend).
