### ISSUE TITLE
How to setup networking on second VM?

### ISSUE THREAD

**Issue by sominwadhwa** [firecracker-microvm/firecracker#1956]
So the networking setup detailed [here](https://github.com/firecracker-microvm/firecracker/blob/master/docs/network-setup.md) works fine so as long as you have a single VM running. What possible changes one can make to scale it more than one VM?

**Comment by KarthikNedunchezhiyan** [comment]
[these scripts](https://github.com/firecracker-microvm/firecracker-demo/tree/master/scripts) will give you idea.

**Comment by iulianbarbu** [comment]
> So the networking setup detailed [here](https://github.com/firecracker-microvm/firecracker/blob/master/docs/network-setup.md) works fine so as long as you have a single VM running. What possible changes one can make to scale it more than one VM?

Firecracker manages a single VM. To configure/start multiple VMs, you would need start multiple Firecracker processes. You would need to apply the networking setup for each Firecracker.

**Comment by sominwadhwa** [comment]
@KarthikNedunchezhiyan the scripts helped, thanks!
