### ISSUE TITLE
Test: Invalid ELF magic number

### ISSUE THREAD

**Issue by bbros-dev** [firecracker-microvm/firecracker#1968]
Nit picking but I noticed there is no test case for the scenario: Invalid ELF magic number.

~~Hmm, even the following is rejected~~ (bitrot?) 

Seems the file is OK once re-extracted.
I'm leaving the following as examples to add to the getting started (Troubleshooting section?) to show the variation in output a user can expect to see from a valid kernel.

```bash
$ file vmlinux 
vmlinux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=47ba3aa09eb7819f064f0ecdced
fe48f020f5d26, stripped
```

So what is legal?

From the getting started links (AMD64):

```bash
$ file hello-vmlinux.bin 
hello-vmlinux.bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=8647c7e2e72433a17
adcc6f485c42764f187d2ff, not stripped
```
 
From the [ firecracker/src/vmm/tests/mock_resources/test_elf.bin](https://github.com/firecracker-microvm/firecracker/raw/108aaf8725a386bab9a1a203dba99a1ffc169b82/src/vmm/tests/mock_resources/test_elf.bin)

```bash
$ file test_elf.bin
test_elf.bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

~~So the difference does not appear to be a stripped/not stripped.~~
~~Any hints or tips?~~

**Comment by aghecenco** [comment]
This is somewhat covered by the bigger picture of switching to [`linux-loader` from rust-vmm](https://github.com/rust-vmm/linux-loader/) (https://github.com/firecracker-microvm/firecracker/issues/1860).
There's a [test](https://github.com/rust-vmm/linux-loader/blob/ec930d700f43458f191ee50404810a155accb0ec/src/loader/x86_64/elf/mod.rs#L464) there for this scenario.
