### ISSUE TITLE
micro-http: allow no space after ":"parsing header 

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1975]

**Comment by aghecenco** [comment]
[RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) says `Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. The field value MAY be preceded by any amount of LWS [linear white space]`. #1983 implements this => closing.
