### ISSUE TITLE
Running Firecracker in Docker container

### ISSUE THREAD

**Issue by mazzy89** [firecracker-microvm/firecracker#1999]
The getting started explains all the steps to download Firecracker and run it creating a new socket.

I would like to run it as a Docker container and wire a contribution.

Do you see any obstacles? Which base image would you recommend to start?

**Comment by dianpopa** [comment]
Hello @mazzy89 ,

Sorry for the late response. Can you provide more detail about what you want to achieve. What do you mean by running Firecracker as a Docker container? What base image are you referring to?

**Comment by mazzy89** [comment]
Hello @dianpopa

I've actually achieved that.

I was able to spin up Firecracker inside a Docker container and bootstrap Flatcar Linux as OS.

Thank you for replying here

**Comment by dianpopa** [comment]
Oh that is really cool! 
If you ever feel like it, you could help share the knowledge of your achievement in a PR. A great place for this would be our [dev setup documentation](https://github.com/firecracker-microvm/firecracker/blob/1026a7c11fa8aab9b61e79ae0315439eb8e053a5/docs/dev-machine-setup.md).

Thank you!

**Comment by mazzy89** [comment]
Sure. I would like to share this achievement in a PR. Thanks

**Comment by ustiugov** [comment]
I'd like to share a relevant achievement. 

We have set up GitHub Actions CI environment for integration testing of an entire FaaS (Knative/Kubernetes) cluster with multiple Firecracker MicroVMs in a Docker container (by extending [kind](https://kind.sigs.k8s.io/) framework for K8s CI/CD). 

Credit to @shyamjesal.

**Comment by ustiugov** [comment]
apologies, here is the [link to the code](https://github.com/ease-lab/vhive/pull/107)

**Comment by acatangiu** [comment]
We should find a better place for these than comments on this issue 🚀 🥇
