### ISSUE TITLE
Create a snapshot test matrix to cover various microvm configurations.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2007]
The matrix must test all combinations of:
- 1-8 vCPUs
- 256 - 8192 MB RAM
- 1/2/3/4 net devices
- 1/2/3/4 rw/ro block devices
- vsock device

Tests should create a snapshot and then resume it a new microvm and validate all resources are available (net/block) and any CPU/Disk/net intensive workload can run successfully.

**Comment by dianpopa** [comment]
The various microVM configurations specified in this issue (and some more) were validated [as part of this PR](https://github.com/firecracker-microvm/firecracker/pull/2638). These configurations are also regularly being validated by having included them in our performance pipeline.
