### ISSUE TITLE
Add snapshot stress tests.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2009]
All the tests must run on top of the test matrix defined in #2007 

The following scenarions should be covered:
- 1000 successful sequential snapshots starting with a fresh vm 
- 1000 successful sequential snapshots starting from a resumed snapshot artifact.
- TBD

**Comment by sandreim** [comment]
This needs to be implemented in a separate CI pipeline.

**Comment by kalyazin** [comment]
We already have a test running [5 snapshots](https://github.com/firecracker-microvm/firecracker/blob/826831d566f54fa88b3fe6d672a0d5f79ba35258/tests/integration_tests/functional/test_snapshot_basic.py#L74) in sequence. We can't see a reason why we should extend it to 1000.
