### ISSUE TITLE
Unnatural flow of virtio initialization

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#2015]
The flow of registering a new virtio device now passes through the following function calls:
- `attach_virtio_device` (which calls into registration functions on both the device manager and the event manager)
- `register_new_virtio_mmio_device` (in the device manager)
- `register_virtio_mmio_device` (in device manager; called from `register_new_virtio_mmio_device`)
- `register_mmio_device` (in device manager; called from `register_virtio_mmio_device`)

We now have 3 functions with almost the same name in the device manager. The name is not helping in identifying what is the difference between these 3 functions, which makes the code harder to read.

**Comment by HQ01** [comment]
Interested to help out!
