### ISSUE TITLE
micro_http: firecracker hangs if content-length > request body

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#2017]
If the user specifies a content-length that is bigger than the request body size, Firecracker hangs waiting for more input to achieve the content-length target.

Example:

```bash
curl --unix-socket /run/firecracker.socket -i \
    -X GET 'http://localhost/machine-config' \
    -H  'Accept: application/json'          \
    -H  'Content-Length: 20' \
    -d 'some body'
```

**Comment by iulianbarbu** [comment]
My thought is that we can work around the issue with something like the following:
- Content-Length % 1024 == 0, expect to receive the body in Content-Length / 1024 rounds of EPOLLIN. If received less than 1024 in any round, raise error.
- Content-Length % 1024 == X, expect to receive the body in (Content-Length / 1024) + 1 rounds of EPOLLIN. If received less than 1024 in any of the first Content-Length / 1024, then raise error. If received less or more than X in the last round, raise error.

**Comment by lauralt** [comment]
Just leaving it here too: the awkward partial fix from https://github.com/firecracker-microvm/firecracker/pull/2018 didn't work for request body sizes % 1024 == 0 and with Content-Length passed by user > body size. This scenario should be carefully tested when we will come with other fix.

**Comment by iulianbarbu** [comment]
Firecracker API server thread does not hang when it receives deceiving requests, like the one from the issue description. It can handle other requests in parallel. The client hangs, waiting for a response. 

This GET request should be treated more carefully by the API server. GETs do not need bodies. If we match the content-length to the body length, then Firecracker returns with: {"fault_message":"GET request cannot have a body."}. Maybe we can fail fast for this specific case. However, for requests that involves bodies sending, we can not do much to help the client, if the request is malformed.

**Comment by lauralt** [comment]
Yep, sorry, the title was not the most accurate, it makes sense to me, when having json bodies too, to return some error if Content-Length is > body size, but since `micro_http` doesn't care (from what I remember) what is the body type, it will probably be weird to check this.

**Comment by dianpopa** [comment]
This behavior can be triggered only from the host (the guest is not affected - we are ensuring through this [integration test](https://github.com/firecracker-microvm/firecracker/blob/v1.1.1/tests/integration_tests/functional/test_mmds.py#L617)).
Given that the host user is trusted in Firecracker's threat model, we do not plan to implement additional checks.
