### ISSUE TITLE
Add host CPU model information in snapshot header.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2023]
This would help debugging and enable extra compatibility checks before loading a snapshot.
We need to do this for both x86 and aarch64.
- [x] x86 -> https://github.com/firecracker-microvm/firecracker/pull/2305
- [x] aarch64 -> https://github.com/firecracker-microvm/firecracker/pull/2457

**Comment by GeorgeLS** [comment]
Hello, I would like to work on this one.
Feel free to assign it one me.

**Comment by sandreim** [comment]
Hi @GeorgeLS, sorry for the late reply, but I already picked this up and I'll post a PR soon.

**Comment by berciuliviu** [comment]
Completed in #2457
