### ISSUE TITLE
Refactor virtio device activation

### ISSUE THREAD

**Issue by ioanachirca** [firecracker-microvm/firecracker#2025]
Investigate whether device activation (`process_activation_event` from the corresponding `event_handler.rs` files) can be refactored into an interface that is common to all virtio devices. More context is in [this thread](https://github.com/firecracker-microvm/firecracker/pull/1912#discussion_r428033585).

**Comment by kalyazin** [comment]
We aren't going to take the refactoring, because we can't see how it is going to simplify code.
