### ISSUE TITLE
Loading snapshot is allowed after configuration of kernel and rootfs

### ISSUE THREAD

**Issue by luminitavoicu** [firecracker-microvm/firecracker#2060]
Loading a snapshot should be accepted only on a fresh Firecracker process and the only resources that can be configured beforehand are: Logger and Metrics. However, Firecracker allows creating a new boot source and configuration of rootfs prior to snapshot loading. 

I attached bellow the script used to produce this behaviour (this also downloads the kernel and rootfs) and a valid snapshot example for loading.

[load_snapshot.zip](https://github.com/firecracker-microvm/firecracker/files/5020530/load_snapshot.zip)

**Comment by sandreim** [comment]
We need to cover this properly in issue #2005.

**Comment by acatangiu** [comment]
Covered in thorough unittests in #2251
