### ISSUE TITLE
Add API to retrieve supported snapshot versions.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2063]

**Comment by GeorgeLS** [comment]
Hello, I'm keen in systems programming and I would like to contribute to Firecracker.
Also, this is my first try in open source.
I read the documentation and the code about versioning control in firecracker but it's not clear to me what we would like to achieve here.
Is there a defined set of versions that Firecracker supports or we would like to persist all the snapshot versions that the user has created so far?
For the second one I would imagine the API something like this:

```
curl --unix-socket $socket -i \
    -X GET 'http://localhost/snapshot' \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json'
```

and the response being (in JSON):

```
{
    [
        {
            "snapshot_path": "/full/path/to/snapshot_file",
            "version": "0.23.0"
         },
        {
            "snapshot_path": "/full/path/to/snapshot_file",
            "version": "0.30.0"
        },
        ...
    ]
}
```

Please give me your thoughts/ideas on the matter so we can discuss it and potentially I could start working on it.

Thank you in advance,
George

**Comment by luminitavoicu** [comment]
Hi @GeorgeLS! 

We greatly appreciate your initiative to contribute to Firecracker. 
Firecracker has an internal design to map the release version to the specific snapshot data format versions. What we were aiming for here, was to be able to fetch a list of the supported snapshot versions. We have not decided yet on the most suitable mechanism for this (API or command line parameter). 
This issue has already been picked up by a member of the Firecracker team and a RFC will be up soon, so you can check the progress there if you are interested in keeping up to date with this.

Thank you again,
Luminita

**Comment by dianpopa** [comment]
Functionality was implemented by this [PR](https://github.com/firecracker-microvm/firecracker/pull/2247) by extending the "--version" command line parameter to also show supported snapshot versions.
