### ISSUE TITLE
Boot timer prod removal: enable device only for firecracker "test" mode

### ISSUE THREAD

**Issue by luminitavoicu** [firecracker-microvm/firecracker#2069]
The boot timer device supports logging the boot time of the guest since InstanceStart command. In the past, this was handled using PIO for x86_64 and MMIO for aarch64. In order to unify the code in a generic mechanism, we came up with a MMIO boot timer 'device'. The implementation for x86_64 involved changing PIO writes to 0x03f0 to MMIO writes to 0xd0000000. For aarch64 the mechanism did not change.

This boot time functionality is used only during testing, therefore we decided to load the device only when specified, instead of activating it by default. A dedicated **--boot-timer** parameter would be added to the cmdline options in order to request the boot timer feature.

**Comment by sandreim** [comment]
There is also the option of adding a --test-mode parameter which has the right semantics about not using this in production 🤔

**Comment by acatangiu** [comment]
I like the idea of having a --test-mode switch with subparams. By itself it's not enough as we want different configs for different tests.

Shall we tackle this as a separate enhancement or do we think we can do it as part of this issue?

**Comment by dianpopa** [comment]
Fixed by #2078.
