### ISSUE TITLE
How to debug Firecracker with Rust-lldb?

### ISSUE THREAD

**Issue by sumatejit** [firecracker-microvm/firecracker#2071]
After built the source code and use the Rust-lldb debugs Firecracker binary on ``` debug ``` path. The absolutes path is ``` firecracker/build/cargo_target/x86_64-unknown-linux-gnu/debug```.  I  execute command line below.

``` $lldb ./firecracker ```
``` $(lldb)run --api-sock /tmp/firecracker.socket. ```

Start guest machine with cURL command line calls to the micro api-server on Firecracker. Firecracker can run normal status to prompt waits received command line from user. If we want to list source specified break point to the line of codes, How can list source code for setting debug point? The command line below not show any source during try to debug the Firecracker. 

``` $(lldb)source list ```

**Comment by serban300** [comment]
Hi @sumatejit ,

I am able to reproduce the issue only when I compile using devtool: 
```
$ tools/devtool build
``` 
and load the resulting binary with `rust-lldb` from outside the docker container that's used for building.

However if I compile with `cargo` directly, it works: 

```
$ cargo build
$ lldb ./firecracker
(lldb) run --api-sock /tmp/firecracker.socket.
...
root@localhost:~# Process 19873 stopped
* thread #1, name = 'firecracker', stop reason = signal SIGSTOP
    frame #0: 0x0000000000801dd7 firecracker`epoll_pwait + 31
firecracker`epoll_pwait:
->  0x801dd7 <+31>: cmpl   $-0x26, %eax
    0x801dda <+34>: movl   %eax, %r10d
    0x801ddd <+37>: jne    0x801df1                  ; <+57>
    0x801ddf <+39>: testq  %r8, %r8
(lldb) source list
   32  	fn main() {
   33  	    LOGGER
   34  	        .configure(Some(DEFAULT_INSTANCE_ID.to_string()))
   35  	        .expect("Failed to register logger");
   36  	
   37  	    if let Err(e) = register_signal_handlers() {
   38  	        error!("Failed to register signal handlers: {}", e);
   39  	        process::exit(i32::from(vmm::FC_EXIT_CODE_GENERIC_ERROR));
   40  	    }
   41  	
```

Could you try to build the executable using `cargo` and see if it works ?

**Comment by sumatejit** [comment]
> Hi @sumatejit ,
> 
> I am able to reproduce the issue only when I compile using devtool:
> 
> ```
> $ tools/devtool build
> ```
> 
> and load the resulting binary with `rust-lldb` from outside the docker container that's used for building.
> 
> However if I compile with `cargo` directly, it works:
> 
> ```
> $ cargo build
> $ lldb ./firecracker
> (lldb) run --api-sock /tmp/firecracker.socket.
> ...
> root@localhost:~# Process 19873 stopped
> * thread #1, name = 'firecracker', stop reason = signal SIGSTOP
>     frame #0: 0x0000000000801dd7 firecracker`epoll_pwait + 31
> firecracker`epoll_pwait:
> ->  0x801dd7 <+31>: cmpl   $-0x26, %eax
>     0x801dda <+34>: movl   %eax, %r10d
>     0x801ddd <+37>: jne    0x801df1                  ; <+57>
>     0x801ddf <+39>: testq  %r8, %r8
> (lldb) source list
>    32  	fn main() {
>    33  	    LOGGER
>    34  	        .configure(Some(DEFAULT_INSTANCE_ID.to_string()))
>    35  	        .expect("Failed to register logger");
>    36  	
>    37  	    if let Err(e) = register_signal_handlers() {
>    38  	        error!("Failed to register signal handlers: {}", e);
>    39  	        process::exit(i32::from(vmm::FC_EXIT_CODE_GENERIC_ERROR));
>    40  	    }
>    41  	
> ```
> 
> Could you try to build the executable using `cargo` and see if it works ?

Note for new user cannot run with cargo default toolchain such ```x86_64-unknown-linux-gnu ```.  You can add new toolchain for compile the Firecracker with command line below.
```
$rustup target add x86_64-unknown-linux-musl 
```
After this we can compile source code with new toolchain add to Rustup by use command line.
```
$cargo build --target x86_64-unknown-linux-musl --verbose
```
You can see the binary file at target toolchain like ```x86_64-unknown-linux-musl/debug```.  This path contains binary file for running on debug mode by show a source code. 

```
(lldb) run --api-sock /tmp/firecracker.socket
Process 9986 launched: '/home/vagrant/workspacerust/firecracker/build/cargo_target/x86_64-unknown-linux-musl/debug/firecracker' (x86_64)

Process 9986 stopped
* thread #1, name = 'firecracker', stop reason = signal SIGSTOP
    frame #0: 0x00000000007cee56 firecracker`__syscall + 25
firecracker`__syscall:
->  0x7cee56 <+25>: retq   

firecracker`stub_dlsym:
    0x7cee57 <+0>:  leaq   0x30fca(%rip), %rdi
    0x7cee5e <+7>:  subq   $0x8, %rsp
    0x7cee62 <+11>: xorl   %eax, %eax
(lldb) source list
   32  	fn main() {
   33  	    LOGGER
   34  	        .configure(Some(DEFAULT_INSTANCE_ID.to_string()))
   35  	        .expect("Failed to register logger");
   36  	
   37  	    if let Err(e) = register_signal_handlers() {
   38  	        error!("Failed to register signal handlers: {}", e);
   39  	        process::exit(i32::from(vmm::FC_EXIT_CODE_GENERIC_ERROR));
   40  	    }
   41  	
```

For my opinion we can close this issue.

**Comment by serban300** [comment]
It's nice to hear that it works. I'll close the issue.
