### ISSUE TITLE
[Dev] snapshot versioning: add warning comments to bump version when changing any Versionize struct

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#2089]
Any time we change a `#[derive(Versionize)]` struct we need to bump the snapshot version. Recent experiences have shown that this is not obvious and can easily be missed in both dev and review.

Let's add a warning comment for each such structure to raise visibility on this subtle requirement. Something like:

```diff
#[derive(Versionize)]
/// Holds the device states.
+// NOTICE: Any changes to this structure require a snapshot version bump.
pub struct DeviceStates {
    /// Block device states.
    pub block_devices: Vec<ConnectedBlockState>,
    /// Net device states.
    pub net_devices: Vec<ConnectedNetState>,
    /// Vsock device state.
    pub vsock_device: Option<ConnectedVsockState>,
}
```

**Comment by sandreim** [comment]
👍 

The integration tests in PR #2067 will fail if this happens. But still, there are corner cases when the deserialization could be successful and garbage state would be loaded. However I believe, this is highly unlikely to happen.

**Comment by HQ01** [comment]
Interested to help out!

**Comment by HQ01** [comment]
PR created at #2281.
