### ISSUE TITLE
[Feature Request] Support build from private repositories

### ISSUE THREAD

**Issue by alexandermerritt** [firecracker-microvm/firecracker#2104]
## Why is this feature request important?  What are the use cases?  Please describe.

Firecracker currently pulls dependent crates from the public web via https:// (e.g., see all Cargo.toml files).

For folks who work on such dependencies to test new features or functionality and who are required to keep cloned repositories within corporate networks access-controlled via SSH, dependencies are specified via git://

Firecracker builds in a docker container, which (tag `v14`) does not have a local `git` binary in the file system, and instead clones via the cargo git library. The git library does not observe SSH config files (e.g., $HOME/.ssh/config) to know which keys to use for cloning.

This Issue requests changes made to the build container, and / or the tools/devtool script to enable cloning dependent crates during `cargo build` which are accessed via git://

## Describe the desired solution

I imagine a solution on the host where we set up ssh-agent and add keys with ssh-add, then pass through the environment variables into the docker container. If the built-in Cargo git library does not support using ssh-agent, then update the container image to have a git binary, and instruct Cargo to use that for builds.

Key management and such would remain within the host, and allow the container to take advantage of them without extra steps to add the keys.

In the host:

```bash
eval `ssh-agent -s`
# ensure you have some keys in $HOME/.ssh/
ssh-add
```

Pass environment variables `SSH_AUTH_SOCK` and `SSH_AGENT_PID` to the container (as is currently done for web proxies), and enable access to the path specified by the former variable.

## Describe possible alternatives

I have identified two possible alternatives.

To avoid needing to modify the build container: clone the dependencies you need to modify and place them somewhere in your Firecracker directory, e.g., firecracker/deps/. Then edit the Cargo.toml files which depend on this crate to point to a path where this exists:

```toml
foo = { path = "/firecracker/deps/foo" }
```

These will be visible within the build container as it is mounted within it at the root-level directory. This solution is perhaps the fastest and least invasive. You can still push, commit, fetch, etc. from this repo in firecracker/deps/foo/ as any normal clone.

My current solution is to run the build container interactively, add apt proxies, install git and vim, copy over the private ssh key and config file, commit the container instance as a new image, and then update tools/devtool to use this image.

This is not sustainable because:
- it requires modifying the container
- each update to the upstream image requires updating the container locally
- updates to keys on the host, require updating the container
- you cannot share the image on a shared machine as your private keys are contained within
- it is hacky

The ideal solution allows the container to remain stateless, and to access configuration details from the user's host environment in order to complete the build.

Below is my current solution:

This is `tools/docker-create-gitfix.sh`

```bash
#! /usr/bin/env bash
set -e; set -u; set -x
cd $(dirname $0)

##
## Run this script once, after cloning the Firecracker repo
## and after setting up docker, to update the Firecracker
## build container to be able to clone from [corp] internal
## git repositories.
##

K=ssh-key
[[ ! -e $K ]] && \
        echo 'Put your ssh private key in file ssh-key' && \
        exit 1

I=fcuvm/dev:v14
N=fc-gitfix

# grab the Firecracker container from the interwebs
docker pull $I

# remove existing image
docker rmi --force $N

# run Firecracker container in background
H=$(docker run --privileged --detach $I sleep 9999)

# create command script to execute inside container
C=`mktemp`
sed -e "/PUTKEYHERE/r $K" docker-install-git.sh | grep -v PUTKEYHERE >$C
docker exec -i $H bash <$C
rm -f $C

# shut down container
docker exec -i $H pkill sleep

# create new image from launched instance
docker commit $H $N
```

and this is my secondary script at `tools/docker-install-git.sh` which is a set of commands executed within the container to update it:

```bash
#! /usr/bin/env bash
set -e; set -u; set -x

##
## DO NOT RUN THIS FILE DIRECTLY!
##

cat <<EOF >/etc/apt/apt.conf
Acquire::http::Proxy "http://proxy.your-corp.com:12345";
Acquire::https::Proxy "http://proxy.your-corp.com:23456";
EOF

apt update
apt install -y git vim

mkdir -p /root/.ssh
chmod 711 /root /root/.ssh

cat <<EOF >/root/.ssh/ssh-key
PUTKEYHERE
EOF

cat <<EOF >/root/.ssh/config
Host *.gitplace.your-corp.com
    IdentityFile /root/.ssh/ssh-key
    StrictHostKeyChecking no
EOF

chmod 600 /root/.ssh/*
```

Change a dependent crate path in one of the Cargo.toml files within the Firecracker codebase to point to a git:// location where you have cloned / mirrored / forked a private instance.

Tell Cargo to [use the local git binary](https://doc.rust-lang.org/cargo/reference/config.html#net) in the file system:

```diff
diff --git a/.cargo/config b/.cargo/config
index 389e0f9f..8e7a7322 100644
--- a/.cargo/config
+++ b/.cargo/config
@@ -10,3 +10,6 @@ rustflags = [
        "-C", "link-arg=-lgcc",
        "-C", "link-arg=-lfdt",
 ]
+
+[net]
+git-fetch-with-cli = true
```

Ignore the user's key from git tracking:

```diff
diff --git a/.gitignore b/.gitignore
index 195864bf..796ff01c 100644
--- a/.gitignore
+++ b/.gitignore
@@ -5,3 +5,4 @@ target
 .idea
 __pycache__
 *.pyc
+tools/ssh-key
```

Update the build script to use the new container image (and fix a bug that complained about a UID not existing...):

```diff
diff --git a/tools/devtool b/tools/devtool
index 4e48918c..d1191056 100755
--- a/tools/devtool
+++ b/tools/devtool
@@ -73,7 +73,7 @@
 # Development container image (name:tag)
 # This should be updated whenever we upgrade the development container.
 # (Yet another step on our way to reproducible builds.)
-DEVCTR_IMAGE="fcuvm/dev:v14"
+DEVCTR_IMAGE="fc-gitfix"

 # Naming things is hard
 MY_NAME="Firecracker $(basename "$0")"
@@ -506,7 +506,6 @@ cmd_build() {
     # Note: we need to pass an explicit TARGET_CC to cargo, because the `cc`
     # crate gets confused for aarch64 musl.
     run_devctr \
-        --user "$(id -u):$(id -g)" \
         --workdir "$CTR_FC_ROOT_DIR" \
         --env TARGET_CC=musl-gcc \
         -- \
```

Now you can build with `tools/devtool build`.

## Additional context

Hacking / contributing on Firecracker from within corporate networks seems very restricted without this ability.

I am using Firecracker v0.22.0 which uses the docker image tag v14.

References:
- [Cargo SSH authentication](https://doc.rust-lang.org/cargo/appendix/git-authentication.html#ssh-authentication)
- [Cargo net configuration](https://doc.rust-lang.org/cargo/reference/config.html#net)
- [Cargo Issue 2078 - support .ssh/config](https://github.com/rust-lang/cargo/issues/2078)

## Checks
- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

Tried my best to search existing documentation but did not find much specific to Firecracker. Solutions were via Cargo and Docker interfaces directly.

**Comment by gc-plp** [comment]
Hi @alexandermerritt.

Thank you for taking the time to research this. It's a very useful proposal.

We've prioritized it and will start looking into the usecases that you pointed out.

**Comment by raduweiss** [comment]
Just a quick update here. @alexandermerritt , do you think you can open a draft PR with your proposed changes? That way we can discuss on the specifics of the proposal. I personally think it's a good idea (but will need to get the team's input on the implications/implementation).

**Comment by alindima** [comment]
Thanks again for your research @alexandermerritt. Are you interested in opening a PR for this proposal?

**Comment by alexandermerritt** [comment]
Hello. By PR @raduweiss and @alindima you are asking for specific code changes that implement a solution? The text I wrote above with code is a hack, not something that would be put into a real PR, and was meant to highlight the mechanism of my current ad-hoc solution. As I wrote, the two methods I have do not seem to be sustainable, and another approach maybe should be sought out. I am unaware what that might be, and had hoped by submitting this Issue, someone more knowledgable would give me some feedback. This kind of discussion should happen before I (or someone) submit any kind of PR. Do either of you have any suggestions?

I am not familiar with @gc-plp but their reply sounded like a PR would be worked on. Is this not true?

Are you looking to close this Issue unless I submit a PR?

I only put the effort into submitting this Issue because I feel this problem is not small and a non-temporary solution seems non-trivial, but I do not have much time to figure this out. So, I wrote up as much of my own understanding as much as I could, hopefully to help someone else until a real solution is proposed, and implemented.

If someone is willing to contribute discussion to this Issue to help it make progress, I will of course participate because it is still valuable to me, at least...

**Comment by alindima** [comment]
Hi. Sorry if we were not clear enough. We aren't planning on closing this issue without a fix, since we see the value in this proposal.

We were just wondering if you are interested to contribute to fix this issue or should we begin to do this ourselves.
We haven't managed to find a clear solution yet for this problem, but we will start working on it.

I'll update the issue with more details once we draft a possible solution
