### ISSUE TITLE
[Bug] Firecracker exits before returning API response when loading an invalid snapshot.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2116]
## Describe the bug

Due to the current design, any failure on the vCPU resume path will cause Firecracker to exit before sending a response.

## To Reproduce

1. Create a snapshot that contains a corrupted vCPU state. 
2. Load the snapshot.

## Expected behaviour

Firecracker should exit after returning API response.

## Environment

- Firecracker version: v0.23.

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by berciuliviu** [comment]
Fixed by #2282
