### ISSUE TITLE
Improve logger to include thread name (vcpu#/api/vmm)

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2117]
Multiple threads concurrently write the log file and the source of the logs is not obvious. If we add the thread id the logs would become more readable.

**Comment by HQ01** [comment]
interested to help out!

**Comment by sandreim** [comment]
Hey @HQ01! Thank you for your interest in contributing to Firecracker. 

I will try to summarize some next steps to get you started:
- Dive deep the Firecracker `logger` crate  which  provides an implementation for the API abstraction by the [log crate](https://crates.io/crates/log)
- Change the code so the log prefix also include thread ids. It should live in `Logger::create_prefix(&self, record: &Record)` 
- Would be nice if you find a solution to use the thread names instead of ids like: **vmm, api, vcpu#1, vcpu#2** ..
- Write unit and integration tests
- Publish PR

If you get stuck along the way please reach out to us via Slack or this ticket.

**Comment by HQ01** [comment]
Hi @sandreim, thanks for the information! To provide you with more context, we are 4 students in UT Austin's virtualization class, and look forward to contributing to an open-source project as part of our coursework -- Firecracker really attracts us as an exciting project to work on :) We will start from relatively simple issues, but hopefully we can fix them all one by one. Will keep you posted as we start working on them!

**Comment by 2018kguo** [comment]
Hey @sandreim, just as a quick status update, we recently started coding this up and have added functionality to Logger::create_prefix such that it has an option to include the thread name in the prefix, We have added a few unit tests and have about to start writing integration tests. Things are still in a pretty rough state, but this is our current branch: [here](https://github.com/Preston-Sundar/firecracker/tree/Feature-Improve-logger-to-include-thread-name).

**Comment by Preston-Sundar** [comment]
PR opened at https://github.com/firecracker-microvm/firecracker/pull/2314

**Comment by acatangiu** [comment]
Fixed by #2352
