### ISSUE TITLE
[Bug] Differentiate between whitelisted ioctls parameters on x86_64 and aarch64

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#2128]
## Describe the bug

At this moment, [we are not labelling the specific x86_64](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/default_syscalls/mod.rs#L73) ioctl parameters (mainly used for the snaphot support).

**Comment by alindima** [comment]
Have a look at the seccomp auditing feature branch: https://github.com/firecracker-microvm/firecracker/blob/af888c7b55d253da254ad547c2ee5e4bbfb5166c/src/vmm/src/default_syscalls/mod.rs#L51
It should be merged in mainline after the necessary testing.

**Comment by dianpopa** [comment]
Cool, thanks for the reference! We should add a "Fixes #2128" when merging the functionality in mainline.

**Comment by alindima** [comment]
Sure, I will do that. However, can this be considered a bug? I think it's more of an improvement
