### ISSUE TITLE
Investigate snapshot restore performance on host kernel >= 5.4

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#2129]
The snapshot restore operation is slower on AMD than on Intel. 

We should investigate why and either fix the root cause or change the `test_snapshot_resume_latency` test in order to check different values for AMD and Intel.

**Comment by serban300** [comment]
This seems to be related to the host kernel version. On `5.4` I'm getting restore times that revolve around 30ms. On `4.19` I'm getting restore times that revolve around 4 ms.

**Comment by serban300** [comment]
On host kernel `5.4` looks like the difference between 4ms and 30ms is caused by the jailer.

**Comment by serban300** [comment]
On host kernel `5.4` the problem seems to be caused by the cgroups. When I start jailer without applying the cgroups the overhead disappears.

**Comment by serban300** [comment]
The entire overhead comes from the `KVM_CREATE_VM` ioctl:

When running within the jailer cgroup: 
```
ioctl(12, KVM_CREATE_VM, 0)             = 14 <0.027335>
```

When running without cgroups:
```
ioctl(12, KVM_CREATE_VM, 0)             = 14 <0.000352>
```

The difference is about `27ms`.

**Comment by serban300** [comment]
For the moment I traced the overhead to the `kvm_arch_post_init_vm()` function in the host kernel. I will dig deeper.

**Comment by serban300** [comment]
Looks like the overhead was introduced by [this](https://lore.kernel.org/lkml/20190719140000.31694-9-juri.lelli@redhat.com/) kernel patch.

More specifically these 2 commits:

[sched/core: Prevent race condition between cpuset and __sched_setscheduler()](https://github.com/torvalds/linux/commit/710da3c8ea7dfbd327920afd3831d8c82c42789d)
[cgroup/cpuset: Convert cpuset_mutex to percpu_rwsem](https://github.com/torvalds/linux/commit/1243dc518c9da467da6635313a2dbb41b8ffc275)

**Comment by serban300** [comment]
Actually, to be even more specific, looks like the overhead was introduced only by the following commit:
[cgroup/cpuset: Convert cpuset_mutex to percpu_rwsem](https://github.com/torvalds/linux/commit/1243dc518c9da467da6635313a2dbb41b8ffc275)

I tried to use `cpuset_mutex` instead of `percpu_rwsem` and the overhead disappears.

**Comment by sandreim** [comment]
The issue is reproducible on Intel/AMD.

**Comment by serban300** [comment]
Just a quick update. I stumbled upon some documentation. Looks like this is how a `percpu_rwsem` is supposed to work. Quoting from https://github.com/torvalds/linux/blob/master/Documentation/locking/percpu-rw-semaphore.rst

> Locking for reading is very fast, it uses RCU and it avoids any atomic instruction in the lock and unlock path. On the other hand, locking for writing is very expensive, it calls synchronize_rcu() that can take hundreds of milliseconds.

**Comment by serban300** [comment]
I managed to reproduce the issue with this simple rust executable:

```
use kvm_ioctls::Kvm;
use std::time::{Instant, Duration};
use std::thread;

fn main() {
    thread::spawn(move || {
        thread::sleep(Duration::from_millis(500));
    }).join();

    let kvm = Kvm::new().unwrap();
    let start = Instant::now();
    kvm.create_vm().unwrap();
    let elapsed = start.elapsed();
    println!("Elapsed: {:.2?}", elapsed);
}
```

and this small script that emulates what jailer does:

```
#!/bin/bash

cgcreate -g cpuset:/firecracker
echo 0-15 >> /sys/fs/cgroup/cpuset/firecracker/cpuset.cpus
echo 0 >> /sys/fs/cgroup/cpuset/firecracker/cpuset.mems

echo $$ > /sys/fs/cgroup/cpuset/firecracker/tasks && ./test
```

Note that if we don't add the extra thread:
```
    thread::spawn(move || {
        thread::sleep(Duration::from_millis(500));
    }).join();
```
The issue doesn't reproduce.

**Comment by serban300** [comment]
When a writer requests access to some shared data, the RCU schedules it on a queue and then waits for at least one so-called "grace-period" to pass. A grace period is a period in witch the RCU waits for all the previously acquired read locks to be released. A grace period ends after all the CPUs go through a quiescent state. Grace periods can be quite long.

When we start the process (`echo $$ > /sys/fs/cgroup/cpuset/firecracker/tasks && ./test`) a write lock request is being performed and a grace period starts. If we don't add the extra `thread::sleep(Duration::from_millis(500));`, when we get to `kvm.create_vm().unwrap();`, the previous grace period is already in progress, so AFAIU the RCU does an optimization where the new lock request is "merged" in the same grace-period  with the previous one. So we don't have to wait for a new grace period. 

Otherwise, if we do `thread::sleep(Duration::from_millis(500));`, the grace period generated by the first lock request ends, and `kvm.create_vm().unwrap();` asks for a new grace period, ending up waiting 20-30ms.

This is the desired RCU behavior. And it looks like the `cgroup_init()` code has a related [optimization](https://github.com/torvalds/linux/blob/7575fdda569b2a2e8be32c1a64ecb05d6f96a500/kernel/cgroup/cgroup.c#L5687) to drive down the boot time. Unfortunately this only works before the first use of the `rcu_sync`.

I don't think there's any easy way around this issue.
