### ISSUE TITLE
make CPUID templates vendor dependent

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#2130]
For the moment we have 2 CPUID templates: T2 and C3. They are both Intel-specific.

We have to store this information and validate it when applying a template. We shouldn't be able to apply Intel templates on AMD or vice-versa.

**Comment by rpaul98** [comment]
Hi, @edengarza, @amaniduncker, and I are students at UT and are looking to contribute to an open source project for our virtualization class. We were wondering if we could get assigned to this issue.

Thanks!

**Comment by serban300** [comment]
Hi ! Thanks for the interest in firecracker ! For this specific issue, There is already a PR under review. Sorry ! But if you're interested about other issues, we would be happy to accept contributions. In general the issues that are marked with the "Good first issue" or "Good first contribution" tag would be recommended.
