### ISSUE TITLE
[Devel] Prevent performance regressions via automated periodic performance tests

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#2144]

**Comment by xmarcalx** [comment]
The team developed buildkite pipelines to automate performance tests which run every night against our **main** branch to prevent performance regressions.

As part of the automated performance tests campaign, we regress test the following metrics on different kernels and CPU architectures:
1. read/write block devices
2. network latency
3. network tcp throughput 
4. vsock throughput
5. snapshot latency

The tests executed can be found in [firecracker](https://github.com/firecracker-microvm/firecracker)/[tests](https://github.com/firecracker-microvm/firecracker/tree/main/tests)/[integration_tests](https://github.com/firecracker-microvm/firecracker/tree/main/tests/integration_tests)/performance/ .
