### ISSUE TITLE
[Doc] Add snapshot performance section in documentation

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2150]
The snapshot create/resume timings must be documented for all supported platforms. There are multiple variables that influence these timings: memory size, vcpu count, device count, host kernel/config and host load.  All of them need to be covered in the documentation with measurements across a discrete set of sandbox sizes.

**Comment by alsrdn** [comment]
We're tracking publishing the performance numbers under this issue: https://github.com/firecracker-microvm/firecracker/issues/2939
