### ISSUE TITLE
[Feature Request] Can firecracker run on host with kernel-5.4.x?

### ISSUE THREAD

**Issue by ktmlm** [firecracker-microvm/firecracker#2152]
# This issue is very simple.

# **Can firecracker run on host with kernel-5.4.x?**

I do NOT need you to resolve any problems for me.

Just tell me `can run` OR `can NOT run`, thanks.

**Comment by ktmlm** [comment]
#### below is the results of my tests:

- [Normal] CentOS-8.x, kernel 4.18.x
- [Crash] Alpine-3.12.x, kernel 5.4.x
- [Crash] Ubuntu-2004, kernel 5.4.x
- [Crash] Gentoo-17.1, kernel 5.4.x
- [Normal] Gentoo-17.1, kernel 4.19.x (custom)

**Comment by acatangiu** [comment]
Hi @ktmlm, while we don't test with all kernel versions, we're also not aware of any blockers in using newer kernel versions.

Can you share the boot log (serial console output) for the tests that crash?

**Comment by ktmlm** [comment]
@acatangiu thanks for your reply, this is the output on `Ubuntu 2004(Linux 5.4.0-48-generic x86_64)`: 

```
[root@xxx /tmp]# modprobe kvm
[root@xxx /tmp]# ~/firecracker/target/debug/firecracker --config-file cfg.json --no-api
[src/firecracker/src/main.rs:267] &config_json = "{\n  \"boot-source\": {\n    \"kernel_image_path\": \"/tmp/vmlinux\",\n    \"boot_args\": \"console=ttyS0 reboot=k panic=1 pci=off\"\n  },\n  \"drives\": [\n    {\n      \"drive_id\": \"rootfs\",\n      \"path_on_host\": \"/tmp/rootfs.ext4\",\n      \"is_root_device\": true,\n      \"is_read_only\": false\n    }\n  ],\n  \"machine-config\": {\n    \"vcpu_count\": 2,\n    \"mem_size_mib\": 1024,\n    \"ht_enabled\": false\n  }\n}\n"

2020-10-01T20:18:53.499589013 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:68] Shutting down VM after intercepting a bad syscall (202).

2020-10-01T20:18:53.499684739 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:116] Shutting down VM after intercepting signal 31, code 1.
```

**Comment by sandreim** [comment]
Seems to be similar to: #2044

**Comment by ktmlm** [comment]
@sandreim OK, that's it. thanks
