### ISSUE TITLE
Replace Polly with rust-vmm/event-manager

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2154]

**Comment by humancalico** [comment]
@sandreim Can I work on this?

**Comment by dianpopa** [comment]
Hi @humancalico ,

We were planning on working on this in the near future but if you want to start work on this you can go ahead and I can help you with guidance. I encourage you to join our [slack channel](https://tinyurl.com/firecracker-microvm) and ping me there for anything.

**Comment by acatangiu** [comment]
Fixed by #2604
