### ISSUE TITLE
[Bug] Return error if user wants to configure CPU templates for aarch64

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#2165]
## Describe the bug

Firecracker offers users the possibility of configuring the CPU features exposed by the guest by applying C3 and T2 templates. On aarch64, this functionality is not supported yet. However, trying to specify a cpu template through the API on aarch64 is possible even though it has no consequences.

## To Reproduce

` 1. Start Firecracker on an aarch64 via ./build/cargo_target/aarch64-unknown-linux-musl/debug/firecracker --api-sock /tmp/firecracker.socket.`
`2. Configure Firecracker via curl --unix-socket /tmp/firecracker.socket -i \
     -X PUT "http://localhost/machine-config" \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
     -d "{ 
	    \"vcpu_count\": 1, 
	    \"mem_size_mib\": 32,
	    \"ht_enabled\": false,
	    \"cpu_template\": \"T2\"
         }"`

==> no error is returned.

## Expected behaviour

Error should be returned when user specifies CPU template on aarch64.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`

## Checks
- [ ] Have you searched the Firecracker Issues database for similar problems?
- [ ] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

**Comment by ahmedaabouzied** [comment]
I can work on that.

**Comment by dianpopa** [comment]
Cool, I will assign you to this issue.
For the implementation, you can follow the example of "SendCtrlAltDel" api request:https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/src/request/actions.rs#L41.

If you encounter obstacles contact us on our [slack channel](https://github.com/firecracker-microvm/firecracker/blob/94b2313646a1a8676e35fe7580623f450bee9a45/README.md#faq--contact).
Thanks!
