### ISSUE TITLE
Align MMDS configuration and MMDS operation device requirements

### ISSUE THREAD

**Issue by bbros-dev** [firecracker-microvm/firecracker#2174]
## Describe the bug

Per RFC issue #1866 / PR #1883: 

> ... the APIs for MMDS data store creation or MMDS configuration do not output any error if there is no network device configured. However, in terms of its operation, MMDS is not reachable if there is no network device which allows MMDS requests

and 

> The misalignment which might cause customer confusion comes from the fact that the MMDS configuration requirements does not correspond with MMDS operation requirements. I can not say this is a required design choice or simply an arbitrary happening due to unclear requirements. My understanding is that it is not a blocker of any sort for Firecracker usage and configuration since we haven't had any issues with it so far. I also believe that with the advent of the Device-API matrix it will be easier to think for the future in terms of API refinement in this area. Feel free to open any issue on this topic.

## To Reproduce

Issue is identified per @iulianbarbu comments in PR #1883

## Expected behaviour

Configuring MMDS for a uVM without a network device should return an error to the effect that MMDS **operation** requires a network device.

## Environment

- Firecracker version.

```bash
$ firecracker --version
Firecracker v0.21.1
```
- Host and kernel version.
```bash
$ uname -a
Linux desktop.local.lan 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Rootfs used: Not relevant
- Architecture: ` x86_64`

## Additional context

**How has this bug affected you?** Consuming Firecracker errors requires different logic depending on the API-device pair. 

**What are you trying to achieve?** Robust error handling.

**Do you have any idea of what the solution might be?** Single code path for Firecracker API-device pair error handling?

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by sandreim** [comment]
Thanks for logging this @bbros-dev . We need to discuss this further about  how/when we report the error or if any API changes make sense and help.
