### ISSUE TITLE
run cargo audit with --deny-warnings enabled

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#2182]
Without adding this flag, breaking changes related to cargo audit (which may turn into errors in time, see [this thread](https://github.com/RustSec/advisory-db/issues/414#issuecomment-708306092)) won't be caught by `test_sec_audit.py` because we are not passing  `--deny-warnings` flag to `cargo audit`. By passing the flag, the test will fail because of the warning that will be emitted when such changes are happening. See [this comment](https://github.com/RustSec/advisory-db/issues/414#issuecomment-708377448).

To replicate the error, on  v0.21.3 or v0.22.1, it's enough to just run the `test_sec_audit.py`.
Relevant line in output:

`E   error: error loading advisory database: parse error: unexpected character found: ``` at line 1 column 1`.

It is also worth mentioning, if we choose to run `cargo audit` with `--deny-warnings`, using yanked versions won't be allowed anymore (`versionize` and `versionize_derive` at this moment). To check this, you can run on the current master (commit 176e8e8feb58de295310509aefda9cdcc37e66c0) `test_sec_audit.py`, after updating this [line](https://github.com/firecracker-microvm/firecracker/blob/master/tests/integration_tests/security/test_sec_audit.py#L27) to:

`utils.run_cmd('cargo audit --deny-warnings -q -f {}'.format(cargo_lock_path))`.

(Or simply just run in firecracker `cargo audit --deny-warnings -q -f Cargo.lock`)

**Comment by aghecenco** [comment]
Blocked since https://github.com/firecracker-microvm/versionize/pull/23 (included in [`versionize` v0.1.4](https://github.com/firecracker-microvm/versionize/releases/tag/v0.1.4))

**Comment by dianpopa** [comment]
Fixed by #2858
