### ISSUE TITLE
Log errors for block device close()

### ISSUE THREAD

**Issue by alindima** [firecracker-microvm/firecracker#2188]
The file backing Firecracker's block device, like any other rust `File` is closed when going out of scope or when calling `drop` on the `File`, without any error handling: https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/fd.rs#L284.

This may be a design flaw of rust's `File` struct, since the linux man page states that:

> Not checking the return value of close() is a common but nevertheless serious programming error. It is quite possible that errors on a previous write(2) operation are first reported at the final close(). Not checking the return value when closing the file may lead to silent loss of data.

One thing we can do to ensure that the subsequent `close()` will run successfully is calling `fsync()` on the file descriptor in advance.
This can be done as a `Drop` implementation for the `DiskProperties` member struct of the block device.

As far as I can tell, there is not much we can do to handle the potential error and data loss, apart from logging it, which may still be useful.

**Comment by jain98** [comment]
Hi, first timer here. I'd be interested in giving this a shot.

**Comment by berciuliviu** [comment]
Hey @jain98! I wonder if you are still looking/working on this issue? If not, I could tackle it since I've got some time on my hands.
Thanks!

**Comment by jain98** [comment]
@berciuliviu feel free to take up the issue.

**Comment by berciuliviu** [comment]
Linked with [2223](https://github.com/firecracker-microvm/firecracker/pull/2223)

**Comment by berciuliviu** [comment]
Closed as duplicate to issue [2207](https://github.com/firecracker-microvm/firecracker/issues/2207)
