### ISSUE TITLE
[Bug] Cannot load kernel due to invalid memory configuration or invalid kernel image. Invalid ELF magic number

### ISSUE THREAD

**Issue by olehdevua** [firecracker-microvm/firecracker#2201]
## Describe the bug

Firecracker can't start vm from an image pointed in [tutorial](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md)

## To Reproduce

Go through first 3 steps from [Running Firecracker tutorial](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-firecracker)

I receive next output:

```bash
>  firecracker --api-sock /tmp/firecracker.socket
2020-10-19T16:16:49.117519319 [anonymous-instance:ERROR:src/api_server/src/parsed_request.rs:95] Received Error. Status code: 400 Bad Request. Message: Cannot load kernel due to invalid memory configuration or invalid kernel image. Invalid ELF magic number
2020-10-19T16:27:53.243690359 [anonymous-instance:ERROR:src/firecracker/src/main.rs:67] Firecracker panicked at 'Error creating the Kvm object: Error(2)', src/libcore/result.rs:1165:5
2020-10-19T16:27:53.244510016 [anonymous-instance:ERROR:src/firecracker/src/main.rs:77]    0: firecracker::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::continue_panic_fmt
   3: rust_begin_unwind
   4: core::panicking::panic_fmt
   5: core::result::unwrap_failed
   6: vmm::builder::build_microvm
   7: vmm::rpc_interface::PrebootApiController::build_microvm_from_requests
   8: firecracker::main
   9: std::rt::lang_start::{{closure}}
  10: main

Aborted
```

## Expected behaviour

Run vm

## Environment

- Firecracker version = `v0.22.1.`
- Host and guest kernel versions = `Linux debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux`.
- Rootfs used = `https://s3.amazonaws.com/spec.ccfc.min/img/hello/fsfiles/hello-rootfs.ext4`.
- Architecture = `x86_64`.
- Kernel image = `https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin`.

## Additional context

Maybe it's related to:
* https://github.com/firecracker-microvm/firecracker/issues/1968
* https://github.com/kata-containers/documentation/issues/749
## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

**Comment by olehdevua** [comment]
When I try to start `firecracker` with config file, I have similar result

```bash
firecracker --api-sock /tmp/firecracker.socket --config-file /tmp/vm_config.json
2020-10-19T17:10:17.115557432 [anonymous-instance:ERROR:src/firecracker/src/main.rs:276] Building VMM configured from cmdline json failed: KernelLoader(InvalidElfMagicNumber)
```

> vm_config.json

```json
{
  "boot-source": {
    "kernel_image_path": "/tmp/vmlinux.bin",
    "boot_args": "console=ttyS0 reboot=k panic=1 pci=off"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "/tmp/hello-rootfs.ext4",
      "is_root_device": true,
      "is_read_only": false
    }
  ],
  "machine-config": {
    "vcpu_count": 2,
    "mem_size_mib": 1024,
    "ht_enabled": false
  }
}
```

**Comment by aghecenco** [comment]
Hi @olehdevua! Looks like there are 2 different issues here -
1. Firecracker reporting the stock kernel as being invalid
1. `/dev/kvm` not found on the host

The latter is causing the panic. Can you please check if you have `/dev/kvm` and access to it? Also, can you please paste the output of `tools/devtool checkenv` (from the `firecracker` directory)?

**Comment by aghecenco** [comment]
@olehdevua I tried out [Firecracker v0.22.1](https://github.com/firecracker-microvm/firecracker/releases/tag/v0.22.1) with [the stock kernel](https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin) too and I'm not seeing the error you reported. Maybe the kernel file you're trying to run got corrupted? Can you check its md5 against the one in s3? Posting it here for comparison:
```
$ wget https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin

hello-vmlinux.bin                         100%[====================================================================================>]  20.28M  1.08MB/s    in 23s     

2020-10-19 17:31:10 (901 KB/s) - ‘hello-vmlinux.bin’ saved [21266136/21266136]

$ md5sum hello-vmlinux.bin 
fce96ecd9aa0150c1849151b251215dc  hello-vmlinux.bin
```

**Comment by olehdevua** [comment]
@aghecenco 
Yes, `kvm` was not enabled. I forgot to do it after I bought new PC. Sorry.
Now everything is ok.
Thanks
