### ISSUE TITLE
Add mechanism to select per block device cache strategy.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2207]
We should investigate the opportunity and possibilities to allow customers to influence how host storage is being accessed in the Firecracker block device emulation. Here is a list of switches that might make sense to expose as configuration options:
- ignore flush commands (from guest virtio driver) for performance reasons
- use host page cache for read/write operations or prefer direct io with the block file
- synchronous mode (O_SYNC/O_DSYNC) - writes will be reported complete only when committed to the host storage device

**Comment by berciuliviu** [comment]
Relates to [2223](https://github.com/firecracker-microvm/firecracker/pull/2223)
