### ISSUE TITLE
[Bug] lIPv6 duplicate addressdetected

### ISSUE THREAD

**Issue by RDaneelOlivav** [firecracker-microvm/firecracker#2222]
## Describe the bug

When following the tutorial of network setup in an AWS Ubuntu 18 instance, it gives this error.

localhost:~# [   41.373407] IPv6: eth0: IPv6 duplicate address fe80::10af:e9ff:feee:4dc2 detected!

## To Reproduce

1) Launch an AWS instance with ubuntu  18 ( ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20200908 (ami-0823c236601fef765) )
2) Follow the [hello world tutorial](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) plus [the network tutorial](https://github.com/firecracker-microvm/firecracker/blob/master/docs/network-setup.md)

## Expected behaviour

When testing in ARM works.
But in Instances for x86 doesnt work

Any ideas of what could be happening here?

**Comment by serban300** [comment]
Hi @RDaneelOlivav ! What kind of AWS instance are you using ? Is this also reproducing on `.metal` instances ?

**Comment by raduiliescu** [comment]
Most likely this is a problem with your setup and you are using the same mac address for two VMs or other interfaces. The address that was detected as duplicate, is a link local IPv6 addresses that is auto generated with the prefix fe80::/10 while the subfix is most likely the mac address or a hash based on mac. For more info see - https://tools.ietf.org/html/rfc4861 and https://tools.ietf.org/html/rfc8064.

**Comment by dianpopa** [comment]
Hi @RDaneelOlivav 

Are you still facing this problem? Is still something we can help with?

**Comment by serban300** [comment]
Closing this issue for the moment. @RDaneelOlivav please feel free to reopen it if you're still facing the issue.
