### ISSUE TITLE
[Improvement] Use `BitRange` from cpuid crate for computing bit shift in VGIC's ICC registers

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#2236]
We have a specialized structure for reading bit ranges, for example 10:8. It is defined in the cpuid crate. It's called BitRange. We could move it to the utils crate an use it here instead of bit shifts.

**Comment by serban300** [comment]
Actually I think we should move the contant of the `cpuid` crate into `arch/86_64` since it's x86 specific. And then we can also use the `BitHelper` trait for ARM.

**Comment by serban300** [comment]
I don't think it's worth implementing this especially after merging #2386 . We would have to:
- move cpuid into arch
- implement BitRangeExt for u64

This is a lot of work and we would use BitHelper for only 2 operations.

Closing the issue for the moment.
