### ISSUE TITLE
Performance testing: Report improvements

### ISSUE THREAD

**Issue by alindima** [firecracker-microvm/firecracker#2241]
Some of Firecracker's existing performance tests, like `test_boottime` only check that the actual boot time is lower than the baseline.

However, the tests do not account for when some changes actually increase the performance. We should add interval checks with pre-determined delta values, so that we catch performance improvements during test runs, and we adjust the target values accordingly.

This is similar to what currently happens with the code coverage check - the test also fails if the actual coverage is higher than the target value (with a delta margin), forcing an update.

**Comment by pb8o** [comment]
Won't fix, we will track boottime as a metric, without checking it against a baseline

**Comment by alindima** [comment]
Does this mean that boottime will no longer be validated in the tests?
This is quite an important metric for Firecracker and it enabled us to discover regressions in the past.

Also, as far as I remember, this issue covered other tests as well, such as process start up time and not only.

**Comment by pb8o** [comment]
Hi Alin! For now it is still validated against the max threshold to identify regressions. However as this issue says, it is hard to identify a regression/improvement on a metric from a single test run, and baselining the metric creates churn. We are internally revisiting how we track performance, possibly doing it outside of the tests, but rest assured we will keep tracking this metric :)
