### ISSUE TITLE
[Improvement] Implement new mechanism to test balloon functionality

### ISSUE THREAD

**Issue by georgepisaltu** [firecracker-microvm/firecracker#2261]
Currently in the integration test, in order to test if balloon inflate and deflate operations are successful, we check the RSS (resident set size) before the operation, send the API request to perform the operation, then `sleep` for some time to wait for the operations to complete, as they are not instantaneous. This can be improved by creating a testing mechanism that takes a reading of the desired metric and compares it to a baseline established previously. In the case the assertion fails, it sleeps for some small amount of time, then tries again, up to a max allowed tries. This will speed up the tests, as a lot of time is generally wasted during those `sleep`s.

**Comment by acatangiu** [comment]
It'd be cool to fix this by implementing a `utils` general _monitor_ object that polls a given `condition` at a given `interval` with a given `timeout`.

This _monitor_ can be then reused throughout various tests that also suffer from the same problem.

**Comment by EvanJP** [comment]
I wouldn't mind being assigned to this ~ (looking for issues to help out on for my UT Austin virtualization class, I've worked with others on an open-source rust repo as well [https://github.com/unicode-org/icu4x](https://github.com/unicode-org/icu4x))

**Comment by acatangiu** [comment]
@EvanJP I see this was fixed in #2264 ; I don't know why the issue remained open.. closing it now.
