### ISSUE TITLE
security(jailer): add a default security to prevent pid-exhaust attack

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [firecracker-microvm/firecracker#2273]
## Why is this feature request important?  What are the use cases?  Please describe.

If the malicious actor escapes from the firecracker virtualization barrier can perform a pid-exhaust attack (exhaust all pids on the host, possibly via creating infinite zombies).

## Describe the desired solution

Jailer can restrict this attack through [pid cgroup controller](https://www.kernel.org/doc/Documentation/cgroup-v1/pids.txt). setting `pids.max` to some safe number (not `max`) can prevent this attack as malicious actor cannot create task more than `pids.max`.

## Describe possible alternatives

Suggest a safe `pids.max` number in documentation and ask user to pass via `--cgroup` parameter of jailer.

## Additional context

* IMO this security can be added default in jailer because i was not able see a usecase to override `pids.max` value by user.
* IMO as `pids.max` is firecracker process dependent it will be good if firecracker community maintain a suitable value for it. In future firecracker community can alter that value based on their usecase.

* Docker has a `--pid-limit` argument to limit max pids of single container. default value is max. checked in `Docker version 19.03.6, build 369ce74a3c`.

## Checks
- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by raduiliescu** [comment]
Thank you for bringing your security concerns to our attention! We will investigate these immediately and follow up with you within 5 business days to provide a status.

**Comment by raduiliescu** [comment]
Hi @KarthikNedunchezhiyan ,

On Firecracker we use [seccomp](https://www.kernel.org/doc/Documentation/prctl/seccomp_filter.txt) filters to limit the system calls allowed by the host OS to the required minimum. In our [prod-host setup](https://github.com/firecracker-microvm/firecracker/blob/master/docs/prod-host-setup.md) we recommend running in production with the highest level of filtering --seccomp-level=2. Even assuming a failure of the virtualization barrier, calling clone, fork or exec syscalls is not allowed, making it impossible to trigger a pid exhaustion attack.
Setting pids.max thorugh pid cgroup controller for mitigating a pid-exhaustion attack appears to be redundant, so I propose closing this issue. Please reopen if you have any additional comments.

Thanks!
