### ISSUE TITLE
[Bug] InstanceInfo YAML description is inconsistent with Firecracker implementation

### ISSUE THREAD

**Issue by gc-plp** [firecracker-microvm/firecracker#2287]
## Describe the bug

There is an inconsistency in how Firecracker returns the `InstanceInfo` structure when compared to how it's described in the YAML file:
- YAML: https://github.com/firecracker-microvm/firecracker/blob/ce6b03cd7c351a0fe9996f734cb577bb22af9702/src/api_server/swagger/firecracker.yaml#L814
- Firecracker: https://github.com/firecracker-microvm/firecracker/blob/f81db9cb4fe2100bac8957dc69da4e0db209d01a/src/vmm/src/vmm_config/instance_info.rs

Change introduced here: https://github.com/firecracker-microvm/firecracker/commit/54e9963127b6ecdc9fe7457f58a76816f13bafcc (edited) 

## To Reproduce
1. Start a Firecracker instance.
2. Run `curl --unix-socket api.sock -i -X GET "http://localhost:/"`

## Expected behaviour

`InstanceInfo` should be returned in the same format as how it's described in the YAML file.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`

## Checks
- [ ] Have you searched the Firecracker Issues database for similar problems?
- [ ] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

**Comment by acatangiu** [comment]
Duplicate of #2294
