### ISSUE TITLE
[Code improvement] deduplicate literal HTTP responses in tests

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#2293]
There are many tests with literal hardcoded HTTP responses that bloat the code. Some of them even have data embedded in them, making those tests hard to maintain.

Example possible deduplication:

in https://github.com/firecracker-microvm/firecracker/blob/e8200f3c3eaba014220e447e8d426c8cf8607eec/src/api_server/src/parsed_request.rs#L511 :

```diff
-        let expected_response = format!(
-            "HTTP/1.1 200 \r\n\
-             Server: Firecracker API\r\n\
-             Connection: keep-alive\r\n\
-             Content-Type: application/json\r\n\
-             Content-Length: 122\r\n\r\n{}",
-            VmConfig::default().to_string()
-        );
+        let body = VmConfig::default().to_string();
+        let expected_response = http_response_ok(&body);
        );
```

where `http_response_ok()` could be reused in all tests.

Example `http_response_ok()` definition:

```rust
fn http_response_ok(body: &str) {
    format!(
        "HTTP/1.1 200 \r\n\
         Server: Firecracker API\r\n\
         Connection: keep-alive\r\n\
         Content-Type: application/json\r\n\
         Content-Length: {}\r\n\r\n{}",
         status_code,
         body.len(),
         body,
    )
}
```

**Comment by EvanJP** [comment]
Hi!  I would like to be assigned to this if possible as a first issue to explore the code base (one of the many UT Austin students looking for issues to help out on)

**Comment by EvanJP** [comment]
Would we want to be parsing the (firecracker.yaml)[https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/swagger/firecracker.yaml] file in case the API changes, or should we just keep it simple and hard-code the function definitions first? 

An example function definition might be `fn call_machine-config(request: Request, ht_enabled: bool, mem_size_mib: i32, track_dirty_pages: Option<bool>, vcpu_count: i32) -> String` where `Request` is simply an enum for `PATCH, POST,` etc.

If the usage of `Option` for the optional params seem good to y'all I'll go ahead with implementing these.

**Comment by acatangiu** [comment]
I don't follow. I'm guessing you're talking about further improvements, this issue is very simple and only tracks deduplicating all the http static/hardcoded contents.

Example: define a function:
```rust
fn http_response_ok(body: &str) {
    format!(
        "HTTP/1.1 200 \r\n\
         Server: Firecracker API\r\n\
         Connection: keep-alive\r\n\
         Content-Type: application/json\r\n\
         Content-Length: {}\r\n\r\n{}",
         status_code,
         body.len(),
         body,
    )
}
```

and use it across tests in `firecracker/src/api_server/src/parsed_request.rs` to replace hardcoded http contents

**Comment by EvanJP** [comment]
I just created a PR #2340 for this @acatangiu. Please review!

> I'm guessing you're talking about further improvements, this issue is very simple and only tracks deduplicating all the http static/hardcoded contents.

Yeah, I was suggesting creating functions that would take in all the parameters for the REST API YAML, and then creating the formatted string from there, removing all hard-coded strings from the tests, but it would probably be overkill and require a lot of changes if the YAML changes.
