### ISSUE TITLE
Replace fixture generation through exec() with a cleaner method

### ISSUE THREAD

**Issue by gbionescu** [firecracker-microvm/firecracker#2297]
Currently, [image fixtures](https://github.com/firecracker-microvm/firecracker/blob/master/tests/conftest.py#L467) are built by enumerating capabilities in the S3 bucket and calling `exec()` to create new fixtures.

It would be much cleaner to have a list of images inside the test framework that generates the fixtures for us.

Documentation will also have to be updated: https://github.com/firecracker-microvm/firecracker/blob/41c9cdb00d1061b6f7a67b0cf754edd2ebdd069c/tests/README.md#adding-microvm-images

**Comment by kumargu** [comment]
Happy to help on the issue.

**Comment by roypat** [comment]
Above PR has been merged. With the new CI artifacts, we no longer generate fixtures through `exec`
