### ISSUE TITLE
[Feature Request] integration tests: need support for per-binary version API

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#2315]
## Why is this feature request important?  What are the use cases?  Please describe.

We have tests (currently some snapshot ones) that run multiple `firecracker` versions. The tests currently use the same API code to communicate with them, but the `firecracker` API changes over time.

## Describe the desired solution

Tests contain a framework that has per firecracker-version API code so that the API differences are transparent to the actual functional tests.

## Describe possible alternatives

Currently tests themselves implement special logic to differentiate between firecracker api versions.

## Additional context

NA

## Checks
- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by pb8o** [comment]
We have decided to only support the current version of Firecracker in the integration tests. Furthermore cross-version snapshot support is deprecated in #4230. Resolving.
