### ISSUE TITLE
[Bug] Incorrect --version output for main branch builds.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2317]
## Describe the bug

./firecracker --version outputs ```Firecracker v0.21.0-695-g8101086b-dirty```

## Expected behaviour

./firecracker --version should output ```Firecracker v0.24.0-695-g8101086b-dirty```

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by alindima** [comment]
Firecracker's `--version` arg simply returns the output of `git describe --dirty`.
According to the documentation:

> The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit.

The way I see it, this is not really a problem with Firecracker's version command. This is a problem with the way we tag releases.

If we tag releases on branches other than master, that have a different commit history (even different hashes/ordering), this output is actually normal.

IMHO, if we see this as a problem, we should make sure that all release tags happen on master.

**Comment by raduweiss** [comment]
If the release binaries have proper output for `./firecracker --version` (since they get the right tags on their release branches), the other way to make this consistent may be to add a single tag on the main branch that results in the right language, e.g., `Firecracker devbrach-695-g8101086b-dirty`. I think this should work with the [one-flow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow) branching strategy we're now using.

**Comment by sandreim** [comment]
I like the idea to tag main branch with something like v0.24-wip. Once the v0.24 release branch is created we can create a new tag with v0.25-wip and so on.

**Comment by sandreim** [comment]
Interested to see what @firecracker-microvm/compute-capsule folks think.

**Comment by alindima** [comment]
+1 for tagging the main branch as a post-release step for major and minor releases

**Comment by acatangiu** [comment]
@sandreim I think you need to `git pull --tags` locally to get the latest tags

**Comment by acatangiu** [comment]
I see the problem, we only tag release branches but not mainline anymore.

**Comment by l1x** [comment]
After compiling on the master branch I get the following:

```
build/cargo_target/aarch64-unknown-linux-musl/release/firecracker --version
Firecracker v0.21.0-729-g41168250

Supported snapshot data format versions: v0.23.0, v0.24.0
```

During compilation:

```
[Firecracker devtool] About to pull docker image fcuvm/dev:v24
...
Compiling firecracker v0.23.0 (/firecracker/src/firecracker)
```

**Comment by alsrdn** [comment]
Closing this issue since we want to add functionality to override the version string if needed. See https://github.com/firecracker-microvm/firecracker/issues/3057
