### ISSUE TITLE
[tests] Differentiate between statistics consumer and measurements consumer

### ISSUE THREAD

**Issue by iulianbarbu** [firecracker-microvm/firecracker#2318]
In the current design, there is no clear distinction between the statistics consumer and measurements consumers. The current functionality seems duplicated for both cases and their implementation are very similar. In practice, there is no clear way to differentiate between the two and where should they be used. This will help for easier documentation of the usage as well.

We must separate the consumption interfaces for the two types of consumers. Furthermore, the statistics definitions receive a mandatory statistics function argument, which is not needed for directly consumed statistics. This argument must be optional.

**Comment by alsrdn** [comment]
Closing this for now. While this is a nice to have improvement, the current system works well for our use-case. We might want to re-open it when/if we decide to change or improve the perf testing framework.
