### ISSUE TITLE
[Feature Request] Add capability to dump the Firecracker configuration

### ISSUE THREAD

**Issue by raduiliescu** [firecracker-microvm/firecracker#2356]
## Why is this feature request important?  What are the use cases?  Please describe.
When replicating an issue is important to start from the Firecracker configuration used by the customers. 
There is no way to dump the configuration of a running Firecracker microVM. Currently all API calls received by FC are logged, but this happens only on the info level which is not configured by default.

Either the customer has to reproduce the issue again with info log enabled, or have all commands recorded in some way.

## Describe the desired solution

Would be nice to add --dump-config API endpoint that would either dump a config file or a record of all the commands.

## Checks
- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by Tobbeman** [comment]
I can take a look if maintainers want the feature in the code base.

An /export endpoint sounds like a good idea to me.

**Comment by sandreim** [comment]
Thanks for the bias for action @Tobbeman. An `/export` endpoint also sounds good to me, but I would like to hear how the @firecracker-microvm/compute-capsule folks think about this as well.

**Comment by georgepisaltu** [comment]
I think the endpoint solution proposed by @Tobbeman is a great way to do this, should also be straightforward to implement.

**Comment by dianpopa** [comment]
It would be a great feature to have in Firecracker. An `/export` endpoint sounds good to me. @Tobbeman thanks for the interest in contributing!

**Comment by sandreim** [comment]
@Tobbeman looks like `/export` is the way to go. We're happy to review the PR once it is ready 😄

**Comment by Tobbeman** [comment]
Great, I'll look into it :+1:

**Comment by acatangiu** [comment]
An `API` endpoint sounds good to me too. The URL name will depend on what information it will offer which in turn depends on the implementation.

There have been two options thrown around on this thread:
1. Exporting current configuration
2. Exporting a log of historic configuration commands

A quick brain-dump on approaching each of these two options:
1. Firecracker does not keep per-se configuration information other than internal intrinsic state. When a resource is configured, the _configuration description_ is used to build the resource, then the _description_ is discarded.
To provide _descriptions_ at runtime, new code spanning multiple components would be required to generate _configuration descriptions_ from internal state.
2. Which brings me to the second option, where we could simply store the _configuration descriptions_ provided by the user or even the complete _configuration API commands_ and their responses (results). This full configuration history can be provided on an `/export`-like request.
This option could be implemented and handled solely in/by the `api_server` component.

I would personally opt for option 2.
I would also agree to option 1, provided we make sure that the per-resource _description_ mechanism is generic and decoupled enough so as to be also accepted by the https://github.com/rust-vmm/ (future and current) upstream components.

**Comment by Tobbeman** [comment]
Hello, sorry for slow response, I have not been able to put as much time as I wanted into this.

I'm not very familiar with the code-base, so I have mostly been experimenting so far.

My first naive implementation was to take the running [VmResource](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/resources.rs#L79) and transform it into [VmmConfig](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/resources.rs#L55), similar to option 1 @acatangiu mentioned.

This however means some code has to be modified as some of the entries in VmResource is the result of a one way transformation from VmConfig. For example BootConfigSource -> BootSource transform string entries to file descriptors. While there are potential ways to transform back, they are pretty "hacky" with several [drawbacks](https://stackoverflow.com/questions/1188757/retrieve-filename-from-file-descriptor-in-c)

The simplest solution in my mind would be to embed the SourceConfig as a entry in BootSource. While it would solve the problem I'm not sure how "beautiful" the solution is.

I think I'd rather see option 2 and will attempt that.
As mentioned this solution could probably store the history of changes as well fairly easily, is that of interest?

**Comment by Tobbeman** [comment]
I just recalled why I started going for option 1.
One drawback with option 2 would be having to keep track in each separate config endpoints when/if to update the history. That is something that is easily implemented but might be annoying to maintain. Would a new config endpoint be introduced, it could easily be overlooked to also update the config history.

I'll see if I can create a middleware to make maintenance easier.

**Comment by acatangiu** [comment]
> One drawback with option 2 would be having to keep track in each separate config endpoints when/if to update the history. 

I think keeping per-endpoint history is overkill. A simple global record of all configuration commands should work good enough I think.

If they're interested in a certain endpoint, users can always filter the big json for interested endpoints

**Comment by Tobbeman** [comment]
Sorry, perhaps we misunderstand each other
If we keep a record of the config in api_server, any action that change the config must also change the record, right?

I mean, if we add network config that must also be reflected in the record.
Thus all endpoints must continuously add to the record

**Comment by acatangiu** [comment]
I was thinking of a simple version where we just keep all config cmds history.

So: 
> If we keep a record of the config in api_server, any action that change the config must also change the record, right?

No need to change anything, just add to the history, users can see history of commands and deduce final config easily.

I see this would be mostly as a debugging/auditing mechanism, and not something used in production so I would keep complexity to a minimum.

**Comment by Tobbeman** [comment]
Right, I think I finally understand what you are saying. 
Thanks for being patient with me :) 

I guess we only need to store configuration changes, right?
So only PUT/PATCH

Question, could we simply change the default logging level or change the level that api_server logs requests?

**Comment by Tobbeman** [comment]
Created a draft PR
The payload is currently being escaped excessively but the PR will show my intentions
