### ISSUE TITLE
[Bug] v0.24.0 release does not have jailer in assets

### ISSUE THREAD

**Issue by mrl5** [firecracker-microvm/firecracker#2390]
previous releases had `jailer` in assets, however for some reason release `v0.24.0` has only `firecracker` but `jailer` is missing

is this expected?

**Comment by raduweiss** [comment]
Hi @mrl5! The releases are now `.tgz` archives, and all the previous artifacts, including the jailer binaries, are in the archive. As far as we can tell the jailer binaries are indeed in the archives for v0.24.

**Comment by mrl5** [comment]
thanks for info :) could you pls confirm that this will be like this in following releases?

**Comment by sandreim** [comment]
@mrl5 Confirmed 😁

**Comment by mrl5** [comment]
thanks for quick response, you guys are awesome!
