### ISSUE TITLE
[Bug] getting-started guide not updated to latest release model

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [firecracker-microvm/firecracker#2394]
## Describe the bug

[getting-started.md#getting-the-firecracker-binary](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#getting-the-firecracker-binary) is not updated to latest release model

## To Reproduce

Follow the steps provided in the [getting-started.md#getting-the-firecracker-binary](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#getting-the-firecracker-binary)

## Expected behavior

Expected to download the firecracker binary.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`
Updating the  [getting-started.md#getting-the-firecracker-binary](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#getting-the-firecracker-binary) to new release flow.

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by KarthikNedunchezhiyan** [comment]
Can someone please confirm that this is not intentional, happy to raise an MR 🙂.

**Comment by gc-plp** [comment]
Hi @KarthikNedunchezhiyan.

We recently updated the release model and indeed it looks like the documentation needs updating.

Please go ahead with opening a PR.
