### ISSUE TITLE
[fail  to reboot in arm64

### ISSUE THREAD

**Issue by magnate3** [firecracker-microvm/firecracker#2396]
## Describe the bug
when I executes  reboot in vm ,the vm actually executes poweroff

[  OK  ] Started Update UTMP about System Runlevel Changes.

Ubuntu 18.04.2 LTS fadfdd4af58a ttyS0

fadfdd4af58a login: root
Password: 
Last login: Mon Jan  4 02:24:24 UTC 2021 on ttyS0
Welcome to Ubuntu 18.04.2 LTS (GNU/Linux 4.14.138 aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.
root@fadfdd4af58a:~# reboot
[  OK  ] Stopped target Timers.
[  OK  ] Stopped Message of the Day.
[  OK          Stopping Serial Getty on ttyS0...
         Stopping Getty on tty2...
         Stopping Getty on tty4...
         Stopping Getty on tty5...
         Stopping Getty on tty3...
[  OK  ] Stopped getty on tty2-tty6 if dbus and logind are not available.
         Stopping Getty on tty6...
         Stopping OpenBSD Secure Shell server...
[  OK  ] Stopped Getty on tty5.
[  OK  ] Stopped Getty on tty4.
[  OK  ] Stopped Getty on tty3.
[  OK  ] Stopped Getty on tty6.
[  OK  ] Stopped Getty on tty2.
[  OK  ] Stopped Serial Getty on ttyS0.
[  OK  ] Stopped OpenBSD Secure Shell server.
[  OK  ] Removed slice system-serial\x2dgetty.slice.
[  OK  ] Removed slice system-getty.slice.
         Stopping Permit User Sessions...
[  OK  ] Stopped Permit User Sessions.
[  OK  ] Stopped target Remote File Systems.
[  OK  ] Stopped target Basic System.
[  OK  ] Stopped target Sockets.
[  OK  ] Stopped target Slices.
[  OK  ] Stopped target System Initialization.
[  OK  ] Stopped target Local Encrypted Volumes.
[  OK  ] Stopped target Swap.
         Stopping Update UTMP about System Boot/Shutdown...
[  OK  ] Stopped Apply Kernel Variables.
[  OK  ] Stopped Load Kernel Modules.
         Stopping Load/Save Random Seed...
[  OK  ] Stopped target Paths.
[  OK  ] Stopped Dispatch Password Requests to Console Directory Watch.
[  OK  ] Stopped Forward Password Requests to Wall Directory Watch.
[  OK  ] Stopped Load/Save Random Seed.
[  OK  ] Stopped Update UTMP about System Boot/Shutdown.
[  OK  ] Stopped Create Volatile Files and Directories.
[  OK  ] Stopped target Local File Systems.
[  OK  ] Stopped target Local File Systems (Pre).
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
         Starting Reboot...
[   13.213008] reboot: Restarting system
[   13.213008] reboot: Restarting system
root@ubuntu:~# ps -elf | grep firecracker
0 S root     11729 48133  0  80   0 -  1096 pipe_w 12:04 pts/0    00:00:00 grep firecracker
root@ubuntu:~# ps -elf | grep firecracker
0 S root     11875 48133  0  80   0 -  1096 pipe_w 12:05 pts/0    00:00:00 grep firecracker
root@ubuntu:~# 

## To Reproduce

`[Author TODO: Steps to reproduce the behaviour:]`
`[ 1. Start Firecracker via....]`
`[ 2.  execute reboot ]`
`[ 3. the vm poweroff and not reboot again ]`

## Expected behaviour

`[Author TODO: A clear and concise description of what you expected to happen.]`

## Environment

 root@ubuntu:~# uname -a
Linux ubuntu 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:10:24 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu:~#

**Comment by georgepisaltu** [comment]
Hi @magnate3,

Because we do not manage power states through ACPI or a similar mechanism, we don't support the traditional reboot. Issuing a `reboot` command in the guest will result in shutting down the VM and the Firecracker process gracefully and that is intended. We currently have no way of cleanly rebooting on `aarch64`.

**Comment by georgepisaltu** [comment]
For a more in depth look, I encourage you to check out our [FAQ](https://github.com/firecracker-microvm/firecracker/blob/master/FAQ.md#how-can-i-gracefully-reboot-the-guest-how-can-i-gracefully-poweroff-the-guest).

I'll close this issue.
