### ISSUE TITLE
Commit 76528ea4 aarch64: setup cache topology regression

### ISSUE THREAD

**Issue by pclesr** [firecracker-microvm/firecracker#2407]
# Describe the bug

Commit 76528ea4 aarch64: setup cache topology causes a regression on systems that do not have FDT cache entries.

## To Reproduce

On an aarch64 system with a minimal FDT, run without this commit. 

Then, add the commit. Firecracker will fail with:
`2021-01-08T13:40:26.079775900 [vmnetns:main] Building VMM configured from cmdline json failed: ConfigureSystem(SetupFDT(ReadCacheInfo(InvalidCacheAttr("Line Size", "cannot parse integer from empty string"))))
`

## Expected behaviour

Firecracker should have sufficient defaults to handle this. Also, the code should check for the existence of the required entries in /sysfs and display an error warning instead of the above cryptic message.

## Environment

The FDT is basic, with no cache architecture lines in the FDT. As a result, `/sys/devices/system/cpu/cpu0/cache//index{0..2}` contains only
```
ls /sys/devices/system/cpu/cpu0/cache//index0
level power shared_cpu_list shared_cpu_map type uevent
```

`[ - Firecracker version.]`
Upstream master as of Jan 8. Last commits:
364cf32b (upstream/master, upstream_master) Increase Pytest Coverage
62d7a1b8 Implement Guard Paging Mechanism
bf4796da docs: updating Firecracker maintainers
1026a7c1 CI: modify func for retrieving files

`[ - Host and guest kernel versions.]`
Host: android 4.14
`[ - Rootfs used.]`
N/A
`[ - Architecture.]`
aarch64
`[ - Any other relevant software versions.]`

## Additional context

I have to revert this commit to use firecracker.

`[Author TODO: Do you have any idea of what the solution might be?]`
Check for and supply reasonable defaults for cache params.

## Checks

- [ x] Have you searched the Firecracker Issues database for similar problems?
- [x ] Have you read the existing relevant Firecracker documentation?
- [x ] Are you certain the bug being reported is a Firecracker issue?

**Comment by dianpopa** [comment]
Hi @pclesr ,

Thanks for logging an issue for this problem. I will post a PR with a fix as soon as I get some bandwidth. Of course that you are also welcome to post a PR with the fix if you want to.

**Comment by dianpopa** [comment]
Hello @pclesr ,

I posted https://github.com/firecracker-microvm/firecracker/pull/2438 which is meant to solve this issue. Do you think you can try it out and see if it solves your problem?

Thanks!

**Comment by pclesr** [comment]
Thank you for fixing this. I can now boot on a machine that does not support those fields. The log contains the following:
```
2021-02-11T14:44:13.644784800 [foo:main] Could not read the coherency line size for cache level 1
2021-02-11T14:44:13.644873400 [foo:main] Could not read the size for cache level 1
2021-02-11T14:44:13.644914100 [foo:main] Could not read the number of sets for cache level 1
2021-02-11T14:44:13.645116300 [foo:main] Could not read the coherency line size for cache level 1
2021-02-11T14:44:13.645155500 [foo:main] Could not read the size for cache level 1
2021-02-11T14:44:13.645190500 [foo:main] Could not read the number of sets for cache level 1
2021-02-11T14:44:13.645360900 [foo:main] Could not read the coherency line size for cache level 2
2021-02-11T14:44:13.645396700 [foo:main] Could not read the size for cache level 2
2021-02-11T14:44:13.645432900 [foo:main] Could not read the number of sets for cache level 2
2021-02-11T14:44:13.645466600 [foo:main] Could not read cache level for index 3: Failed to read cache information: No such file or directory (os error 2)
```

Maybe not all the error logs are required; maybe just log the first one since after that it is doubtful that the others will be there as well, but that's just a nit.

**Comment by dianpopa** [comment]
> Thank you for fixing this. I can now boot on a machine that does not support those fields. The log contains the following:
> 
> ```
> 2021-02-11T14:44:13.644784800 [foo:main] Could not read the coherency line size for cache level 1
> 2021-02-11T14:44:13.644873400 [foo:main] Could not read the size for cache level 1
> 2021-02-11T14:44:13.644914100 [foo:main] Could not read the number of sets for cache level 1
> 2021-02-11T14:44:13.645116300 [foo:main] Could not read the coherency line size for cache level 1
> 2021-02-11T14:44:13.645155500 [foo:main] Could not read the size for cache level 1
> 2021-02-11T14:44:13.645190500 [foo:main] Could not read the number of sets for cache level 1
> 2021-02-11T14:44:13.645360900 [foo:main] Could not read the coherency line size for cache level 2
> 2021-02-11T14:44:13.645396700 [foo:main] Could not read the size for cache level 2
> 2021-02-11T14:44:13.645432900 [foo:main] Could not read the number of sets for cache level 2
> 2021-02-11T14:44:13.645466600 [foo:main] Could not read cache level for index 3: Failed to read cache information: No such file or directory (os error 2)
> ```
> 
> Maybe not all the error logs are required; maybe just log the first one since after that it is doubtful that the others will be there as well, but that's just a nit.

@pclesr I addressed your feedback regarding logging. Let me know if there is any issue left. Thanks!
