### ISSUE TITLE
[Feature Request] Do we plan to support mips platform

### ISSUE THREAD

**Issue by ruishawn** [firecracker-microvm/firecracker#2415]
# Feature Request
We can run fireacker on x86_64 and arm64 platform,  do we have plan to support mips platform?

## Checks

- I want to generate a binary file for mips platform, but failed.

**Comment by sandreim** [comment]
Hi @ruishawn! Currently MIPS is not supported, but that doesn't mean we can't add it to our roadmap if we discover a compelling usecase. Can you give us some context and details about your usecase for Firecrackerer on MIPS?

**Comment by serban300** [comment]
Hi @ruishawn ! Sorry, just a quick ping. Could you offer us more details on your use case for Firecracker on MIPS ?

**Comment by serban300** [comment]
I will resolve this issue for the moment. Please feel free to reopen it if needed.
