### ISSUE TITLE
[Bug] Not able to launch firecracker with `--node 1` jailer argument

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [firecracker-microvm/firecracker#2417]
# Describe the bug

I was able to spawn firecracker successfully if the jailer argument has `--node 0` but it is getting failed (error provided below) for `--node 1` constantly. But I have sufficient cpus and memory in all numa nodes.

```
[123:main:ERROR:src/firecracker/src/main.rs:53] Firecracker panicked at 'called `Result::unwrap()` on an `Err` value: VcpuFd(Error(12))', src/vmm/src/vstate/vcpu/mod.rs:209:48
```

I have come across this https://github.com/firecracker-microvm/firecracker/issues/835 but In my case i have sufficient memory and cpus (provided the data in addition context section).

## To Reproduce

In my machine launching the below command produces the error.

```
sudo ./jailer --id 123 --exec-file ./firecracker --uid 1000 --gid 1000 --chroot-base-dir ./jail --node 1 -- --config-file fc_config.json --no-api
```

fc_config.json content

```
{
    "boot-source": {
        "kernel_image_path": "vmlinux",
        "boot_args": "console=ttyS0 reboot=k panic=1 pci=off"
    },
    "drives": [
        {
            "drive_id": "rootfs",
            "path_on_host": "rootfs.ext4",
            "is_root_device": true,
            "is_read_only": false
        }
    ],
    "machine-config": {
        "vcpu_count": 1,
        "mem_size_mib": 1024,
        "ht_enabled": false
    }
}
```

## Expected behavior

Able to launch firecracker process in `--node 1` argument.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
v0.24.0-x86_64
`[ - Host kernel versions.]`
3.10.0-957.21.3.el7.x86_64
`[ - Rootfs and guest kernel used.]`
rootfs and vmlinux is getting-started one.
`[ - Architecture.]`
x86_64
`[ - Any other relevant software versions.]`

## Additional context

```
$ free -g
              total        used        free      shared  buff/cache   available
Mem:            125           1         122           0           1         123
Swap:             0           0           0

$ numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 6 7 8 9 20 21 22 23 24 25 26 27 28 29
node 0 size: 65234 MB
node 0 free: 62780 MB
node 1 cpus: 10 11 12 13 14 15 16 17 18 19 30 31 32 33 34 35 36 37 38 39
node 1 size: 65536 MB
node 1 free: 62844 MB

$ cat /sys/fs/cgroup/cpuset/cpuset.mems
0-1

$ cat /sys/fs/cgroup/cpuset/cpuset.cpus
0-39

$ cat /sys/fs/cgroup/cpuset/firecracker/cpuset.mems
0-1

$ cat /sys/fs/cgroup/cpuset/firecracker/cpuset.cpus
0-39

$ cat /sys/fs/cgroup/cpuset/firecracker/123/cpuset.cpus
10-19,30-39

$ cat /sys/fs/cgroup/cpuset/firecracker/123/cpuset.mems
1
```

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

**Comment by sandreim** [comment]
Hi @KarthikNedunchezhiyan. It seems that the error pops up even if there is enough memory available on both nodes. We'll look into it and get back to you soon.

**Comment by sandreim** [comment]
You are using an unsupported host kernel version: 3.10.0-957.21.3.el7.x86_64.

Minimum supported host kernel version is 4.14, please see FAQ here: https://github.com/firecracker-microvm/firecracker/blob/master/FAQ.md#what-operating-systems-are-supported-by-firecracker

PS: This is different than issue #835. The error is returned by the KVM_CREATE_VCPU ioctl.
