### ISSUE TITLE
Update the KVM capability checks.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2418]
Right now, the capabilities we check against are outdated -  https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/vstate/system.rs#L62

We need to iterate all KVM APIs currently used in Firecracker and update the capability list.

**Comment by binoychitale** [comment]
Hi @sandreim , I'd like to pick this up.
If I understand correctly, we want to perform a check for all the APIs from the `kvm_ioctls` wrapper that we are using.  (i.e methods being called on the various kvm [structs](https://docs.rs/kvm-ioctls/0.6.0/kvm_ioctls/#structs))

**Comment by acatangiu** [comment]
@binoychitale that is correct. Some of the kvm APIs depend on certain kvm capabilities, the capability dependencies are clearly documented in the public kvm API.

This issue tracks work in Firecracker to check the availability of those capabilities at microVM start-time.
