### ISSUE TITLE
Add JSON linter test

### ISSUE THREAD

**Issue by alindima** [firecracker-microvm/firecracker#2422]
Given the fact that performance baselines are going to be formatted as JSON files (example [test_block_performance](https://github.com/firecracker-microvm/firecracker/blob/master/tests/integration_tests/performance/configs/block_performance_test_config_raw.json)), Firecracker should have a JSON linter/formatter, so that we ensure proper style and readability.

We should probably install a linter, like [this one](https://github.com/zaach/jsonlint) in the docker container and add a integration test in the style folder that validates all json files

**Comment by Twister915** [comment]
I've written a version of this, but I thought it made more sense to just try to find JSON files and parse them with python, failing if the JSON is malformed. This does not check that the JSON is "pretty," but we could expand it to support that by doing something essentially like: `file_contents == json_pretty_print(json_parse(file_contents))`.

Please advise if you'd like to use an external tool instead, or how/if you want to address pretty printing as mentioned above. I will open a WIP PR tonight with my initial implementation.

**Comment by dianpopa** [comment]
> I've written a version of this, but I thought it made more sense to just try to find JSON files and parse them with python, failing if the JSON is malformed. This does not check that the JSON is "pretty," but we could expand it to support that by doing something essentially like: `file_contents == json_pretty_print(json_parse(file_contents))`.
> 
> Please advise if you'd like to use an external tool instead, or how/if you want to address pretty printing as mentioned above. I will open a WIP PR tonight with my initial implementation.

Hi @Twister915 ,

As far as my concern, your PR is enough for the moment. In my opinion, It would actually be a bit risky, since in the future we might have big jsons (for example a json used in performance testing) that we do not intend to pretty print. I will review in detail your PR shortly, thanks for the contribution!

**Comment by alindima** [comment]
Actually, even for lengthy JSONs, like the ones for performance testing baselines, we should have them pretty-printed. I think readability is important here as well, since some portions of those files are manually edited.

As you suggested @Twister915, we could simply compare the result of something like `json.dumps(indent=4)` to the actual JSON file.

This will however not have the advantage of clearly specifying formatting problems (like which line and column is wrong).
However, I think one can quickly format the code by having a script that simply runs a `json.dumps(indent=4)` over the JSON file.

First of all, I think you should check for reliability between runs. There may be a difference in the order of keys, for example, between multiple runs on the same file and we should first check that this is not the case.

If this does not suffice, I think we would need to use an external JSON formatting tool.

**Comment by gc-plp** [comment]
I think that we're being over cautious here. 

A JSON file should not be just lying around in our repo - it should have a purpose. That purpose should be either serving tests, baselines or simple examples for running Firecracker. 

JSON files should be validated by actually being interpreted by the functionality that depends on having them in the repo. For example, the performance tests do reference the jsons and load them, which makes them implicitly valid.

As for readability, if we want to make sure that they're indented in a way that we want, we should validate the way in which they're produced.

**Comment by Twister915** [comment]
@gc-plp 

```
JSON files should be validated by actually being interpreted by the functionality that depends on having them in the repo. For example, the performance tests do reference the jsons and load them, which makes them implicitly valid.
```

This is true, I agree. An invalid JSON, without this new code, can be put into the repository.

The only argument I see for still having this test is to have nicer error messages, clearly saying "this JSON file at `xyz.json` is invalid" instead of a failure in a different test.

**Comment by gc-plp** [comment]
We will address potential errors as part of the test failures. An authors responsibility is to make sure that tests pass before submitting.
