### ISSUE TITLE
Research VM topology.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2469]
VMMs can expose a topology the same way physical machines do. The topology Firecracker presents can have impact on guest scheduler decisions and can affect performance.

- CPU: threads, cores, dies, packages and sockets
- Cache hierarchy - L1/L2/L3
- NUMAness

**Comment by andreeaflorescu** [comment]
There is an issue that was talking about the cache topology as well, with some useful links: https://github.com/firecracker-microvm/firecracker/issues/1599

**Comment by sandreim** [comment]
Thanks @andreeaflorescu, that link in the issue is really useful. I will probably close this one as duplicate.
