### ISSUE TITLE
"for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done" is not working in container of Docker

### ISSUE THREAD

**Issue by yilmazsen** [firecracker-microvm/firecracker#2473]
Hello Dear Community of Firecracker,

Nowadays, I am working on firecracker microvm's. However, i saw that issue:
When I try to build new image from docker image this command **"for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done"** does not work. So I attempted to change this command like that **"for d in bin etc lib root sbin usr; do tar c "/$d" || tar x -C /my-rootfs; done"** it worked. After that when I run this image with firecracker, this image had not work.
Is there any problem with that command ? or Should I change docker version or firecracker version something like that ? 

if anyone could help me, I will be happy 
Best regards

**Comment by twitchyliquid64** [comment]
What kernel, kernel command line etc did you use?

**Comment by yilmazsen** [comment]
Thank you for your reply, I was using amazon' hello-vmlinux.bin (https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin).  By the way I was using Dockerfile with alpine image.  I solved my problem. I will type here what is my solution. @twitchyliquid64

**Comment by twitchyliquid64** [comment]
Do you get any console messages?

And is your rootfs in the correct format? If you are `tar`'ing the files, I'm not sure if that works (the [example here](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-firecracker) uses an ext4 filesystem)

**Comment by gc-plp** [comment]
Hi @yilmazsen. I assume that you're referring to [this](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md#creating-a-rootfs-image) example from the Firecracker repository, right?

Could you give us more details on what did not work when trying out the commands in the guide? What were the error messages?

**Comment by yilmazsen** [comment]
I am explaining that problem:

when we create a rootfs (https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md#creating-a-rootfs-image) image for our app. Such as nginx, I saw that problem. I followed these instructions:

```bash
docker run -it --rm -v /tmp/my-rootfs:/my-rootfs alpine
apk add openrc
apk add util-linux
apk add nginx 

# Set up a login terminal on the serial console (ttyS0):
ln -s agetty /etc/init.d/agetty.ttyS0
echo ttyS0 > /etc/securetty
rc-update add agetty.ttyS0 default

# Make sure special file systems are mounted on boot:
rc-update add devfs boot
rc-update add procfs boot
rc-update add sysfs boot

# Then, copy the newly configured system to the rootfs image:
for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done
for dir in dev proc run sys var; do mkdir /my-rootfs/${dir}; done

# All done, exit docker shell
exit
```

<img width="671" alt="Screen Shot 2021-03-02 at 21 19 49" src="https://user-images.githubusercontent.com/3442583/109695745-5456f900-7b9d-11eb-95b1-3720e1559292.png">

Is that normal ? @twitchyliquid64 What I did after install my apps for example nginx, if any folder created after installation nginx  under  the / directory, i copied these folders under the /my-rootfs. After of all, my rootfs image worked.

**Comment by gc-plp** [comment]
@yilmazsen, yes the messages are expected, but these are not errors.

Glad to know that the rootfs image eventually worked. Since this was sorted out, can we close the issue?

**Comment by yilmazsen** [comment]
@gc-plp of course , you can close this issue but you should add more details about this command "for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done".  Some of the people might be confused about it.

**Comment by gc-plp** [comment]
@yilmazsen thanks for the suggestion. Would you be interested in adding a PR?

**Comment by yilmazsen** [comment]
Of course, if you want, I can add a PR for my suggestion.
