### ISSUE TITLE
[Platforms] Update Firecracker Linux Kernel support policy & Linux kernel testing

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#2481]
# Feature Request

Firecracker currently supports Linux kernel 4.14+ for both guests and hosts. We need to improve this policy since some of the upcoming features won't work with older kernel versions.

## Describe the desired solution

We in the early stages of thinking about this. Any input is welcome!

Whatever we do, we'll have to end up testing on more kernel versions, including at least one that's future to the current support window. We currently only test on 4.14, so our statement that we support 4.14+ is basically "we test on 4.14, but we'll fix issues on 4.14+".

## Describe possible alternatives

TBA

If we don't update the policy at all, future Firecracker binaries will have to selectively enable/disable capabilities such as io_uring depending on host/guest Linux kernel versions, and at some point we'll also go out of the support window (the kernel itself is supported until 2024, but depending on the actual the actual distro support window might be much shorter).

## Additional context

TBA

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by andrewhsu** [comment]
@raduweiss wondering if you could provide more details/constraints for requirements? Is Firecracker looking to match kernel support for Amazon Linux 2? Does Firecracker wish to test on the mainline branch of the Linux Kernel to provide feedback to the kernel developers before a stable release of Linux kernel is cut? Is Firecracker looking to provide kernel version parity with other distros like Ubuntu, CentOS, or Fedora?

**Comment by raduweiss** [comment]
@andrewhsu we don't have answer to all those questions yet, but we're actively working through them.

I don't think we planned to test mainline kernels before a stable release, bur rather to test new stable releases before calling them supported it in Firecracker. However, we'll consider this in our next discussion on the topic.

@dianpopa will be able to share more once we start converging on an approach; we'd be happy to get community input here!

**Comment by dianpopa** [comment]
Starting with v1.0.0, we have released a kernel support policy that can be found here: https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md.
