### ISSUE TITLE
[Bug] Renaming target_mb and amount_mb to target_mib and amount_mib

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker#2482]
# Describe the bug

[Memory ballooning](https://github.com/firecracker-microvm/firecracker/blob/master/docs/ballooning.md) API is taking MB-based parameters (target_mb and amount_mb). However MachineConfiguration has been having mem_size_mib, which is MiB-based.

It would be better to use MiB throughout Firecracker for consistency.

## To Reproduce

N/A

## Expected behaviour

Firecracker uses either MB or MiB. I prefer MiB since that's what Firecracker has been using already. Switching to MB altogether breaks existing customers.

## Environment

NA

## Additional context

I've noticed that while reviewing https://github.com/firecracker-microvm/firecracker-go-sdk/pull/316

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by gc-plp** [comment]
@kzys, indeed this is inconsistent, good call!

I think that there are 3 options here:

1. We change the API endpoint to be consistent, but we break the current API layout.
2. We support both, but this seems a bit awkward.
3. We implement [versioned API support](https://github.com/firecracker-microvm/firecracker/issues/1503) and go with option 1 with versioning on top.

Option 3 sounds the most appealing to me as it offers a clean way of mapping API requests to versions. What do you think?

**Comment by kzys** [comment]
Firecracker is relatively young software and memory ballooning is even younger. Firecracker has made some breaking changes in past;

- InstanceInfo's status were Uninitialized, Starting and Running, but now they are Not started, Running and Paused
- There were log_fifo and metrics_fifo, but later renamed to log_path and metrics_path

I'm not against about versioned API itself, but this memory ballooning change is too minor compared to the incurring cost of supporting multiple versions.

**Comment by sandreim** [comment]
Thanks for the input here @kzys . My take on this is that we are dealing with a cosmetic change without any functionality impact. We'll sync on this and come back with a clear path forward.

**Comment by georgepisaltu** [comment]
Hi @kzys,

We are sure to fix the API definition so that it reflect the MiB semantics. We are still trying to decide whether this should be done in a patch release now or if it will be delivered in the v0.25 release.

We will let you know once we make a decision.

**Comment by georgepisaltu** [comment]
Hi all,

We have decided to deliver the fix renaming `target_mb` and `actual_mb` to `target_mib` and `actual_mib`, respectively, in Firecracker v0.25.

This issue will remain open until we merge the PR with the fix.

**Comment by georgepisaltu** [comment]
The PR with the fix was merged.

We will, however, keep this issue open until we release a patched Firecracker v0.24 with this fix as well.
