### ISSUE TITLE
Add stepping ability

### ISSUE THREAD

**Issue by LegNeato** [firecracker-microvm/firecracker#2483]
# Feature Request

Often you'll want to pause a VM and then run it for a set amount of wall clock time, cpu time, or cpu instructions and then pause it again.

## Describe the desired solution

New api, which allows a stopped / paused vm to run for a set number of cycles or time and then stop / pause automatically. Perhaps an optional callback should be used so a supervisor process doesn't have to poll the vm state to see when it is done stepping.

## Describe possible alternatives
* One can call pause, resume, and then pause quickly to approximate stepping. But it would not be deterministic.

## Additional info

I'm willing to put up a PR if someone will mentor me.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by gc-plp** [comment]
Hi @LegNeato, thanks for your interest in Firecracker!

Could you describe a use case where this feature would be applicable? 

While running for a set amount of time aka wall clock is possible even with the current implementation, the other options may not be easy to implement and we'd like to understand how this would fit in a real-life scenario.

Currently, there is an open PR on implementing [GDB server](https://github.com/firecracker-microvm/firecracker/pull/2333) in Firecracker, which allows you to step instruction by instruction.

**Comment by LegNeato** [comment]
Ah, gdb server is what I need! Thank you for the quick response.
