### ISSUE TITLE
Can't PATCH the balloon device

### ISSUE THREAD

**Issue by RoyceDavison** [firecracker-microvm/firecracker#2490]
Hi, I have a problem with the PATCH balloon operation. I can successfully create a balloon device and get balloon statistics. But it failed to update my balloon device. The error is `{"fault_message":"Device is inactive, check balloon driver is enabled."}`. The following `updateBalloon.sh` is used to update the balloon device:

```
#!/bin/bash
socket_location=/temp/firecracker.socket
amount_mb=10
curl --unix-socket $socket_location -i \
    -X PATCH 'http://localhost/balloon' \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -d "{
        \"amount_mb\": $amount_mb \
    }"`
```

I use firecracker v0.24.1 & v0.24.2 following [this balloon device doc](https://github.com/firecracker-microvm/firecracker/blob/master/docs/ballooning.md). My setup is the same as the [quick start guide](https://github.com/firecracker-microvm/firecracker/blob/780b5e38da359b3540baffa53e9bfdb4db8f319e/docs/getting-started.md) except I use different version of firecracker. Get kernel & rootfs by running the script from the [quick start guide](https://github.com/firecracker-microvm/firecracker/blob/780b5e38da359b3540baffa53e9bfdb4db8f319e/docs/getting-started.md) without change anything. 

Do I miss something to have it work properly?

Thanks, 
Royce

**Comment by RoyceDavison** [comment]
> Hi @RoyceDavison,
> 
> The error you encountered means that Firecracker cannot detect any driver in the guest for the balloon device. This is most likely because you have not configured the balloon driver in the guest kernel. You can do so by adding the following lines to your kernel config:
> `CONFIG_MEMORY_BALLOON=y`
> `CONFIG_VIRTIO_BALLOON=y`

Do you mean add these two lines to my local kernel config or add into guest kernel config? Isn't the vmlinux I am using from quick start guide already had these configs?

> The other situation in which you get this error is when you try to use the balloon before the driver was initialized in the guest. Are you patching the balloon immediately after starting the VM?

Nope. I create the balloon first and then use patch.

**Comment by RoyceDavison** [comment]
I think you are right I miss the above configs. I compile a new guest kernel w/ [this config](https://github.com/firecracker-microvm/firecracker/blob/780b5e38da359b3540baffa53e9bfdb4db8f319e/resources/microvm-kernel-arm64.config). Using this guest kernel, the PATCH operation works fine.

**Comment by georgepisaltu** [comment]
@RoyceDavison I'm glad it worked with that config!

We have logged an issue to update the links to kernel images in the quick start guide, linked [here](https://github.com/firecracker-microvm/firecracker/issues/2495).

**Comment by gregorybrzeski** [comment]
@georgepisaltu maybe wording for this error message can be improved as suggested in #2496 in order to make it clearer, leaving no room for confusion or doubt.
