### ISSUE TITLE
[ACPI] Add support for ACPI Power Management

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#2493]
# Feature Request

This is a feature tracking issue for the work to enable power management support for Firecracker microVMs through ACPI.

## Describe the desired solution

Implement virtual power management via ACPI which will result in the usual power related commands (reboot, halt, shutdown) not needing a dedicated device (i.e i8042 on x86_64).

## Describe possible alternatives

No other alternatives are taken into account.

## Checks

- [ ] Have you searched the Firecracker Issues database for similar requests?
- [ ] Have you read all the existing relevant Firecracker documentation?
- [ ] Have you read and understood Firecracker's core tenets?

**Comment by sudanl0** [comment]
We will track this as part of internal activity so closing this for now.
