### ISSUE TITLE
[Bug] Kernel download link doesn't match in quickstart

### ISSUE THREAD

**Issue by RoyceDavison** [firecracker-microvm/firecracker#2513]
# Describe the bug
I tried to use the memory balloon following, but the kernel downloaded from [QuickStartGuide](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) does not support memory balloon driver. This kernel was downloaded by using a second shell to run the script under "get the kernel and rootfs, if you don't have any available:..." 

This pr #2500 is related to update the kernel links. However, it doesn't update the shell script to get the kernel and rootfs, specially 

`image_bucket_url="https://s3.amazonaws.com/spec.ccfc.min/img"
`
`if [ ${arch} = "x86_64" ]; then
    kernel="${image_bucket_url}/hello/kernel/hello-vmlinux.bin"`
 
To match the pr #2500, the link should be `https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin`

aarch64 arch needs to be updated as well.

## Expected behaviour
The compiled kernel should support memory balloon driver. 

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by serban300** [comment]
Thanks for pointing this out ! I published PR #2514 for fixing this issue.

**Comment by serban300** [comment]
Fixed by #2514 . Closing the issue.
