### ISSUE TITLE
Use a dedicated performance tool to measure start-up latency in the CI

### ISSUE THREAD

**Issue by luminitavoicu** [firecracker-microvm/firecracker#2516]
The `--start_time_us` and `--start-time-cpu-us` flags are only used internally by our CI, in order to detect start-up latency regression. Firecracker is currently responsible of measuring the startup performance by itself, however this logic becomes hard to maintain as we face additional use cases (as it was the case with [this PR](https://github.com/firecracker-microvm/firecracker/pull/2488)).

We should deprecate these parameters and consider using `perf` (or another similar tool) to analyze performance evolution in our CI.

**Comment by alindima** [comment]
Could we instead just increment the startup time metric with the absolute time, instead of the delta?
This way, people who are interested in measuring the delta should just do the subtraction

**Comment by acatangiu** [comment]
> Could we instead just increment the startup time metric with the absolute time, instead of the delta?

I'm not sure how that would work for `cpu time`; even if'd work we'd end up with a split implementation with fc exporting some timestamps that could just as easily be taken by the caller/measuring application.

I'm `+1` on the issue proposal to remove these pseudo-measuring-tools from firecracker.

Anyway, we should do a call-out to Firecracker users to see if the exported metric that we use in CI is also used or useful for them in production before moving forward with removing it.

**Comment by alindima** [comment]
I don't see that would be the problem for `cpu time`, but I agree that it would be cleaner to just use another external measuring tool.

I think a next step would be to have an RFC PR that modifies the startup time performance test to use this external tool, so that we can discuss further

**Comment by sudanl0** [comment]
Initial reason why the issue was created is no longer valid. We have customers using this flag so we cannot remove them right away so closing the issue.
BTW, we are updating documentation on how to use these flags and as part of that internal activity we can re-evaluate what is a better approach for this.
