### ISSUE TITLE
snapshot resume / base image update clarification

### ISSUE THREAD

**Issue by jgraettinger** [firecracker-microvm/firecracker#2525]
_Aside: the slack workspace invite link from the repo README is expired_.

I've been playing with incremental snapshots. Very cool!
Suppose the following:

1) Resume a VM from a snapshot with `memory_file_base`
2) Take a new `Diff` snapshot that writes into `memory_file_diff` (with an enclosing in a `Pause` / `Resume`)
3) Reducing `memory_file_diff` into `memory_file_base` using:

```console
$ dd bs=4096 if=memory_file_diff of=memory_file_base conv=sparse,notrunc
```

**Question**: is this safe?

The snapshot docs make a general prohibition of mutating `memory_file_base` while the VM runs:
 > The memory file pointed by mem_file_path must be considered immutable from Firecracker and host point of view. It backs the guest OS memory for read access through the page cache. External modification to this file corrupts the guest memory and leads to undefined behavior.

The important constraint of my question is that the reduction uses seeks to only write portions of `memory_file_base` which are explicitly include as allocated blocks of `memory_file_diff` (e.g. using `lseek` with `SEEK_DATA` / `SEEK_HOLE`).

I _believe_ this is okay because the VM references `memory_file_base` using a COW mechanism, and portions of `memory_file_base` which are over-written by the reduction are also known to already be shadowed due to COW. But it would be nice to know for sure :)

**Comment by acatangiu** [comment]
> I believe this is okay because the VM references memory_file_base using a COW mechanism, and portions of memory_file_base which are over-written by the reduction are also known to already be shadowed due to COW. But it would be nice to know for sure :)

Yes, that sounds right. However, we have never tested this and advise against it unless you absolutely really have to. Accidentally overwriting any byte not yet shadowed can lead to subtle, hard-to-detect errors.
