### ISSUE TITLE
Flush of the TLB buffer

### ISSUE THREAD

**Issue by chadbrewbaker** [firecracker-microvm/firecracker#2534]
# Describe the bug

See the Virginia paper, http://www.cs.virginia.edu/~av6ds/papers/isca2021a.pdf

Is this sufficient to flush the TLB buffer?
https://github.com/firecracker-microvm/firecracker/blob/a367796e66eeac42d9ce1294c0fbbca6191e9cf3/resources/microvm-kernel-x86_64.config#L148

`[Author TODO: A clear and concise description of what the bug is.]`

## To Reproduce

I found it unethical to attempt this on an AWS Lambda instance.

## Expected behaviour

I would expect Firecracker jobs to flush the TLB buffer, also TLB flushes within a job at least at the cgroup level.

Perhaps a feature request, but Firecracker/Lambda should provide a default network jailed worker cgroup that only has read/write access to whitelisted directories. PDF parsing etc will never be safe.

## Environment

x86 according to the paper.

## Additional context

The kernel has some existing TLA+ specs.
https://git.kernel.org/pub/scm/linux/kernel/git/cmarinas/kernel-tla.git

## Checks

- [ X] Have you searched the Firecracker Issues database for similar problems?
- [X ] Have you read the existing relevant Firecracker documentation?
- [ X] Are you certain the bug being reported is a Firecracker issue?

**Comment by sandreim** [comment]
Hi @chadbrewbaker ! Thanks for reporting this. We are looking into it and will post updates here in the next days.

**Comment by alindima** [comment]
AWS is not impacted by the concerns discussed in the University of Virginia’s “I See Dead μops: Leaking Secrets via Intel/AMD Micro-Op Caches” paper, as existing instance isolation techniques are sufficient to protect against the techniques described. 

​

For a detailed discussion of the paper, we recommend Jon Masters' recent blog post:

https://comparch.org/2021/05/01/i-see-dead-uops-thoughts-on-the-latest-spectre-paper-targeting-uop-caches/
