### ISSUE TITLE
How network performance can be tested between two firecrackers separately deployed in two servers ?

### ISSUE THREAD

**Issue by h2cw2l** [firecracker-microvm/firecracker#2545]
My test env is shown as figure below.
1、There two servers "Server 1" and "Server 2".
2、I deploy two firecrackers separately in  "Server 1" and "Server 2".
3、I want to test the network performance between the two firecrackers.

As far as I know，network of firecracker is based on NAT, so the ip of firecracker is not exposed to each other.
So, when I use iper3, "iperf3 -c 172.16.0.1 -p 5151 -t 6000",  which ip should follws "-c" ?

Any reply will be appreciated.
![image](https://user-images.githubusercontent.com/58133919/117450343-adfbeb00-af73-11eb-81bd-1e0888819a7b.png)

**Comment by gc-plp** [comment]
> So, when I use iper3, "iperf3 -c 172.16.0.1 -p 5151 -t 6000", which ip should follws "-c" ?

The address that `eth0` has on `Server 1` or `Server 2`, depending on which Firecracker instance you're running the iperf client from.

**Comment by h2cw2l** [comment]
> 
> 
> > So, when I use iper3, "iperf3 -c 172.16.0.1 -p 5151 -t 6000", which ip should follws "-c" ?
> 
> The address that `eth0` has on `Server 1` or `Server 2`, depending on which Firecracker instance you're running the iperf client from.

Thank you very much.

**Comment by gc-plp** [comment]
> Is there any other configuration should be applied to the iperf3's server ?
> I think the port of iperf3's cilient can not be the same with server's, because it is translated between firecracker and its host ?

You should make sure that you set up port forwarding before running the test.

**Comment by h2cw2l** [comment]
> 
> 
> > Is there any other configuration should be applied to the iperf3's server ?
> > I think the port of iperf3's cilient can not be the same with server's, because it is translated between firecracker and its host ?
> 
> You should make sure that you set up port forwarding before running the test.

Yes, I have set ip_forward and my config refernces [network-setup.md](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md).

After I add a nat rule，the test is passed.
iptables -t nat -A PREROUTING -i eth0 -d 10.194.139.67 -p tcp --dport 6161 -j DNAT --to 172.16.0.2:6161

**Comment by gc-plp** [comment]
> After I add a nat rule，the test is passed.

Sounds good. Can we close this issue?
