### ISSUE TITLE
When I set block cache_type to Writeback, there is error tell me it is not supportted ?

### ISSUE THREAD

**Issue by h2cw2l** [firecracker-microvm/firecracker#2559]
Hello,

Problem like figure below, how can I set cache type to Writeback ?
Any reply willl be appreciated.
![图片](https://user-images.githubusercontent.com/58133919/118070676-ee76c100-b3d8-11eb-831a-4b4a7aba4b35.png)

**Comment by gc-plp** [comment]
Hi @h2cw2l. 

You are probably using an older Firecracker version that does not handle the `cache_type` parameter.

The `cache_type` parameter was added in [this PR](https://github.com/firecracker-microvm/firecracker/pull/2447) and we have not done any releases that include it, but the upcoming `v0.25` release will include this change.

To obtain a binary that handles the `cache_type` parameter, you can build from the latest `main` revision.
