### ISSUE TITLE
How can I run firecracker on the back end so that there is no need for each microVM to occupies a terminal ?

### ISSUE THREAD

**Issue by h2cw2l** [firecracker-microvm/firecracker#2561]
Hello,

Now, I only know to start microVM by cmd below, but it need occupies a terminal, how can it releases the terminal.

./firecracker --api-sock /tmp/firecracker.socket

**Comment by acatangiu** [comment]
For simple scenario I recommend using a terminal multiplexer such as `tmux` or `screen`.

**Comment by acatangiu** [comment]
For production scenarios, you should use the jailer [1] binary with `--daemonize` option.

[1] https://github.com/firecracker-microvm/firecracker/blob/main/docs/jailer.md

**Comment by alindima** [comment]
I think we can close this issue. @h2cw2l feel free to reopen if you need to
