### ISSUE TITLE
Test Firecracker with Different Host and Guest AMIs

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#257]
We currently test Firecracker only on one host kernel. We need to add more configurations to our CI, including:

Host:
- [x] Latest AL2.
- [ ] TBD

Guest:
- [ ] Customer images.
- [ ] Security testing image.

Why do we need this?
To catch bugs like #253 as early as possible.

**Comment by dianpopa** [comment]
We now have a kernel policy in place that enumerates the currently supported host and guest kernel versions: https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md.
