### ISSUE TITLE
[Bug] Seccomp failure are not logged in logs or metrics in fc versions > 0.24

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#2587]
Any seccomp violation results in the termination of the Firecracker process without any logging done regarding the termination reason.

`seccomp::num_faults` metric is not increased either.

This results in no visibility and no post-incident debug-ability for seccomp violations.

This does not affect Firecracker versions `v0.24.x` and lower/older.

**Comment by acatangiu** [comment]
The root-cause has been identified as being the lack of full support for `SIGSYS` in `signalfd` kernel implementation.

This is fixed in newer kernels: https://patchwork.ozlabs.org/project/linux-um/patch/20180428140702.3925-2-ebiederm@xmission.com/
But 4.14 for example doesn't have the fix: https://elixir.bootlin.com/linux/v4.14/source/fs/signalfd.c#L100

Looks like we need to use a synchronous signal handler for `SIGSYS`. We can keep the async signalfd implementation for the other signals.

**Comment by alindima** [comment]
Fixed by #2593
