### ISSUE TITLE
rate limiting: handle or disallow scenarios where max virtio req size > token bucket size

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#259]
Rate limiting currently works by allowing or temporarily blocking virtio virtqueue requests based on the request size and the ratelimiter token bucket remaining budget.
We can easily reproduce scenarios where a virtio request can exceed the token bucket size, in such scenarios traffic is forever blocked since there will never be enough budget to serve that request.

Solutions:
1. Augment the design and implementation to be able to do partial processing of virtio requests. This means we need to do extra internal accounting of queue processing.
2. Enforce limits and validations in rate limiter configurations to disallow such scenarios.

**Comment by Lay-ton** [comment]
Hi, @acatangiu I am a student in UT Austin's virtualization class. We are a group of 3 and were wondering if this was still an open issue. If so could we get a little more information on what needs to be done?

**Comment by acatangiu** [comment]
Hi @Lay-ton while this is a valid issue that can be triggered under certain rate-limiter configurations, we've had no complaints from Firecracker customers/users, so this is a low priority issue.

The rate-limiter is implemented on a steady-rate-refilling-token-bucket design, where each request consumes tokens from the bucket if there are enough there or is delayed until there are enough.
The overall rate of consumption is smaller or equal to the constant rate at which the bucket is refilled.

In certain configurations where the `bandwidth` bucket size is configured to be smaller than the virtio request size, the rate-limiter _leaks_ by allowing a higher rate than configured. This happens because blocking a request until there are enough tokens in the bucket will block it forever since the bucket itself is smaller than the request size, so we just consume the whole bucket and allow that request, and that results that the actual rate is larger than the limit by `diff = request.size - bucket.size`.

There are multiple solutions to this problem with varying degrees of creativity and complexity.
1. Enhance the virtio-block/net/vsock implementations to allow partial processing of virtio requests. This implies some internal buffering in the device emulation of a virtio request that does not have enough budget in its rate-limiter to complete as a whole. [High complexity - multiple components involved]
2. Enhance the rate-limiter implementation, and when identifying this corner-case, instead of consuming everything in the bucket and letting it pass, calculate how many buckets would it take for the request to be properly rate-limited and block it for a proportionate amount of time instead of just blocking for the standard/static duration. [Low complexity - catch-all fix]
3. Propose another approach altogether for the rate-limiter implementation.
4. Etc.

The second option seems like a good idea, don't know if that satisfies the required level of complexity/work you were looking for.

**Comment by Spoonbender** [comment]
@georgepisaltu accidentally stumbled upon a TODO that still needs be removed: https://github.com/firecracker-microvm/firecracker/blob/89a131d8e359e7c00361c79a30a1d678c8d9278e/src/rate_limiter/src/lib.rs#L151
