### ISSUE TITLE
use GuestMemory::read_from() and GuestMemory::write_to() in Vsock

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#2592]
As part of https://github.com/firecracker-microvm/firecracker/pull/2574 we refactored vsock in order to use vm-memory methods instead of raw pointers. For performance reasons and limitations related to our vm-memory wrapper crate we used `GuestMemoryRegion::read_from()` and `GuestMemoryRegion::write_to()`

After dirty [bitmap tracking](https://github.com/rust-vmm/vm-memory/pull/125) is merged in `rust-vmm/vm-memory` we should be able to use GuestMemory::read_from() and GuestMemory::write_to() directly.

**Comment by alindima** [comment]
While the performance aspect is fixed by #2661 , this issue is blocked by: https://github.com/rust-vmm/vm-memory/issues/171

**Comment by roypat** [comment]
With #3653 this no longer applies
