### ISSUE TITLE
[Bug] Run the unit tests in debug mode as well

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#2594]
# Describe the bug

Currently the unit tests are only running in release mode. This is a bit unfortunate because in release mode things such as overflow & underflows are wrapping around, and bugs might go unnoticed, leading to undefined behaviors.

If we run the tests in both release & debug modes, we can catch the arithmetic operation failures in tests as these will cause panics when run in debug.

## To Reproduce

N/A

## Expected behaviour

Update the running of unit test to include the debug target.

## Environment

Main branch.

## Additional context

N/A

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by alindima** [comment]
We run the coverage test in debug mode. I remember I explicitly tested an with overflow, that panicked in the kcov test

**Comment by andreeaflorescu** [comment]
Didn't notice that :laughing: closing it.
