### ISSUE TITLE
[Bug] Sporadic CI failure in "test_failing_filter" test

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#2607]
# Describe the bug

Every once in a while CI integration tests fail with:

```
framework/report.py:244: in func_wrapper
    original_function(*args, **kwargs))
integration_tests/security/test_custom_seccomp.py:174: in test_failing_filter
    test_microvm.start(check=False)
framework/microvm.py:758: in start
    response = self.actions.put(action_type='InstanceStart')
framework/resources.py:28: in put
    json=datax
framework/decorators.py:25: in timed
    result = method(*args, **kwargs)
framework/http.py:72: in put
    return super().put(url, data=data, **kwargs)
/usr/local/lib/python3.6/dist-packages/requests/sessions.py:602: in put
    return self.request('PUT', url, data=data, **kwargs)
/usr/local/lib/python3.6/dist-packages/requests/sessions.py:542: in request
    resp = self.send(prep, **send_kwargs)
/usr/local/lib/python3.6/dist-packages/requests/sessions.py:655: in send
    r = adapter.send(request, **kwargs)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py:498: in send
    raise ConnectionError(err, request=request)
E   requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

## Expected behaviour

The test should work fine.

## Additional context / 1st level investigation

The test starts firecracker with `ioctl` syscall denied by seccomp. It then configures and boots a microvm expecting it to fail with a seccomp violation.

The problem stems because seccomp violation happens during a CI-initiated API call:
```
framework/microvm.py:758: in start
    response = self.actions.put(action_type='InstanceStart')
```

The firecracker process is killed by seccomp as intended, but sometimes the `python3.6/dist-packages/requests/sessions.py` implementation used to send the API call raises a `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))` exception while waiting for a response which by design will never come.

## Possible solutions

1. See if `requests/sessions.py` can be configured for this test only to ignore `ConnectionError(RemoteDisconnected)`
  or even better,
2. Change the test to trigger seccomp violation on some other operation than during an API call. A first idea would be to do a `ping` or send some network packet while denying some syscall used by the emulated net device.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by serban300** [comment]
Fixed by #2615
