### ISSUE TITLE
[Feature Request] Modify mem_size_mib at runtime

### ISSUE THREAD

**Issue by jeromegn** [firecracker-microvm/firecracker#2610]
# Feature Request

We'd like to change memory limits at runtime so we can resize microvms without restarting them.

KVM can already do this via `virsh setmem`

## Describe the desired solution

An API call to modify the memory limit on a microvm. This should also be reflected inside the VM if possible.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by gc-plp** [comment]
Hi @jeromegn. 

For resizing the microVM memory, you can use the [ballooning](https://github.com/firecracker-microvm/firecracker/blob/main/docs/ballooning.md) feature.

According to the [virsh setmem](https://libvirt.org/manpages/virsh.html#setmem) documentation, when using the `--live` parameter, a balloon operation is done, which is basically the same as what I've linked above. 

> KVM can already do this via virsh setmem

Assuming here that you're referring to what qemu can do, it's worth noting that both Firecracker and qemu use KVM for launching VMs.

**Comment by jeromegn** [comment]
I thought ballooning was only to reclaim memory on the host? Reading the docs, it's not _entirely_ clear it can be used to **add** memory to a microvm. I suppose if I set the target higher than the initially set memory?

**Comment by gc-plp** [comment]
> I suppose if I set the target higher than the initially set memory?

That's correct.

The strategy of working with a dynamic memory model is to start a microVM with the maximum amount of memory that you would need and then inflate the balloon to reclaim some of the space. Once you need to add more memory to the microVM, you deflate the balloon.

**Comment by georgepisaltu** [comment]
Hi @jeromegn,

You're right, the balloon can't be used to add memory to a running microVM. But what you can do is start a microVM with more memory than what you want to use at first and configure the balloon device to eat the excess memory. Then you can deflate the balloon to access the extra memory when you need it. You will still be unable to add more memory than you started with (in case you realize down the line that you need even more memory than the excess you provisioned at boot) but by virtue of demand-paging memory, you will not actually use the excess until you need it.

This is not _really_ memory hotplug, but looks, works and feels like memory hotplug :smile: . Let us know if this workaround is suited to your use case.

**Comment by dianpopa** [comment]
> Hi @jeromegn,
> 
> You're right, the balloon can't be used to add memory to a running microVM. But what you can do is start a microVM with more memory than what you want to use at first and configure the balloon device to eat the excess memory. Then you can deflate the balloon to access the extra memory when you need it. You will still be unable to add more memory than you started with (in case you realize down the line that you need even more memory than the excess you provisioned at boot) but by virtue of demand-paging memory, you will not actually use the excess until you need it.
> 
> This is not _really_ memory hotplug, but looks, works and feels like memory hotplug 😄 . Let us know if this workaround is suited to your use case.

@jeromegn does the suggestion mentioned above help with your use case? Do you need additional guidance here?

**Comment by jeromegn** [comment]
> @jeromegn does the suggestion mentioned above help with your use case? Do you need additional guidance here?

We haven't played with this too much yet. We're currently working on other stuff and should check it out again soon! I think the response was enlightening though 😄

**Comment by luminitavoicu** [comment]
Closing this issue for now. Feel free to reopen when necessary.
