### ISSUE TITLE
Use resolver = 2 in Cargo.toml

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#2611]
We recently discovered that dev dependency features leak into release builds. This can be fixed by specifying `resolver = 2` in the Cargo.toml configuration, which is made available with the Rust 1.51 release as far as I understand. Since Firecracker switched to the newer Rust version, it might make sense to enable the non-default resolver as this might help in eliminate some programming errors.

More details about this here: https://github.com/rust-vmm/rust-vmm-container/issues/50

**Comment by roypat** [comment]
With rust edition 2021 (with which all releases starting from 1.1 are built), `resolver = 2` is the default: https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
