### ISSUE TITLE
Add negative test for TSC snapshot restore on different CPU models

### ISSUE THREAD

**Issue by georgepisaltu** [firecracker-microvm/firecracker#2624]
We need to add a test for restoring a snapshot with TSC on a different CPU model than the one on which the snapshot was taken. For more details about this, see PR #2596  and [this comment](https://github.com/firecracker-microvm/firecracker/pull/2596#discussion_r650848310).

**Comment by sudanl0** [comment]
This will be covered as part of https://github.com/firecracker-microvm/firecracker/issues/2985
