### ISSUE TITLE
[Feature Request] Make a way to silence "Failed to register serial input fd" log message

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker#2651]
# Feature Request

Firecracker's main branch currently always logs the following error when I use from Firecracker Go SDK.

```
Failed to register serial input fd: event_manager: failed to manage epoll file descriptor: Operation not permitted (os error 1)
```

Before using `rust-vmm/event_manager`, Firecracker was logging the following warning.

```
Could not add serial input event to epoll: Error during epoll call: Operation not permitted (os error 1)
```

I think (not fully confirmed), Firecracker is calling epoll_ctl(2) against the process' stdin, but it doesn't support polling, that results EPERM.

## Describe the desired solution

Not really sure. It is possible to gracefully handle the situation?

## Describe possible alternatives

Alternatively we could make the log message from an error to a warning, but it would be great if we can get rid of the log message entirely regardless of the logging level.

## Additional context

It is not blocking anything on our end.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by georgepisaltu** [comment]
The log level change might have happened when we switched to the rust vmm event manager, we need to look into this further and see if what can we do about it.

**Comment by berciuliviu** [comment]
After a discussion with Kazu and some investigation done on why this happens, this is what I found out:
- the error comes from rust-vmm/event_manager
- the error appears when the serial input is not available. The function `serial_input_fd()` from `devices/legacy/serial.rs` file returns -1 if the FD is not available, or the FD if it is. We do not check the result of the function before passing it to `ops.add()` in the event_manager. Hence, if we pass -1, the exactly above error will be shown.

In this case, a solution would be to check for the function's result before trying to register the FD with the event_manager. Any other error that should arise from a valid FD should be reported.

**Comment by acatangiu** [comment]
> In this case, a solution would be to check for the function's result in Firecracker before trying to register the FD with the event_manager. Any other error that should arise from a valid FD should be reported.

Sounds good!
