### ISSUE TITLE
works on Jetson Nano

### ISSUE THREAD

**Issue by lucaszanella** [firecracker-microvm/firecracker#2664]
Hello, I'd like to just confirm that this works on the Nvidia Jetson Nano. The Nano does not come with KVM so I made a tutorial on how to recompile the kernel/device trees with proper support for KVM/irqchip: https://github.com/lucaszanella/jetson_nano_kvm

I then followed https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md but with `make Image` instead of `make vmlinux` and this amazing script (modified from https://jvns.ca/blog/2021/01/23/firecracker--start-a-vm-in-less-than-a-second/) to launch:

```
set -eux

TAP_DEV="fc-88-tap0"

# set up the kernel boot args
MASK_LONG="255.255.255.252"
MASK_SHORT="/30"
FC_IP="169.254.0.21"
TAP_IP="169.254.0.22"
FC_MAC="02:FC:00:00:00:05"

KERNEL_BOOT_ARGS="ro console=ttyS0 noapic reboot=k panic=1 pci=off nomodules random.trust_cpu=on"
KERNEL_BOOT_ARGS="${KERNEL_BOOT_ARGS} ip=${FC_IP}::${TAP_IP}:${MASK_LONG}::eth0:off"

# set up a tap network interface for the Firecracker VM to user
ip link del "$TAP_DEV" 2> /dev/null || true
ip tuntap add dev "$TAP_DEV" mode tap
sysctl -w net.ipv4.conf.${TAP_DEV}.proxy_arp=1 > /dev/null
sysctl -w net.ipv6.conf.${TAP_DEV}.disable_ipv6=1 > /dev/null
ip addr add "${TAP_IP}${MASK_SHORT}" dev "$TAP_DEV"
ip link set dev "$TAP_DEV" up

VMLINUX_BIN=~/Image
ROOTFS=~/rootfs.ext4

# make a configuration file
cat <<EOF > vmconfig.json
{
  "boot-source": {
    "kernel_image_path": "$VMLINUX_BIN",
    "boot_args": "$KERNEL_BOOT_ARGS"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "$ROOTFS",
      "is_root_device": true,
      "is_read_only": false
    }
  ],
  "network-interfaces": [
      {
          "iface_id": "eth0",
          "guest_mac": "$FC_MAC",
          "host_dev_name": "$TAP_DEV"
      }
  ],
  "machine-config": {
    "vcpu_count": 2,
    "mem_size_mib": 1024,
    "ht_enabled": false
  }
}
EOF
# start firecracker
./firecracker --no-api --config-file vmconfig.json
```

I compiled both firecracker and alpine kernel and jetson nano kernel with KVM on the jetson itself and everything worked fine. Hope it can help someone. 

ps: how do I log into the alpine lol? `root` and blank won't work, neither `root` and `alpine`. I'd like to test the internet connection.

**Comment by georgepisaltu** [comment]
Hi @lucaszanella ,

Glad you got this up and running! For the login part, when creating the rootfs, run `passwd` inside the container to change the password of `root`.

**Comment by sandreim** [comment]
Hey @lucaszanella, I hope you can now login with the rootfs password update as pointed out by @georgepisaltu . I'll close this ticket, please reopen if you need more help.
