### ISSUE TITLE
[Hardening] MMDSv2

### ISSUE THREAD

**Issue by luminitavoicu** [firecracker-microvm/firecracker#2675]
Introduce MMDS version 2, which allows session oriented requests to fetch MMDS meta-data, by providing a session token. This functionality replicates EC2’s [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) implementation.

**Comment by dianpopa** [comment]
MMDSv2 is GA starting with [release 1.1.0](https://github.com/firecracker-microvm/firecracker/releases/tag/v1.1.0).
