### ISSUE TITLE
[Bug] KVM_EXIT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by a74731248** [firecracker-microvm/firecracker#2710]
# Describe the bug

When I follow the [getting start](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md#running-firecracker) to run firecracker, I have got the error as follows, and I dont know how to deal with it.

```
[anonymous-instance:fc_vcpu 0:ERROR:src/vmm/src/vstate/vcpu/mod.rs:475] Received KVM_EXIT_INTERNAL_ERROR signal
```

and the result of `tools/devtool checkenv` command are as follows:
```
[Firecracker devtool] Checking prerequisites for running Firecracker.
[Firecracker devtool] Please check ../docs/getting-started.md#prerequisites in case of any error.
[Firecracker devtool] Checking Host Security Configuration.
[Firecracker devtool] Please check ../docs/prod-host-setup.md in case of any error.
[Firecracker devtool] WARNING: retpoline, IBPB, IBRS: DISABLED.
[Firecracker devtool] WARNING: VMX: cache flushes: DISABLED
```

and the version of firecracker I try inlcude both release-v0.24.6 and build from source, they are all end with the error above.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version]: release-v0.24.6 & build from source`
`[ - Host and guest kernel versions]: CentOS Linux release 7.9.2009 (Core) & 5.13.12-1.el7.elrepo.x86_64`
`[ - Rootfs used.]:  hello-rootfs.ext4`
`[ - Architecture.]: x86`

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by dianpopa** [comment]
Hi @a74731248,

Did you manage to reinstall and try again? Does the error still replicate?

**Comment by a74731248** [comment]
> Hi @a74731248,
> 
> Did you manage to reinstall and try again? Does the error still replicate?

yes,I have reinstall my system, and the error disappear.

**Comment by dianpopa** [comment]
Issue got solved by reinstalling host system, not related to Firecracker.
