### ISSUE TITLE
[Bug] Socket doesn't show tty upon InstanceStart.

### ISSUE THREAD

**Issue by joshxyzhimself** [firecracker-microvm/firecracker#2729]
# Describe the bug

I am trying to follow the Getting Started guide at https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md.

On shell 1, the socket doesn't show tty upon InstanceStart at shell 2 even when I'm getting 204's.

## To Reproduce

- Run https://github.com/joshxyzhimself/fc/blob/main/fc_install.sh
  - KVM support check
  - Install docker
  - Set KVM read-write access
  - Install firecracker (download, extract, set permissions)
  - Download kernel
  - Download rootfs
- At shell 1, run https://github.com/joshxyzhimself/fc/blob/main/fc_socket.sh
  - rm -f /tmp/firecracker.socket
  - ./firecracker --api-sock /tmp/firecracker.socket
- At shell 2, run https://github.com/joshxyzhimself/fc/blob/main/fc_guest_api.sh
  - Set guest kernel
  - Set guest rootfs
  - Start machine

At shell 2, all returns 204, but shell 1 shows no output.

When I try to re-run the fc_guest_api.sh, it says that the VM has already started.

## Expected behaviour

I'm expecting it to have tty output on shell 1.

I have ran the same scripts on a DigitalOcean VM Ubuntu 21.04 and they work. I am lost on why it doesn't work on my desktop.

At FAQ.md I've also tried the suggested boot args, but I'm still getting no output.

![image](https://user-images.githubusercontent.com/60829711/136517944-3feebd6b-1060-408f-a8de-a2258bae5d1f.png)

(From https://github.com/firecracker-microvm/firecracker/blob/main/FAQ.md)

## Environment

- Firecracker v0.24.6
- Host: Ubuntu 21.04 Desktop, 5.11.0-16-generic
- Guest 
  - https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin
  - https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/rootfs/bionic.rootfs.ext4

```
root@device:~/fc# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```

```
root@device:~/fc# uname -r
5.11.0-16-generic
```

```
root@device:~/fc# kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

```
root@device:~/fc# ./firecracker --version
Firecracker v0.24.6

Supported snapshot data format versions: v0.23.0, v0.24.0
```

```
root@device:~/fc# lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      21
Model:                           19
Model name:                      AMD A8-6600K APU with Radeon(tm) HD Graphics
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         3323.754
CPU max MHz:                     3900.0000
CPU min MHz:                     1900.0000
BogoMIPS:                        7780.95
Virtualization:                  AMD-V
L1d cache:                       32 KiB
L1i cache:                       128 KiB
L2 cache:                        4 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush m
                                 mx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep
                                 _good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 f
                                 ma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr
                                 8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce
                                  nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd vmmcall bmi1 a
                                 rat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pa
                                 usefilter pfthreshold
```

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by georgepisaltu** [comment]
Hi @joshxyzhimself,

Sorry for the delayed response. I think in the Ubuntu desktop case the console has a different name (not `ttyS0`). I would suggest setting up the network inside the VM and connecting through SSH to see exactly what devices are available inside the guest. You can follow [this guide](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md) to setup your network. Let me know if you found anything!
