### ISSUE TITLE
[Question] Firecracker minimum RAM requirement

### ISSUE THREAD

**Issue by zamazan4ik** [firecracker-microvm/firecracker#2737]
Hi!

I am trying to find any explanations, why 128 Mib of RAM was chosen as a minimal requirement for the VM? Why we cannot allocate a VM with e.g. 64 Mib of RAM?

I've tried to find any details about this design decision but without any success.

Thanks in advance!

P.S. Sorry for duplication but "Discussions" section looks like not very active.

**Comment by georgepisaltu** [comment]
Hi @ZaMaZaN4iK 

I don't think it's a minimal requirement for VM memory in the sense that it's not enforced. I just confirmed this by booting up a VM with 64 MiB of RAM, then 48 and it still works. As long as your setup allows it, both host and guest configurations, you can go lower than 128 MiB of RAM.

I'd like to point out that Firecracker is oversubscribing memory by default using demand paging. This means that even if you start a 2 GiB VM, the actual memory used by the process will be much lower (probably around 150 MiB) until you "touch" that memory and is gets physically allocated on the host. I understand this does not address the need to put an upper limit to how much memory the guest is allowed to use, but it's worth mentioning.

Could you please let us know where in the documentation and/or API did you find 128 MiB to be a minimal requirement for Firecracker? We would like to take a look at that and possibly rephrase it or actually enforce the limit if we find a compelling argument.

**Comment by ZaMaZaN4iK** [comment]
>The 128 mentioned in both of those linked docs are duplicates and neither says (or even implies) that 128 is a limit. It's just a specific use case that is mentioned.

I understand it. But some people interpret these values as a minimum requirement. That's why I am asking to note somewhere in the documentation explicitly that 128 Mib is not a minimum requirement. It just improves a little bit current documentation :)

> As far as why Lambda sets a minimum of 128, does it matter? I'm assuming they looked at metrics of millions of invocations of some internal tool and came up with that number. Even if anyone related to this project knew the answer to the question, they probably couldn't talk about it.

I am asking because maybe people know it and share their knowledge with the public community. If no - okay, that's fine.
