### ISSUE TITLE
[Feature Request] Improve Invalid JSON Error Message

### ISSUE THREAD

**Issue by zicklag** [firecracker-microvm/firecracker#2765]
# Feature Request

Currently, when there are any issue parsing the JSON config file for firecracker, we get an error message that doesn't describe what is wrong with the JSON file, only that it is invalid.

```bash
➜ firecracker --no-api --config-file config.json
2021-10-29T15:14:13.216004769 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:321] Configuration for VMM from one single json failed: InvalidJson
```

Serde already provides us file location and key information about what the problem is while parsing the JSON, and we should display that to the user so they know what to fix in the config file.

## Describe the desired solution

The error message should describe what part of the JSON file is incorrect, and why.

## Describe possible alternatives

I haven't thought of any alternatives.

My workaround was literally to compile firecracker myself and use the long debug print ( `{:#?}` ) instead of the short debug print ( `{:?}` ) on the error message. :stuck_out_tongue_winking_eye: 

## Additional context

Pull request coming up!

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by alindima** [comment]
Hello, this issue was actually fixed by this PR: https://github.com/firecracker-microvm/firecracker/pull/2649.
It's just that it wasn't yet released, so you probably was running with a release build of Firecracker.

The current output on latest main is:
`Configuration for VMM from one single json failed: InvalidJson(Error("missing field drives", line: 22, column: 1))`, so I'll close this issue.

**Comment by zicklag** [comment]
Oh, cool, I must not have tried the latest master before testing my own changes to it! Anyway, thanks!. :)
