### ISSUE TITLE
[Feature Request] Please remove the implied "roadmap" to remove the ability ro run Firecracker without jailer

### ISSUE THREAD

**Issue by fadams** [firecracker-microvm/firecracker#2785]
# Feature Request
Please remove the implied "roadmap" to remove the ability to run Firecracker without jailer.

In the design docs: https://github.com/firecracker-microvm/firecracker/blob/main/docs/design.md and possibly elsewhere there is a comment:
```
Firecracker should be started only via the jailer binary. The firecracker binary can also be executed directly, but this will no longer be possible in the future.
```
Although starting Firecracker from jailer might be a good approach in some circumstances, there are legitimate use cases where this might not be ideal or even be sub-optimal.

In my situation I am launching firecracker in a (Docker) container and by doing that there is a similar level of additional containment to that provided by jailer - e.g. it is running in isolated mount, pid, network, etc. namespaces, and the cgroups (cpu/memory etc.) that I specify when starting the container will resource limit the firecracker executable in a similar way to when using jailer.

Whilst it is possible to run jailer from the Docker container a) It is not clear that it is actually providing any meaningful additional security benefits in that situation b) in order to run jailer in a container one has to actively *reduce* the container's security by providing elevated privileges. To run jailer the container needs to be run with CAP_SYS_ADMIN, CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_MKNOD, CAP_SETGID, CAP_SETUID, CAP_SYS_CHROOT and to run jailer as a non-root user in the container I need to run:
```
setcap cap_chown,cap_dac_override,cap_mknod,cap_setgid,cap_setuid,cap_sys_admin,cap_sys_chroot=eip jailer
```
Moreover I need a custom seccomp profile to add pivot_root to the seccomp allow list (CAP_SYS_ADMIN ungates unshare, but that capability is way more privileged than I'd like) also a custom apparmor profile is required.

I'm aware that jailer will drop these capabilities when it starts firecracker, but in general I'd prefer to not allow then in the first place, especially given the marginal, if any, additional benefits that jailer gives in addition to the container isolation.

## Describe the desired solution
Please consider removing the statement (and thus implied roadmap) that at some point it might not be possible to run Firecracker without jailer - the current position offers the flexibility to choose to use jailer or to take another approach and whilst it is totally sensible to provide guidance on how best to run Firecracker in production it is unhelpful to have an implicit roadmap to remove that option as I believe that running without jailer is a legitimate use case.  

## Describe possible alternatives
If it became mandatory to use jailer it would be possible, but at the cost of launching a container with far more privileges than I'd like.

## Additional context
N/A

**Comment by raduweiss** [comment]
@fadams apologies for the late reply here. This makes sense, thank you very much for the detailed explanation.

In the end the right message there is something like "Firecracker is designed with two layers of isolation: the Linux KVM + Firecracker virtualization boundary, and the container-like Linux layer (isolated mount, pid, network, etc. namespaces, cgroups, seccomp, etc.); the latter can be readily provided by the jailer binary that's part of each Firecracker release, or by equivalent technology deployed by Firecracker users. In production, Firecracker should not be run without this second layer of isolation."

We'll workout some clear wording here and update the docs.

**Comment by fadams** [comment]
Thanks for the reply @raduweiss that would be great, I really appreciate it.
I think the wording above around the intent looks good.
