### ISSUE TITLE
[Bug] Properties in cgroup2 with length > 2

### ISSUE THREAD

**Issue by XieGuochao** [firecracker-microvm/firecracker#2800]
# Describe the bug

In `cgroup version 2`, cgroup attribute files may have lengths greater than 2. For example, `hugetlb.1GB.max` and `memory.swap.max` are two attributes that should be able to set with `Jailer` process. However, the current `jailer` implementation assumes the length of cgroup attribute to be 2.

For the full documentation of cgroup2: [Control Group v2 - The Linux Kernel Documentation](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html).

## To Reproduce

```
jailer ... \
       --cgroup-version 2 \
       --cgroup memory.swap.max 10G
```

## Expected behaviour

It should not fail.

## Solution

The cause of the source code is in `firecracker/src/jailer/src/cgroup.rs`:

```
// Extract the controller name from the cgroup file. The cgroup file must follow
// this format: <cgroup_controller>.<cgroup_property>.
fn get_controller_from_filename(file: &str) -> Result<&str> {
    let v: Vec<&str> = file.split('.').collect();

    // Check format <cgroup_controller>.<cgroup_property>
    if v.len() != 2 {
        return Err(Error::CgroupInvalidFile(file.to_string()));
    }

    Ok(v[0])
}
```

We should change `if v.len() != 2` to `if v.len() < 2` to solve this issue.

**Comment by luminitavoicu** [comment]
Hi @XieGuochao, thanks for opening this issue. We will take a look and circle back to you.
