### ISSUE TITLE
[Bug] Fail to compile with docker in restricted environment

### ISSUE THREAD

**Issue by nmanthey** [firecracker-microvm/firecracker#2803]
# Describe the bug

Firecracker build instructions from the README or documentation fail to succeed on certain docker setups.

## To Reproduce

I tried to build Firecracker on my Ubuntu machine, and got the following output (likely due to the docker container not being able to access network):

```
firecracker$ tools/devtool build
[Firecracker devtool] Starting build (debug, musl) ...
    Updating git repository `https://github.com/firecracker-microvm/kvm-bindings`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `kvm-bindings`

Caused by:
  Unable to update https://github.com/firecracker-microvm/kvm-bindings?tag=v0.5.0-1#4569d3f5

Caused by:
  failed to fetch into: /usr/local/rust/git/db/kvm-bindings-6ea931839e214d47

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/firecracker-microvm/kvm-bindings' 'refs/tags/v0.5.0-1:refs/remotes/origin/tags/v0.5.0-1'` (exit code: 128)
  --- stderr
  fatal: unable to access 'https://github.com/firecracker-microvm/kvm-bindings/': Could not resolve host: github.com
  ```

## Expected behaviour

A successful build, using a container with network access.

## Environment

Ubuntu 18.04 with docker, `Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3`

## Additional context

Using the hosts network for docker containers allows to successfully build Firecracker. The following patch should be the solution, but might not work in environments I am not aware of:

```
diff --git a/tools/devtool b/tools/devtool
index 22c24039..f252f5b7 100755
--- a/tools/devtool
+++ b/tools/devtool
@@ -597,6 +597,7 @@ run_devctr() {
     docker run "${docker_args[@]}" \
         --rm \
         --volume /dev:/dev \
+        --network host \
         --volume "$FC_ROOT_DIR:$CTR_FC_ROOT_DIR:z" \
         --env OPT_LOCAL_IMAGES_PATH="$(dirname "$CTR_MICROVM_IMAGES_DIR")" \
         --env PYTHONDONTWRITEBYTECODE=1 \
@@ -2067,7 +2068,7 @@ cmd_build_rootfs() {
     img_file="$rootfs_dir_host/$ROOTFS_NAME"
     dd if=/dev/zero "of=$img_file" bs=1M count=$SIZE
     mkfs.ext4 -F "$img_file"
-    docker run --env ROOTFS_NAME=$ROOTFS_NAME --env PARTUUID=$PARTUUID --privileged --rm -i -v "$FC_ROOT_DIR:/firecracker"  "$FROM_CTR" bash -s <<'EOF'
+    docker run --env ROOTFS_NAME=$ROOTFS_NAME --env PARTUUID=$PARTUUID --network host --privileged --rm -i -v "$FC_ROOT_DIR:/firecracker"  "$FROM_CTR" bash -s <<'EOF'
 rootfs_dir=/firecracker/build/rootfs
 img_file="$rootfs_dir/$ROOTFS_NAME"
 resource_dir="/firecracker/resources/tests"
```

## Checks

- [ ] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by avr1** [comment]
I tried building firecracker for the first time, using ubuntu 20.04 with `docker version 20.10.8`, and I ran into the same problem as above. Making those changes seemed to fix it for me as well. What environments do you think might run into problems with this change? I can try creating a VM for them and building on those platforms as a first issue.

**Comment by dianpopa** [comment]
Hi,

Based on the error message, seems that the docker container has some DNS issues. So, what I would propose here is to firstly check whether it might be something of this kind. Can you please try opening (or creating) `/etc/docker/daemon.json` and putting the following DNS server in it:
```
{
    "dns": ["8.8.8.8"]
}
```
After this, restart you docker service and retry `tools/devtool build`.
Let me know how that works.

**Comment by avr1** [comment]
Interesting, I tried to replicate the issue on another VM with the same setup, and didn't run into any problems. Could it be an issue with a VM setting, that might have changed between my setups?

**Comment by dianpopa** [comment]
Hi!

What do you mean by VM with the same setup. Building the project should not be related to how you setup the VM. Are you maybe referring to host setup?

**Comment by avr1** [comment]
That's correct, sorry about the confusion. When I created a new host VM to build Firecracker on, I didn't have the same issue.

**Comment by dianpopa** [comment]
> Hi,
> 
> Based on the error message, seems that the docker container has some DNS issues. So, what I would propose here is to firstly check whether it might be something of this kind. Can you please try opening (or creating) `/etc/docker/daemon.json` and putting the following DNS server in it:
> 
> ```
> {
>     "dns": ["8.8.8.8"]
> }
> ```
> 
> After this, restart you docker service and retry `tools/devtool build`. Let me know how that works.

@nmanthey can you please let me know if this solves your issue?

**Comment by dianpopa** [comment]
Closing due to no reply from requester.
Feel free to re open if necessary.
