### ISSUE TITLE
[Bug] Intermittent failures for test_patch_drive_limiter on Intel 5.10

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#2828]
# Describe the bug

Lately we have seen intermittent failures for test_patch_drive_limiter integration test. See [1] and [2]. It might be related to latest io_uring functionality since [2] is the oldest found failure and it only happens on 5.10 pipeline.

I can seem to find a failure before 
[1] - https://buildkite.com/firecracker/firecracker-x86-64-intel-kernel-5-dot-10-ci/builds/391#82505b12-b109-4c76-8d89-caf4c7a8bde2
[2] - https://buildkite.com/firecracker/firecracker-x86-64-intel-kernel-5-dot-10-ci/builds/389#8aee80a8-029f-4282-b329-185f4ce2f9dc

**Comment by alindima** [comment]
Since it also happens on the main branch, this cannot be related to io_uring (The io_uring development is happening on a feature branch).

**Comment by dianpopa** [comment]
Oh, I was under the impression we merged io_uring func into main. In that case it only happens for main unless you also found a failure on the io_uring feature branch, also?

**Comment by alindima** [comment]
> Oh, I was under the impression we merged io_uring func into main. In that case it only happens for main unless you also found a failure on the io_uring feature branch, also?

I also found failures on the io_uring branch, yep. I added a commit that relaxed the test limits to 30% (from 20%). I plan on backporting the commit to main as well.

**Comment by alindima** [comment]
This was fixed by merging the io_uring branch into main: https://github.com/firecracker-microvm/firecracker/pull/2836
Closing this.
