### ISSUE TITLE
Root image build fails to creatre/mount image, doesn't explain why, keeps going, fails to produce working image

### ISSUE THREAD

**Issue by theosib-amazon** [firecracker-microvm/firecracker#2831]
# Describe the bug

I'm using buildtool to make a root image. It wasn't until I couldn't boot the image that I found this error:

```
Mounting /firecracker/build/rootfs/bionic.rootfs.ext4 on /firecracker/build/rootfs/mnt ...
mount: /firecracker/build/rootfs/mnt: failed to setup loop device for /firecracker/build/rootfs/bionic.rootfs.ext4.
```

But then it just keeps on going...

```
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
...
```

If this absolutely critical step fails, then the process should stop, leaving us with enough information to diagnose the problem.

This is the result of an earlier failure that should ALSO have caused the build process to stop and produce an informative error but didn't"

```
dd: error writing ‘/home/ec2-user/firecracker.git/build/rootfs/bionic.rootfs.ext4’: No space left on device
```

The thing is, this error should not occur since (a) my host filesystem has 512G of space, and (b) you're presumably making a sparse image.

## To Reproduce

./tools/devtool build_rootfs -s 64G

## Expected behaviour

It should either complete successfully or provide an informative error message.

## Environment

Version: GIt head as of Dec 27, 2021
Host kernel: 4.14.252-195.483.amzn2.x86_64
Guest kernel: N/A
Root fs: Default
Architecture x86-64

## Additional context

`[Author TODO: How has this bug affected you?]`
I'm probably going to have to go through the manual process.

`[Author TODO: What are you trying to achieve?]`
Set up a basic VM with a large enough root disk that I can get my work done.

`[Author TODO: Do you have any idea of what the solution might be?]`
No.

## Checks

- [X] Have you searched the Firecracker Issues database for similar problems?
- [X] Have you read the existing relevant Firecracker documentation?
- [X] Are you certain the bug being reported is a Firecracker issue?

**Comment by theosib-amazon** [comment]
One thing I just noticed is that the virtual size of the root image it tried to create was on the order of 512G, although it was sparse. I definitely asked for 64G, so I don't know why dd tried to make something bigger.

**Comment by theosib-amazon** [comment]
Oh, I figured it out. The instructions don't specify the units of the size. They're 1 meg blocks. Maybe update the docs? Or reject an invalid size? Or interpret the size when the user specifies units?

**Comment by georgepisaltu** [comment]
Hi @theosib-amazon,

Our devtool helper for creating a rootfs takes a `-s SIZE` parameter, parsed [here](https://github.com/firecracker-microvm/firecracker/blob/main/tools/devtool#L2035), which then gets passed to the `dd` command found [here](https://github.com/firecracker-microvm/firecracker/blob/main/tools/devtool#L2068). `SIZE` means MB in this context with `bs=1M`.

I assume you're talking about the documentation in [rootfs-and-kernel-setup.md](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md#use-the-provided-recipe-1), which should indeed specify some units.
