### ISSUE TITLE
[Feature Request] Firecracker for Mac OS

### ISSUE THREAD

**Issue by jayavanth** [firecracker-microvm/firecracker#2845]
# Feature Request

It will enable development on Macs. You don't have to spin up a VM on a Mac to run firecracker. Macs are also getting very powerful with the new chips and a there is lot of potential especially for future Mac Pro Racks with M1 chips.

## Describe the desired solution

Running firecracker on Mac Hypervisor. This is the clean solution where Firecracker would just run on Hypervisor instead of Linux KVM.

## Describe possible alternatives

An alternate solution is to use a standalone VM on Mac such as Qemu, virtualbox, VMWare. But none of these are officially supported at the moment. Official support for a VM would be a good alternative.

## Checks

- [Yes, checked slack as well ] Have you searched the Firecracker Issues database for similar requests?
- [Yes] Have you read all the existing relevant Firecracker documentation?
- [Yes ] Have you read and understood Firecracker's core tenets?

**Comment by alsrdn** [comment]
Can you please describe your use-case a bit more? We're interested in what kind of deployment and features this support will provide. Also what kind of workloads will Firecracker on MacOS run?

**Comment by tatodorov** [comment]
One use case what comes to my mind is for running containers on Mac in lightweight virtual machines.
Currently the most feature rich way for that is Docker Desktop for Mac.
However, this is a closed source commercial product.
An alternatives like Podman and Lima already exist, but they rely on qemu.
Docker Desktop for Mac leverages hyperkit, but the open source version seems is not yet supported on M1 Mac - [#330](https://github.com/moby/hyperkit/issues/330).

**Comment by JonathanWoollett-Light** [comment]
We do not plan to support MacOS. Firecracker is highly dependent on KVM. To change this would require significant effort required and we do not currently see a significant use case.

**Comment by sorenbs** [comment]
With [MacOS 15 introducing support for Nested Virtualization](https://www.reddit.com/r/MacOSBeta/comments/1dcy5di/nested_virtualization_macos_15/?rdt=40327), is it feasible to run Firecracker in a linux VM on MacOS?

**Comment by pb8o** [comment]
Hi @sorenbs, it may be possible to run Firecracker as you describe, using a linux VM guest and if KVM works in the guest, then launching Firecracker. We haven't tried this though. There may be issues related to the CPU, since we have only tested Firecracker in AWS Graviton instances.

Let us know of your experience if you try it :)
