### ISSUE TITLE
On integration test concurrency

### ISSUE THREAD

**Issue by namespaceXP** [firecracker-microvm/firecracker#2870]
I've that firecracker has disabled integration test concurrency for `framework concurrency issues`. I wonder what exactly are the issues, and is there a chance to solve them?

**Comment by alindima** [comment]
Hi! I remember there were a number of concurrency-related bugs, like race conditions which I don't think we managed to track down.
We actually plan on removing the concurrency support from the framework since it's unused.
@gc-plp got more insight here?

**Comment by gc-plp** [comment]
@alindima, @namespaceXP IIRC there were some concurrency issues with the python framework some of which were fixed, but the main problem was that some performance/timing tests would occasionally fail. 

Concurrency can be reenabled, but the method used to filter which tests run in parallel needs to be looked at, to make sure that time-sensitive tests do not run in parallel with anything else.

I'd say that a more valuable effort could be put into running the [CI suite](https://buildkite.com/firecracker/firecracker-x86-64-intel-kernel-5-dot-10-ci) on multiple machines to reduce CI run times, as it's quite an easy fix.

**Comment by dianpopa** [comment]
Hi @namespaceXP,

Resolving the concurrency issues that we currently have with our CI would require higher level insight into the framework we use to run our CI. As such I think this is not something easily doable from outside.

We really really appreciate your involvement! Feel free to pick up any other issue that you find interesting.
Thanks!
