### ISSUE TITLE
[Feature Request] Make it possible to disable networking after starting VM

### ISSUE THREAD

**Issue by libre-man** [firecracker-microvm/firecracker#2881]
# Feature Request

We would like to be able to remove a network interface after the VM has been created, or at least be able to disable any traffic flowing through the existing interfaces.

## Describe the desired solution

Currently it is possible to rate limit network devices, but setting 0 disables the limiting. We would love to be able to set a limit of 0 bytes and 0 operations. That is probably not possible because of backwards compatibility, but maybe a new route that disables a network interface.

## Describe possible alternatives

We can work around this by either setting a very low limit (small bucket and large `refill_time`) but that doesn't guarantee that no traffic gets through. Another option is to disable forwarding, but that requires root access to change iptables rules.

## Additional context

For our use case of Firecracker (sandboxing automatic grading environments) we want to disable networking for certain tests. However, when you load a snapshot (we snapshot the container after setting it up for all the students of an assignment) the network configuration is inherited, so we cannot disable it easily. Or we can disable it, but then making it available for later tests is not really possible.

## Checks

- [X] Have you searched the Firecracker Issues database for similar requests?
- [X] Have you read all the existing relevant Firecracker documentation?
- [X] Have you read and understood Firecracker's core tenets? (I think this would fit, as network rate limiting is also implemented)

**Comment by libre-man** [comment]
Ah that makes sense. Currently we just disable networking with `ip` which works fine, but it seems cleaner to let the vmm handle that kind of stuff.

**Comment by raduiliescu** [comment]
I am closing this issue for now. Please feel free to reopen if new use cases arise.
