### ISSUE TITLE
[Q] Does the micro VM have init running?

### ISSUE THREAD

**Issue by ES-Yukun** [firecracker-microvm/firecracker#2887]
Does the micro VM have init running?

**Comment by raduiliescu** [comment]
Hi @ES-Yukun ,

When you bootup a microVM you will need to specify the kernel, the rootfs and, optionally an init.rd. A Linux system will always have an init process and that might come from init.rd if used, or from the rootfs you specified.

Thanks!

**Comment by ES-Yukun** [comment]
Thank you👍

**Comment by ES-Yukun** [comment]
Thank you👍
