### ISSUE TITLE
[Bug] Cannot restore diff snapshots of snapshots with active VSock connection

### ISSUE THREAD

**Issue by libre-man** [firecracker-microvm/firecracker#2888]
# Describe the bug

Resuming a diff snapshot of a VM that was created from a snapshot and had an active vsock connection as some point fails.

## To Reproduce

1. Create a firecracker from a root fs and kernel with vsock and network.
2. Create an active vsock connection to the vm.
3. Close the vsock connection (issue also happens when the connection is not closed) and snapshot (diff or full) the machine
4. Load the created snapshot, with the same rootfs and kernel
5. Open an active vsock connection again.
6. Close the connection again (or not, also happens then) and create a diff snapshot of the machine
7. Merge the memory files together (using the technique of #2802)
8. Load the snapshot using the merged memory file and latest state file
9. An error is logged `virtio queue number of available descriptors 65526 is greater than queue max size 256`

## Expected behaviour

The machine restores normally, and I can open new vsock connections again.

## Environment

- Firecracker version: v1.0.0 and v0.25.1
- Host kernel: 5.10.0-11-cloud-amd64
- Guest kernel: 5.4
- Rootfs used: Ubuntu 20.04
- Architecture: amd64

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

I'm trying to load diff snapshots.

`[Author TODO: Do you have any idea of what the solution might be?]`

It def. doesn't help to simply increase the queue limit. Yes increasing the limit to 512 makes the error go away, but then firecracker just exits with code 0.

## Checks

- [X] Have you searched the Firecracker Issues database for similar problems?
- [X] Have you read the existing relevant Firecracker documentation?
- [X] Are you certain the bug being reported is a Firecracker issue?

**Comment by raduiliescu** [comment]
Hi @libre-man ,

Thanks for bringing this into our attention!
Can you please look over this issue and let us know if the same one? https://github.com/firecracker-microvm/firecracker/issues/2802. They seem related.

**Comment by sandreim** [comment]
@raduiliescu looks like he is already using the technique from #2802. Seems to be a different issue.

@libre-man If you always create diffs, did you merge all diffs(steps 3,6) using the said procedure ?

**Comment by libre-man** [comment]
Yes I am using the technique of #2802 (both the program linked as a custom implementation have the same issue).

I do merge the memory files (as I created two snapshots there are only two) with the technique, I'm not merging the state files, should I also do that?

**Comment by serban300** [comment]
Hi @libre-man !

You don't need to merge the state files.

These seems to be the exact opposite of #2802 . Probably the memory page that contains the virtio queue len is overwritten with zeroes when it shouldn't be, leading to `queue.avail_idx = 0` and then `queue.avail_idx - queue.next_avail` will be close to `u16::MAX` which causes the error message that you get.

There could be a problem in the `merge_snap` repo. I did some changes this week trying to improve it. I have a couple of questions:
1. What commit in the `merge_snap` repository did you try ?
2. Could you try the initial commit in the repo (https://github.com/serban300/merge_snap/commit/dca418bfb21b060272db735778634409b6abe7ae) ?
3. Does the issue reproduce only when using vsock ?
4. If point `2.` doesn't solve the issue, could you maybe fork https://github.com/vadimberezniker/fcsnapshotissue and modify it in order to reproduce the scenario that you are describing ? Or provide the exact commands that you are using ? It would help us investigate the issue.

**Comment by libre-man** [comment]
Hi @serban300,

I have the same issue when I don't merge the memory snapshots at all, so I can't image that it is.
To answer your questions:
1. I tried the latest commit on the main branch.
2. Same issue unfortunately.
3. Yes, when not using vsock I don't have an issue.
4. I will do that later this weekend or next week Monday, as currently it is in integrated in an application we are developing and I don't think the firecracker-go-sdk has an easy way to extract the exact API calls.

**Comment by serban300** [comment]
> 4. I will do that later this weekend or next week Monday, as currently it is in integrated in an application we are developing and I don't think the firecracker-go-sdk has an easy way to extract the exact API calls.

Ok, thanks ! Looking forward to this. I tried to reproduce the issue with `nc-vsock` and `socat` and didn't manage to do it yet.

**Comment by libre-man** [comment]
Hi @serban300,

I rewrote the storage layer for our application to also be able to use btrfs, and now we no longer have the mentioned issue. So it has to be something with zfs and sparse files. It would be very nice if firecracker could output its diff memory files in a different layout than sparse files, and provide a tool to merge them, although I recon that is probably out of scope for the project.

**Comment by serban300** [comment]
Hi @libre-man,

> What kind of block size does firecracker expect? So how small should it be possible for the holes to be?

Each block is the size of a memory page. So usually 4096 Bytes.

> I rewrote the storage layer for our application to also be able to use btrfs, and now we no longer have the mentioned issue. So it has to be something with zfs and sparse files. It would be very nice if firecracker could output its diff memory files in a different layout than sparse files, and provide a tool to merge them, although I recon that is probably out of scope for the project.

Ok, it's good to hear that it works. A different layout would probably imply other disadvantages. But we'll definitely consider it. Also an action item on our side would be to investigate the issue with ZFS when we have time.

Anyway, I'll resolve this issue for the moment since the problem is fixed.

**Comment by simonis** [comment]
I ran today in this issue as well:
```
2022-12-30T19:53:03.430402737 [anonymous-instance:main:WARN:src/logger/src/lib.rs:33] [DevPreview] Virtual machine snapshots is in development preview.
2022-12-30T19:53:03.452016541 [anonymous-instance:main:WARN:src/devices/src/legacy/serial.rs:249] Failed to register serial input fd: event_manager: failed to manage epoll file descriptor
2022-12-30T19:53:03.453060026 [anonymous-instance:main:ERROR:src/devices/src/virtio/queue.rs:280] virtio queue number of available descriptors 57386 is greater than queue max size 256
2022-12-30T19:53:03.479887574 [anonymous-instance:main:WARN:src/logger/src/lib.rs:37] [DevPreview] Virtual machine snapshots is in development preview - 'load snapshot' VMM action took 49296 us.
2022-12-30T19:53:03.480025057 [anonymous-instance:fc_api:ERROR:src/api_server/src/parsed_request.rs:190] Received Error. Status code: 400 Bad Request. Message: Load microVM snapshot error: Cannot build a microVM from snapshot: Cannot restore microvm state. Error: Cannot restore devices: Block(Persist(InvalidInput))
```
I haven't used ZFS. I used a diff snapshot (i.e. `"snapshot_type": "Diff"), but just a single one (i.e. I haven't merged it with another snapshot).

- Friecracker version:  Firecracker v1.1.0-72-gde0e0814
- Host kernel: 5.4.0-136-generic # 153~18.04.1-Ubuntu
- Guest kernel: Linux version 5.19.8

Until now I've only seen this once for a snapshot which was taken from a running Firecracker process after my Ubuntu 18.04 laptop was suspended for about two days (i.e. I started Firecracker with vsock, connected with ssh and ran some basic vsock tests with `socat`. Then I suspended my Laptop and resumed it after ~2 days. My ssh connection into the guest was still active. I did run Python to get the local CID with `fcntl.ioctl` and finally took the snapshot). This snapshot always reproduced the above error.

Not sure if you might want to reopen this issue?

**Comment by luminitavoicu** [comment]
Hi, @simonis, thanks for letting us know about your issue!

> I used a diff snapshot (i.e. `"snapshot_type": "Diff"), but just a single one (i.e. I haven't merged it with another snapshot).

I am curious if this snapshot was the first `Diff` snapshot you took or not. Because `Diff` snapshots output to the memory file only the memory regions that have changed (dirty bits) since the last snapshot created. This means that for the first `Diff` snapshot, it will save the entire memory state (since it compares against a zero memory region) and it will be equivalent to a `Full` snapshot. However, all subsequent `Diff` snapshots will contain only those bits of memory changed since the last snapshot. In order to be able to use one of these, you need to merge the `Diff` snapshot with a base. I am curious if this is the case for you situation.

> Host kernel: 5.4.0-136-generic # 153~18.04.1-Ubuntu
Guest kernel: Linux version 5.19.8

One other thing to note is that we test continuously Firecracker (and guarantee functionality) on host and guest kernel versions 4.14 and 5.10. Please see [this page](https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md) for more details on our kernel support policy.

**Comment by simonis** [comment]
It was the first snapshot (i.e. I did no merge) but it is still sparse. However, the resulting memory file contains holes for physical pages which were not mapped in the guest. Not sure if this will also the case for a Full snapshot?

**Comment by BasToTheMax** [comment]
Hello.

I am having the same issue.

What I am doing:
- Create vmA
- Make a Full snapshot of vmA
- Destroy vmA
- Start vmB by loading the snapshot (diff's enabled)
- Create a Diff snapshot
- Destroy vmB
- Merge the Full and the Diff snapshot. (command below)
- Start vmC by loading the newly created (merged) snapshot.
- Firecracker crashes with the error below:

Snapshot command:
```
./snapshot-editor edit-memory rebase \
     --memory-path ./snap/mem1 \
     --diff-path ./snap/mem2
 ```

Firecracker logs:
```
2023-12-25T17:24:28.369578016 [anonymous-instance:fc_api:INFO:src/api_server/src/parsed_request.rs:163] The request was executed successfully. Status code: 204 No Content.
2023-12-25T17:24:28.387220678 [anonymous-instance:fc_api:INFO:src/api_server/src/parsed_request.rs:70] The API server received a Put request on "/snapshot/load" with body "{\n            \"snapshot_path\": \"./snap/snap1\",\n            \"mem_file_path\": \"./snap/mem1\",\n            \"enable_diff_snapshots\": true,\n            \"resume_vm\": true\n    }".
2023-12-25T17:24:28.387596935 [anonymous-instance:main:WARN:src/vmm/src/logger/mod.rs:33] [DevPreview] Virtual machine snapshots is in development preview.
2023-12-25T17:24:28.387873552 [anonymous-instance:main:INFO:src/vmm/src/persist.rs:314] Host CPU vendor ID: [71, 101, 110, 117, 105, 110, 101, 73, 110, 116, 101, 108]
2023-12-25T17:24:28.387891803 [anonymous-instance:main:INFO:src/vmm/src/persist.rs:315] Snapshot CPU vendor ID: [71, 101, 110, 117, 105, 110, 101, 73, 110, 116, 101, 108]
2023-12-25T17:24:28.413620267 [anonymous-instance:main:ERROR:src/vmm/src/devices/virtio/queue.rs:296] virtio queue number of available descriptors 4097 is greater than queue max size 256
2023-12-25T17:24:28.413716156 [anonymous-instance:main:INFO:src/vmm/src/lib.rs:818] Vmm is stopping.
2023-12-25T17:24:28.481140691 [anonymous-instance:fc_api:ERROR:src/api_server/src/parsed_request.rs:190] Received Error. Status code: 400 Bad Request. Message: Load snapshot error: Failed to restore from snapshot: Failed to build microVM from snapshot: Failed to restore MMIO device: Cannot restore devices: VirtioBlock(Persist(InvalidInput))
2023-12-25T17:24:28.481173674 [anonymous-instance:fc_api:WARN:src/api_server/src/lib.rs:139] PUT /snapshot/load: mem_file_path field is deprecated.
2023-12-25T17:24:28.481367990 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:94] RunWithApiError error: Failed to build MicroVM: Loading snapshot failed..
2023-12-25T17:24:28.481410903 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:97] Firecracker exiting with error. exit_code=1
```

Host kernel: `Linux bttm 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux` (`uname -a`)
Guest kernel: `vmlinux-5.10.bin` 

Download script used:
```bash
# Some var
ARCH="$(uname -m)"

release_url="https://github.com/firecracker-microvm/firecracker/releases"
latest=$(basename $(curl -fsSLI -o /dev/null -w  %{url_effective} ${release_url}/latest))


curl -L ${release_url}/download/${latest}/firecracker-${latest}-${ARCH}.tgz \
| tar -xz

mv release-${latest}-$(uname -m)/firecracker-${latest}-${ARCH} firecracker
mv release-${latest}-$(uname -m)/snapshot-editor-${latest}-${ARCH} snapshot-editor

rm release-${latest}-$(uname -m) -r

wget https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/${ARCH}/kernels/vmlinux-5.10.bin
mv vmlinux-5.10 kernel

chmod +x ./firecracker
chmod +x ./snapshot-editor
```

To give more context:
- The guest is running debian 12
- The rootfs is build using docker
- The guest is running docker (so docker in the microvm)
- Docker in the guest runs a container (a minecraft server, to be exact)

If you need more details, feel free to ask :wink:.

I hope someone can help me fix the issue. I will probably also ask in the slack server.
