### ISSUE TITLE
Increase the number of guard pages to help mitigate rowhammer/SMASH

### ISSUE THREAD

**Issue by twitchyliquid64** [firecracker-microvm/firecracker#2895]
# Ask

Increase the guard region (`src/vm-memory/src/lib.rs`) to be a few hundred kB to Mb in size.

# Rationale

Rowhammer (all variants) are only effective at flipping bits in X (1-2 typically, with it getting increasingly impossible the further you go) adjacent rows.

Heuristically, a system not under memory pressure seems to service large allocations (like the memory for the guest) from a contiguous allocation. This is ideal because it means we aren't getting pages all over the place, including adjacent to important structures like page tables.

Given the above two factors, a simple + most-of-the-time-in-practice mitigation would be to increase the size of the guard region from one page to the rough size which will cover the logical addressing of rows in typical DIMM RAM.

Based on the observation from the smash paper that row addressing was the MSBs starting at about bit 16-20, we can make it much harder most of the time by having guard sizes in the few hundred kb, and neigh impossible by having guard regions 1-3mb in size (the bigger the better, but at this size i imagine theres a reasonable tradeoff with resource wastage).

What do you think?

**Comment by georgepisaltu** [comment]
Hi,

Firecracker can only control its virtual page allocations and their mappings with guest memory. The Rowhammer/SMASH issue is related to physical pages. 

We investigated the Rowhammer and SMASH attacks and our recommendation is to not use vulnerable hardware.

The [guard pages in vm-memory](https://github.com/firecracker-microvm/firecracker/blob/eb8de3ba1f7cb636d2aaa632fe96b234f3a302e6/src/vm-memory/src/lib.rs#L26) are there to protect against out-of-bounds accesses into guest memory. The pages are `PROT_NONE` and have no physical backing in host RAM, so extending the guard region would have no effect on the actual physical RAM.

We advise users to be mindful of the SMASH/Rowhammer risks and be protected at the hardware level.

**Comment by twitchyliquid64** [comment]
Thanks for taking a stance on this. While ideal to use non-vulnerable hardware, this isnt always practical.

I'll note that what Im trying to get across is that while userspace can only control its virtual mappings, heuristically a large contiguous allocation is typically serviced by contiguous physical memory (sans memory pressure on the host). Its this property that makes increasing the guard page size a nice & easy most-of-the-time-in-practice mitigation.

**Comment by twitchyliquid64** [comment]
Good catch on `PROT_NONE`, we would need actual pages here (but could set them as write-protected / non-execute).
