### ISSUE TITLE
Add bash linter integration test

### ISSUE THREAD

**Issue by alindima** [firecracker-microvm/firecracker#2903]
Install `shellcheck` (or a similar checker) inside devctr and add a python integration test that runs it on the shell scripts we have in Firecracker, like `tools/devtool` and other `.sh` files

**Comment by dianpopa** [comment]
Hi @austinvazquez 

Very happy you want to help with this issue. The steps you propose sound good to me. I will help you with pushing the docker image once the PR is up.

**Comment by austinvazquez** [comment]
@dianpopa thanks for the feedback. I'll begin looking into the changes and open a PR soon.

**Comment by roypat** [comment]
We've discussed this with the team today and decided against adding shellcheck to our CI. This is mainly due to having bad experiences with its false-positive rates, that are similar to markdownlint, which already creates a lot of noise for us.
