### ISSUE TITLE
[Bug] Kernel Config for building x86 5.10 fails

### ISSUE THREAD

**Issue by wimax-grapl** [firecracker-microvm/firecracker#2905]
# Describe the bug

I tried following [these instructions](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md#use-the-provided-recipe) to build a microVM kernel, but for the other extant x86 config, 5.10. 

## To Reproduce

```
wimax@penguin:/tmp/tmp.fnIrRQe1JO/firecracker$ git log | head -n5
commit d3e98b9a4ae024de63f072c57015d8b7b0c1b061
Author: Luminita Voicu <lumivo@amazon.com>
Date:   Fri Jan 28 14:20:05 2022 +0200

    release v1.0


wimax@penguin:/tmp/tmp.fnIrRQe1JO/firecracker$ readonly KERNEL="x86_64-5.10"
wimax@penguin:/tmp/tmp.fnIrRQe1JO/firecracker$ readonly KERNEL_CONFIG="resources/guest_configs/microvm-kernel-${KERNEL}.config"


wimax@penguin:/tmp/tmp.fnIrRQe1JO/firecracker$ ./tools/devtool build_kernel --config "${KERNEL_CONFIG}" --nproc 8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6046  100  6046    0     0  38509      0 --:--:-- --:--:-- --:--:-- 38509
Starting kernel build.
Downloading kernel from https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.0.tar.xz
Extracting kernel sources...
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot create regular file '/tmp/tmp.fnIrRQe1JO/firecracker/build/kernel/linux-5.10.0/.config': No such file or directory
[ERROR] Kernel directory not found.

[Firecracker devtool] Successfully built kernel!
[Firecracker devtool] Kernel binary placed in: /tmp/tmp.fnIrRQe1JO/firecracker/build/kernel/linux-5.10.0/vmlinux-5.10.0-x86_64.bin
wimax@penguin:/tmp/tmp.fnIrRQe1JO/firecracker$ ls /tmp/tmp.fnIrRQe1JO/firecracker/build/kernel/linux-5.10.0/vmlinux-5.10.0-x86_64.bin
ls: cannot access '/tmp/tmp.fnIrRQe1JO/firecracker/build/kernel/linux-5.10.0/vmlinux-5.10.0-x86_64.bin': No such file or directory
```

## Expected behaviour
1. I would have expected a kernel to be built. It looks like 5.10.0 does not exist on https://cdn.kernel.org/pub/linux/kernel/v5.x/ for starters!
2. Moreover, I would have expected Devtool to not give me these clearly incorrect "Successfully built kernel!" messages intermixed with the failures.

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]` 1.0.0
`[ - Host and guest kernel versions.]` Host: Debian Bullseye on Crostini: 5.4.163-17383-gbc0d0d65633b
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by dianpopa** [comment]
@wimax-grapl I was able to build a kernel using the exact instructions you gave, can you please try again the exact steps and let me know if any error comes up?

As far as the script declaring a successful build even with errors, this should be fixed by https://github.com/firecracker-microvm/firecracker/pull/3261.

Feel free to re-open if any issue encountered.
