### ISSUE TITLE
[Feature Request] Update readme.md logo to better fit dark mode

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#2937]
# Feature Request

Using the logo with the white background looks awkward in dark mode, thus using the logo with the transparent background would be preferable.

## Describe the desired solution

Update `readme.md` to use `./docs/images/fc_logo_full_transparent-bg.png` for better visuals in dark mode.

Before|After
---|---
![firecracker-light](https://user-images.githubusercontent.com/16856679/161067686-28f87c5c-7397-47ac-8bfc-0584eda6317d.png) | ![firecracker-dark](https://user-images.githubusercontent.com/16856679/161067527-f43e6b14-4eb5-4d40-afe3-ae4ef3d18e1f.png)

## Describe possible alternatives

Could also use `./docs/images/fc_sticker_full_white-bg.png`, e.g.

<image src="https://user-images.githubusercontent.com/16856679/161068375-72b699d4-a677-4843-9461-66ee3a7049ff.png" width=500>

This may be preferable if a white background is desired. I would suggest this might look best centred with significant padding.

## Additional context

As this is a non-technical change there is no real context to consider.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by dianpopa** [comment]
Fixed by #2950.
Thanks @JonathanWoollett-Light for the contribution!
