### ISSUE TITLE
[UFFD] Allow user space to handle memory page faults

### ISSUE THREAD

**Issue by xmarcalx** [firecracker-microvm/firecracker#2938]
# Feature Request

Give customer the control on how to load memory when a page fault happen in order to improve workload latency

## Describe the desired solution

A page fault should be delegated from the kernel to the user space to allow a user space process to develop a specific page-handling mechanism.
UFFD (usefaultfd) create a file descriptor for handling page fault in user space which can be polled by an user space process in order to be notified about a page fault and react to it.

## Describe possible alternatives

There are not known alternative.
Currently, any page fault is handled by the kernel.

## Additional context
Related issues: #2921 

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by xmarcalx** [comment]
#2921

**Comment by luminitavoicu** [comment]
#2947
