### ISSUE TITLE
Publish performance test results

### ISSUE THREAD

**Issue by xmarcalx** [firecracker-microvm/firecracker#2939]
# Feature Request

Publish performance test results

## Describe the desired solution
As result of the automation of the performance tests done in #2144  we should try to automatically publish performance test result in order to be easily consumed by the community.

## Describe possible alternatives

Currently we are releasing performance baseline metrics as json file inside the test folder. 

## Additional context
This is a follow up activity of the development performed in #2144

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by pb8o** [comment]
Resolving this since there has been no interest from the community and we don't see a lot of value on it.
