### ISSUE TITLE
[Feature Request] Suppress warning for unused struct field

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#2953]
# Feature Request

Add `#[allow(dead_code)]` attribute onto the `format_version` field of the `Snapshot` struct defined under `src/snapshot/src/lib.rs`.

## Describe the desired solution

The field `format_version` is private and unused within the crate, therefore it produces this warning. I would assume it is used via some other mechanism, so if in this case where it cannot be removed I would suggest adding the `#[allow(dead_code)]` attribute to the field like:
```rust
#[derive(Debug)]
pub struct Snapshot {
    hdr: SnapshotHdr,
    // This field is used by ... this cannot be detected because ... therefore we have added this attribute to 
    //  suppress the unnecessary warning.
    #[allow(dead_code)]
    format_version: u16,
    version_map: VersionMap,
    // Required for serialization.
    target_version: u16,
}
```
Using this attribute I would argue there should be a comment explaining why it is valid, in this case this may describe why it is used and why the compiler cannot detect this.

## Describe possible alternatives

If `#[allow(dead_code)]` cannot be used I would suggest an extensive comment discussing why.

## Additional context

I cannot think of any particularly relevant additional context.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by alindima** [comment]
After a quick glance, it seems to me that this field is indeed unused. The format version is calculated from the magic id using `get_format_version()` so there is no need to persist it in the `Snapshot` struct at the moment.
This may change if we add a new snapshot format.

I suggest we remove this field.
