### ISSUE TITLE
Output file from VM

### ISSUE THREAD

**Issue by jackdouglas** [firecracker-microvm/firecracker#2982]
I have a modified VM that runs a shell script on boot and creates a file. That all works fine until I shut the VM down - at that point if I mount the rootfs from the jail, the file I created has dissapeared. Presumably this is because of some sort of overlay on the root fs when the VM is active?

If that's correct, is there any way to turn that off, so the actual root fs can be modified by the VM, or failing that, is there an easy way to write the file to some output stream so the calling program can get the data in it?

**Comment by dianpopa** [comment]
What I can think it could happen is that an overlay is happening in the guest. Can you check what `mount` command returns when run before rebooting the VM?

**Comment by jackdouglas** [comment]
Thanks @dianpopa, I figured out that the issue only happened with `--resource-limit fsize=1000000` - the VM would exit early and although I could see the file in the VM I guess it couldn't sync to disk. Setting `--resource-limit fsize=250000000` as per the docs and the issue goes away.

Can I ask why I can get away with setting `no-file` to a very small number (eg 128) but not `fsize`?

**Comment by jackdouglas** [comment]
> fsize puts a size limit on the file that the Firecracker process creates, while no-file limits the number of file descriptors the process can open.

OK, so only `fsize` puts a limit on the resource usage of the VM itself, is that correct? (because the whole file system is just a single file to firecracker process).

And `fsize` needs to be at least as large as the root file system because that is copied on launch?

**Comment by jackdouglas** [comment]
I think I understand this now, thanks for your help!
