### ISSUE TITLE
device channel parameters setting in firecracker

### ISSUE THREAD

**Issue by thunderZH963** [firecracker-microvm/firecracker#2997]
I want to increase the network bandwidth by setting the Rx / TX queue size of NIC(eht0) in microVM. However I exec
"ethtool -L eth0 combined 10", "Cannot set device channel parameters: Invalid argument" is shown.

I know in qemu/kvm, .we can use xml to set them, but if firecracker supports this setting?

"ip link set tap0 txqueuelen [NUM]" in host os is equal to this?

**Comment by serban300** [comment]
Hi @thunderZH963 ,

Probably this is again related to the rootfs. On my custom rootfs with Ubuntu 21.10 it works, but the only argument that it will accept is `1`. Otherwise I am getting the following error:

```
netlink error: requested channel count exceeds maximum (offset 36)
```

Closing this issue since it's not related to Firecracker.
