### ISSUE TITLE
protocol 'tcp' unknown!

### ISSUE THREAD

**Issue by thunderZH963** [firecracker-microvm/firecracker#2998]
I find that maybe NPtcp is not supported in firecracker?
```
if(!(proto = getprotobyname("tcp"))){
   printf("NetPIPE: protocol 'tcp' unknown!\n");
   exit(555);
 }
```
"protocol 'tcp' unknown!\" will be triggered.

I thought it was the kernel version. But when I tried the configuration here(https://github.com/firecracker-microvm/firecracker/blob/main/resources/guest_configs/microvm-kernel-x86_64-5.10.config), I regained vmlinux.bin, it still not works.

Why?

Looking forward to your reply and discussion.

**Comment by serban300** [comment]
Hi @thunderZH963 ! I'm not familiar with NetPIPE, but Firecracker support tcp. Could there be something missing from your rootfs ?

**Comment by thunderZH963** [comment]
> Hi @thunderZH963 ! I'm not familiar with NetPIPE, but Firecracker support tcp. Could there be something missing from your rootfs ?

    Hello, I recognize that firetracker supports TCP. However, my rootfs is built through [tools](https://github.com/firecracker-microvm/firecracker/blob/main/tools/devtool), and no relevant errors are found during this period. At the same time, the rootfs provided in docs also has the same problem.
    After my further exploration, I found that the relevant tests of TCP can be executed normally, but some functions such as getprotobyname ("TCP") are not supported. I guess whether the syscalls involved are not supported by fireracker.

**Comment by serban300** [comment]
I build a rootfs with Ubuntu 21.10 from http://cdimage.ubuntu.com/ubuntu-base/releases/21.10/release/ubuntu-base-21.10-base-amd64.tar.gz , ran the following code:
```
#include <stdio.h>
#include <netdb.h>

int main() {
    struct protoent *proto;
    if(!(proto = getprotobyname("tcp"))){
        printf("NetPIPE: protocol 'tcp' unknown!\n");
    } else {
        printf("OK\n");
    }
    return 0;
}
```

And the output is `OK`.

So Firecracker should support this. And I'm not sure if it has to do with syscalls. The documentation says: `The getprotobyname() call searches the /etc/protocol or tcpip.ETC.PROTO data set for the specified protocol name. `

Can you check the output of `cat /etc/protocols` on your VM please ? Personally among other protocols I'm also getting:
```
tcp	6	TCP		# transmission control protocol
```

**Comment by serban300** [comment]
Also resolving this issue since it's not related to Firecracker.
