### ISSUE TITLE
Can't connect to local socket

### ISSUE THREAD

**Issue by paulfryer** [firecracker-microvm/firecracker#2999]
Following the getting started guide. Was able to start firecracker in one shell, now trying to connect to the socket in another, but can't connect to server. What should I do for next step to troubleshoot?

```
paul@edge-device-01:~/firecracker/release-v1.1.0-aarch64$ curl --unix-socket /tmp/firecracker-socket -i -X PUT 'http://localhost/boot-source'
curl: (7) Couldn't connect to server
```

**Comment by mattschlebusch** [comment]
Hi @paulfryer ,

At a glance it looks like the path to the socket has a typo, this path should be identical to the path provided when launching the firecracker process:

```
--unix-socket /tmp/firecracker-socket
```

The file name should be `firecracker.socket` (take note of the dot, versus the forward slash). With the file path tweaked you should expect a response along the lines of **"empty put request."**. The console session running the firecracker process should corroborate that it received a message with the error message as well.

Following from that, just make sure to include the payload in the request as per the [getting started guide](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md) to ensure the guest kernel is configured to fulfill what the API call is intended for.
