### ISSUE TITLE
Can't join slack

### ISSUE THREAD

**Issue by zeenix** [firecracker-microvm/firecracker#3007]
# Describe the bug

I can't figure out how to join [your slack](https://firecracker-microvm.slack.com/)? Is it restricted to invite-only? There is only the option to login and if I use my account from another space, I'm told that I can't do that. There is no option provided to create an account.

If this is intentional, it'd be great to not invite people there in the CONTRIBUTING file.

**Comment by dianpopa** [comment]
hi @zeenix,

Sorry for not making this smooth for you. Indeed you can join our slack by using the invite link from our [README](https://github.com/firecracker-microvm/firecracker/blob/5a201e13e3d419049858bd1836a05da1db7ef96a/README.md#faq--contact). Does this work for you?

I will also update the Contributing section to point to this.

**Comment by zeenix** [comment]
Hi @dianpopa,

> Sorry for not making this smooth for you. Indeed you can join our slack by using the invite link from our [README](https://github.com/firecracker-microvm/firecracker/blob/5a201e13e3d419049858bd1836a05da1db7ef96a/README.md#faq--contact). Does this work for you?

Oh, that works perfectly. :+1: Thanks so much. :pray:
