### ISSUE TITLE
No feedback in node shell

### ISSUE THREAD

**Issue by jackdouglas** [firecracker-microvm/firecracker#3033]
I have a custom rootfs based on a node:18-alpine Docker image working following [the FAQ guide](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md) (though I'm just using the supplied kernel rather than compiling my own).

Mostly things look fine, I can start up the Micro-VM and run shell commends, can edit files with `vi` etc. Running `node` or `node -i` give no feedback however. There is no node prompt and no commands generate any response at all:

```
(none):~# node
1+1
var x=1;
x
```

I can't exit with `.exit` only with CTRL+C. I don't think this is a node issue as it works when run as a Docker container, just not as a Firecracker MicroVM. I guess it's something to do with the console, any hints as to how I can find out?

**Comment by bchalios** [comment]
Do you use the console for interacting with the VM? Have you tried with SSH?

**Comment by jackdouglas** [comment]
Yes I'm using the console - I will get networking set up and try the same with ssh. Is this expected not to work via the console?

**Comment by jackdouglas** [comment]
It's not just node that is affected - I can't successfully run sshd (or even ssh-keygen). Most commands just hang and provide no feedback even when I try to turn debug info on:

```sh
/usr/sbin/sshd -D -ddd -f /etc/ssh/sshd_config

**Comment by jackdouglas** [comment]
I've discovered I need to wait (several minutes) after booting until the kernel's random-number generator is ready to generate random numbers:

```sh
(none):~# [  576.210866] random: crng init done
```

after that everything works fine including sshd and node:

```sh
(none):~# node
Welcome to Node.js v18.2.0.
Type ".help" for more information.
> 1+1
2
> 
```

**Comment by jackdouglas** [comment]
It looks like I can use `random.trust_cpu=on` in the kernel boot arguments with a kernel >4.19. I can get the supported 4.14 kernel from the link in the quickstart guide (https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin) - is there anywhere I can download the same for 5.10?

**Comment by jackdouglas** [comment]
or I can just install `haveged` which is god enough for me!
