### ISSUE TITLE
[Bug] getting-started.md is out of date

### ISSUE THREAD

**Issue by cperciva** [firecracker-microvm/firecracker#3038]
# Describe the bug

I noticed two issues:

1. The "opinionated way of running Firecracker" suggests Ubuntu 18.04, which is very old.
2. The precompiled firecracker binaries are now inside a subdirectory in their tarballs, so the `mv` command doesn't work.

## To Reproduce

1. Read getting-started.md.
2. Try to follow the instructions.

## Expected behaviour

1. Ubuntu 22.04 should be recommended instead of 18.04.
2. The `mv` command should have the right path so it actually works.

## Environment

Documentation in main branch.

## Additional context

PR coming shortly.

**Comment by bchalios** [comment]
Using Ubuntu 18.04 to run Firecracker is just a recommendation in this context. You can use any other version of Ubuntu (or other distro) to run Firecracker.

On the `mv` command, we should fix that, thanks for the PR.

**Comment by cperciva** [comment]
@bchalios I agree that there's no requirement to use 22.04 instead of 18.04.  But recommending an old release will (a) surprise and potentially confuse people (who may wonder if 18.04 is recommended because 22.04 doesn't work), and (b) may cause problems in the future as Amazon deprecates old AMIs.  It seems more sensible to recommend 22.04 to new users.

**Comment by michalani** [comment]
According to https://ubuntu.com/about/release-cycle 18.04 has security updates until 2028, thus change (1) would be pointless.

**Comment by cperciva** [comment]
@bchalios @michalani Ok, if you don't like the s/18.04/22.04/ I can take that commit out.  @dianpopa You approved the PR including that change, are you ok with me dropping it and leaving just the `mv` command fix?

**Comment by dianpopa** [comment]
> @bchalios @michalani Ok, if you don't like the s/18.04/22.04/ I can take that commit out. @dianpopa You approved the PR including that change, are you ok with me dropping it and leaving just the `mv` command fix?

Yup, all good

**Comment by cperciva** [comment]
Ok done.
