### ISSUE TITLE
ovn integration 

### ISSUE THREAD

**Issue by alizowghi** [firecracker-microvm/firecracker#3040]
Hi
I want to attach specific interface that is a part of specific ovn switch.
Fircecracker microvm only support tap device and when i attach an internal interface in host to microvm network it says:

{"fault_message":"Could not create Network Device: TapOpen(IoctlError(Os { code: 22, kind: InvalidInput, message: \"Invalid argument\" }))"}

**Comment by dianpopa** [comment]
Hi @alizowghi,

Seems that the "TUNSETIFF" ioctl fails for you. Can you let me know how are you creating the interface?
Did you take a look at the network setup example: https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md#on-the-host.

**Comment by alizowghi** [comment]
Hi @dianpopa 

`ovs-vsctl add-port br-int vm1 -- set Interface vm1 type=internal -- set Interface vm1 external_ids:iface-id=vm1

ip link set vm1 address 40:44:00:00:00:01
ip addr add 192.168.0.11/24 dev vm1
ip link set vm1 up

`

**Comment by alizowghi** [comment]
Hi,
The problem solved.
`ip tuntap add mode tap vmport1
ovs-vsctl add-port br-int vmport1 -- set Interface vmport1 external_ids:iface-id=vm1
ip link set vmport1 address 40:44:00:00:00:01
ip link set vmport1 up

curl --unix-socket /tmp/firecracker2.socket -i   -X PUT 'http://localhost/network-interfaces/eth0'   -H 'Accept: application/json'   -H 'Content-Type: application/json'   -d '{
      "iface_id": "eth0",
      "guest_mac": "40:44:00:00:00:01",
      "host_dev_name": "vmport1"
    }'`
