### ISSUE TITLE
[Bug] Slack Link Expired in Readme

### ISSUE THREAD

**Issue by ryanrussell** [firecracker-microvm/firecracker#3072]
# Describe the bug

Slack chat link in readme not functional

## To Reproduce

1. Go to bottom of https://github.com/firecracker-microvm/firecracker
2. Click Slack join link

## Expected behaviour

Join the chat :)

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?

**Comment by luminitavoicu** [comment]
Hi @ryanrussell, thank you for letting us know about this! I have posted a PR with the new invite, please feel free to use that link to join the slack.
