### ISSUE TITLE
[ci] Improved coverage ci needed

### ISSUE THREAD

**Issue by ihciah** [firecracker-microvm/firecracker#3100]
I am working on a small patch(#3098) and I found it's hard to pass coverage ci.

# Why writing a fixed threashold in code is not a good solution
I checked the code and found that in this project it maintains coverage target in code, which may be outdated and unable to calculate commit diff.
There is a `COVERAGE_MAX_DELTA` design, I think its purpose is to allow commits which cause coverage drop little. But comparing to a fixed number will not make it work.

> For example, our target is 80%, we allow 1% drop for a single commit and current coverage is 85%.
> CommitA: cause coverage -5.5% and it will pass.
> CommitB: cause coverage -0.5% but it will fail.

As the result, the coverage improvement by former commits will always be broken by later commits, and the whole coverage will always be near the threashold. Also the author of CommitB will complain that.

# Maintain it in other places
The core problem for this issue is that we need to maintain the coverage history in an platform, so that we can calculate the diff of each commit and let the commit pass or fail.
A platfrom I suggest to use is [codecov](https://about.codecov.io/). With it we can submit coverage in ci with secret to make the coverage data safe.
Except for coverage number, it also submits the coverage details. Which is good for contributers to check where is not covered.

# An example
Another project I maintained may be as an example([codecov link](https://app.codecov.io/gh/bytedance/monoio), [ci link](https://github.com/bytedance/monoio/blob/master/.github/workflows/coverage.yml)). And with codecov we can view coverage in module level  or commit level, it will be possible to calculate coverage diff of one commit.

**Comment by JonathanWoollett-Light** [comment]
This is an issue we have discussed and decided to address moving forward. We intend to implement a solution like https://github.com/marketplace/actions/continuous-benchmark but adjusted to use BuildKite and other specifics.

**Comment by JonathanWoollett-Light** [comment]
[codecov](https://about.codecov.io/) looks interesting thank you for bringing this to our attention.

**Comment by roypat** [comment]
We have switched to using codecov.io in https://github.com/firecracker-microvm/firecracker/pull/4015
