### ISSUE TITLE
Is there a prebuilt 5.10 kernel to download?

### ISSUE THREAD

**Issue by jackdouglas** [firecracker-microvm/firecracker#3109]
The [quickstart guide](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md) has a link to [a pre-built 4.14 kernel](https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin), and somewhere in the issues here I found another 4.14 kernel that was optimised for faster boot time, but I haven't found any 5.10 kernels (the other currently supported kernel version in the [Kernel Support Policy](https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md)).

Are any 5.10 kernels available for download anywhere?

**Comment by dianpopa** [comment]
HI!

Yup there is!

x86 - https://s3.amazonaws.com/spec.ccfc.min/ci-artifacts/kernels/x86_64/vmlinux-5.10.bin
aarch64 - https://s3.amazonaws.com/spec.ccfc.min/ci-artifacts/kernels/aarch64/vmlinux-5.10.bin

**Comment by jackdouglas** [comment]
marvellous, thanks very much!
