### ISSUE TITLE
Using NVME-oF over RDMA

### ISSUE THREAD

**Issue by Adhilr** [firecracker-microvm/firecracker#3137]
Hi, this is not a feature request. I am trying to access an NVME-oF over RDMA disk from the MicroVM. To make the RDMA work we need the NIC/PIC available inside the MicroVM. Is it possible to do this, are there any docs or references we can use to do this?

**Comment by alsrdn** [comment]
Hi @Adhilr, thanks for your interest in using Firecracker! Unfortunately, Firecracker does not have a PCI device model and can't pass through network devices to the Guest so you can't use RDMA with a HW NIC inside the uVM. PCI passthrough support is currently unplanned for Firecracker and we don't know if/when we'll implement this feature.
