### ISSUE TITLE
Enable invpcid_single Flag as Part of T2 CPU Templates

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#319]
**What is invpcid_single**
invpcid_single is basically invpcid (already enabled in Firecracker) and CR4.PCIDE=1.

**Why**
This is a feature enabled on T2 and C3, but not enabled in the Firecracker microvm. I think whoever picks this up should do a bit more research on why is it useful and if we should actually do that.

**How**
- [ ] Add define for PCDIE shift in x86_64/src/regs.rs
- [ ] Enable the flag in sregs.cr4

**Comment by alindima** [comment]
`invpcid` is indeed enabled in EC2 T2 instance. It is also not masked in Firecracker T2 CPU template and tested in the CPUID integration tests: https://github.com/firecracker-microvm/firecracker/blob/8f9ec61fcea45d81c561ec854d5622265dc7c595/tests/integration_tests/functional/test_cpu_features.py#L314
