### ISSUE TITLE
Use `clippy::cast_lossless`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3196]
Implement the `clippy::cast_lossless`.

**Comment by roypat** [comment]
From [clippy's list of lints](https://rust-lang.github.io/rust-clippy/master/#cast_lossless)

> **What it does**
> Checks for casts between numerical types that may be replaced by safe conversion functions.
> 
> **Why is this bad?**
> Rust’s as keyword will perform many kinds of conversions, including silently lossy conversions. Conversion functions such as i32::from will only perform lossless conversions. Using the conversion functions prevents conversions from turning into silent lossy conversions if the types of the input expressions ever change, and make it easier for people reading the code to know that the conversion is lossless.
