### ISSUE TITLE
Use `clippy::cast_possible_truncation`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3197]
Implement the `clippy::cast_possible_truncation`.

**Comment by roypat** [comment]
From [clippy's list of lints](https://rust-lang.github.io/rust-clippy/master/#cast_possible_truncation)

> **What it does**
> Checks for casts between numerical types that may truncate large values. This is expected behavior, so the cast is Allow by default.
> 
> **Why is this bad?**
> In some problem domains, it is good practice to avoid truncation. This lint can be activated to help assess where additional checks could be beneficial.

**Comment by JBYoshi** [comment]
@sarimaleem and I would like to work on this. We're doing a class project for UT Austin's virtualization class, where we're supposed to work on issues in virtualization-related open source projects. Is this issue open for us to work on?
