### ISSUE TITLE
Use `clippy::cast_precision_loss`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3199]
Implement the `clippy::cast_precision_loss`.

**Comment by roypat** [comment]
From [clippy's list of lints](https://rust-lang.github.io/rust-clippy/master/#cast_precision_loss)

> **What it does**
> Checks for casts from any numerical to a float type where the receiving type cannot store all values from the original type without rounding errors. This possible rounding is to be expected, so this lint is Allow by default.
> Basically, this warns on casting any integer with 32 or more bits to f32 or any 64-bit integer to f64.
> 
> **Why is this bad?**
> It’s not bad at all. But in some applications it can be helpful to know where precision loss can take place. This lint can help find those places in the code.

**Comment by JonathanWoollett-Light** [comment]
See https://github.com/firecracker-microvm/firecracker/pull/3325
