### ISSUE TITLE
Use `clippy::cast_sign_loss`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3200]
Implement the `clippy::cast_sign_loss`.

**Comment by roypat** [comment]
From [clippy's list of lints](https://rust-lang.github.io/rust-clippy/master/#cast_sign_loss)

> **What it does**
> Checks for casts from a signed to an unsigned numerical type. In this case, negative values wrap around to large positive values, which can be quite surprising in practice. However, as the cast works as defined, this lint is Allow by default.
> 
> **Why is this bad?**
> Possibly surprising results. You can activate this lint as a one-time check to see where numerical wrapping can arise.

**Comment by sladyn98** [comment]
I would like to give this issue a shot, I was looking at the codebase and it seems that I would have to add these as lint rules, am I correct or are there more places in the codebase where I would have to make this change

**Comment by roypat** [comment]
Hi @sladyn98, welcome to Firecracker! :)
Yes, generally this would involve adding a `#[warn(clippy:cast_sign_loss)]` to each crate in the Firecracker workspace, and then fixing the warnings rustc throws at you! You can use Jonathan's PR [here](https://github.com/firecracker-microvm/firecracker/pull/3204/files) as a reference.

**Comment by ls-1801** [comment]
Is this issue still up for grabs? I have a PR ready.
