### ISSUE TITLE
False negatives of `clippy::unneccesary_cast`/`clippy::needless_borrow`

### ISSUE THREAD

**Issue by roypat** [firecracker-microvm/firecracker#3215]
Due to a bug in clippy that is fixed in nightly, the version of clippy we currently use does not warn for many instances of `clippy::unncessary_cast`: https://github.com/rust-lang/rust-clippy/issues/9562. Running `cargo +nightly clippy` on the firecracker workspace yields around 50 warnings of this type.

Something similar happens to a lesser extend with the `unnecessary_borrow` lint, however I could not track the change of behavior in clippy down to a specific issue.

This might cause issues if we ever decide to upgrade rust past 1.66 (once it is stable ofc), since we deny warnings.

**Comment by Gilnaa** [comment]
Running with current nightly clippy (`clippy 0.1.66 (0da281b 2022-10-27)`) also uses `clippy::uninlined-format-args`:
```
error: variables can be used directly in the `format!` string
  --> src/vmm/build.rs:23:20
   |
23 |     json_path.push(format!("{}.json", target));
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
   = note: `-D clippy::uninlined-format-args` implied by `-D warnings`
help: change this to
   |
23 -     json_path.push(format!("{}.json", target));
23 +     json_path.push(format!("{target}.json"));
   |

error: variables can be used directly in the `format!` string
  --> src/vmm/build.rs:41:5
   |
41 |     println!("cargo:rerun-if-changed={}", json_path);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
help: change this to
   |
41 -     println!("cargo:rerun-if-changed={}", json_path);
41 +     println!("cargo:rerun-if-changed={json_path}");
   |
```

This lint will also have to be disabled specifically in order to make this work on newer clippys. (It can be trivially fixed, of course, but it will affect the MSRV, which I'm not sure if firecracker has)

**Comment by roypat** [comment]
We might want to specify a "minimum supported rust version" (https://doc.rust-lang.org/clippy/configuration.html#specifying-the-minimum-supported-rust-version) so prevent issues like this going forward.

**Comment by Gilnaa** [comment]
Is there an agreed minimum Rust version for firecracker?

**Comment by bchalios** [comment]
Yes, currently we are building Firecracker with Rust 1.64. Unfortunately, this is not very well documented but you can deduce it by looking at the Dockerfiles[1][2] we use for building the docker images we use through `devtool` [3].

At the moment, we can't do anything for this issue, we will keep it open as an action item reminder for whenever you upgrade the toolchain past 1.66 (as @roypat mentioned)


[1] https://github.com/firecracker-microvm/firecracker/blob/main/tools/devctr/Dockerfile.x86_64
[2] https://github.com/firecracker-microvm/firecracker/blob/main/tools/devctr/Dockerfile.aarch64
[3] https://github.com/firecracker-microvm/firecracker/blob/main/tools/devtool
