### ISSUE TITLE
`cargo build` produces `x86_64` binary on ARM

### ISSUE THREAD

**Issue by roypat** [firecracker-microvm/firecracker#3221]
# Describe the bug

Since we globally specify the `x86_64-unknown-linux-musl` target, plain `cargo build` (e.g. when building firecracker _without_ the `devtool build` wrapper. `devtool build` will always set the correct target) will always produce a `x86_64` binary, even if that binary cannot be executed on the host platform (e.g. on ARM).

## To Reproduce

run `cargo build` on non-`x86_64` machine (you will have to install quite a few dependencies to get the cross-compilation to actually work)

## Expected behaviour

`cargo build` produces a binary that is compatible with the host architecture. Particularly, we want it to compile for `x86_64-unknown-linux-musl` on `x86_64` linux, and for `aarch64-unknown-linux-musl` on ARM linux. 

## Environment

N/A

## Additional context

This stems from the fact that cargo does not allow us to specify targets dependent on host architecture. On option would be to remove the `target` directive in `.cargo/config` completely, although this would also change the behavior on `x86_64` (it would produce a binary with glibc ABI instead of musl, which is not desirable). 

It might not be possible to achieve the desired behavior without changes to cargo 

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by ls-ivan-kiselev** [comment]
> it would produce a binary with glibc ABI instead of musl, which is not desirable

Does it compile to `x86_64-unknown-linux-musl` by default just for the static linking and avoiding system dependencies or is there some other reason?

**Comment by roypat** [comment]
This was fixed in https://github.com/firecracker-microvm/firecracker/pull/4121
