### ISSUE TITLE
[Bug] `cargo update` results in un-buildable workspace

### ISSUE THREAD

**Issue by roypat** [firecracker-microvm/firecracker#3226]
# Describe the bug

Running `cargo update` or deleting `Cargo.lock` results in an un-buildable workspace in the sense that `cargo build` fails with compilation errors due to incompatible dependencies. 

## To Reproduce

1. Run `cargo update` or delete `Cargo.lock`
2. Run `cargo build` (or `./tools/devtools build`)

## Expected behaviour

The dependencies specified in the various `Cargo.toml` files are compatible and the build succeeds

## Additional context

This is due to us using `>=` instead of `=` to specify dependency versions for crates that do not follow semver (e.g. crates prior to version one, especially `rust-vmm`). For example, `vmm-sys-utils=0.10.0` does not export `ioctl_expr` anymore, but since `utils/Cargo.toml` specifies `vmm-sys-utils>=0.8.0`, this version is downloaded by `cargo update`.

To fix this, we need to go through `Cargo.lock` and lock our dependencies to versions that are proven to compile.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by roypat** [comment]
Additionally, we can use this as an opportunity to ensure that we are not using different versions of the same crate across different workspace members. This could improve compilation time.

**Comment by andreeaflorescu** [comment]
The `ioctl_expr` is exported, but it was changed from a macro to a const fn: https://github.com/rust-vmm/vmm-sys-util/commit/7fd919203bf11d076be3d169ddf18b5fabf0fd86.

**Comment by JonathanWoollett-Light** [comment]
It must now be included with the full path `use vmm_sys_util::ioctl::ioctl_expr` (where previously `use vmm_sys_util::ioctl_expr` would work).

I would also agree with setting a specific version with `=` rather than `>=` here.
