### ISSUE TITLE
Use `clippy::exit`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3233]
Implement [`clippy::exit`](https://rust-lang.github.io/rust-clippy/master/#exit).

> ### What it does
> 
> exit() terminates the program and doesn’t provide a stack trace.
>
> ### Why is this bad?
> 
> Ideally a program is terminated by finishing the main function.

Without a stack trace and the program converging on main it can become difficult to track down errors and understand the flow of the program. 

[The standard library documentation](https://doc.rust-lang.org/stable/std/process/fn.exit.html) also notes:

> preferably, simply return a type implementing [Termination](https://doc.rust-lang.org/stable/std/process/trait.Termination.html) (such as [ExitCode](https://doc.rust-lang.org/stable/std/process/struct.ExitCode.html) or Result) from the main function and avoid this function altogether:

**Comment by dhruvsethi227** [comment]
Hello, my name is Dhruv and I am a senior computer science student at UT Austin. My group and I were wondering if we could tackle this issue as part of our virtualization class assignment.

**Comment by JonathanWoollett-Light** [comment]
If you could contribute on this issue that would be great! We always appreciate contribution so feel free to do so.

I would note that among the issues tagged with `Contribute: Good First Issue` this is likely to be one of the more difficult ones.

**Comment by 0xkelvin** [comment]
@JonathanWoollett-Light does anyone working on this, otherwise i can take it

**Comment by JonathanWoollett-Light** [comment]
@0xkelvin Your contribution would be awesome, you should always feel free to contribute on open issues, you don't need to ask.
