### ISSUE TITLE
Use `core::arch::x86_64::has_cpuid`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3271]
It would be preferable to use the more general [`core::arch::x86_64::has_cpuid`](https://doc.rust-lang.org/core/arch/x86_64/fn.has_cpuid.html) to check for CPUID support.

Blocked on: https://github.com/rust-lang/rust/issues/48556

**Comment by roypat** [comment]
Mh, the rust-lang issue you linked is blocked, and it seems that there is some bug marking the cpuid function as nightly even though it should be stable https://github.com/rust-lang/rust/issues/98253

**Comment by roypat** [comment]
The issue tracking this on rust's side has yet again changed: https://github.com/rust-lang/rust/issues/60123

**Comment by roypat** [comment]
That being said, [Wikipedia](https://en.wikipedia.org/wiki/CPUID) has this to say about the `cpuid` instruction: 
> It was introduced by [Intel](https://en.wikipedia.org/wiki/Intel) in 1993 with the launch of the [Pentium](https://en.wikipedia.org/wiki/Pentium) and [SL-enhanced 486](https://en.wikipedia.org/wiki/SL-enhanced_486) processors.[[1]](https://en.wikipedia.org/wiki/CPUID#cite_note-1)

And it also seems that either x86_64 CPUs without CPUID support don't exist, or even the linux kernel wouldn't work on them (https://www.geoffchappell.com/studies/windows/km/cpu/cpuid/index.htm), so why do we need to ever do such a check in the first place? :thinking:

**Comment by workingjubilee** [comment]
You probably do not, and if you ever did want to actually know about the CPU's cpuid support, you would want to also ask questions about e.g. whether the `cpuid_fault` feature exists, or else it would be a dangerously incomplete answer. This is why `has_cpuid` is a bad function: it provides a useless answer to a useless question.

**Comment by roypat** [comment]
Hi @workingjubilee, 
thanks for your input! I agree that this is not a question that makes sense for us to ask. We have a clearly defined set of supported architectures, and all of those have the cpuid instruction. But even beyond that, Firecracker, being a virtual machine manager, needs VMX on Intel, which is even newer than CPUID. So lots of things would go wrong before we even hit a CPUID instruction in the first place (not that I can even find a single call to `__cpuid` in our code anyway. I am assuming KVM internally uses it). I also see now a comment on rust-lang/rust#60123 from a few days ago that Rust doesn't have targets without CPUID anymore. Yet another reason why Firecracker cannot work on such platforms. 

So I am going ahead with closing this issue :)
