### ISSUE TITLE
Update all error structs/enums to use `thiserror::Error`

### ISSUE THREAD

**Issue by ShadowCurse** [firecracker-microvm/firecracker#3278]
Currently most error enums in Firecracker use `thiserror::Error` to automatically implement `Error` and `Display` and `From` traits. 
But there are some that still don't use `thiserror` and have 50+ lines of implementations of `Display` trait or use `derive_more::From`

The goal of this issue is to make all Error structs/enums in Firecracker uniform.

**Comment by pb8o** [comment]
Some work in this regard is ongoing.

**Comment by roypat** [comment]
Note that when a manual implementation of `Display` is changed to one derived by `thiserror`, tests that only exist to mark the manual `Display` implementation as covered from a code coverage standpoint (such as [this one](https://github.com/firecracker-microvm/firecracker/blob/27b1c94d925d48e5bcc1cdc76e9889ab24366689/src/vmm/src/builder.rs#L1617-L1651)) should be removed, as grcov will not consider proc-macro generated code, and proc-macro processed attributes in its coverage reports

**Comment by sri-srikanth** [comment]
Hey!
I am a Computer Science student at the University of Texas at Austin taking a Virtualization course. My two groupmates and I were wondering if we could contribute to resolving this issue. Please let me know if this would be possible and we can get started.

**Comment by ShadowCurse** [comment]
Hi @sri-srikanth, you are welcome to work on this issue.
