### ISSUE TITLE
[Upstream] `atty` crate has unsoundness bug

### ISSUE THREAD

**Issue by roypat** [firecracker-microvm/firecracker#3284]
This issues tracks the effort of our upstream dependencies to resolve [RUSTSEC-2021-0145](https://rustsec.org/advisories/RUSTSEC-2021-0145.html). We transitively depend on `atty` through `criterion`, where the fix is implemented https://github.com/bheisler/criterion.rs/pull/628. Once this PR is merged, we can revert https://github.com/firecracker-microvm/firecracker/pull/3283 and properly fix the warning by updating criterion.

**Comment by zulinx86** [comment]
Since we backported the fix in #3282 on v1.1, we need to revert this on v1.1 as well.
Let me leave this comment not to forget it.

**Comment by roypat** [comment]
Same thing for 1.0 (via https://github.com/firecracker-microvm/firecracker/pull/3288)

**Comment by roypat** [comment]
The PR fixing this in criterion.rs just got merged!
