### ISSUE TITLE
[Local Dev Env] musl-gcc build error: unrecognized command-line option '-m64'

### ISSUE THREAD

**Issue by ls-ivan-kiselev** [firecracker-microvm/firecracker#3337]
Hello!

Trying to develop around firecracker locally, `tools/devtool build` works just fine, but VS Code rust-analyzer (and so as `cargo build`) fails:

```
  TARGET = Some("x86_64-unknown-linux-musl")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-musl
  CC_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_musl
  CC_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-musl
  CFLAGS_x86_64-unknown-linux-musl = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_musl
  CFLAGS_x86_64_unknown_linux_musl = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "musl-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/ec2-user/git/firecracker/build/cargo_target/x86_64-unknown-linux-musl/debug/build/userfaultfd-sys-34c155e861f988a8/out/src/consts.o" "-c" "src/consts.c"
  cargo:warning=cc1: error: unrecognized command-line option '-m64'
  exit status: 1
```
I have installed the latest version of `musl-gcc` (1.2.3) as described [here](https://www.musl-libc.org/how.html).

My host:
```
$ musl-gcc --version
gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)

$ uname -r
5.15.73-45.135.amzn2022.aarch64

$ rustc --version
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

There is some [advice on StackOverflow](https://stackoverflow.com/questions/58244095/gcc-7-error-unrecognized-command-line-option-m64) in regard to this error, but the project is fairly complex and I struggle a little bit to understand where exactly to apply them within the code and it's fairly hard to get my feet wet with firecracker without the help of rust-analyzer :)

Any hints would be appreciated, thanks!

Edit: The issue is fairly reproducible by setting up a fresh dev environment as described and just trying `cargo build`

**Comment by pb8o** [comment]
It looks like you are trying to cross-compile Firecracker? What happens if you set the target to x86_64?

```
  TARGET = Some("x86_64-unknown-linux-musl")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-unknown-linux-gnu")
```

**Comment by pb8o** [comment]
Also this may be due to #3221

**Comment by ls-ivan-kiselev** [comment]
Yeah, I figured as much that by default `cargo build` tries to compile to `x86_64-unknown-linux-musl` whatever the host is, for the reason described in https://github.com/firecracker-microvm/firecracker/issues/3221, so it is totally a duplicate, I'd presume.

**Comment by ls-ivan-kiselev** [comment]
Closing the issue due to the previous comment, thanks.
