### ISSUE TITLE
Use `split_array_ref`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3347]
Use [`<[T; N]>::split_array_ref`](https://doc.rust-lang.org/std/primitive.array.html#method.split_array_ref) to improve `src/cpuid/src/intel/mod.rs` `IntelCpuid::default_brand_string`.

Blocked on https://github.com/rust-lang/rust/issues/90091

**Comment by 0xkelvin** [comment]
can i take this @JonathanWoollett-Light

**Comment by JonathanWoollett-Light** [comment]
@0xkelvin This issue cannot be closed or worked on until https://github.com/rust-lang/rust/issues/90091 is closed and [`<[T; N]>::split_array_ref`](https://doc.rust-lang.org/std/primitive.array.html#method.split_array_ref) is stabilized.

**Comment by 0xkelvin** [comment]
i see

**Comment by roypat** [comment]
Hey Jonathan, I've had a look at the `default_brand_string` function, and I honestly don't see where we could use `split_array_ref` in it, even if it were stabilized (and actually it seems like `split_array_ref` got removed altogether in https://github.com/rust-lang/rust/pull/117561). 

So I'm closing this for now. Please feel free to reopen if you still think there's a refactor possible in `default_brand_string`
