### ISSUE TITLE
[Feature Request] Update gettings started scripts with last version of curl

### ISSUE THREAD

**Issue by kalil-pelissier** [firecracker-microvm/firecracker#3395]
# Feature Request

The script example provided in the `getting-started.md` file for the call of the firecracker unix socket is no longer working with the last version of curl (7.85.0).
It seems this problem is related to this [issue](https://github.com/curl/curl/issues/936).

## Describe the desired solution

I fixed this issue with the following changes:
```sh
# Current script
curl --unix-socket /tmp/firecracker.socket  -i \
  -X PUT "http://localhost/actions" ...

---

# Solution
curl --unix-socket /tmp/firecracker.socket http://localhost/actions -i \
  # Move URL before HTTP verb. 
  -X PUT ...
```

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by kalil-pelissier** [comment]
Hi :smiley:,
I'm new to the firecracker project and very interested in it!
I hope this first issue will be a simple but good getting-started point on the project.

**Comment by dianpopa** [comment]
Hi @kalil-pelissier,

Welcome to Firecracker! Thanks for the interest! 
Your proposal sounds good to you. I was just interested whether this would be a backwards compatible change (i.e user not running with latest version of curl will still have successful API triggers?).

Thanks!

**Comment by kalil-pelissier** [comment]
Hi @dianpopa ,
I tried to reproduce the bug without succeeding (maybe a miss configuration last time I created the PR).
Nevertheless, the two syntaxes seem to work with version `7.85.X` and less (I tried with `7.74`).
So I think that this PR will not be my first contribution to Firecracker, sorry about the disturbance.

**Comment by dianpopa** [comment]
Thanks for getting back @kalil-pelissier ! As far as my understanding, we can close the issue for now.
