### ISSUE TITLE
[Bug] Boot-timer and metrics file results in empty

### ISSUE THREAD

**Issue by ProMCProgramer** [firecracker-microvm/firecracker#3396]
# Describe the bug

I use the api to create the microvm. I start the firecracker process with the --boot-timer option. 
Calling the api's for metrics and logs, with following:
Logger: `{
        "log_path": "./logs.txt",
        "level": "Info",
        "show_level": false,
        "show_log_origin": false,

    }`
Metrics`{
        "metrics_path": "./metrics.log",
    }`,
Using the tutorial kernel and the tutorial Filesystem.

Trying to get some metrics about the startup time.

But the result of the metrics file is following:
`{"utc_timestamp_ms":1674720996721,"api_server":{"process_startup_time_us":0,"process_startup_time_cpu_us":0,"sync_response_fails":0,"sync_vmm_send_timeout_count":0},"balloon":{"activate_fails":0,"inflate_count":0,"stats_updates_count":0,"stats_update_fails":0,"deflate_count":0,"event_fails":0},"block":{"activate_fails":0,"cfg_fails":0,"no_avail_buffer":0,"event_fails":0,"execute_fails":0,"invalid_reqs_count":0,"flush_count":0,"queue_event_count":0,"rate_limiter_event_count":0,"update_count":0,"update_fails":0,"read_bytes":0,"write_bytes":0,"read_count":0,"write_count":0,"rate_limiter_throttled_events":0,"io_engine_throttled_events":0},"deprecated_api":{"deprecated_http_api_calls":0,"deprecated_cmd_line_api_calls":0},"get_api_requests":{"instance_info_count":0,"machine_cfg_count":0,"mmds_count":0,"vmm_version_count":0},"i8042":{"error_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":0,"reset_count":0,"write_count":0},"latencies_us":{"full_create_snapshot":0,"diff_create_snapshot":0,"load_snapshot":0,"pause_vm":0,"resume_vm":0,"vmm_full_create_snapshot":0,"vmm_diff_create_snapshot":0,"vmm_load_snapshot":0,"vmm_pause_vm":0,"vmm_resume_vm":0},"logger":{"missed_metrics_count":0,"metrics_fails":0,"missed_log_count":0,"log_fails":0},"mmds":{"rx_accepted":0,"rx_accepted_err":0,"rx_accepted_unusual":0,"rx_bad_eth":0,"rx_count":0,"tx_bytes":0,"tx_count":0,"tx_errors":0,"tx_frames":0,"connections_created":0,"connections_destroyed":0},"net":{"activate_fails":0,"cfg_fails":0,"mac_address_updates":0,"no_rx_avail_buffer":0,"no_tx_avail_buffer":0,"event_fails":0,"rx_queue_event_count":0,"rx_event_rate_limiter_count":0,"rx_partial_writes":0,"rx_rate_limiter_throttled":0,"rx_tap_event_count":0,"rx_bytes_count":0,"rx_packets_count":0,"rx_fails":0,"rx_count":0,"tap_read_fails":0,"tap_write_fails":0,"tx_bytes_count":0,"tx_malformed_frames":0,"tx_fails":0,"tx_count":0,"tx_packets_count":0,"tx_partial_reads":0,"tx_queue_event_count":0,"tx_rate_limiter_event_count":0,"tx_rate_limiter_throttled":0,"tx_spoofed_mac_count":0},"patch_api_requests":{"drive_count":0,"drive_fails":0,"network_count":0,"network_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"mmds_count":0,"mmds_fails":0},"put_api_requests":{"actions_count":1,"actions_fails":0,"boot_source_count":1,"boot_source_fails":0,"drive_count":1,"drive_fails":0,"logger_count":1,"logger_fails":0,"machine_cfg_count":1,"machine_cfg_fails":0,"metrics_count":1,"metrics_fails":0,"network_count":1,"network_fails":0,"mmds_count":0,"mmds_fails":0,"vsock_count":0,"vsock_fails":0},"seccomp":{"num_faults":0},"vcpu":{"exit_io_in":0,"exit_io_out":0,"exit_mmio_read":0,"exit_mmio_write":0,"failures":0,"filter_cpuid":0},"vmm":{"device_events":0,"panic_count":0},"uart":{"error_count":0,"flush_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":0,"write_count":0},"signals":{"sigbus":0,"sigsegv":0,"sigxfsz":0,"sigxcpu":0,"sigpipe":0,"sighup":0,"sigill":0},"vsock":{"activate_fails":0,"cfg_fails":0,"rx_queue_event_fails":0,"tx_queue_event_fails":0,"ev_queue_event_fails":0,"muxer_event_fails":0,"conn_event_fails":0,"rx_queue_event_count":0,"tx_queue_event_count":0,"rx_bytes_count":0,"tx_bytes_count":0,"rx_packets_count":0,"tx_packets_count":0,"conns_added":0,"conns_killed":0,"conns_removed":0,"killq_resync":0,"tx_flush_fails":0,"tx_write_fails":0,"rx_read_fails":0}}
{"utc_timestamp_ms":1674721056721,"api_server":{"process_startup_time_us":0,"process_startup_time_cpu_us":0,"sync_response_fails":0,"sync_vmm_send_timeout_count":0},"balloon":{"activate_fails":0,"inflate_count":0,"stats_updates_count":0,"stats_update_fails":0,"deflate_count":0,"event_fails":0},"block":{"activate_fails":0,"cfg_fails":0,"no_avail_buffer":0,"event_fails":0,"execute_fails":0,"invalid_reqs_count":0,"flush_count":0,"queue_event_count":4090,"rate_limiter_event_count":0,"update_count":0,"update_fails":0,"read_bytes":200997888,"write_bytes":19361792,"read_count":13446,"write_count":1755,"rate_limiter_throttled_events":0,"io_engine_throttled_events":0},"deprecated_api":{"deprecated_http_api_calls":0,"deprecated_cmd_line_api_calls":0},"get_api_requests":{"instance_info_count":0,"machine_cfg_count":0,"mmds_count":0,"vmm_version_count":0},"i8042":{"error_count":0,"missed_read_count":0,"missed_write_count":6,"read_count":362,"reset_count":0,"write_count":123},"latencies_us":{"full_create_snapshot":0,"diff_create_snapshot":0,"load_snapshot":0,"pause_vm":0,"resume_vm":0,"vmm_full_create_snapshot":0,"vmm_diff_create_snapshot":0,"vmm_load_snapshot":0,"vmm_pause_vm":0,"vmm_resume_vm":0},"logger":{"missed_metrics_count":0,"metrics_fails":0,"missed_log_count":0,"log_fails":0},"mmds":{"rx_accepted":0,"rx_accepted_err":0,"rx_accepted_unusual":0,"rx_bad_eth":0,"rx_count":0,"tx_bytes":0,"tx_count":0,"tx_errors":0,"tx_frames":0,"connections_created":0,"connections_destroyed":0},"net":{"activate_fails":0,"cfg_fails":0,"mac_address_updates":0,"no_rx_avail_buffer":3,"no_tx_avail_buffer":0,"event_fails":0,"rx_queue_event_count":4,"rx_event_rate_limiter_count":0,"rx_partial_writes":0,"rx_rate_limiter_throttled":0,"rx_tap_event_count":21,"rx_bytes_count":3032,"rx_packets_count":23,"rx_fails":0,"rx_count":69,"tap_read_fails":0,"tap_write_fails":0,"tx_bytes_count":3204,"tx_malformed_frames":0,"tx_fails":0,"tx_count":36,"tx_packets_count":18,"tx_partial_reads":0,"tx_queue_event_count":18,"tx_rate_limiter_event_count":0,"tx_rate_limiter_throttled":0,"tx_spoofed_mac_count":0},"patch_api_requests":{"drive_count":0,"drive_fails":0,"network_count":0,"network_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"mmds_count":0,"mmds_fails":0},"put_api_requests":{"actions_count":0,"actions_fails":0,"boot_source_count":0,"boot_source_fails":0,"drive_count":0,"drive_fails":0,"logger_count":0,"logger_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"metrics_count":0,"metrics_fails":0,"network_count":0,"network_fails":0,"mmds_count":0,"mmds_fails":0,"vsock_count":0,"vsock_fails":0},"seccomp":{"num_faults":0},"vcpu":{"exit_io_in":24602,"exit_io_out":29400,"exit_mmio_read":6300,"exit_mmio_write":6307,"failures":0,"filter_cpuid":0},"vmm":{"device_events":0,"panic_count":0},"uart":{"error_count":0,"flush_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":445,"write_count":24712},"signals":{"sigbus":0,"sigsegv":0,"sigxfsz":0,"sigxcpu":0,"sigpipe":0,"sighup":0,"sigill":0},"vsock":{"activate_fails":0,"cfg_fails":0,"rx_queue_event_fails":0,"tx_queue_event_fails":0,"ev_queue_event_fails":0,"muxer_event_fails":0,"conn_event_fails":0,"rx_queue_event_count":0,"tx_queue_event_count":0,"rx_bytes_count":0,"tx_bytes_count":0,"rx_packets_count":0,"tx_packets_count":0,"conns_added":0,"conns_killed":0,"conns_removed":0,"killq_resync":0,"tx_flush_fails":0,"tx_write_fails":0,"rx_read_fails":0}}
{"utc_timestamp_ms":1674721116721,"api_server":{"process_startup_time_us":0,"process_startup_time_cpu_us":0,"sync_response_fails":0,"sync_vmm_send_timeout_count":0},"balloon":{"activate_fails":0,"inflate_count":0,"stats_updates_count":0,"stats_update_fails":0,"deflate_count":0,"event_fails":0},"block":{"activate_fails":0,"cfg_fails":0,"no_avail_buffer":0,"event_fails":0,"execute_fails":0,"invalid_reqs_count":0,"flush_count":0,"queue_event_count":106,"rate_limiter_event_count":0,"update_count":0,"update_fails":0,"read_bytes":4415488,"write_bytes":1261568,"read_count":271,"write_count":144,"rate_limiter_throttled_events":0,"io_engine_throttled_events":0},"deprecated_api":{"deprecated_http_api_calls":0,"deprecated_cmd_line_api_calls":0},"get_api_requests":{"instance_info_count":0,"machine_cfg_count":0,"mmds_count":0,"vmm_version_count":0},"i8042":{"error_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":0,"reset_count":0,"write_count":0},"latencies_us":{"full_create_snapshot":0,"diff_create_snapshot":0,"load_snapshot":0,"pause_vm":0,"resume_vm":0,"vmm_full_create_snapshot":0,"vmm_diff_create_snapshot":0,"vmm_load_snapshot":0,"vmm_pause_vm":0,"vmm_resume_vm":0},"logger":{"missed_metrics_count":0,"metrics_fails":0,"missed_log_count":0,"log_fails":0},"mmds":{"rx_accepted":0,"rx_accepted_err":0,"rx_accepted_unusual":0,"rx_bad_eth":0,"rx_count":0,"tx_bytes":0,"tx_count":0,"tx_errors":0,"tx_frames":0,"connections_created":0,"connections_destroyed":0},"net":{"activate_fails":0,"cfg_fails":0,"mac_address_updates":0,"no_rx_avail_buffer":0,"no_tx_avail_buffer":0,"event_fails":0,"rx_queue_event_count":0,"rx_event_rate_limiter_count":0,"rx_partial_writes":0,"rx_rate_limiter_throttled":0,"rx_tap_event_count":1,"rx_bytes_count":99,"rx_packets_count":1,"rx_fails":0,"rx_count":3,"tap_read_fails":0,"tap_write_fails":0,"tx_bytes_count":426,"tx_malformed_frames":0,"tx_fails":0,"tx_count":4,"tx_packets_count":2,"tx_partial_reads":0,"tx_queue_event_count":2,"tx_rate_limiter_event_count":0,"tx_rate_limiter_throttled":0,"tx_spoofed_mac_count":0},"patch_api_requests":{"drive_count":0,"drive_fails":0,"network_count":0,"network_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"mmds_count":0,"mmds_fails":0},"put_api_requests":{"actions_count":0,"actions_fails":0,"boot_source_count":0,"boot_source_fails":0,"drive_count":0,"drive_fails":0,"logger_count":0,"logger_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"metrics_count":0,"metrics_fails":0,"network_count":0,"network_fails":0,"mmds_count":0,"mmds_fails":0,"vsock_count":0,"vsock_fails":0},"seccomp":{"num_faults":0},"vcpu":{"exit_io_in":5439,"exit_io_out":22159,"exit_mmio_read":186,"exit_mmio_write":186,"failures":0,"filter_cpuid":0},"vmm":{"device_events":0,"panic_count":0},"uart":{"error_count":0,"flush_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":581,"write_count":20565},"signals":{"sigbus":0,"sigsegv":0,"sigxfsz":0,"sigxcpu":0,"sigpipe":0,"sighup":0,"sigill":0},"vsock":{"activate_fails":0,"cfg_fails":0,"rx_queue_event_fails":0,"tx_queue_event_fails":0,"ev_queue_event_fails":0,"muxer_event_fails":0,"conn_event_fails":0,"rx_queue_event_count":0,"tx_queue_event_count":0,"rx_bytes_count":0,"tx_bytes_count":0,"rx_packets_count":0,"tx_packets_count":0,"conns_added":0,"conns_killed":0,"conns_removed":0,"killq_resync":0,"tx_flush_fails":0,"tx_write_fails":0,"rx_read_fails":0}}
{"utc_timestamp_ms":1674721176721,"api_server":{"process_startup_time_us":0,"process_startup_time_cpu_us":0,"sync_response_fails":0,"sync_vmm_send_timeout_count":0},"balloon":{"activate_fails":0,"inflate_count":0,"stats_updates_count":0,"stats_update_fails":0,"deflate_count":0,"event_fails":0},"block":{"activate_fails":0,"cfg_fails":0,"no_avail_buffer":0,"event_fails":0,"execute_fails":0,"invalid_reqs_count":0,"flush_count":0,"queue_event_count":1,"rate_limiter_event_count":0,"update_count":0,"update_fails":0,"read_bytes":0,"write_bytes":20480,"read_count":0,"write_count":5,"rate_limiter_throttled_events":0,"io_engine_throttled_events":0},"deprecated_api":{"deprecated_http_api_calls":0,"deprecated_cmd_line_api_calls":0},"get_api_requests":{"instance_info_count":0,"machine_cfg_count":0,"mmds_count":0,"vmm_version_count":0},"i8042":{"error_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":0,"reset_count":0,"write_count":0},"latencies_us":{"full_create_snapshot":0,"diff_create_snapshot":0,"load_snapshot":0,"pause_vm":0,"resume_vm":0,"vmm_full_create_snapshot":0,"vmm_diff_create_snapshot":0,"vmm_load_snapshot":0,"vmm_pause_vm":0,"vmm_resume_vm":0},"logger":{"missed_metrics_count":0,"metrics_fails":0,"missed_log_count":0,"log_fails":0},"mmds":{"rx_accepted":0,"rx_accepted_err":0,"rx_accepted_unusual":0,"rx_bad_eth":0,"rx_count":0,"tx_bytes":0,"tx_count":0,"tx_errors":0,"tx_frames":0,"connections_created":0,"connections_destroyed":0},"net":{"activate_fails":0,"cfg_fails":0,"mac_address_updates":0,"no_rx_avail_buffer":0,"no_tx_avail_buffer":0,"event_fails":0,"rx_queue_event_count":1,"rx_event_rate_limiter_count":0,"rx_partial_writes":0,"rx_rate_limiter_throttled":0,"rx_tap_event_count":5,"rx_bytes_count":1007,"rx_packets_count":5,"rx_fails":0,"rx_count":15,"tap_read_fails":0,"tap_write_fails":0,"tx_bytes_count":426,"tx_malformed_frames":0,"tx_fails":0,"tx_count":4,"tx_packets_count":2,"tx_partial_reads":0,"tx_queue_event_count":2,"tx_rate_limiter_event_count":0,"tx_rate_limiter_throttled":0,"tx_spoofed_mac_count":0},"patch_api_requests":{"drive_count":0,"drive_fails":0,"network_count":0,"network_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"mmds_count":0,"mmds_fails":0},"put_api_requests":{"actions_count":0,"actions_fails":0,"boot_source_count":0,"boot_source_fails":0,"drive_count":0,"drive_fails":0,"logger_count":0,"logger_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"metrics_count":0,"metrics_fails":0,"network_count":0,"network_fails":0,"mmds_count":0,"mmds_fails":0,"vsock_count":0,"vsock_fails":0},"seccomp":{"num_faults":0},"vcpu":{"exit_io_in":0,"exit_io_out":0,"exit_mmio_read":8,"exit_mmio_write":8,"failures":0,"filter_cpuid":0},"vmm":{"device_events":0,"panic_count":0},"uart":{"error_count":0,"flush_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":0,"write_count":0},"signals":{"sigbus":0,"sigsegv":0,"sigxfsz":0,"sigxcpu":0,"sigpipe":0,"sighup":0,"sigill":0},"vsock":{"activate_fails":0,"cfg_fails":0,"rx_queue_event_fails":0,"tx_queue_event_fails":0,"ev_queue_event_fails":0,"muxer_event_fails":0,"conn_event_fails":0,"rx_queue_event_count":0,"tx_queue_event_count":0,"rx_bytes_count":0,"tx_bytes_count":0,"rx_packets_count":0,"tx_packets_count":0,"conns_added":0,"conns_killed":0,"conns_removed":0,"killq_resync":0,"tx_flush_fails":0,"tx_write_fails":0,"rx_read_fails":0}}
{"utc_timestamp_ms":1674721236721,"api_server":{"process_startup_time_us":0,"process_startup_time_cpu_us":0,"sync_response_fails":0,"sync_vmm_send_timeout_count":0},"balloon":{"activate_fails":0,"inflate_count":0,"stats_updates_count":0,"stats_update_fails":0,"deflate_count":0,"event_fails":0},"block":{"activate_fails":0,"cfg_fails":0,"no_avail_buffer":0,"event_fails":0,"execute_fails":0,"invalid_reqs_count":0,"flush_count":0,"queue_event_count":8,"rate_limiter_event_count":0,"update_count":0,"update_fails":0,"read_bytes":8192,"write_bytes":122880,"read_count":2,"write_count":30,"rate_limiter_throttled_events":0,"io_engine_throttled_events":0},"deprecated_api":{"deprecated_http_api_calls":0,"deprecated_cmd_line_api_calls":0},"get_api_requests":{"instance_info_count":0,"machine_cfg_count":0,"mmds_count":0,"vmm_version_count":0},"i8042":{"error_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":0,"reset_count":0,"write_count":0},"latencies_us":{"full_create_snapshot":0,"diff_create_snapshot":0,"load_snapshot":0,"pause_vm":0,"resume_vm":0,"vmm_full_create_snapshot":0,"vmm_diff_create_snapshot":0,"vmm_load_snapshot":0,"vmm_pause_vm":0,"vmm_resume_vm":0},"logger":{"missed_metrics_count":0,"metrics_fails":0,"missed_log_count":0,"log_fails":0},"mmds":{"rx_accepted":0,"rx_accepted_err":0,"rx_accepted_unusual":0,"rx_bad_eth":0,"rx_count":0,"tx_bytes":0,"tx_count":0,"tx_errors":0,"tx_frames":0,"connections_created":0,"connections_destroyed":0},"net":{"activate_fails":0,"cfg_fails":0,"mac_address_updates":0,"no_rx_avail_buffer":0,"no_tx_avail_buffer":0,"event_fails":0,"rx_queue_event_count":0,"rx_event_rate_limiter_count":0,"rx_partial_writes":0,"rx_rate_limiter_throttled":0,"rx_tap_event_count":0,"rx_bytes_count":0,"rx_packets_count":0,"rx_fails":0,"rx_count":0,"tap_read_fails":0,"tap_write_fails":0,"tx_bytes_count":344,"tx_malformed_frames":0,"tx_fails":0,"tx_count":2,"tx_packets_count":1,"tx_partial_reads":0,"tx_queue_event_count":1,"tx_rate_limiter_event_count":0,"tx_rate_limiter_throttled":0,"tx_spoofed_mac_count":0},"patch_api_requests":{"drive_count":0,"drive_fails":0,"network_count":0,"network_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"mmds_count":0,"mmds_fails":0},"put_api_requests":{"actions_count":0,"actions_fails":0,"boot_source_count":0,"boot_source_fails":0,"drive_count":0,"drive_fails":0,"logger_count":0,"logger_fails":0,"machine_cfg_count":0,"machine_cfg_fails":0,"metrics_count":0,"metrics_fails":0,"network_count":0,"network_fails":0,"mmds_count":0,"mmds_fails":0,"vsock_count":0,"vsock_fails":0},"seccomp":{"num_faults":0},"vcpu":{"exit_io_in":293,"exit_io_out":453,"exit_mmio_read":9,"exit_mmio_write":9,"failures":0,"filter_cpuid":0},"vmm":{"device_events":0,"panic_count":0},"uart":{"error_count":0,"flush_count":0,"missed_read_count":0,"missed_write_count":0,"read_count":14,"write_count":317},"signals":{"sigbus":0,"sigsegv":0,"sigxfsz":0,"sigxcpu":0,"sigpipe":0,"sighup":0,"sigill":0},"vsock":{"activate_fails":0,"cfg_fails":0,"rx_queue_event_fails":0,"tx_queue_event_fails":0,"ev_queue_event_fails":0,"muxer_event_fails":0,"conn_event_fails":0,"rx_queue_event_count":0,"tx_queue_event_count":0,"rx_bytes_count":0,"tx_bytes_count":0,"rx_packets_count":0,"tx_packets_count":0,"conns_added":0,"conns_killed":0,"conns_removed":0,"killq_resync":0,"tx_flush_fails":0,"tx_write_fails":0,"rx_read_fails":0}}
}
`

As seen it is 0.

As far as I understood your documentation, you do not describe how to got this values to work. And the boot-timer option does also not result in this?

How do I get some startup time and metrics out of firecracker?

## Expected behaviour

I expect to get a boot-time value instead of 0. The documentation is not complete.

## Environment

`[firecracker 1.1.2 ]`
Tutorial kernel / Tutorial rootfs
x86-64 architecture - Ubuntu 22.04

## Checks

- [x ] Have you searched the Firecracker Issues database for similar problems?
- [ x] Have you read the existing relevant Firecracker documentation?
- [x ] Are you certain the bug being reported is a Firecracker issue?

**Comment by simonis** [comment]
You have to trigger the creation of the timestamp from within the VM as described here: https://github.com/firecracker-microvm/firecracker/blob/main/resources/tests/init.c

Notice that you can do this several times from within the VM to get the time since the VM was booted.

**Comment by dianpopa** [comment]
Hi!

Boot timer is not related to `process_startup_time_us`. Boot timer measures time from `InstanceStart` till guest init. `process_startup_time_us` measures how much it takes for Firecracker to start (from moment the process is executed till socket bind).

What exactly are you interested in? What documentation you were using?

**Comment by dianpopa** [comment]
@ProMCProgramer in order to retrieve the guest boot time with with the `--boot-timer` option, you need to look in the log file (not the metrics file) for a string that starts with this: `Guest-boot-time`. You find info on how to configure a log file here: https://github.com/firecracker-microvm/firecracker/blob/main/docs/logger.md.

If you need more info on this, feel free to re-open. Thanks!
