### ISSUE TITLE
Move `src/vm-memory` under `src/utils`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#3408]
Remove `src/vm-memory` and move the functionality under `src/utils`.

**Comment by roypat** [comment]
I have a branch locally where I made this change, let me rebase and make a PR

**Comment by joannejchen** [comment]
Hi, I'm a student taking a virtualization course at the University of Texas at Austin. My partner (@scotran) and I would like to try to take up this issue.

**Comment by OLUWAMUYIWA** [comment]
I'm interested in working on this issue.

**Comment by aaqaishtyaq** [comment]
Hey. Can I pick this up?

**Comment by JonathanWoollett-Light** [comment]
@aaqaishtyaq Contribution would be really appreciated here, you should always feel free to contribute on open issues, you don't need to ask.
