### ISSUE TITLE
Kernel 6.1 support?

### ISSUE THREAD

**Issue by krk** [firecracker-microvm/firecracker#3426]
Now that the kernel 6.1 is marked as LTS, I was wondering what the plan is for its support: https://kernel.org/category/releases.html

[kernel-policy](https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md) mentions 4.14 and 5.10 would be supported in 2022.

**Comment by xmarcalx** [comment]
Hi @krk ,

Thanks for the question. 
Yes as specified in the kernel policy as well "every year we are considering for enablement the latest LTS version" and therefore we will look into support kernel 6.1 too along this year 😃 

Hope it helps!

**Comment by xmarcalx** [comment]
I see the author acknowledged the message therefore closing this issue.
In general, feel free to post questions in the "Discussions" functionality as well in our slack channel :)
