### ISSUE TITLE
[Bug] Could not create Network Device: TapOpen(IoctlError(Os { code: 16, kind: ResourceBusy

### ISSUE THREAD

**Issue by tamalsaha** [firecracker-microvm/firecracker#3465]
# Describe the bug

I am using firecracker to run VMs for GH actions. I have using 2 TAP devices (eth0 for MMDS, eth1 for internet). I see that occasionally firecracker will report `Resource Busy` when starting VMs. See logs below:

```
Feb 21 15:23:45 gha-0 gh-ci-hostctl[53958]: time="2023-02-21T15:23:45Z" level=debug msg="PUT /network-interfaces/eth0 HTTP/1.1\r\nHost: localhost\r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 74\r\nAccept: application/json\r\nContent-Type: application/json\r\nAccept-Encoding: gzip\r\n\r\n{\"guest_mac\":\"AA:FC:ac:1a:00:01\",\"host_dev_name\":\"fc1\",\"iface_id\":\"eth0\"}\n\n"
Feb 21 15:23:45 gha-0 gh-ci-hostctl[53958]: time="2023-02-21T15:23:45Z" level=debug msg="HTTP/1.1 400 \r\nContent-Length: 137\r\nConnection: keep-alive\r\nContent-Type: application/json\r\nServer: Firecracker API\r\n\r\n{\"fault_message\":\"Could not create Network Device: TapOpen(IoctlError(Os { code: 16, kind: ResourceBusy, message: \\\"Resource busy\\\" }))\"}\n"
Feb 21 15:23:45 gha-0 gh-ci-hostctl[53958]: time="2023-02-21T15:23:45Z" level=debug msg="createNetworkInterface returned for fc1"
Feb 21 15:23:45 gha-0 gh-ci-hostctl[53958]: time="2023-02-21T15:23:45Z" level=warning msg="Failed handler \"fcinit.CreateNetworkInterfaces\": [PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:Could not create Network Device: TapOpen(IoctlError(Os { code: 16, kind: ResourceBusy, message: \"Resource busy\" }))}"
Feb 21 15:23:45 gha-0 gh-ci-hostctl[53958]: E0221 15:23:45.786421   53958 stream.go:190] failed to process payload for event gh-walker-firewalk-4234182008-build-1: [PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:Could not create Network Device: TapOpen(IoctlError(Os { code: 16, kind: ResourceBusy, message: "Resource busy" }))}
```

I don't know what causes this. I would appreciate any help regarding this.

## To Reproduce

`[Author TODO: Steps to reproduce the behaviour:]`
`[ 1. Start Firecracker via....]`
`[ 2. Configure Firecracker via....]`
`[ 3. ....]`

## Expected behaviour

`[Author TODO: A clear and concise description of what you expected to happen.]`

## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by xmarcalx** [comment]
Hi @tamalsaha, 

Please can you fill up the other section of the bug reports with the data requested? 
It will help us to understand better the context, thanks!
