### ISSUE TITLE
[Bug] Firecracker uses up 100% CPU after an upgrade from v1.1.2 to v1.3.1

### ISSUE THREAD

**Issue by gorbak25** [firecracker-microvm/firecracker#3542]
# Describe the bug

After upgrading firecracker from v1.1.2 to v1.3.1 the VMM instantly uses up 100% of the CPU while not creating an unix api socket. Firecracker eventually manages to create the socket, but it takes a few minutes. After attaching to the faulty firecracker process with `strace` it is revealed that firecracker is stuck in a loop trying to close every pid in existence:
![image](https://user-images.githubusercontent.com/1352848/226239503-4b116d7e-c786-4f93-a4c3-bd5cdd893757.png)

## To Reproduce

Run firecracker inside a privileged docker container based on `node:16-bullseye` with `/dev/kvm` mounted inside.  v1.1.2 works fine,  v1.3.1 doesn't work at all.

## Expected behaviour

The Firecracker process starts without using 100% of the CPU and creates an unix socket.

## Environment
 - Firecracker version: v1.3.1
- Host kernel: 6.1.12-arch1-1 Archlinux
- Guest kernel: 5.6
- Rootfs used: Ext4, ubuntu 22.04
- Architecture: x86_64, AMD Ryzen 9 5950X

## Additional context
I was working on my startup which is a project for creating and managing dev environments inside Firecracker Microvm's. The project works fine using firecracker v1.1.2, after I upgraded the firecracker version the project broke.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by gorbak25** [comment]
This is the offending commit: https://github.com/firecracker-microvm/firecracker/commit/f79c94d9789903aa8cb433678491cc1e3cf2c313
Turns out the limit for open FD's is pretty high in the container I've been running firecracker in.
![image](https://user-images.githubusercontent.com/1352848/226242309-e84f196b-17bc-4132-b874-2707354ce5b5.png)

**Comment by Rohan-Jagannathan** [comment]
Hello, I am representing a group of undergraduate UT Austin students aiming to contribute to open-source virtualization projects on behalf of a virtualization course. Could we have this issue assigned to us?
