### ISSUE TITLE
Unit test the jailer 

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#363]
Kcov reports 0% coverage for all the files that are jailer related.

**Comment by dianpopa** [comment]
Coverage reported for jailer crate right now: 42.6%. Not closing this issue yet since there is room for improvement, see above.
[cov.zip](https://github.com/firecracker-microvm/firecracker/files/4319390/cov.zip)

**Comment by pkj415** [comment]
Interested in working on this to ramp up on Firecracker! (Just some context - I am a graduate student at UT trying to know more about Firecracker and will be working with Xiang Gu).

Does commenting here implicitly mean this issue gets assigned to me?

**Comment by dianpopa** [comment]
Hi @pkj415 , 

Are you still interested in working on this issue? I will assign it to you after confirmation.

**Comment by pkj415** [comment]
Hi @dianpopa, yes you can assign this to me. Sorry for the delay in reply, I missed this notification somehow.

**Comment by dianpopa** [comment]
All the unit testable jailer code is covered.
