### ISSUE TITLE
[Feature Request] Support a1.metal instance for dev environment

### ISSUE THREAD

**Issue by cm-iwata** [firecracker-microvm/firecracker#3651]
# Feature Request

I'm working on resolving #3278, and some of the code is specific to aarch64 architecture, so I need an aarch64 machine as my development environment. I set up my development environment using a1.metal instance, but the integration tests are not running due to the following error:

```
ImportError while loading conftest '/firecracker/tests/conftest.py'.
conftest.py:100: in <module>
    from framework.properties import global_props
framework/properties.py:95: in <module>
    global_props = GlobalProps()
framework/properties.py:51: in __init__
    self.cpu_model = get_cpu_model_name()
framework/utils_cpuid.py:46: in get_cpu_model_name
    return ARM_CPU_DICT[raw_cpu_model]
E   KeyError: '0xd08'
```

I check cpu info on a1.metal instance

```
cat /proc/cpuinfo | grep 'CPU part' | uniq
CPU part	: 0xd08
```

And supported CPUs are defined [here](https://github.com/firecracker-microvm/firecracker/blob/e4ec3f84ae6682bd825adf37be1d987b23c0f2c6/tests/framework/utils_cpuid.py#L13).

So `0xd08` is not support now.

## Describe the desired solution

I hope that the a1.metal instance is supported as a development environment and that integration tests can be run successfully.

## Additional context
I found several chat messages on Slack regarding the a1.metal instance.

- https://firecracker-microvm.slack.com/archives/CDL3FUR8B/p1678851573672739
- https://firecracker-microvm.slack.com/archives/CEBSNEPDX/p1676076833559409?thread_ts=1676071299.298589&cid=CEBSNEPDX

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by xmarcalx** [comment]
Hi @cm-iwata ,

thank you very much for your interest in solving issue #3278.

At the moment we have no plan to support a1.metal instances in Firecracker.
Could you run your test on a supported machine? If no, can you maybe modify the code locally to allow the test to run in your setup but not committing the change required into a PR?

Otherwise you would need to rely on our CI to validate your changes in a PR, sorry.

Thanks again for your work on Firecracker!

**Comment by cm-iwata** [comment]
@xmarcalx 
Thank you for reply

>Could you run your test on a supported machine? 

i3.metal Instance is too expensive ​:cry:​

>If no, can you maybe modify the code locally to allow the test to run in your setup but not committing the change required into a PR?

I got it.
Some test case is fail on a1.metal.
But, It is working correctly for the test case I want to check.
I'll try to work this way.

**Comment by dianpopa** [comment]
hi @cm-iwata 

It is true that our tests do not support validating Firecracker on `a1.metal` but you should be able to run Firecracker there too. We tested this a while ago :). 

I will close this one for the moment, let us know what you find out. Thanks!
