### ISSUE TITLE
[Feature Request] devtool checkenv ignore security warnings when not affected

### ISSUE THREAD

**Issue by mcenirm** [firecracker-microvm/firecracker#3739]
# Feature Request

In `devtool checkenv`, in the _Host Security Configuration_ section, improve the tests so that it does not warn about CPU vulnerabilities that do not apply to the CPU. (Not a bug, but the extra confusion seems to be counter to the purpose of `checkenv`.)

As an example, Intel-specific warnings on an AMD CPU:

* lack of L1TF mitigations
* checking for `kvm_intel` and EPT

```console
$ tools/devtool checkenv
[Firecracker devtool] Checking prerequisites for running Firecracker.
[Firecracker devtool] Please check ../docs/getting-started.md#prerequisites in case of any error.
[Firecracker devtool] Checking Host Security Configuration.
[Firecracker devtool] Please check ../docs/prod-host-setup.md in case of any error.
[Firecracker devtool] WARNING: retpoline, IBPB, IBRS: DISABLED.
[Firecracker devtool] WARNING: Mitigation: PTE Inversion: DISABLED
[Firecracker devtool] WARNING: VMX: cache flushes: DISABLED
grep: /sys/module/kvm_intel/parameters/ept: No such file or directory
[Firecracker devtool] WARNING: EPT DISABLED. Performance will be affected.
$ cat /sys/devices/system/cpu/vulnerabilities/l1tf
Not affected
$ grep 'model name' /proc/cpuinfo  | uniq
model name      : AMD EPYC 7543P 32-Core Processor
$ uname -r
5.14.0-284.11.1.el9_2.x86_64
$
```

## Describe the desired solution

Maybe test for `Not affected`?

## Describe possible alternatives

Maybe add a note about "this would not apply to an AMD CPU"?

## Additional context

n/a

## Checks

- [X] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by roypat** [comment]
Hey Michael, 

Thanks for bringing this to our attention. The command indeed seems rather stale, we'll need to update it :)

**Comment by kalyazin** [comment]
https://github.com/firecracker-microvm/firecracker/pull/3755 is merged to address that. Thanks for reporting!
