### ISSUE TITLE
 The function get_kernel_version is defined twice in two different places.

### ISSUE THREAD

**Issue by cm-iwata** [firecracker-microvm/firecracker#3751]
The function get_kernel_version is defined redundantly in two places
1. https://github.com/firecracker-microvm/firecracker/blob/69bd798b9f4e452dfcc3a9812ceff11edaa2d86e/tests/framework/properties.py#L25
2. https://github.com/firecracker-microvm/firecracker/blob/69bd798b9f4e452dfcc3a9812ceff11edaa2d86e/tests/framework/utils.py#L678

I believe these should be consolidated into one location to eliminate the duplication.

Based on my research, here is the usage of each file:

| file                                                     | import from             |
| ------------------------------------------------------------ | -------------------- |
| tests/framework/artifacts.py                                 | framework.utils      |
| tests/integration_tests/functional/test_rng.py               | framework.properties |
| tests/integration_tests/performance/conftest.py              | framework.utils      |
| tests/integration_tests/performance/test_network_latency.py  | framework.utils      |
| tests/integration_tests/functional/test_cpu_features.py      | framework.utils      |
| tests/integration_tests/performance/test_snapshot_perf.py    | framework.utils      |
| tests/integration_tests/functional/test_cpu_template_helper.py | framework.utils      |
| tests/integration_tests/performance/test_block_performance.py | framework.utils      |
| tests/integration_tests/performance/test_network_tcp_throughput.py | framework.utils      |
| tests/integration_tests/performance/test_vsock_throughput.py | framework.utils      |
| tests/integration_tests/performance/test_snapshot_restore_performance.py | framework.utils      |

If I could be in charge of refactoring, I would like to work on the following fixes

1. Remove the definition of get_kernel_version in tests/framework.properties.py.
2. Replace the usage of get_kernel_version in tests/integration_tests/functional/test_rng.py with the one defined in tests/framework.utils.py.

Is it okay to refactor like this?

**Comment by luminitavoicu** [comment]
Hi @cm-iwata, thanks for catching this! Indeed, the two functions have the same core functionality and you rightly spotted that the one in [firecracker/tests/framework/utils.py](https://github.com/firecracker-microvm/firecracker/blob/69bd798b9f4e452dfcc3a9812ceff11edaa2d86e/tests/framework/utils.py#L678) is the one to keep. The steps you described look good to me so if you would like to work on removing the duplication, you can go for it. Let us know if you need support with anything!
