### ISSUE TITLE
[Feature Request] Support 5.15 and 6.1 LTS kernels

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker#3837]
# Feature Request

Firecracker's supported kernel versions are currently [4.14 and 5.10](https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md), but now there are 5.15 and 6.1 LTS kernels too.

Would Firecracker support these new LTS kernels in 2023 or 2024?

## Describe the desired solution

Support these kernels.

## Describe possible alternatives

Firecracker isn't strongly tied to Linux kernel versions. So customers still can use these newer LTS versions at "own risk".

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by pb8o** [comment]
Hi! Thanks for your interest. We have some preliminary support for 6.1 in the `main` branch, but not in a supported release. We are actively working on it, but we don't have a concrete date. As for 5.15, we currently don't have plans to support it.

**Comment by cperciva** [comment]
@pb8o I have a closely related request -- I considered opening a new issue but figured it might be more useful to mention it here.  With a 5.15 kernel Firecracker is working for me except that the tests fail with

```
E   FileNotFoundError: [Errno 2] No such file or directory: '/firecracker/tests/integration_tests/performance/configs/test_block_performance_config_5.15.json'
```

Even if 5.15 isn't officially supported, can the tests be adjusted to skip tests (or at least provide a more helpful error message) where they need (and lack) a configuration defined for the kernel?

**Comment by roypat** [comment]
Hi @cperciva, 
the issue you describe looks like of #3726 (which accidentally got closed because I mentioned it in a commit it seems, sorry about that). As a workaround (until we fix up the block test, which hopefully will happen as soon as some refractoring work is done :crossed_fingers:), you can do `./tools/devtool test -- integration_tests/functional`, which makes pytest not even try to discover the performance tests.

**Comment by roypat** [comment]
> Hi cperciva@, the issue you describe looks like #3726 (which accidentally got closed because I mentioned it in a commit it seems, sorry about that). As a workaround (until we fix up the block test, which hopefully will happen as soon as some refractoring work is done crossed_fingers), you can do `./tools/devtool test -- integration_tests/functional`, which makes pytest not even try to discover the performance tests.

Fixed with #3940 :)

**Comment by rstrlcpy** [comment]
I've built 6.1 (with enabled nf_tables) and successfully booted it using `v1.3.3` and ubuntu-22.04 rootfs.  docker works well inside the micro VM.

**Comment by xmarcalx** [comment]
HI,
As @pb8o  sent in the previous message we are continuing to work to officially support kernel 6.1, which hopefully will be announced soon. 
Of course, there is nothing that prevent you to starting use Firecracker also with different kernel versions than the one we specify but it is at your own risks
