### ISSUE TITLE
[Bug] devtool failed to build with no permission to create directory when updating kvm-bindings 

### ISSUE THREAD

**Issue by fangn2** [firecracker-microvm/firecracker#3960]
# Describe the bug
Used `devtool` to build firecracker locally, build failed with failed to create directory issue when updating dependency `kvm-bindings`
```
$ tools/devtool -y build
[Firecracker release.sh 2023-07-12T15:09:26+00:00] Building version=1.5.0-dev, profile=debug, target=x86_64-unknown-linux-musl...
warning: patch for `kvm-bindings` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
    Updating git repository `https://github.com/firecracker-microvm/kvm-bindings`
error: failed to load source for dependency `kvm-bindings`

Caused by:
  Unable to update https://github.com/firecracker-microvm/kvm-bindings?tag=v0.6.0-1#e8359204

Caused by:
  failed to create directory `/usr/local/rust/git/db/kvm-bindings-6ea931839e214d47`

Caused by:
  Permission denied (os error 13)
```
## To Reproduce

* Clone/checkout main branch 
* run command `tools/devtool -y build`

## Expected behaviour

firecracker binary got built

## Environment

```
$ uname -m
x86_64
admin@ip-10-0-0-174:~/firecracker
$ uname -r
5.10.0-23-cloud-amd64
```

## Additional context

Seems related to the development image [tag change from v60 to v61](https://github.com/firecracker-microvm/firecracker/commit/6e973a797ae64c6e6b4d2f665ed320b9b39f32b8#diff-a781bef1e62a4cc6cbc73e5c14ec8a17635e7f2dc36943209f7c9922c24420c5R75) introduced in PR #3904 

Simply change that tag from 61 to 60, build will be happy. 

```
$ git diff tools/devtool
diff --git a/tools/devtool b/tools/devtool
index 308bf6f1..d4319743 100755
--- a/tools/devtool
+++ b/tools/devtool
@@ -72,7 +72,7 @@
 DEVCTR_IMAGE_NO_TAG="public.ecr.aws/firecracker/fcuvm"

 # Development container tag
-DEVCTR_IMAGE_TAG=${DEVCTR_IMAGE_TAG:-v61}
+DEVCTR_IMAGE_TAG=${DEVCTR_IMAGE_TAG:-v60}
```

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by roypat** [comment]
Hey Tony, 
thanks for the report. I can indeed confirm that a fresh clone of firecracker produces the error you describe, and that v60 works. I'm assuming it has something to do with adding kani to docker container, I'll have a look

**Comment by roypat** [comment]
Mh, in v60, we have 

```bash
$ ls -la /usr/local/rust/
total 48
drwxr-xr-x 8 root root 4096 Jun 30 13:58 .
drwxr-xr-x 1 root root 4096 Jun 30 13:58 ..
-rw-r--r-- 1 root root  483 Jun 30 14:02 .crates.toml
-rw-r--r-- 1 root root 2275 Jun 30 14:02 .crates2.json
-rw-r--r-- 1 root root    0 Jun 30 13:58 .package-cache
drwxr-xr-x 2 root root 4096 Jun 30 14:02 bin
drwxr-xr-x 2 root root 4096 Jun 30 14:02 downloads
-rw-r--r-- 1 root root  306 Jun 30 13:58 env
drwxr-xr-x 5 root root 4096 Jun 30 13:58 registry
-rw-r--r-- 1 root root  102 Jun 30 13:58 settings.toml
drwxr-xr-x 2 root root 4096 Jun 30 14:02 tmp
drwxr-xr-x 4 root root 4096 Jun 30 14:02 toolchains
drwxr-xr-x 2 root root 4096 Jun 30 14:02 update-hashes
```

while in v61 we have 

```
$ ls -la /usr/local/rust/
total 44
drwxr-xr-x 7 root root 4096 Jun  8 08:56 .
drwxr-xr-x 1 root root 4096 Jun  8 08:52 ..
-rw-r--r-- 1 root root  368 Jun  8 08:56 .crates.toml
-rw-r--r-- 1 root root 1813 Jun  8 08:56 .crates2.json
-rw-r--r-- 1 root root    0 Jun  8 08:53 .package-cache
drwxr-xr-x 2 root root 4096 Jun  8 08:56 bin
drwxr-xr-x 2 root root 4096 Jun  8 08:53 downloads
-rw-r--r-- 1 root root  306 Jun  8 08:52 env
lrwxrwxrwx 1 root root   37 Jun  8 08:56 git -> /firecracker/build/cargo_git_registry
lrwxrwxrwx 1 root root   33 Jun  8 08:56 registry -> /firecracker/build/cargo_registry
-rw-r--r-- 1 root root  102 Jun  8 08:53 settings.toml
drwxr-xr-x 2 root root 4096 Jun  8 08:53 tmp
drwxr-xr-x 3 root root 4096 Jun  8 08:52 toolchains
drwxr-xr-x 2 root root 4096 Jun  8 08:53 update-hashes
```

Seems the symlinks didnt get set up during container building, e.g. it didn't execute the commands after https://github.com/firecracker-microvm/firecracker/blob/921242fe878c5d6c88ccdcdf33f0e4d4785aed38/tools/devctr/Dockerfile#L79

**Comment by roypat** [comment]
Mh, in CodeBuild that line is printed as 

```
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain "$RUST_TOOLCHAIN"     && rustup target add $ARCH-unknown-linux-musl     && rustup component add llvm-tools-preview     && cargo install cargo-audit cargo-deny grcov cargo-sort     && rm -rf "$CARGO_HOME/registry"     && ln -s "$CARGO_REGISTRY_DIR" "$CARGO_HOME/registry"     && rm -rf "$CARGO_HOME/git"     && ln -s "$CARGO_GIT_REGISTRY_DIR" "$CARGO_HOME/git"
```

so I was thinking maybe with the line breaks gone the comment eats up the rest of the commands, but building a container locally without the comment still causes the issue :thinking:

**Comment by fangn2** [comment]
@roypat  Thanks for the quick turnaround! 
I would also suggest to add some tests after the dev docker image got built to mitigate regression in the future. 

Tests can be as simple as use the new image to build firecracker `tools/devtool -y build`.

**Comment by roypat** [comment]
> @roypat Thanks for the quick turnaround! I would also suggest to add some tests after the dev docker image got built to mitigate regression in the future.
> 
> Tests can be as simple as use the new image to build firecracker `tools/devtool -y build`.

That's a very reasonable request. I've opened #3966 to track this, as its not trivially possible to integrate this with our current testing framework (which is built upon executing things _inside_ the container).

**Comment by fangn2** [comment]
Thanks @roypat ! 
I can confirm the issue has been fixed from HEAD of main branch.
