### ISSUE TITLE
[Feature Request] Add devtool sanity checks to the CI

### ISSUE THREAD

**Issue by roypat** [firecracker-microvm/firecracker#3966]
# Feature Request

Originating from https://github.com/firecracker-microvm/firecracker/issues/3960#issuecomment-1634417864. To prevent breakage of non-`devtool test` commands when updating the devctr, we should have some sanity checks in our CI that verify the devtool commands we advertise in our documentation (e.g. `devtool build`) work as intended. 

## Describe the desired solution

A new buildkite step, similar to the "Style" or "Kani" steps is added which tries executing devtool commands and fails if any of them exit with non-zero code. It should only trigger if `tools/devctr/Dockerfile` is in the changeset of a PR, as to not waste CI resources (similarly to how currently a markdown-only change does not trigger the functional tests). 

If someone from the open source community wants to pick up this issue, please let me know and I'll be happy to provide assistance/more detailed implementation guidance. 

## Describe possible alternatives

Leaving it untested

## Additional context
See #3960 

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by pawelbeza** [comment]
Hey, I would be happy to help with this issue
