### ISSUE TITLE
Think about Guest/Host I/O Cache Behavior in Firecracker

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#399]
More specifically, these words related to caching block I/O:

*We want guests to cache often enough that we get good performance consistency, and we don't burn CPU in emulated devices all the time, but little enough that we're not burning too much memory on page cache (especially of disk-backed pages). I don't have good ideas about how to balance those yet, and we don't have a lot of control without the balloon driver.*

*The best we can do for now is to try size our VMs only a little bit bigger than the workload memory limit, so there's some cache but not too much. We should give some thought to how much that is.*

**Comment by AlexandruCihodaru** [comment]
We will focus on this area when the need arises.
