### ISSUE TITLE
[Bug] Broken s3 endpoint for linux kernel binary

### ISSUE THREAD

**Issue by BenjaminChun** [firecracker-microvm/firecracker#4173]
# Describe the bug

To create a microvm, we will need to install a linux kernel binary. The s3 endpoint for the linux kernel provided returns with an error 404.

## To Reproduce

Following steps from [link](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md#getting-a-rootfs-and-guest-kernel-image)

1. Run cmd `ARCH="$(uname -m)"` , this will assign variable ARCH to the output of the command `uname -m`
2. Run cmd `wget https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.6/${ARCH}/vmlinux-5.10.186` , this makes a request to the endpoint provided.

## Expected behaviour

The command line should show a download process of the linux kernel binary, and eventually download the binary in the current directory.

## Environment

Running on a x86_64 machine

## Additional context

I am trying to create a microVM with an updated version of linux. This version does satisfy my criteria but I am also wondering where I can find the binaries for other linux kernels that are compatible with firecracker microVM.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by roypat** [comment]
Hi!
Thanks for reporting this. The correct link is https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.6/x86_64/vmlinux-5.10.197 (for x86) or https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.6/aarch64/vmlinux-5.10.197 (for aarch64). Sorry about that, when we regenerated the artifacts after the 1.5 release we consumed new patch releases, so the filenames changes, which I overlooked. I'll get the docs updated asap :)
