### ISSUE TITLE
High MicroVM Instantiation Rates and udev Troubles

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#419]
Tim found this problem:

*Has anyone else had trouble with udev when running a lot of firecracker VMs?  I was testing how quickly I could run/recover tiny VMs and ended up running firecracker ~700 times a second on an i3.metal instance.  During the test, and for about 5 minutes afterwards, udev was taking 100% CPU, dealing with a backlog of messages from the kernel about /dev/kvm.  It looks like each run of firecracker causes two messages from the kernel to udev.*

*This seems like it shouldn't be a problem in realistic workloads but I wondered if there's a known fix.*

**Comment by alindima** [comment]
Please reopen with more information if issue still persists
