### ISSUE TITLE
i8042 internal buffer full

### ISSUE THREAD

**Issue by CloudAceEmma** [firecracker-microvm/firecracker#4240]
### when i use curl  with /actions API  to put SendCtrlAltDel to stop guestVm , there are some errors:

> 2023-11-15T09:10:34.270211712 [anonymous-instance:fc_api:ERROR:src/api_server/src/parsed_request.rs:189] Received Error. Status code: 400 Bad Request. Message: Internal Vmm error: I8042 error: i8042 internal buffer full.
> 2023-11-15T09:10:34.271529411 [anonymous-instance:fc_api:ERROR:src/api_server/src/parsed_request.rs:189] Received Error. Status code: 400 Bad Request. Message: Internal Vmm error: I8042 error: i8042 internal buffer full.
> 2023-11-15T09:10:34.272822601 [anonymous-instance:fc_api:ERROR:src/api_server/src/parsed_request.rs:189] Received Error. Status code: 400 Bad Request. Message: Internal Vmm error: I8042 error: i8042 internal buffer full. 
**How to solve this?**

**Comment by sudanl0** [comment]
Hi @CloudAceEmma, we don't see this issue generally so could you please share some more details by following the below template:

## To Reproduce

`[Author TODO: Steps to reproduce the behaviour:]`
`[ 1. Start Firecracker via....]`
`[ 2. Configure Firecracker via....]`
`[ 3. Is the issue consistent or a rare/corner case scenario etc.?]`
`[ 3. ....]`


## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

**Comment by CloudAceEmma** [comment]
To Reproduce:
 1.Start Firecracker via firecracker --api-sock /var/lib/firecracker/vm001.socket
 2. Configure Firecracker via pacman -S  firecracker.
 3. the issue is consistent
 Environment:
 firecracker 1.5.0
 Host Linux version 6.5.7, Guest Linux version 5.10.186
  Rootfs ubuntu1~22.04.1
  Architecture x86_64

**Comment by CloudAceEmma** [comment]
> Hi @CloudAceEmma, we don't see this issue generally so could you please share some more details by following the below template:
> 
> ## To Reproduce
> `[Author TODO: Steps to reproduce the behaviour:]` `[ 1. Start Firecracker via....]` `[ 2. Configure Firecracker via....]` `[ 3. Is the issue consistent or a rare/corner case scenario etc.?]` `[ 3. ....]`
> 
> ## Environment
> `[Author TODO: Please supply the following information):]` `[ - Firecracker version.]` `[ - Host and guest kernel versions.]` `[ - Rootfs used.]` `[ - Architecture.]` `[ - Any other relevant software versions.]`

sorry, it's my client code's problem, direct api call with curl does not reproduce the problem, will close it, thanks!
