### ISSUE TITLE
[Bug] Dev setups for Google Cloud Plattform(GCP) not working properly

### ISSUE THREAD

**Issue by NikeNano** [firecracker-microvm/firecracker#4281]
# Describe the bug

The dev setups for GCP don't work. It seems like the setup for [nested virtualization](https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling) have changed. 

I also think instructions could be simplified a lot this works for me: 

```bash
gcloud compute instances create firecracker  --enable-nested-virtualization   --zone=europe-west1-d   --min-cpu-platform="Intel Haswell" --machine-type=n1-standard-2
```

I believe simplifying and don't have to bother with disc and images will make it easier for new users to try it out on GCP.  I would be happy to contribute the updates to the docs. 

## To Reproduce
[Run the GCP ](https://github.com/firecracker-microvm/firecracker/blob/6be6cae22a94eb921e5c665a55fa8aff0f1de3e7/docs/dev-machine-setup.md#gcp)

## Expected behaviour

```bash
grep -cw vmx /proc/cpuinfo
```
should return something different then 0
## Environment

`[Author TODO: Please supply the following information):]`
`[ - Firecracker version.]`
`[ - Host and guest kernel versions.]`
`[ - Rootfs used.]`
`[ - Architecture.]`
`[ - Any other relevant software versions.]`

## Additional context

`[Author TODO: How has this bug affected you?]`

`[Author TODO: What are you trying to achieve?]`

`[Author TODO: Do you have any idea of what the solution might be?]`

## Checks

- [X] Have you searched the Firecracker Issues database for similar problems?
- [X] Have you read the existing relevant Firecracker documentation?
- [X] Are you certain the bug being reported is a Firecracker issue?

**Comment by roypat** [comment]
Hi @NikeNano 
Thank you for reporting this issue, and sorry for any inconvenience caused. The setup guide for GCP is entirely community maintained (as we do not use GCP for our development activities). We would very much appreciate a PR to update it with the additional steps you had to follow to get it to work (and feel free to ping me in the PR for review).

**Comment by NikeNano** [comment]
> Hi @NikeNano Thank you for reporting this issue, and sorry for any inconvenience caused. The setup guide for GCP is entirely community maintained (as we do not use GCP for our development activities). We would very much appreciate a PR to update it with the additional steps you had to follow to get it to work (and feel free to ping me in the PR for review).

Great will fix it during the weekend!
