### ISSUE TITLE
[Bug] parent-cgroup does not work as expected

### ISSUE THREAD

**Issue by MrMaxxan** [firecracker-microvm/firecracker#4287]
# Describe the bug

When starting a jailer with the parent-cgroup specified but no cgroup flags specified, then the rules in the parent cgroup folder is ignored.

## To Reproduce

`jailer --id myid --parent-cgroup firecracker --cgroup-version 2 --exec-file /usr/local/bin/firecracker-v1.5.0 --uid 1000 --gid 1000  --chroot-base-dir /tmp`

but if I run with a dummy cgroup parameter it works:

`jailer --id myid --parent-cgroup firecracker --cgroup-version 2 --cgroup=memory.max=max --exec-file /usr/local/bin/firecracker-v1.5.0 --uid 1000 --gid 1000  --chroot-base-dir /tmp`

## Expected behaviour

If I have a cgroup folder set up with all my settings it should be possible to use that without using any dummy parameters

## Environment

Firecracker v1.5.0, kernel 5.10, Ubuntu 22.04

## Additional context
More info in this [slack thread](https://firecracker-microvm.slack.com/archives/CDL3FUR8B/p1701272766109229)

**Comment by roypat** [comment]
Hi @MrMaxxan,
Thank you for the bug report. We will look into this issue as soon as possible
