### ISSUE TITLE
how to use test_uffd.py

### ISSUE THREAD

**Issue by shenben** [firecracker-microvm/firecracker#4291]
Could you please offer me a detailed case to test the [test_uffd.py](tests/integration_tests/functional/test_uffd.py)?

**Comment by shenben** [comment]
More than delighted to hear from you @roypat .

According to the Firecracker documentation, results from testing the [test_uffd.py](https://github.com/firecracker-microvm/firecracker/issues/tests/integration_tests/functional/test_uffd.py) integration test can be obtained by executing `./tools/devtool test -- integration_tests/functions/test_uffd.py` after having compiled the firecracker from source code. However, when I followed these instructions, all 4 tests cases conducted for test_uffd.py failed. Unfortunately, no detailed error messages were provided, so I am unsure of what caused the tests to fail. 
```
===================================================== short test summary info ======================================================
FAILED integration_tests/functional/test_uffd.py::test_bad_socket_path[ubuntu] - Failed: Timeout >300.0s
FAILED integration_tests/functional/test_uffd.py::test_unbinded_socket[ubuntu] - Failed: Timeout >300.0s
FAILED integration_tests/functional/test_uffd.py::test_valid_handler[ubuntu] - Failed: Timeout >300.0s
FAILED integration_tests/functional/test_uffd.py::test_malicious_handler[ubuntu] - Failed: Timeout >300.0s
============================================= 4 failed in 1234.42s (0:17:14) ======================================================
```
Do you have any simpler examples that demonstrate how the uffd module in firecracker interacts with the KVM memory region in a real use case? Just like [tools/create_snapshot_artifact/main.py](https://github.com/firecracker-microvm/firecracker/blob/92bbb053cf6e547d225b0741a67e7737c4942fe4/tools/create_snapshot_artifact/main.py) for a VM snapshot creating.

Thank you and any suggestions are welcome.

Here are the details of my execution environment:
```
Python 3.10.12
pytest-7.3.1
pluggy-1.0.0
Docker version 24.0.4, build 3713ee1
Firecracker v1.4.1
gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
cargo 1.66.1 (ad779e08b 2023-01-10)
kernel 5.15.0-89-generic
Ubuntu 22.04.2 LTS
Intel(R) Xeon(R) x86_64Gold 5317 CPU @ 3.00GHz x86_64
```

**Comment by shenben** [comment]
I appreciate you  @roypat taking the time to provide those suggestions earlier. Unfortunately, downgrading the host kernel to 5.10 did not resolve the [test_uffd.py](https://github.com/firecracker-microvm/firecracker/issues/tests/integration_tests/functional/test_uffd.py) test failures. The detailed logs are shown in [https://gist.github.com/shenben/641be7efd3262f229c5b40cb2a72c076](https://gist.github.com/shenben/641be7efd3262f229c5b40cb2a72c076). Do you have any other ideas on how I can troubleshoot and fix this issue?

Additionally, I'm looking for approaches to better pre-populate guest memory pages from a snapshot memory file into the KVM memory region, either internally or externally to Firecracker. The goal is to more proactively pre-populate the page table mapping pages into the KVM memory region that is controlled under Firecracker's process virtual memory space, looking for solutions beyond just using UFFD. Could you recommend an implementation that is relatively straightforward?

**Comment by roypat** [comment]
Thanks for sharing those logs! From that, it actually looks like its not a UFFD issue, but rather that the tests time out while downloading the artifacts (e.g. rootfs and kernel) needed to run them. You can try removing the timeout in https://github.com/firecracker-microvm/firecracker/blob/92bbb053cf6e547d225b0741a67e7737c4942fe4/tests/pytest.ini#L12. As for the page table thing, maybe `MAP_POPULATE` is what you want, e.g. something like https://github.com/firecracker-microvm/firecracker/pull/3944? Sadly, we do not provide any UFFD reference implementations

**Comment by pb8o** [comment]
v1.4.1 may harder to get started than v1.5.1 or mainline. Is there any reason you need to run this in v1.4.1?

**Comment by shenben** [comment]
Final solution:  Using kernel 5.10.130 instead of 5.10.0 as the host kernel resolved the uffd issue smoothly.
