### ISSUE TITLE
Documentation on PARTUUID Support

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#438]
We merged PARTUUID support, but we currently supply no documentation/example which describes the changes required from the user. It's important to mention that, in order to use this feature, the customer has to provide a disk image, rather than a partition image, which must be configured in a certain way.

**Comment by raduweiss** [comment]
We should also look into removing PARTUUID support since this is not strictly required - customers can extract partitions from the disk image.

**Comment by dianpopa** [comment]
> We should also look into removing PARTUUID support since this is not strictly required - customers can extract partitions from the disk image.

The PARTUUID functionality should be kept at least until we solve the limit of max 10 devices on x86_64. See #1268.
