### ISSUE TITLE
[Feature Request] Recipe for github actions test runner using firecracker?

### ISSUE THREAD

**Issue by root-11** [firecracker-microvm/firecracker#4472]
# Feature Request

As a open source developer I need to run my open source test suite with a variety of OS'es, but have confidential data in the test suite that cannot be added to the open source repo.

I would therefore like to run the test suite like with using github actions but locally using FireCracker.

## Describe the desired solution

I would like a recipe that enables me to use Firecracker and a **minimal** github actions styled yaml (test matrix) to run my build and test suite, just like github actions do.

## Describe possible alternatives

Not sure alternatives do not really apply here.

## Additional context

I know this is a request for a recipe, which implies "how to use" rather than "develop deep understanding". However I believe this is such a common need for others that I'm convinced it deserves a chance in a thriving open source community such as this.

## Checks

- [X] Have you searched the Firecracker Issues database for similar requests?
- [X] Have you read all the existing relevant Firecracker documentation?
- [X] Have you read and understood Firecracker's core tenets?

**Comment by roypat** [comment]
Hi @root-11,
Thank you for your feature request. Sadly, this is not a use-case of Firecracker we have experience with, so we cannot provide any instructions for how to execute GitHub actions locally inside Firecracker microVMs (although we also do not see any specific reason for why this should not be possible - although please keep in mind that Firecracker only supports Linux, so it can not help with running tests locally on multiple operating systems). Maybe a tool such as https://github.com/nektos/act could fulfill your needs?

**Comment by root-11** [comment]
> Maybe nektos ...
This is exactly what I was looking for but didn't find. Thank you @roypat
