### ISSUE TITLE
Add `clippy::error_impl_error`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#4488]
Set the clippy lint `clippy::error_impl_error` to warn and fix the warnings.

**Comment by jaoleal** [comment]
Don't you think that will be a bit messy for the whole code ? See the Down Point [here](https://rust-lang.github.io/rust-clippy/master/index.html#/clippy::error_impl_error)

**Comment by JonathanWoollett-Light** [comment]
@jaoleal enabling the lint forces us to not name any types `Error` and it will warn and fail CI if we do.

Do you still have concerns?

**Comment by jaoleal** [comment]
>Could you clarify some of your concerns if they still apply?

No, i had the wrong idea of the lint...

I made it, here https://github.com/firecracker-microvm/firecracker/pull/4494
