### ISSUE TITLE
Use `u32` to describe descriptor chain lengths

### ISSUE THREAD

**Issue by bchalios** [firecracker-microvm/firecracker#4548]
### Description

Currently, parts of our virtio code use usize to describe the lengths of descriptor chains [[1](https://github.com/firecracker-microvm/firecracker/blob/036d9906a09ed759597ee88bab6c1278e4fd7655/src/vmm/src/devices/virtio/iovec.rs#L43)], while other parts use u32, which results in some ugly casts that can panic if a descriptor chain with length exceeding 2^32-1 bytes slips through validation somehow [[2](https://github.com/firecracker-microvm/firecracker/blob/036d9906a09ed759597ee88bab6c1278e4fd7655/src/vmm/src/devices/virtio/rng/device.rs#L123)]. According to the virtio spec, descriptor chains can be at most 2^32-1 bytes long (as the "len" parameter in the used ring is a u32). We should thus use u32 instead of usize to describe these lengths, and upcast when interacting with non-virtio code that expects lengths to be usize.

### Solution

* Change the len parameters in IoVecBuffer[Mut] to be u32
* Inside of the from_descriptor_chain functions, add validation that the total length does not overflow a u32, and return a new IoVecError variant if it does

**Comment by BipulLamsal** [comment]
hey i want to work in this issue do i need to make changes for IoVecBufferMut and IoVecBuffer both

**Comment by bchalios** [comment]
Hey @BipulLamsal thanks for your interest in this. I think there was someone already working on this. Let me confirm with them and I will come back to you.
