### ISSUE TITLE
Error writing to file - write (28: No space left on device) [IP: 185.125.190.36 80]

### ISSUE THREAD

**Issue by lebron8dong** [firecracker-microvm/firecracker#4557]
# Describe the bug

When I started firecracker according to getting-started, an error occurred when executing unminimize: Error writing to file - write (28: No space left on device) [IP: 185.125.190.36 80].

## To Reproduce

 getting-started tutorial.

1. Running firecracker will require two terminals, the first one running the firecracker binary, and a second one for communicating with the firecracker process via HTTP requests.
2.  unminimize

## Expected behaviour
Error writing to file - write (28: No space left on device) [IP: 185.125.190.36 80].
![image](https://github.com/firecracker-microvm/firecracker/assets/73160333/4aa3355c-e275-47f8-abdb-423964ea47be)

## Environment
host: ubuntu22.04
mircoVm: ubuntu22.04
 Firecracker v1.7.0

How to configure virtual disk size?

**Comment by pb8o** [comment]
The rootfs are small on purpose to avoid downloading/copying large files. You can tweak the ext4 rootfs with something like:

```sh
truncate -s 2G build/img/x86_64/ubuntu-22.04.ext4
resize2fs -f build/img/x86_64/ubuntu-22.04.ext4
```

**Comment by lebron8dong** [comment]
I have allocated 4G, but an error occurred when installing python3-pip [2077.545011] Out of memory: Killed process 2115 (apt-get) total-vm:84300kB, anon-rss:66288kB, file-rss:0kB, shmem-rss: 0kB, UID:0 pgtables:204kB oom_score_adj:0
Killed.

**Comment by pb8o** [comment]
Looks like the guest does not have enough memory to run `apt-get`. You would need to launch the guest with more memory, 256MB for example.

Just for the record, we have never tried `unminimize` in our rootfs. I am not sure it will work with the current one.

**Comment by lebron8dong** [comment]
Thank you so much. The command I executed is apt-get install python3 python3-pip, and the python3-pip installation process will be killed. How to increase memory in firecracker?

**Comment by lebron8dong** [comment]
I use the configuration file to change the memory size, but an error occurs when configuring the network interface: curl --unix-socket /tmp/firecracker.socket -i -X PUT 'http://localhost/network-interfaces/eth0' -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{
       "iface_id": "eth0",
       "guest_mac": "AA:FC:00:00:00:01",
       "host_dev_name": "tap0"
     }'

error:
curl: (7) Failed to connect to localhost port 80 after 0 ms: Couldn't connect to server

**Comment by lebron8dong** [comment]
Thank you so much. I have successfully used configuration files to change the memory size.

**Comment by lebron8dong** [comment]
What is the password after using config-file to start firecracker? I need the password when transferring files.

**Comment by lebron8dong** [comment]
What is the password after using config-file to start firecracker? I need the password when transferring files.

**Comment by lebron8dong** [comment]
When I use config-file to start firecracker and bring up the network, I get an error when trying to transfer files:
scp /home/aiot/cat.jpg root@172.16.0.2:/root/firecracker
error
ssh: connect to host 172.16.0.2 port 22: Connection refused.

I get the same error using ssh connection:
ssh -i ./ubuntu-22.04.id_rsa root@172.16.0.2
error:
ssh: connect to host 172.16.0.2 port 22: Connection refused.

But I can ping
![image](https://github.com/firecracker-microvm/firecracker/assets/73160333/5e43b5b6-cb6c-414e-9f32-784913492b67)

**Comment by pb8o** [comment]
> When I use config-file to start firecracker and bring up the network

What config file are you using? if it's [the one referenced here](https://github.com/firecracker-microvm/firecracker/blame/main/docs/getting-started.md#L298) then that makes sense, there's no network interfaces configured.

**Comment by ShadowCurse** [comment]
Hi @lebron8dong, we recently updated [network setup doc](https://github.com/firecracker-microvm/firecracker/blob/main/docs/network-setup.md) with correct `MAC` address usage. If you use default `rootfs` from [getting started](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md), can you check if this update fixes your issue?

**Comment by ShadowCurse** [comment]
Closing the issue due to the inactivity. Feel free to reopen if the issue still exists.
