### ISSUE TITLE
Interact with the MicroVM in jail environment and daemon mode.

### ISSUE THREAD

**Issue by dtouzeau** [firecracker-microvm/firecracker#4569]
Hi

I started the microVM running correctly with the jail in daemon mode, I see my VM running in memory but I can't connect to the shell.
The kernel is set ` console=ttyS0 reboot=k panic=1 pci=off`
I tried without success with `stty -F /dev/ttyS0`
but I get an error.
`stty: /dev/ttyS0: Input/output error`

No blog or documentation explain how to access the microvm shell in a jail environment with daemon mode

Any tips ?

**Comment by kalyazin** [comment]
Hi @dtouzeau . Thanks for the enquiry.
Detaching from the controlling terminal is a part of the daemonization procedure, so it is expected that VM's serial console is not accessible.
We would like to assess if providing an access is an important usecase and design a solution or update the documentation to mention this is a limitation.
