### ISSUE TITLE
no internet inside the VM

### ISSUE THREAD

**Issue by chappie1998** [firecracker-microvm/firecracker#4582]
I followed the getting started docs to set up and run the firecracker VM. However, I am not able to access the internet inside the VM.

Firecracker version: v1.6.0
Host and guest kernel versions: ubuntu Os
Rootfs used: Yes

![Screenshot from 2024-04-26 17-00-24](https://github.com/firecracker-microvm/firecracker/assets/35380717/031c1cda-f009-49c7-9314-24fbb6932ba5)

**Comment by chappie1998** [comment]
Hey @JonathanWoollett-Light, I am simply following https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md docs. in one terminal started the VM, and in the second terminal, running the rest of the commands. I am able to ssh, but I can't access the internet.

**Comment by xmarcalx** [comment]
Hi @chappie1998, 

Thanks for the report, by chance did you try a Firecracker with with fix merged in #4681 and verified that solve your problem?
