### ISSUE TITLE
[Bug] Broken link in getting started docs

### ISSUE THREAD

**Issue by csegarragonz** [firecracker-microvm/firecracker#4675]
# Describe the bug

I am following the [getting started](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md) docs, and the link to download the kernel image is broken.

## To Reproduce

```bash
wget https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.9/x86_64/vmlinux-5.10.217
```

## Expected behaviour

The link works.

## Checks

- [ ] Have you searched the Firecracker Issues database for similar problems?
- [ ] Have you read the existing relevant Firecracker documentation?
- [ ] Are you certain the bug being reported is a Firecracker issue?

**Comment by roypat** [comment]
Hi @csegarragonz, 
thanks for reporting. We've fixed this in #4679 (and hopefully updated the guide to never run into this issue again by dynamically determining the correct link).
