### ISSUE TITLE
Phase out support for Linux kernel 4.14

### ISSUE THREAD

**Issue by pb8o** [firecracker-microvm/firecracker#4694]
Linux 4.14 has been EOL since [2024-01-10](https://lore.kernel.org/lkml/2024011046-ecology-tiptoeing-ce50@gregkh/).

It is no longer receiving security fixes, so as part of our security tenets we should not continue supporting it
Linux 4.14 host support was removed in #4689 and the new minimum supported kernel is 5.10.

Supported versions v1.8 and v1.7 still run on Linux 4.14. After we phase out support for those the Firecracker project will no longer support running on 4.14.

**Comment by kanpov** [comment]
Would this also entail 6.1 becoming a supported guest kernel version?

**Comment by xmarcalx** [comment]
Hi @kanpov,

We currently deprecated only host OS kernel version 4.14, and planning to deprecate guest OS kernel version 4.14 soon too.
We already support host OS kernel version 6.1 (https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md) and definitely working on supporting guest OS kernel version 6.1 as substitute of 4.14.
