### ISSUE TITLE
Consider marking externally visible pub functions #[inline]

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#472]
It seems that Rust does not automatically inline functions across crate boundaries unless they are generic, marked `#[inline]`, or LTO is enabled at build time. Since Firecracker is built with LTO, we're fine in this regard, but we don't know what kind of builds people using our (future) public crates will use.

We should decide whether marking externally visible pub functions `#[inline]` in our public crates makes sense. It's interesting to see whether `#[inline]` is just a hint (so the compiler may still skip doing it if there's no benefit), or it actually forces inlining. If the latter is true, things get more complicated because we have to pick only those functions which seem to benefit from the optimization. Hopefully, that's not the case, because otherwise it wouldn't make much sense for `#[inline(always)]` to also be a thing.

**Comment by dianpopa** [comment]
> Since Firecracker is built with LTO, we're fine in this regard, but we don't know what kind of builds people using our (future) public crates will use.

Since the current goal of Firecracker is too consume as much rust-vmm as possible, we no longer need to worry about our crates being used out of Firecracker's context. 
If you think this is still worth following, feel free to re-open and motivate.
