### ISSUE TITLE
Remove Python 3.6 Dependencies from CI

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#475]
Some of the type annotations added in the python style check PR don't work in Python 3.5, which is what some contributors use now. So, we will revert those type annotations.

**Comment by andreeaflorescu** [comment]
Do we still want to do this?

**Comment by dianpopa** [comment]
Now that we provide a docker image for running the CI, there should be no need to worry about the dependencies that it introduces. Closing this.
