### ISSUE TITLE
[Feature Request] Don't check KVM in `tools/devtool checkstyle`

### ISSUE THREAD

**Issue by zulinx86** [firecracker-microvm/firecracker#4768]
Branched from issue #4747 .

# Feature Request

Since `tools/devtool checkstyle` only checks coding style, it doesn't require KVM, but it does the KVM existence check. That prevents users from running it on their development env without KVM.

## Describe the desired solution

Currently, it just calls `cmd_test()` that does the KVM check.

https://github.com/firecracker-microvm/firecracker/blob/main/tools/devtool#L900-L902
```
cmd_checkstyle() {
    cmd_test --no-build -- integration_tests/style -n 4 --dist worksteal
}
```

https://github.com/firecracker-microvm/firecracker/blob/main/tools/devtool#L686
```
cmd_test() {
// snipped
    ensure_kvm
// snipped
}
```

We might be able to add a new option of `cmd_test()` to bypass the check.

## Describe possible alternatives

An alternative could be hardcoding a simplified version of `cmd_test` in `cmd_checkstyle`.

## Additional context

N/A

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by tommady** [comment]
Hi @zulinx86, it seems this issue has been resolved with the merging of [this PR](https://github.com/firecracker-microvm/firecracker/pull/4868). Please let me know if there are any additional goals or directions that this issue is intended to address.
thanks.

**Comment by zulinx86** [comment]
Hi @tommady , thank you so much! I believe your PR fixed this issue!!
