### ISSUE TITLE
MMDS - add logging and metrics

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#478]
- [ ] Metrics:
    - [x] PUT /mmds
    - [x] PATCH /mmds
    - [x] GET /mmds
- [ ] Logging 
    - [x] PUT /mmds
    - [x] PATCH /mmds
    - [x] GET /mmds
    - [ ] Others - To Be Defined

**Comment by AnishShah** [comment]
This issue is really old. But I wanted to know if this is still needed and can I work on it?

**Comment by acatangiu** [comment]
Hi @AnishShah, contributions are welcome! This issue is still accurate, yes.

**Comment by vbmade2000** [comment]
@andreeaflorescu  Can you provide some example of metrics ?

**Comment by andreeaflorescu** [comment]
@vbmade2000 we need to add API metrics that are incremented when PUT/PATCH/GET on /mmds are called.
First, they need to be defined in the appropriate structure. We need to use [PutRequestsMetrics](https://github.com/andreeaflorescu/firecracker/blob/803c8fae14b1194ba103cf7f0ce817376bf9dfc4/src/logger/src/metrics.rs#L121), [Patch](https://github.com/andreeaflorescu/firecracker/blob/803c8fae14b1194ba103cf7f0ce817376bf9dfc4/src/logger/src/metrics.rs#L150), and [GetRequestsMetrics](https://github.com/andreeaflorescu/firecracker/blob/803c8fae14b1194ba103cf7f0ce817376bf9dfc4/src/logger/src/metrics.rs#L108) structures.

After defining the metrics in those structures, we should increment them when the appropriate request is handled. The entry point in the api_server that we're interested in is [here](https://github.com/andreeaflorescu/firecracker/blob/803c8fae14b1194ba103cf7f0ce817376bf9dfc4/src/api_server/src/parsed_request.rs#L44).

You can look at other API metrics examples in the [machine_configuration](https://github.com/andreeaflorescu/firecracker/blob/master/src/api_server/src/request/machine_configuration.rs) module as this one has all metrics we're interested in (put, patch, get).

**Comment by vbmade2000** [comment]
Sure. I'll take a look. Thanks for details @andreeaflorescu .

**Comment by vbmade2000** [comment]
@andreeaflorescu Referring to [machine_configuration](https://github.com/andreeaflorescu/firecracker/blob/master/src/api_server/src/request/machine_configuration.rs), **parse_get_machine_config** calls **METRICS.get_api_requests.machine_cfg_count.inc();**. Should /mmds GET use same ?

**Comment by andreeaflorescu** [comment]
@vbmade2000 you should define new entries for `MMDS` if they do not exist yet. `machine_cfg_*` metrics refer to `/machine-config`. So we would need ones under `METRICS.get_api_requests` for MMDS as well.

**Comment by vbmade2000** [comment]
I understand that. I think I asked wrong question. Anyways I found **MmdsMetrics** struct at https://github.com/andreeaflorescu/firecracker/blob/master/src/logger/src/metrics.rs#L230.  Can it be used ?

My assumption is it can't be used as by names it seems they are not defined to count number of GET requests etc.

**Comment by andreeaflorescu** [comment]
> I understand that. I think I asked wrong question. Anyways I found **MmdsMetrics** struct at https://github.com/andreeaflorescu/firecracker/blob/master/src/logger/src/metrics.rs#L230. Can it be used ?
> 

No, that is not the right structure. The `MmdsMetrics` structure that you found contains metrics related to the internal functionality of the MMDS device, and not related to the API.

The type of `METRICS.get_api_requests` is `GetRequestsMetrics`. If you look at the [definition](https://github.com/andreeaflorescu/firecracker/blob/803c8fae14b1194ba103cf7f0ce817376bf9dfc4/src/logger/src/metrics.rs#L108) you will see that there is one metric for each GET request. You need to add a `mmds_count` field there. There are corresponding structures for PUT & PATCH API requests as well.

Does that make sense?

**Comment by vbmade2000** [comment]
Indeed it does. I will go in that direction.

**Comment by acatangiu** [comment]
Fixed in #2533
