### ISSUE TITLE
`SYS_open` and `SYS_mmap` get denied by the seccomp filter

### ISSUE THREAD

**Issue by raduml97** [firecracker-microvm/firecracker#485]
- `functional/test_api.py::test_api_patch_post_boot`
- `functional/test_api.py::test_patch_drive`

Fail because they get denied by seccomp filtering.
The offending syscalls are `SYS_open` and `SYS_mmap`.

More information about the argument values cannot be acquired because it is not logged by seccomp.
When tracing the syscall invocations of the integration test suite, all recorded rules were added accordingly to the default filter context. This implies that the two offending syscalls were not properly traced and thus there are no rules in place to allow them.

Temporary solution: allow `SYS_open` and `SYS_mmap` regardless of the argument values.

**Comment by raduweiss** [comment]
Is this still happening?

**Comment by aghecenco** [comment]
`open` and `mmap` are allowed through the seccomp filter regardless of parameters and there is no plan to tighten conditions for them. Closing.
