### ISSUE TITLE
[Bug] Slack Invite no longer active

### ISSUE THREAD

**Issue by zvonkok** [firecracker-microvm/firecracker#4860]
As the title says, Slack invite no longer active.
Tried it with different browsers just to be sure.

**Comment by Manciukic** [comment]
Hey, thanks for reporting the issue. This is the new link, I'll update the Readme shortly.
https://join.slack.com/t/firecracker-microvm/shared_invite/zt-2tc0mfxpc-tU~HYAYSzLDl5XGGJU3YIg
