### ISSUE TITLE
[Feature Request] Document: where to run long-running services in the cloud?

### ISSUE THREAD

**Issue by hpvd** [firecracker-microvm/firecracker#4950]
# Feature Request

We like to use firecracker for a distributed deployment.
For this we need to find vendors enabling us to access the different geo-locations (countries) without having to deal with many vendors.
A typical cloud use case :-)

The challenge: firecracker rely on KVM

What are the possibilities to do so without having to rely on daxx expensive aws bare metal instances?

Of course there are some cheap, virtualized offers which should make nested kvm possible -at the first sight.
-> but as far as I know this is not suitable for longer running production use cases because these instances could be auto-live-migrated at anytime which will break the instance....

## Describe the desired solution

Build a list of multi country cloud providers and their instance types where its possible to run firecracker including Cost/Month

## Describe possible alternatives

`[Author TODO: A clear and concise description of any alternative solutions or features you have considered.]`
every possible user has to do this research on his own

`[Author TODO: How do you work around not having this feature?]`
We (and possibly many others) do not adapt solutions using firecracker if we do not find places where we can run it in different geo-locations without having to work with several local vendors.

## Checks

- [ x] Have you searched the Firecracker Issues database for similar requests?
- [ x] Have you read all the existing relevant Firecracker documentation?
- [ x] Have you read and understood Firecracker's core tenets?

**Comment by hpvd** [comment]
e.g. OVP decribes this pretty clearly in their Cloud FAQs:

> Is nested virtualization supported?
> 
> Yes and no.
> 
> Yes because it's enabled (we provide vmx flag to your instance), which means you can start any virtualization technology that relies on this in your instance (such as KVM, QEMU, VirtualBox, Xen, HyperV, etc.).
> 
> No because as soon we will live-migrate your instance (and this can happen any time, based on our hypervisor management), then your kernel may panic.

https://help.ovhcloud.com/csm/en-public-cloud-compute-faq?id=kb_article_view&sysparm_article=KB0050745

**Comment by xmarcalx** [comment]
Hi @hpvd ,

Thank you very much for your interest in Firecracker and opening this request. 

As you said, to run Firecracker you really only need a system where Firecracker has access to /dev/kvm. 
This is the only requirement we have and can document.
Unfortunately is not feasible for us to track all the possible cloud providers in the world and all their instances where Firecracker can run. 
As long as an instance meet the previous requirement, it is up to the users and their workloads to evaluate if price, performances or any other considerations (e.g. can the instance be live migrate, or live upgraded) is suitable for their usecase or not.

Kind Regards,
Marco
