### ISSUE TITLE
VIRTIO: Clear Up Implementation Details

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#520]
We should have a look to see if we understand the following aspects related to VIRTIO net:
- Are we properly making use of hardware offloading when/if such features are available? We mainly care about segmentation offloading and checksum. For example, we skip checksum verification for packets coming from the guest to the MMDS because the guest kernel appears to offload checksum computation. Can we infer when this is going to happen based on VIRTIO feature negotiation, or is there more to it?
- Make sure we understand the implications of that `vnet_hdr` or smt struct which is prepended to frames coming from/going to the TAP.

**Comment by georgepisaltu** [comment]
We'll take a look at this if we start looking at a net hardware offloading feature. Closing this for now.
