### ISSUE TITLE
MMDS - accept only String values on PUT/PATCH

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#529]
We should only accept string values in MMDS. This should be enforce when PUT/PATCH requests are parsed. Otherwise, the guest will receive an Internal Server Error because we don't parse other types.

**Comment by lyuyuan92** [comment]
May I give a try on this one?

**Comment by andreeaflorescu** [comment]
Sure, let us know if you need any help!

**Comment by aghecenco** [comment]
Addressed by #1023
