### ISSUE TITLE
Add Checker Script

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#547]
Add a script to be used by developers in order to check that their development machine supports building & running Firecracker. The said script should also give hints of what needs to be installed/configured.
Probably we also need a similar script for checking if the Firecracker binary can be run on the system.

**Comment by cneira** [comment]
@andreeaflorescu  
Requirements checks in the Firecracker binary are addressed in this PR https://github.com/firecracker-microvm/firecracker/pull/693, besides /dev/kvm and kernel version, is something else needed to check ?.

**Comment by andreeaflorescu** [comment]
For running Firecracker it should be fine. But I was thinking that maybe we could also have a script for development that would check if rust is installed, the musl target and the musl-tools. When using the devtool that is not a problem, but for people that do not want to build Firecracker using docker, it might help.

**Comment by christopherdiehl** [comment]
@andreeaflorescu  do you envision this as apart of `tools/devtool` or a separate shell/ python script? 

Please let me know if I missed any of the requirements to run  in a development setting outside of  docker below:
- Intel CPU
- binutils-dev
- cmake
- curl
- file
- g++
- gcc
- iperf3
- iproute2
- jq
- libcurl4-openssl-dev
- libdw-dev
- libiberty-dev
- libssl-dev
- lsof
- make
- musl-tools
- net-tools
- pkgconf
- python
- python3
- python3-dev
- python3-pip
- python3-venv   
- zlib1g-dev

Python DevTools

- setuptools 
- wheel
- boto3 
- nsenter 
- paramiko 
- pycodestyle 
- pydocstyle 
- pylint 
- pytest 
- pytest-timeout 
- pyyaml 
- requests 
- requests-unixsocket 
- retry

**Comment by acatangiu** [comment]
We've decided that developer systems vary a great deal and trying to maintain a comprehensive list of dependencies is unsustainable.

The recommended tool for development is thus `devtool` which will build/test Firecracker using our provided container.

We also provide a copy/paste-able command in `docs/getting-started.md` that will report whether a system can **run** Firecracker.
