### ISSUE TITLE
PUT MachineConfig acts like a PATCH rather than a PUT

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#557]
Later-edit:

API requests for PUT MachineConfig end up calling `Vmm::set_vm_configuration()` in `vmm/src/lib.rs` which can do partial updates thus invalidating REST rules for PUT.

Suggestion:
- Make all MachineConfig fields mandatory/non-optional (especially since they are actually required and are default() built anyway),
- change current `PUT` with `PATCH` operation as this will make it REST-compliant while keeping same user-experience of partially updating the structure, 
- add a PUT that requires all fields be present.

**Comment by lyuyuan92** [comment]
May I try this one :smile:

**Comment by raduweiss** [comment]
Sure, thanks for the contribution!

In general, unless there's someone else in the `Assignees` field of an issue, it's fair game to just pick it up ... in the rare cases that this conflicts with something, we'll just let you know 😄.

**Comment by lyuyuan92** [comment]
Hi! If payload of the PUT request is empty, VmConfig::into_parsed_request() returns  Error "Empty request" and then returns BadRequest. Do we want to keep it this way or reset VmConfig to its default values?

**Comment by andreeaflorescu** [comment]
I would say we shouldn't allow empty PUT requests. PUT should be used for overwriting existing resources and since it is invalid for the machine-config to have null values for things like vcpu and memory, I don't really see a point in accepting empty requests. I wouldn't reset it to the default either in case an empty request comes.

**Comment by aghecenco** [comment]
Fixed by #1055
