### ISSUE TITLE
Eliminate (some) hardcoded thresholds for integration tests

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#565]
We've discussed about no longer having thresholds (like coverage) as hardcoded values within integration test logic. We can also think about extending this to the point where all threshold values are defined outside test logic, and it's possible to swap between profiles (the real thing, development, computer made of wood, etc.)

**Comment by georgepisaltu** [comment]
Right now we don't have a use case or user request for this. Closing for now.
