### ISSUE TITLE
Remove DeviceState from NetworkInterfaceConfig

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#566]
The device state is a leftover from our previous device model, when we wanted to be able to hot plug/unplug devices. This is not something that we are planing to implement in the near future and should be remove.

The DeviceState structure is defined in `vmm/src/vmm_config/mod.rs` and it is used in the NetworkInterfaceConfig structure definition in `vmm/src/vmm_config/net.rs`.

With this change, the swagger definition (api_server/swagger/firecracker.yaml) also needs to be updated.

**Comment by andreeaflorescu** [comment]
Yap, there are probably other references to the DeviceState. I encourage you to also look into the comments. Also, you will need to update the tests. Since this is a customer facing change, you can also add an #Unreleased section to the changelog saying that the device state is removed.

**Comment by tyleranton** [comment]
Should the #Unreleased section be added above the current release?

**Comment by dianpopa** [comment]
Yes, above the current release.
Something like
```markdown
# Changelog

## Unreleased

### Removed
[Explain change here]

## [0.11.0]

### Added
...
```
