### ISSUE TITLE
Normalize Total/Success/Fail Counter Metrics for VirtIO Devices/Events

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#584]
MMDS, as well as block and net devices emit 2 types of metrics:
* throughput: bytes read & bytes written, tx/rx packets etc
* counter: block device updates, rate limiter events, all errors

There are no counter type metrics for successful `read` and `write` operations, so comparing the rate of failures/successes is not straightforward.

**Comment by raduweiss** [comment]
Looks like there's some inconsistency in the way we express this metrics. For example, `tx_fails` include all types of failures from the other more granular metrics.

**Comment by lyuyuan92** [comment]
I will have a try on this one :)

**Comment by lyuyuan92** [comment]
Hi, Would [`MmdeMetrics.rx_accpeted`](https://github.com/firecracker-microvm/firecracker/blob/8632f303cbd590a6d6a170879cf3f56855d9013a/logger/src/metrics.rs#L258) be sufficient for MMDS's successful read count?

**Comment by aghecenco** [comment]
#1090
