### ISSUE TITLE
Make the rate_limiter Crate Fully Independent

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#589]
The `rate_limiter` crate still has an internal dependency on our `logger` crate, which is not going to be published on `crates.io` as a separate library. We should remove this and any kind of logging altogether (addressing #259 in the process would definitely help) before `rate_limiter` can be considered independent.

**Comment by georgepisaltu** [comment]
This is discussed in https://github.com/rust-vmm/community/issues/107 . Closing this
