### ISSUE TITLE
'poweroff' does not exit the VM 

### ISSUE THREAD

**Issue by rn** [firecracker-microvm/firecracker#598]
Issuing `reboot` exist the VM process (slightly unexpected) while `poweroff -f` or `halt -f` shuts down but does not exit the VM process.

**Comment by aldem** [comment]
> we have no good way of coming back from a reboot

Perhaps, restart the process with last known configuration? Just an idea. But this only makes sense if `poweroff` or `halt` are handled properly. Reporting restart counter in metrics could be useful too.

Kernel functions machine_halt()/machine_power_off() etc are (in theory) PV-ready.

**Comment by acatangiu** [comment]
Firecracker does not implement ACPI and PM devices, therefore operations like
gracefully rebooting or powering off the guest are supported in unconventional ways.

Running the `poweroff` or `halt` commands inside a Linux guest will bring it down but
Firecracker process remains unaware of the guest shutdown so it lives on.

Running the `reboot` command in a Linux guest will gracefully bring down the guest
system and also bring a graceful end to the Firecracker process.

Issuing a `SendCtrlAltDel` action command through the Firecracker API will generate a
`Ctrl + Alt + Del` keyboard event in the guest resulting in a clean reboot on most
guest Linux systems.

https://github.com/firecracker-microvm/firecracker/pull/943 adds this information the the `FAQ.md`
