### ISSUE TITLE
The releases should have a sha256 for the binaries

### ISSUE THREAD

**Issue by rn** [firecracker-microvm/firecracker#601]
It is quite common to add a checksum, like `sha256` for binaries attached to GitHUB releases. This allows downloaders to verify the integrity of the binaries they downloaded. See for example: https://github.com/linuxkit/linuxkit/releases

Note, the quoted `sha256` sums are in a format recognized by `sha256sum -c` (two spaces between the sha256 sum and the file name)

**Comment by aghecenco** [comment]
#879 should envision this step (generating and publishing the checksums) in the release pipeline.
