### ISSUE TITLE
Move autogenerated code in folders with _gen suffix

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#602]
The crates with _sys contain auto-generated code. Move the code to directories that end with _gen suffix so it is clear that the code is auto-generated.

When we rename the directories, we should also update the integration test `test_coverage` from `tests/integration_tests/build/test_coverage.py`. In this test we are excluding the auto-generated code from the coverage report.

**Comment by sejr** [comment]
#676 merged—this issue can be closed.
