### ISSUE TITLE
Move test helpers in `tests` module

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#605]
Move functions used only in tests in the tests module at the end of the file. Otherwise, we are also counting these lines when computing the coverage.

Some helper functions cannot be moved because they are used in tests in other crates. In this case, we should add a comment before the function saying where it is used.

- [x] api_server
- [ ] arch
- [x] cpuid
- [x] devices
- [ ] dumbo
- [x] fc_util
- [ ] jailer
- [x] kernel
- [ ]  logger
- [ ] memory_model
- [ ] micro_http
- [ ] mmds
- [ ] net_gen
- [ ] net_util 
- [ ] rate_limiter
- [ ] seccomp
- [ ] firecracker (src)
- [ ] sys_util
- [ ] virtio_gen
- [ ] vmm

**Comment by raduweiss** [comment]
It was high then, it's not now.
