### ISSUE TITLE
Make sure we use the proper visibility 

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#607]
Restrict the usage of pub in modules, structures, functions.
We should only use pub for functions/structures that are meant to be exposed outside of crates/modules.
This is check needs to be manually done/per crate:
- [x] api_server
- [x] cpuid
- [x] devices
- [x] dumbo
- [x] fc_util
- [ ] jailer
- [x] kernel
- [x] kvm
- [x] kvm_gen
- [ ]  logger
- [x] memory_model
- [x] micro_http
- [x] mmds
- [x] net_gen
- [x] net_util 
- [ ] rate_limiter
- [x] seccomp
- [x] firecracker (src)
- [ ] sys_util
- [ ] virtio_gen
- [x] vmm
- [x] x86_64

**Comment by aghecenco** [comment]
We should keep an eye out for functions that only need to be pub inside a module. Rust has this nifty `pub (in module) fn` thing that controls just how public a function is.

**Comment by kevtheappdev** [comment]
Hi! Is there still work to be done in this area? Interested in helping out!

**Comment by gc-plp** [comment]
Hi @kevtheappdev. Please take a look if interested.

**Comment by kumargu** [comment]
mmds looks clean.

**Comment by raduweiss** [comment]
Thanks for the help here :)

**Comment by kumargu** [comment]
clean-up for ```micro_http``` are merged here - https://github.com/firecracker-microvm/firecracker/pull/2245

**Comment by alindima** [comment]
We decided to close this issue.
Since we will keep pushing code to the repo, the status of this issue will always be outdated. The suitable way of preventing unneeded public exports/fields is through code reviews. This is also not a big issue since Firecracker does not export a library.
