### ISSUE TITLE
Move auto-generated code to separate crates

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#608]
Not all auto-generated files are in separate crates.

One example is the x86 crate which contains both auto-generated code and written code. We need to refactor crates like this to separate the auto-generated code from the rest of the code.
The auto-generated code is currently in crates with `_sys` suffix and the plan is to renamed them to `${name}_gen`. Check issue: #602.

The auto-generated code is excluded from the code coverage report.

**Comment by dianpopa** [comment]
The x86 crate does not exist anymore. All auto-generated code resides now inside crates that are named like `*_gen`. See #756.
