### ISSUE TITLE
Document all Public Functions, Structures, Enums, Modules

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#609]
Document all public functions and structures. We should also add usage examples for public crates.
- [x] api_server
- [x] arch
- [x] cpuid
- [ ] devices
- [x] dumbo
- [ ] firecracker (src)
- [ ] jailer
- [ ] kernel
- [x]  logger
- [x] micro_http
- [ ] mmds
- [x] rate_limiter
- [x] seccomp
- [ ] utils
- [x] vmm

**Comment by raduweiss** [comment]
Lowering priority to medium; it was high at the time, but isn't anymore.

**Comment by alindima** [comment]
Tracked in https://github.com/firecracker-microvm/firecracker/issues/569
