### ISSUE TITLE
Tests: Move from dir structure and S3 tags to manifest.json

### ISSUE THREAD

**Issue by dhrgit** [firecracker-microvm/firecracker#613]
Currently, the integration tests expect to find the test microVM images in an S3 bucket, arranged under a rigid (i.e. hard coded) dir/file structure. We should switch to using a more flexible mechanism, such as a configuration file (e.g. manifest.json). This way, we could:
- add/remove/modify test images and capabilities easier
- use any storage system to hold the microVM images (like https, local disk, etc)
- implement test profiles

**Comment by serban300** [comment]
This issue is obsolete. Closing.
