### ISSUE TITLE
Add Cargo.lock to git

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#617]
This is the first step for achieving reproducible builds. This way we have control over the versions of packets and it is easier to spot when new dependencies are introduced.

**Comment by sejr** [comment]
@andreeaflorescu I have a branch for this on my fork: https://github.com/sejr/firecracker/tree/track-cargo-lock

Is there anything else that needs to be done for this?

**Comment by andreeaflorescu** [comment]
Looks good, please submit a PR. We should do more for the reproducible builds, but at this point it is better to just open a new issue and link this one to it.

**Comment by sejr** [comment]
@andreeaflorescu  #669 merged. Can close this now.
