### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#648]
Run Firecracker on ARM processors.

Task breakdown (as per research carried until  now):
- [x] #516
- [ ] #608 
- [ ] #603 (first check)
- [x] #755
- [x] #756 
- [ ] #757
- [ ] #758  
- [ ] #867 
- [ ] #866

**Comment by dianpopa** [comment]
For clarity, we will use independent PRs labeled with `ARM Support` for keeping track of this functionality.

**Comment by raduweiss** [comment]
For even more clarity, ARM is still on the roadmap 😄. I'd like to switch tracking of roadmap items to something batter than a label (maybe GitHub milestones), and then I'll re-close this.

**Comment by raduweiss** [comment]
Moved to milestone, closing.
