### ISSUE TITLE
Documentation: Add Markdown Linter

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#649]
While the rust and python files in the repository have automated style checks in place that run as part of continuous integration testing, markdown files are not style-checked and this results in PR churn.

Add an integration test for markdown style checking.

**Comment by iranzo** [comment]
Easiest way to add it is to use 'tox' to install requirements in virtual env and then run something like:

tox.ini
~~~
[testenv:markdown]
commands = markdownlint .
~~~


test-requirements.txt
~~~
pymarkdownlint
~~~

.gitlab-ci.yml
~~~ 
before_script:
  - export PATH=/root/.local/bin:$PATH
  - apt-get update
  - apt-get -y install python-dev
  - curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py --user
  - pip install tox setuptools

cache:
  paths:
  - /root/.cache

markdown:
  script:
    - tox -e markdown
~~~


For example...

Which CI/CD do you use for checks?

**Comment by WilliamGrossKC** [comment]
Hi, I was wondering if I could be assigned this issue.

**Comment by rpaul98** [comment]
Hi, @edengarza, @amaniduncker, and I are students at UT and are looking to contribute to an open source project for our virtualization class. We were wondering if we could get assigned to this issue.

Thanks!

**Comment by dianpopa** [comment]
Hi! Great to here this! I will assign you to the issue, feel free to contact us on our slack channel for clarifications. Thanks!

**Comment by dianpopa** [comment]
@rpaul98 for some reason I cannot assign your 2 colleagues to the issue, are they following the repo?
