### ISSUE TITLE
Investigate Recipe-Based Builds

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#652]
While we will never have an expansive set of features, serverless workloads still come in more than one shape and size. To further reduce our attack surface, we should investigate a recipe-based build system that allows customers to create Firecracker binaries with the mix of devices / features that's right for them (e.g., with any combination of virtio net / block / vsock, with or without MMDS).

**Comment by raduweiss** [comment]
This will probably happen as part of rust-vmm. One day we can use it in Firecracker, but until then, closing this issue.

**Comment by andreeaflorescu** [comment]
:(
