### ISSUE TITLE
MicroVM Storage Encryption

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#653]
While the underlying host's storage should be encrypted when running multitenant workloads with Firecracker, there's value in adding another defense in depth layer by encrypting Firecracker's storage, potentially within the Firecracker process.

**Comment by 4x0v7** [comment]
I like this idea. How would we go about managing encryption keys though?
A key per microVM would be best. Something that utilizes AES-NI instructions from the host CPU would be the most performant; just thinking out loud here

**Comment by raduweiss** [comment]
Indeed, this should be per-microVM, and yes, if we can use AES-NI to not slow things down, that would be great. There's quite a lot to think through here:

1. Does we want to only have this feature for read / write drives?
1. How do we set up this API to have secure defaults but still allow for non-encrypted writes if the use case demands it? 
1. How will the read/write caches be handled?
1. How can we leverage existing tooling outside Firecracker (for example, to decrypt drives after Firecracker is done with them / to encrypt them before attaching).

... and probably many others.

**Comment by raduweiss** [comment]
Closing this, will turn it into a milestone.

**Comment by AlexandruCihodaru** [comment]
This approach is not something that we consider to be a good fit for Firecracker as there are ways for customers to handle this outside the uVM.
