### ISSUE TITLE
README links to missing production host setup document

### ISSUE THREAD

**Issue by bcantrill** [firecracker-microvm/firecracker#659]
This project looks really interesting!  The README makes reference to a "production host setup document", but links to a document (docs/prod-host-setup.md) that doesn't seem to exist. Is it possible to include this document, or a redacted version that contains the necessary configuration for the KVM host? (As I prowl around a bit more, it appears that this will be addressed by PR #657, but I am filing this nonetheless in case anyone else hits the same issue.)

**Comment by raduweiss** [comment]
You're right, this will be addressed by #657.
