### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by sampointer** [firecracker-microvm/firecracker#664]
https://github.com/firecracker-microvm/firecracker/blob/master/docs/prod-host-setup.md

https://github.com/firecracker-microvm/firecracker/blame/master/README.md#L52

**Comment by raduweiss** [comment]
Indeed. See #659 and #657.

**Comment by andrewkrug** [comment]
+1 on fix the https://github.com/firecracker-microvm/firecracker/blob/master/docs/prod-host-setup.md link.

**Comment by raduweiss** [comment]
Fixt.
