### ISSUE TITLE
Link to slack channel on website should link to invite to join slack channel

### ISSUE THREAD

**Issue by softprops** [firecracker-microvm/firecracker#666]
The how to contribute part of the website links directly to the slack cahnnel rather than the invite flow to join it. 

I think this can be fixed with an easy change from https://firecracker-microvm.slack.com/ to https://tinyurl.com/firecracker-microvm

![screenshot_20181127-214938](https://user-images.githubusercontent.com/2242/49083031-b9b93280-f28e-11e8-806f-a1c63bac4663.png)

**Comment by raduweiss** [comment]
Should be fixed. Please verify (probably refresh your browser cache) and close the issue if things look good.

**Comment by softprops** [comment]
@raduweiss fast turn around! Just verified. So excited about this project. The feedback loop is impressive :)

**Comment by cperciva** [comment]
FYI Slack is now saying

```
This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.
```

when I follow the link (https://tinyurl.com/firecracker-microvm) on the website.

**Comment by acatangiu** [comment]
@cperciva we're tracking this in #1298
