### ISSUE TITLE
KVM_EXIT_FAIL_ENTRY on Nested Virtualisation

### ISSUE THREAD

**Issue by BenHall** [firecracker-microvm/firecracker#668]
When running Firecracker (v0.11.0) within a VM that has the host CPU flags (VMX etc) and KVM support available, Firecracker crashes with `KVM_EXIT_FAIL_ENTRY`.

Motivation: Create a interactive tutorial at https://www.katacoda.com/firecracker-microvm to allow users to experiment and easily try out the approach. Also the ability to run on various Azure/GCP instances that support Nested Virtualisation. Also local development without requiring linux based laptop.

Related: Checks are in place to check that KVM is supported, I imagine some additional checks are required for nested virtualisation? https://github.com/firecracker-microvm/firecracker/pull/286

CPU Info: 
```
processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 3499.998
cache size      : 12288 KB
physical id     : 3
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms xsaveopt
bugs            :
bogomips        : 6999.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

<details>
<summary>Slack channel discussion</summary>
Ben_Hall [1:07 PM]
I'm trying out the example. I'm getting 204 responses from the HTTP calls. When I try to start the VM, firecracker crashes with `Received KVM_EXIT_FAIL_ENTRY signal` - Any ideas on how to debug this? :slightly_smiling_face:

dianpopa [1:10 PM]
On what architecture are you running?

Alexandra [1:10 PM]
Hi @Ben_Hall - that's a new one for us :slightly_smiling_face: 204 means the requests were successful, and https://lwn.net/Articles/658511/ suggests that `KVM_EXIT_FAIL_ENTRY` indicates a hardware failure to run your VM
lwn.net
Using the KVM API
Many developers, users, and entire industries rely on virtualization, as provided by software like Xen, QEMU/KVM, or kvmtool. While QEMU can run a software-based virtual machine, and Xen can run cooperating paravirtualized OSes without hardware support, most current uses and deployments of virtualization rely on hardware-accelerated virtualization, as provided on many modern hardware platforms. Linux supports hardware virtualization via the Kernel Virtual Machine (KVM) API. In this article, we'll take a closer look at the KVM API, using it to directly set up a virtual machine without using any existing virtual machine implementation.

Ben_Hall [1:11 PM]
@Alexandra @dianpopa It's running inside of a QEMU based system. It has the VMX flag passed to it...

dianpopa [1:13 PM]
Firecracker can only run on physical machines. We do not support nested virtualization
https://github.com/firecracker-microvm/firecracker/tree/master/tests#dependencies

Tarun Pothulapati [1:15 PM]
@dianpopa, I was able to run Firecracker, and it was really fast (as stated) . Great work. and regarding not supporting nested Virtualization, Is there any specific reason for not supporting it? Any challenged to support it?

Ben_Hall [1:16 PM]
@dianpopa Ah! I thought if it passed the host CPU down it would have been OK ? What's the underlying blocker? (edited)

Radu Weiss [1:18 PM]
@Ben_Hall @Tarun Pothulapati the core reason we have only developed for bare metal hosts so far is that we're trying to solve the container / serverless functions isolation problem as efficiently as possible. And nested virtualization has some performance penalties, and some security complexities added to it.

John Pignata [1:18 PM]
Congrats on shipping

Radu Weiss [1:18 PM]
That's not to say we'll never support it, especially if a good use case comes along.
@Ben_Hall I don't think we ever tried that so probably there's no answer off the top of our heads :slightly_smiling_face:
@John Pignata Thanks!
For now the best way to develop is on a linux-based laptop. Are you looking to use QEMU as a develpoment environment?

Ben_Hall [1:22 PM]
@Radu Weiss Thanks for the insight! I was actually writing a Katacoda scenario - https://www.katacoda.com/firecracker-microvm - I was hoping by setting the CPU flags to use the host it would have been OK :slightly_smiling_face: (edited)

Radu Weiss [1:27 PM]
Hey, that's a cool use case we never thought about. :slightly_smiling_face: Do you want to cut us an issue? It's probably the best way to handle this.

Ben_Hall [1:28 PM]
@Radu Weiss Sure thing! Thanks for the help.
</details>

**Comment by warmchang** [comment]
@BenHall You have already prepared the firecracker tutorial on katacoda, and the action is really fast. 👍

**Comment by aliguori** [comment]
What is the VM infrastructure?  It's probably a nested virtualization bug in the host but if you give more details we can happily look.

**Comment by BenHall** [comment]
One of the reasons for this was because we tried a using a VM with 16.04 4.4 Kernel (sorry!)

We've upgraded to 18.04 and 4.15.0-39-generic. We now no longer get the error, instead, firecracker just exits.

Will continue to investigate...

**Comment by BenHall** [comment]
We tried running this on a bare metal instance, with Kernel `4.15.0-29-generic`. We get the same action as within Katacoda where Firecracker just exits without any error messages.

I imagine this points toward something to do with the CPU ?

```
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
stepping	: 9
microcode	: 0x1f
cpu MHz		: 2745.292
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 6799.82
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by raduweiss** [comment]
Well, it definitely works on bare metal instances (e.g., for every PR we spin one up to run all integration tests). Some thoughts:

1. Do the integration tests work for you on that bare metal? Or on a physical laptop with host Kernel >=4.14? See the [getting started](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) guide for info on how to run them.
1. For reference, can you add here the exact sequence of terminal / Firecracker API and commands that you use?

**Comment by BenHall** [comment]
@raduweiss That's a good idea! Thanks.

**Comment by glikson** [comment]
It did work for me on a GCP VM with nested virtualization (Ubuntu 18). I've documented the steps at https://github.com/glikson/firecracker-gcp (can open a PR if such documentation could be useful here).

**Comment by aghecenco** [comment]
Closing is favor of #751 which tracks the nested virtualization support.

**Comment by BenHall** [comment]
Thanks @aghecenco - After investigating, I believe this is was due to an incorrect kernel version which firecracker didn't check on boot.
