### ISSUE TITLE
Usage of fcuvm build container

### ISSUE THREAD

**Issue by huksley** [firecracker-microvm/firecracker#687]
Currently for building the firecracker from source on command line 
you must pull development environment image **fcuvm/dev**

```bash
tools/devtool:77
# Development container image (name:tag)
DEVCTR_IMAGE="fcuvm/dev:latest"
```

This image does not have description or source Dockerfile it is built from:
https://hub.docker.com/r/fcuvm/dev/

Can you please provide **Dockerfile** or additional devtool command to create this image locally?

**Comment by raduweiss** [comment]
@huksley , the `Dockerfile` should be here:

https://github.com/firecracker-microvm/firecracker/blob/master/tools/devctr/Dockerfile

This is also linked from the [getting started](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) guide.

I've noted this down for addition to the FAQ. Closing the issue, reopen if you have additional questions.

**Comment by rn** [comment]
@raduweiss we should also fill out the details on hub. Like image description etc

**Comment by scottschreckengaust** [comment]
The DockerHub page could be more informational, a link to this GitHub repository at a minimum?

**Comment by omo** [comment]
And looks like you've done that? Thanks!
https://hub.docker.com/r/fcuvm/dev 

Would be sufficient to close this one I guess.

**Comment by huksley** [comment]
Looks good! Minor stuff to consider in further development is to streamline _naming_ i.e. here it is called `fcuvm/dev`, in repo it is `devctr` folder.
