### ISSUE TITLE
ERROR: networking failed to start

### ISSUE THREAD

**Issue by ggsonic** [firecracker-microvm/firecracker#696]
in my ubuntu host, run firecracker the way as doc said, outputs:
`Starting networking ...
 *   eth0 ...
sh: invalid number ''
sh: invalid number ''
sh: invalid number ''
sh: invalid number ''
ifconfig: SIOCSIFNETMASK: Address not available`

and 
`run-parts: /etc/network/if-up.d/firecracker-tap: exit status 1            [ !! ]
 * ERROR: networking failed to start`
then it starts
`* Starting sshd.eth0 ...`

not knowing how to handle this

**Comment by raduweiss** [comment]
Can you give us more info on the exact commands you ran to get to that error? Also where do you get the error: within the Firecracker guest, or on the Host?

**Comment by dianpopa** [comment]
Hi @ggsonic , 

We are aware of the errors you receive but they are benign ones. There are some leftover scripts inside the guest that are trying to configure networking for the VM. Indeed,  the getting-started doc does not specify anything about how to do that and we understand how those errors might be confusing. We are working on removing the scripts from the `ext4` sample provided in the doc. Will keep you posted here.

**Comment by dhrgit** [comment]
@ggsonic 
Please try downloading the [rootfs image](https://s3.amazonaws.com/spec.ccfc.min/img/hello/fsfiles/hello-rootfs.ext4) again. It's been updated and you shouldn't see any more networking errors popping up on the console.

**Comment by ggsonic** [comment]
@dhrgit I try the new rootfs image and the error tips gone, but the guest network still not working. I want to setup network-interfaces to let `apk update` work. 
in host(ubuntu 16.04),`ifconfig vmtap33 192.168.241.1/24 up`
then rpc `curl --unix-socket /tmp/firecracker.sock -i \
     -X PUT "http://localhost/network-interfaces/1" \
     -H  'Accept: application/json'          \
     -H "Content-Type: application/json" \
     -d '{
            "iface_id": "1",
            "host_dev_name": "vmtap33",
            "guest_mac": "06:00:00:00:00:01",
            "state": "Attached"
         }''`
in guest ,eth0 bring up, but no IP address, and `apk update` still failed

**Comment by dhrgit** [comment]
@ggsonic 
You can assign an IP address manually. In your microvm:
`ifconfig eth0 192.168.241.2 netmask 255.255.255.0 up`

If you want internet connectivity, you'll also have to:
- set up a default gateway:
  `ip route add default via 192.168.241.1`
- set up your DNS servers under `/etc/resolv.conf`

Also, on your Ubuntu host, you'll need to:
- enable IP forwarding
- set up NAT
- configure your firewall to allow traffic flowing through your `vmtap33` adapter.

**Comment by ggsonic** [comment]
@dhrgit  it worked! Thx a lot!
