### ISSUE TITLE
fault_message vs faultMessage

### ISSUE THREAD

**Issue by yuval-k** [firecracker-microvm/firecracker#701]
hello.
while the swagger spec mentions "faultMessage" as the field for errors, the code itself uses "fault_message".
it's a small difference but it effects generated client.

Could we change one or the other?
I'll be happy to submit a PR if you'll tell me which one to change.

**Comment by yuval-k** [comment]
the easier change would be to change the yaml to match the code. 
I am writing a go client (see here: https://github.com/solo-io/firecracker-go)

**Comment by raduweiss** [comment]
While `fault_message` still needs to get consistent, did you already take a look at https://github.com/firecracker-microvm/firecracker-go-sdk ?

**Comment by yuval-k** [comment]
yes saw that just after opening the issue - thanks for the reference

**Comment by yuval-k** [comment]
I plan to submit a PR there to support metadata son

**Comment by aghecenco** [comment]
Addressed by #713
