### ISSUE TITLE
docs: running firecracker in a VM

### ISSUE THREAD

**Issue by glikson** [firecracker-microvm/firecracker#707]
Would it be useful to include deployment instructions for developers who may want to test firecracker on GCP VMs using nested KVM? I outlined a draft at https://github.com/glikson/firecracker-gcp/blob/master/README.md - can work on a PR here.

**Comment by raduweiss** [comment]
@glikson , I was actually thinking that we need something like a `docs/dev-machine-setup.md` and then in there we can have instructions for:

- How to check if it works on your laptop / desktop (hopefully just `tools/devtool checkenv`).
- How to quickly set up a dev machine a cloud environment, and here we can take in instructions from contributors that have example steps for one cloud or another.

What do you think? Do you want to start up this doc and add the GCP instructions. I have some feedback on the write-up its self (mostly I think it can be simplified), but we can take those up in the PR.
