### ISSUE TITLE
Crate-Based Docs Not Generated / Linked To From Markdown Documentation

### ISSUE THREAD

**Issue by arun-gupta** [firecracker-microvm/firecracker#714]
https://github.com/firecracker-microvm/firecracker/blob/master/docs/design.md links to https://github.com/firecracker-microvm/firecracker/blob/master/docs/rate-limiter.md and gives a 404.

Thanks @jbeda

**Comment by raduweiss** [comment]
That documentation is in the [rate limiter crate](https://github.com/firecracker-microvm/firecracker/blob/master/rate_limiter/src/lib.rs).

**Comment by acatangiu** [comment]
Unreachable document has been removed.

Code documentation can be generated by `cargo doc` and includes documentation for all used crates.
