### ISSUE TITLE
method to query for threadID per vCPU

### ISSUE THREAD

**Issue by egernst** [firecracker-microvm/firecracker#718]
I would like the ability to query firecracker to gain cpu-information.  After digging through the [swagger API](https://github.com/firecracker-microvm/firecracker/blob/master/api_server/swagger/firecracker.yaml),  I see a "get" for machine configuration, but this returns only quantity of vCPUs (along with template, and other non-CPU information).

Specifically, I would like the ability to get on a per-vCPU basis the corresponding thread ID on the host.  
This would be similar to what I could achieve with query-cpus-fast with [QMP](https://qemu.weilnetz.de/doc/qemu-qmp-ref.html).  

As a consumer of firecracker VMM, this will help me with finer grain management of the vCPUs used by the guest (cpu-manager in k8s, cgroup constraints, etc.)

**Comment by egernst** [comment]
@nmeyerhans - please let me know if I'm mistaken and this is already available, or if this is something you're looking for as well.

**Comment by raduweiss** [comment]
So far our thinking was cgroups are great for fine tuning the CPU characteristics processes, and so we encourage folks to use the outer cgroup set up by the `jailer` for any fine tuning. Mapping of microVMs to cgroups on the system can be done via the `jailer` `--id` argument. There's an example in the [jailer docs](https://github.com/firecracker-microvm/firecracker/blob/master/docs/jailer.md#example-run-and-notes).

Does that fit your use case? Any feedback on the usability of this pattern is welcome.

As a sidenote, the jailer also takes a NUMA node argument, in case you want to let microVMs be scheduled freely but only within one NUMA node.

**Comment by egernst** [comment]
Hey Radu, This is fine so long as you are just supporting a single container pod scenario.  While there are other technical blocker I’ll hit first (for multicontainer pods), in K8S you can add CPU affinity on a per container granularity (see static CPU-manager), for example. This is where having thread ID to vCPU mapping is helpful. Cgroups only limits how much, not where. 

Not a show stopper, but something I noticed and figured I’d give early feedback on!  

I do appreciate how simple the interface w firecracker is now!

**Comment by raduweiss** [comment]
Ok, makes sense now. We'll have a chat about how to best expose that.

**Comment by egernst** [comment]
checking on once more on this, @raduweiss

**Comment by raduweiss** [comment]
Right, we had a quick chat about this in the team, the question we couldn't figure out is why the agent in the guest is not handling these things (e.g., the microVM get the right amount of vCPUs and then the agent inside handles CPU affinity / pinning / limiting via the usual guest OS tools.

If we somehow misunderstood the ask, let's just jump on a quick call (probably early next year) and clarify this quickly.

**Comment by dhrgit** [comment]
@egernst The Firecracker threads are named, such that `ps -T -p <firecracker pid>` should show you which thread corresponds to which vCPU. For instance:

```
  PID  SPID TTY          TIME CMD
24933 24933 pts/3    00:00:00 firecracker
24933 24935 pts/3    00:00:00 fc_vmm
24933 24966 pts/3    00:00:00 fc_vcpu0
24933 24967 pts/3    00:00:00 fc_vcpu1
24933 24968 pts/3    00:00:00 fc_vcpu2
24933 24969 pts/3    00:00:00 fc_vcpu3
```

Would that work for you?

**Comment by egernst** [comment]
Yes, this suffices! Thanks @dhrgit
