### ISSUE TITLE
Snap Package Support (Feature Request)

### ISSUE THREAD

**Issue by mikeroyal** [firecracker-microvm/firecracker#723]
I was thinking in the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by raduweiss** [comment]
We definitely don't mind. It's great if more people can use Firecracker easily.

Do you see this snap as a way to help development, or also as a way to distribute the software for production environments?

**Comment by mikeroyal** [comment]
@raduweiss, I feel it's useful for both development and distribution but for this use case, it will make distribution easier across Linux desktops, servers, and IoT devices in production environments.

**Comment by raduweiss** [comment]
We'd love to see such a snap package contribution 👍.

Some practical questions:

- How would updating work? E.g., when we release a new version of Firecracker, does the snap need to be re-built?
- How much can snap configure about the host system? For example, can all the security constraints in our [prod host setup doc](https://github.com/firecracker-microvm/firecracker/blob/master/docs/prod-host-setup.md) be ensured? The background here is that any Firecracker packaging format that conveys the message "install and you're good to run a production workload" should also ensure secure defaults on a system; otherwise we will not be upholding the security bar for our users/customers.

**Comment by mikeroyal** [comment]
@raduweiss  If you use something like build.snapcraft.io or TravisCI, you'll get per-commit or daily updates in the edge channel in the store with no additional work from you. When you do stable releases, you can "snapcraft release fd (releaseno) stable" and that will point the stable channel at that revision. It's possible to push beta releases to the beta channel so more technical users and committed community people can test it. But that's up to you. Essentially there's not a huge amount of maintenance in keeping the snap up to date. 

Security wise each snap is confined using a range of kernel isolation and security mechanisms, tailored to the snap, ensuring that vulnerabilities in the application are contained to the greatest degree currently possible. A careful review process ensures that snaps only receive the permissions they require to operate. Users do not have to make complex security decisions when installing the snap. You can read more about the security and configurations here [A guide to snap permissions and interfaces](https://blog.ubuntu.com/2018/11/01/a-guide-to-snap-permissions-and-interfaces).

**Comment by mikeroyal** [comment]
@raduweiss, sorry for the confusion on my part I will be making the snap for you guys. In my last post, I was trying to be as in-depth as possible of how the whole process works to answer any questions you may have had.

**Comment by raduweiss** [comment]
@mikeroyal got it, thanks!

**Comment by acatangiu** [comment]
@mikeroyal we're wondering if you're still looking at this

**Comment by mikeroyal** [comment]
Hi @acatangiu, yes I am here's the repo where I'm building the snap https://github.com/mikeroyal/firecracker-snap. I just need finish up the snapcraft.yaml config file and it will be ready for tesing.

**Comment by dianpopa** [comment]
[ ] Create the yaml file for building the Firecracker snap. Handled by #1075.
[ ] Push the Firecracker snap to store (maybe make this a part of our release  process).

**Comment by georgepisaltu** [comment]
Closing this as we don't currently have a customer use case.
