### ISSUE TITLE
Link in the repo description is not working

### ISSUE THREAD

**Issue by woernfl** [firecracker-microvm/firecracker#724]
Hey,

Just to let you know that the link in the repo description (http://firecracker-microvm.io) is not working.

![image](https://user-images.githubusercontent.com/28304331/49372886-73cff480-f6fc-11e8-9e7b-995fad3fe3e9.png)

I suppose there is a CNAME missing to redirect it to https://firecracker-microvm.github.io/ site?

Will be happy to help if needed :)

**Comment by raduweiss** [comment]
Looks like we need to touch up our DNS records. Not high priority right now.

**Comment by xavinux** [comment]
@raduweiss link seens to be working ok now.

**Comment by woernfl** [comment]
Yep, all good now.
