### ISSUE TITLE
Create a Tool to Check Prod Host Setup

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#726]
Create a tool that automatically checks a Linux host for all the recommended [prod configuration](https://github.com/firecracker-microvm/firecracker/blob/master/docs/prod-host-setup.md).

**Comment by sejr** [comment]
I'd be happy to tackle this. I imagine it would be best implemented as a script, similar to `devtool`?

**Comment by acatangiu** [comment]
Yes, ideally this would go in a separate script `prodtool` or a more inspired name. But please use a common scripting language to keep life simple 😄 

Right now this script could handle two commands:
- _can I run Firecracker on this system?_ - should check that all prerequisites for running Firecracker are satisfied.
- _Is my system production worthy?_ - should check and report all the necessary steps needed on the host system to provie safety and efficiency when running Firecracker.

These commands can be added independently and we can also iterate.

So @sejr, if you can tackle any of them, we're all for it! 🎉

**Comment by sejr** [comment]
@acatangiu Sounds good. I will just use bash to maintain consistency with devtool.

**Comment by raduweiss** [comment]
@sejr we're wondering if you're still looking at this.

**Comment by sejr** [comment]
@raduweiss My apologies — I was a bit busy with the holidays, but yes, I am still interested in working on this.

**Comment by aghecenco** [comment]
Addressed by #1054
