### ISSUE TITLE
How can I create guest kernel and guest rootfs?

### ISSUE THREAD

**Issue by wangwd1991** [firecracker-microvm/firecracker#732]
I am new to firecracker and kernel and rootfs.

Is there any docs can help me to create guest kernel and guest rootfs.

I want to do some test on centos5/6/7 with firecracker.  
So how can I do this?

Best regards.

**Comment by bkleiner** [comment]
I found myself in the same boat a few days ago.
So i created https://github.com/bkleiner/ubuntu-firecracker which builds a ubuntu image via docker (debian will follow shortly).
I'm pretty sure a similar approach could be taken for centos.

**Comment by raduweiss** [comment]
@bkleiner that's cool!

Are you ok with us including this in a documentation update sometime next week?

**Comment by bkleiner** [comment]
Sure. I'm also open to suggestions. The kernel config is somewhat of a guessing game right now, as i'm unsure whats needed for firecracker (besides the virtio drivers).
Maybe also include https://github.com/bkleiner/debian-firecracker

**Comment by acatangiu** [comment]
I think we need to add the location of our suggested kernel config somewhere visible in the documentation as people are not finding it easily.

@bkleiner it doesn't need to be a guessing game, see here: https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config

**Comment by bkleiner** [comment]
@acatangiu I actually saw that, I based my config of that, but since it's a rather complete config it does not tell me which options are hard requirements. It would be nice to have at least some idea about which these are.

**Comment by yuval-k** [comment]
I've also done a small writeup on how to make kernels from linux kit to work with firecracker:
https://github.com/solo-io/unik/blob/master/docs/compilers/firecracker/make_artifacts.md#get-a-kernel-from-linuxkit

**Comment by wangwd1991** [comment]
> I found myself in the same boat a few days ago.
> So i created https://github.com/bkleiner/ubuntu-firecracker which builds a ubuntu image via docker (debian will follow shortly).
> I'm pretty sure a similar approach could be taken for centos.

Thanks.

It can works on kernel 4.14+.
But Centos5 and Centos6 is base on kernel 2.6.x, and the Centos7 is on kernel 3.10.x.
As I found, that no any restriction on the guest kernel version. 
Does it support the low version kernel?
