### ISSUE TITLE
CII Best Practices badge at CNCF Landscape

### ISSUE THREAD

**Issue by arun-gupta** [firecracker-microvm/firecracker#739]
Firecracker is shown in the CNCF landscape: https://landscape.cncf.io/format=landscape&selected=firecracker

It does not have the `CII Best Practices` badge. It is not a requirement for us but general good practices followed by CNCF graduating projects.

More details at https://bestpractices.coreinfrastructure.org/en/projects

**Comment by alindima** [comment]
We're not currently pursuing this endeavour
