### ISSUE TITLE
api: PutMMDS and GetMMDS a little too loose

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#749]
I am working on the `firecracker-go-sdk` side of things and I noticed that `PutMMDS` and `GetMMDS` have an arbitrary value. I am wondering if we can make this a little more specific, like needs to be a map rather just something arbitrary.

Is there an actual use case for sending something like "hello"? Would it make more sense to just represent this as a JSON string instead of an object?

**Comment by aghecenco** [comment]
Hi @xibz,

`PutMMDS` and `GetMMDS` take arbitrary values by design. It's up to users what they want to keep in Firecracker's MMDS data store, so how you'd store the `hello` string depends on your use case, and how the data structure returned by `GetMMDS` helps your client.
