### ISSUE TITLE
Explicit error message when multiqueue tap device used as backend

### ISSUE THREAD

**Issue by mcastelino** [firecracker-microvm/firecracker#750]
If firecracker is passed a multiqueue tap device created using

```
ip tuntap add name tap0 mode tap multi_queue
```

It reports an error

```
[PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:Cannot open TAP device. Invalid name/permissions. CreateTap(
Os { code: 22, kind: InvalidInput, message: Invalid argument })}
```

Does firecracker not support multi-queue tap devices?

**Comment by alexandruag** [comment]
Hello, you are right, we do not currently support multi-queue TAP devices. We might at some point, because it's a relatively low hanging fruit, but there are no clear plans right now.

**Comment by egernst** [comment]
Hey @alexandruag - pardon me if I'm missing; is it feasible to return an error here so it is clear?  In our case, we determined there's an error because we noticed firecracker was creating its own tap instead of utilizing ours.  Being more explicit may be helpful?

**Comment by raduweiss** [comment]
On multi-queue tap devices, I've just read a bit of the docs to understand what they do. Now I'm wondering what the use case for them is. @egernst , what is Kata using it for?

**Comment by mcastelino** [comment]
@raduweiss 

> On multi-queue tap devices, I've just read a bit of the docs to understand what they do. Now I'm wondering what the use case for them is. @egernst , what is Kata using it for?

We use multiqueue to achieve higher throughput. We scale up the number of queues based on the number of vCPUs till we reach the point of diminished returns. Inside Kata we enable multiple queues also on the interface.

**Comment by mcastelino** [comment]
> Yea, providing friendlier, non-misleading error messages is definitely something we'll iterate through (PRs welcome :D). The part where Firecracker starts creating interfaces by itself when run with the appropriate capabilities is tricker to get rid of, due to how open/create works for TAP interfaces. We could check for the existence of the specified interface beforehand, but that's kinda awkward and adds overhead. Btw, why are you running Firecracker with elevated privileges? Vsock, I guess?

@alexandruag we pre-create the network interface and send it into firecracker. Yes we need vsock today as we need a method to setup a communication channel between the host and the agent we run within the VM. We are open to alternate mechanisms too. Currently we found the vsock is the one that is easiest for us to use with firecracker as kata already has support for the same. We also support virtio-serial, but firecracker currently does not have support for it.

**Comment by alexandruag** [comment]
The current (experimental) `vsock` support makes use of `vhost`, and elevated privileges are required for the initial setup phase. The final `vsock` implementation will not be `vhost`-based, so you'll be able to run Firecracker as a regular process.

**Comment by aghecenco** [comment]
See also https://github.com/cloud-hypervisor/cloud-hypervisor/pull/741

**Comment by jeromegn** [comment]
We're also interested by this. For now we're just setting a bigger TX queue on our tap interfaces.

**Comment by shilezhi1024** [comment]
> See also [cloud-hypervisor/cloud-hypervisor#741](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/741)

maybe like this: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/409/commits
