### ISSUE TITLE
Return error when attempting to open a non-existing tap device

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#754]
Currently, if Firecracker has the `CAP_NET_ADMIN` capability set and is asked to open a tap device that has not been previously created on the host, it creates it first and opens it. The name of the new tap device is `vmtap${INTERFACE_ID}`. This can lead to confusion therefore it would make sense for Firecracker to simply not allow opening non-existing tap devices.

**Comment by andreeaflorescu** [comment]
Not sure if this is going to be possible with our current implementation. I can't find any official documentation, but looking at the kernel code it looks like the ioctl TUNSETIFF is going to create the tap device if it does not exist.

**Comment by cmannett85** [comment]
I have written an [implementation](https://github.com/cmannett85/firecracker/commit/08df645fc928275b8e9b7e77cff300ce1f058a3c) of this that works as expected with basic manual testing.  However I don't know how to unit test it as all the tests relied on `Tap::open_named(..)` to create the TAP if it doesn't exist.

I [started an attempt](https://github.com/cmannett85/firecracker/commit/8cae250eee3898e99e7367d77b15fbfc8e48b905) by changing the TAP to a multi-queue type so I could create the TAP in the relevant unit tests before having the API open it - but this broke other unit tests that relied on a TAP device not being able to be opened twice.  This also required that a method be exposed that still created a TAP as other crates' unit tests needed this ability.

The only alternative I can think of is using a system call `ip tuntap add ...` inside the tests that require it, the downside is that the device is created with the `IFF_PERSIST` flag set and so must be manually deleted with `ip tuntap del ...`.  Does anyone have any better suggestions?

**Comment by aghecenco** [comment]
@cmannett85 your solution relies on `/sys` which is unavailable in the jail, which Firecracker should always be running in per the security recommendations. Outside of `/sys`, I don't know of any native (ioctl-only) way to find out if a tap already exists. And I don't think `/sys` should be mounted in the jail - only the basic requirements should be present there, and I don't believe this qualifies as one. If you can't think of any other way to check this (I can't), I think the best thing to do is to close the issue.

**Comment by dianpopa** [comment]
Double checked in the kernel code if there is any native way we could use to detect whether a tap device already exists. Could not find one. Closing this since no other viable way to implement the proposed enhancement was found.

**Comment by raduiliescu** [comment]
You can also use netlink sockets to list the netdevices. But I am not sure if that is allowed through our Seccomp and if we want to allow it.

**Comment by dianpopa** [comment]
oh  that is indeed an interesting alternative. But yeah, extending the seccomp filter is something we should be careful about and apart from this, I see that making use of netlink sockets require quite a large amount of code and I am not sure that the value it brings is worth the effort of developing and maintaining it.
