### ISSUE TITLE
Firecracker on The Changelog?!

### ISSUE THREAD

**Issue by jerodsanto** [firecracker-microvm/firecracker#760]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of software development since '09.)_

We'd love to have you on the show sometime soon. Who would be the best person to join us to talk about Firecracker and all the cool stuff y'all are up to?

Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by raduweiss** [comment]
@jerodsanto & The Changelog editors, thank you for your invitation, but at the time the maintainers are focusing most of our time on improving Firecracker and supporting integrations with the container community, so we will have to decline.

**Comment by jerodsanto** [comment]
No problem @raduweiss holler at us when your situation changes ✊
