### ISSUE TITLE
Log with the DEFAULT_INSTANCE_ID when the instance ID is not initialized

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#763]
If Firecracker is run outside the jailer and doesn't have a configured instance ID, the logger does not prepend the default instance ID to the messages and the output starts with a blank field:
```
[:ERROR:vmm/src/lib.rs] <..text>
```
The logger should prepend an instance ID and not leave that field blank.

**Comment by jabedude** [comment]
@aghecenco I'd like to take this issue if possible!

**Comment by dianpopa** [comment]
@jabedude Sure, go ahead. We appreciate any contribution!

**Comment by jabedude** [comment]
@dianpopa I was able to get the default instance ID to appear in log messages by simply changing the LOGGER.init() call in src/main.rs to use DEFAULT_INSTANCE_ID instead of an empty string. Is that correct or am I completely misunderstanding the logger crate?

**Comment by acatangiu** [comment]
@jabedude I think you should post a PR and we can review and then iterate changes if necessary.

**Comment by aghecenco** [comment]
Addressed in #765
