### ISSUE TITLE
Address in use and yet checking the ports shows nothing. What does this error mean?

### ISSUE THREAD

**Issue by Jani93** [firecracker-microvm/firecracker#766]
[:ERROR:src/main.rs:49] Panic occurred: PanicInfo { payload: Any, message: Some(Failed to open the API socket: IO Error: Io(Os { code: 98, kind: AddrInUse, message: "Address in use" })), location: Location { file: "src/main.rs", line: 130, col: 37 } }
2018-12-12T14:00:16.176025215 [:ERROR:src/main.rs:53] stack backtrace:
2018-12-12T14:00:16.176069917 [:ERROR:src/main.rs:57] Failed to log metrics while panicking: Logger was not initialized.
Aborted

**Comment by dianpopa** [comment]
Hi @Jani93 ,

That error means the socket that you are trying to bind firecracker to (the one that you specify with --api-socket parameter, default value is /tmp/firecracker.socket) is already in use (meaning the file associated with it already exists on disk and cannot be reused for a new connection). You need to make sure that when running firecracker the file associated with the socket does not exist.

**Comment by bbros-dev** [comment]
I think this error should return some text like:
```
<file> exists. Ensure --api-socket <file> does not exist.
```

Where the `<file>` is replaced by the actual file name passed in.
