### ISSUE TITLE
Run Integration Tests with Last 2 Upstream Stable or LTS Kernels for Guest & Host

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#770]
This issue implies figuring out the host / guest support model for Firecracker. The current proposal is to support Firecracker for the latest 2 stable or LTS branch upstream Linux kernels.

Once the support model is defined, we need to create automation for updating the integration test host and guest images with the in-support kernels. This includes updating the [guest Linux kernel config tweaked to meet Firecracker's specifications](https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config) at every cycle.

**Comment by ad-m** [comment]
"updating the integration test host" the use of nested virtualization should allow the use of the appropriate CI platform instead of the dedicated hosts requiring updating. Eventually we need list of AMI images & Linux kernel version and spawn for each build short-live bare metal instance (possible due PXE).

**Comment by raduweiss** [comment]
Yes, you're right, updating the existing images (automatically) is the way to go. My write-up was not very clear :smile: I meant this: "update both of the intergration test images: the host image (AMI), and the guest image (kernel binary)".

As for nested virt, one thing that we do wih integration testing is prevent performance regression (and we plan to add more tests for network / storage throughput, as well as high-density scenarios). The test performance thresholds are calibrated for bare metal workloads. This is because that's where we (currently) get the best performance, which is the one that's relevant for real-life production use cases.

**Comment by dianpopa** [comment]
We now have a kernel policy in place that details currently tested kernel versions: https://github.com/firecracker-microvm/firecracker/blob/main/docs/kernel-policy.md.
