### ISSUE TITLE
Seccomp: only allow certain ioctls on /dev/kvm

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#779]
The seccomp filters for `sys_ioctl` allow any fd to be passed. Since /dev/kvm is opened by the jailer and the fd is known, the filters for `sys_ioctl` should restrict the syscall to this fd alone.

**Comment by acatangiu** [comment]
AFAIK IOCTLs are also done on the vCPUs FDs, but we know those too before the seccomp filter is installed, so we could whitelist them too and then get a very tight control on the `ioctl` syscall.

**Comment by fristonio** [comment]
Hey! @aghecenco Can I work on this issue?
If I understood this correctly then we need to apply a Seccomp filter on first argument(file descriptor) for KVM related IOCTLs? and this fd should correspond to https://github.com/firecracker-microvm/firecracker/blob/master/jailer/src/lib.rs#L35
@acatangiu can you point me to the code for the IOCTLs related to vCPUs that you mentioned.

**Comment by aghecenco** [comment]
Hey @fristonio, sure! Yes, indeed, the first argument would need to be restricted. There are several sources for potential fds:
* `/dev/kvm`
* vcpu fds (the ones @acatangiu was talking about) - check out functions like [`setup_fpu`](https://github.com/firecracker-microvm/firecracker/blob/f25da0e3ca037ca10361af3ba5a0c70491df0e8d/arch/src/x86_64/regs.rs#L52) for example; look out for functions that operate on vcpu fds in that area
* tap devices, sockets etc

This issue refers strictly to the ioctls executed on `/dev/kvm`. Those are the most too, so feel free to start there :slightly_smiling_face:

**Comment by fristonio** [comment]
Hey! Sorry for late reply. Was busy working on the clippy issue.

The logic for creating kvm is now changed in here https://github.com/firecracker-microvm/firecracker/commit/f72b08d5e474ffd831196af820700c84d05fc94d#diff-8e4517256c6e97ab307cf7bb3ea3daffL32 so we cannot get a constant KVM_FD, this instead is determined by creating a new KVM context in `/vmm/src/lib.rs`. Now the only way we can get kvm fd is by using `Vmm` struct using `Vmm.kvm.fd()`.

With this change the way I see to get the fd for kvm is by sending it in the https://github.com/firecracker-microvm/firecracker/blob/master/vmm/src/lib.rs#L1153 function call and then using that to set up restriction on fd argument. Same goes for vCPU seccomp call. Does this sound good, or am I missing something here?

**Comment by andreeaflorescu** [comment]
Hey @fristonio as we discussed offline this issue is no longer in scope. There are two reasons why:
- the KVM fd is no longer static as you already identified it. We also get the KVM fd from calling new so we are as safe as we can be in terms of using the right file descriptor for calling ioctls.
- there is no point in further restricting the syscalls corresponding to the KVM API (besides checking the syscall number) because calling ioctls on a file descriptor that is not corresponding to `/dev/kvm` will fail anyway.
