### ISSUE TITLE
Remove `backtrace` version hardcode

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#780]
We needed to hard-code the version of the `backtrace` crate to the latest functional one for us (i.e 0.3.9). `cargo update` would give us a crate dependency that triggers unit test failure. See more in [upstream issue](https://github.com/alexcrichton/backtrace-rs/issues/146).

**Comment by dianpopa** [comment]
Removed hardcoded version. Ran `cargo update`. backtrace version 0.3.13 was downloaded. Unfortunately, `sudo env "PATH=$PATH" RUST_TEST_THREADS=1 RUST_BACKTRACE=1 cargo test --all -- --nocapture` still fails.

**Comment by aghecenco** [comment]
Closed by #832
