### ISSUE TITLE
Block Device Rescan: Always reports error

### ISSUE THREAD

**Issue by mcastelino** [firecracker-microvm/firecracker#783]
We use block device rescan to swap disks at runtime. And this API works. However the call to the API always returns an error even if rescan is called after the VM is up and running. 

The error reported is:
`[PUT /actions][400] createSyncActionBadRequest  &{FaultMessage:Payload is required for block device rescan.}` 

What should the payload value be set to?

A simple program to duplicate the same https://github.com/mcastelino/fireclient/blob/topic/hotplug-disk/instance.go#L258

**Comment by mcastelino** [comment]
Setting the payload to the drive id seems to address the issue. However it would still be good to understand what the payload needs to be set to.

Also can you patch multiple drives and issue a single rescan.

https://github.com/mcastelino/fireclient/commit/d8967cc6e398b2a78d268341ef01eedd9bfecf14

**Comment by andreeaflorescu** [comment]
> Setting the payload to the drive id seems to address the issue. However it would still be good to understand what the payload needs to be set to.

The payload needs to be set to the drive id corresponding to drive that needs the rescan. We should add documentation for this, so I created an issue to address it: https://github.com/firecracker-microvm/firecracker/issues/786

> 
> Also can you patch multiple drives and issue a single rescan.

Nop, you can patch one drive at the time. The payload is one drive id.

> 
> [mcastelino/fireclient@d8967cc](https://github.com/mcastelino/fireclient/commit/d8967cc6e398b2a78d268341ef01eedd9bfecf14)

**Comment by mcastelino** [comment]
@dhrgit @andreeaflorescu 

Could you clarify two things
- If patch triggers re-scan when is an explicit re-scan required
- Is rescan required if you do not actually switch the backing store, but the contents of the backing store change due to a host side update? If so how will that work as the VM kernel/drivers will not like host side updates

/cc @nmeyerhans

**Comment by mcastelino** [comment]
Can we have RO block devices (RO from VM point of view), where the host can update and issue a rescan?

**Comment by andreeaflorescu** [comment]
It does support ro devices. If it doesn't it's a bug somewhere.

**Comment by aghecenco** [comment]
Rescan does support RO devices. The [unit tests](https://github.com/firecracker-microvm/firecracker/blob/bdf782fccd708e50ab2d5291580625e2a01a01ce/vmm/src/lib.rs#L2579) trigger rescans on RO scratch drives and the integration test does the same for a rw drive.
