### ISSUE TITLE
KVM: check if there's some KVM emulated CPUID that we can use

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#791]
According to the documentation:

> KVM_GET_EMULATED_CPUID ioctl returns x86 cpuid features which are emulated by kvm.Userspace can use the information returned by this ioctl to query which features are emulated by kvm instead of being present natively.

But 2 rows below there is also this thing:

> Features like x2apic, for example, may not be present in the host cpu but are exposed by kvm in KVM_GET_SUPPORTED_CPUID because they can be emulated efficiently and thus not included here.

We should check what's with this ioctl, maybe there's something that we can use from the emulated CPUID?

**Comment by pkj415** [comment]
@dianpopa can you assign this to me, interested to work on it
