### ISSUE TITLE
Long boot time

### ISSUE THREAD

**Issue by caoruidong** [firecracker-microvm/firecracker#792]
I boot firecracker with 2 cpus and 256M memory in a bare metal with Xeon(R) CPU E5-2620. From logs, I see Guest-boot-time is about 290ms. How do you achieve <125 ms?

**Comment by aghecenco** [comment]
Hi @caoruidong, the 125ms time was achieved on an [i3.metal](https://aws.amazon.com/blogs/aws/new-amazon-ec2-bare-metal-instances-with-direct-access-to-hardware/) host with a custom 4.14 kernel built with [this config](https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config).

**Comment by andreeaflorescu** [comment]
Hi, to debug this problem we will need some additional info. Can you share the Firecracker logs with us? Also, what rootfs are you using? Can you check the boot time using the both the kernel & the rootfs from our S3 bucket spec.ccfc.min?

**Comment by caoruidong** [comment]
@andreeaflorescu Yes, I truly use the kernel and rootfs from S3 bucket.
@acatangiu It really makes sense. I try the boot args in that script, and get 126 ms. So it is better to interact with vm by sshd？

**Comment by acatangiu** [comment]
@caoruidong yes, definitely better to use ssh to interact with your VM if you have networking enabled in it.
The UART/Serial Console is an old and inefficient device 😄

**Comment by caoruidong** [comment]
OK thank you all for answering
