### ISSUE TITLE
DriveID errors with non alphanumeric values

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#794]
Looks like the validation of checking consistency of the drive ID in the URL and body without URL decoding of the URL param is causing issues.

```bash
DEBU[0000] PUT /drives/%21 HTTP/1.1
Host: localhost
User-Agent: Go-http-client/1.1
Content-Length: 90
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{"drive_id":"!","is_read_only":false,"is_root_device":false,"path_on_host":"./drive.img"}
```

Solution could be to either support only alphanumeric drive ids or url decode the drive ID before comparison.

**Comment by aghecenco** [comment]
Closed by  #806
