### ISSUE TITLE
Jailer ID can be empty resulting in overwriting of data

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#795]
If you run the jailer with ID set to `""`, this will cause the default path of `/srv/jailer/firecracker/<id>/root` to now be `/srv/jailer/firecracker/root` which would then constantly override things which seems to be incorrect behavior. I am guessing there needs to be validation to check whether or not the ID is empty.

**Comment by andreeaflorescu** [comment]
Hey, thanks for catching this. I will be working on a fix.

**Comment by xibz** [comment]
Awesome! Thasnks @andreeaflorescu for getting this done.
