### ISSUE TITLE
Enable seccomp by default when running without jailer

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#800]
We enabled seccomp by default only when starting Firecracker via jailer. We should also enforce this for running Firecracker without the jailer.

For this, we should just change the default value of `seccomp_level` to 2 in `src/main.rs`.

**Comment by acatangiu** [comment]
This is already part of https://github.com/firecracker-microvm/firecracker/pull/798, I will close this issue when that PR gets merged.
