### ISSUE TITLE
Improve documentation and comments on expects/unwraps

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#808]
We need to clarify our use of `unwrap`s and `expect`s throughout the code (i.e. gracefully terminate program execution in case of invariant being violated).

**Comment by andreeaflorescu** [comment]
One common usecase that we have to consider is `dev/kvm` not having the proper permissions.

**Comment by bbros-dev** [comment]
Specifically, the instruction to reset this after rebooting (login out to be confirmed) needs to go into the [Getting Started](https://github.com/firecracker-microvm/firecracker/blame/b61369a5bc415091f4bdeb6e37598262470be6a1/docs/getting-started.md#L21).

It does not seem to be the case that the `setfacl` needs to be reset after each invocation of firecracker (see this [comment](https://github.com/firecracker-microvm/firecracker/issues/836#issuecomment-453095836)).
However, my machine has had enough changes I'm not sure if that is true for a vanilla installation.

**Comment by alindima** [comment]
Related to https://github.com/firecracker-microvm/firecracker/issues/593
