### ISSUE TITLE
GCE dev-machine steps need an update

### ISSUE THREAD

**Issue by arun-gupta** [firecracker-microvm/firecracker#818]
Here are the issues with dev-machine-setup for [GCP](https://github.com/firecracker-microvm/firecracker/blob/master/docs/dev-machine-setup.md#gcp):

- In first step, a space before and after `=` breaks the copy/paste
- `gcloud compute disks create` command fails without explicitly specifying the project. The updated command is:

    ```
    gcloud compute disks create ${FC_VDISK}   --image-project ubuntu-os-cloud --image-family ubuntu-1804-lts --project ${FC_PROJECT}
    ```
- Updated command fails with the following error:

    ```
    gcloud compute disks create ${FC_VDISK}   --image-project ubuntu-os-cloud --image-family 
    ubuntu-1804-lts --project ${FC_PROJECT}
    API [compute.googleapis.com] not enabled on project [175661354881]. 
    Would you like to enable and retry (this will take a few minutes)? 
    (y/N)?  yes

    Enabling service [compute.googleapis.com] on project [175661354881]...
    ERROR: (gcloud.compute.disks.create) FAILED_PRECONDITION: Operation does not satisfy the following requirements: billing-enabled {Billing must be enabled for activation of service '' in project 'arun-firecracker' to proceed., https://console.developers.google.com/project/arun-firecracker/settings}
    ```

   Billing account has to explicitly associated by following the instructions in the error message.
- In step 3, a space before and after `=` breaks the copy/paste

**Comment by dianpopa** [comment]
The aforementioned problems were fixed by #2502.
