### ISSUE TITLE
Basic disk setup guide

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#824]
It would be useful to write a doc describing how to build a custom disk image which can then be used to run a Firecracker guest. A good starting point seems to be https://github.com/bkleiner/ubuntu-firecracker, but some standalone instructions are probably very helpful as well.

**Comment by thepwagner** [comment]
This may have been https://github.com/firecracker-microvm/firecracker/pull/1005

**Comment by serban300** [comment]
Good point. Thanks ! Closing the issue.
