### ISSUE TITLE
Update dev-machine-setup document

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#825]
Fill in the missing sections in [dev-machine-setup.md](../blob/master/docs/dev-machine-setup.md) (and also fix & update as necessary).

1. Related to #818.
2. Instructions for AWS incoming in #817.

**Comment by xavinux** [comment]
**Intel Virtual Machine configuration on Proxmox**  #939

**Comment by xavinux** [comment]
**Intel Virtual Machine configuration on Proxmox** #939

**Comment by xavinux** [comment]
#939

**Comment by dianpopa** [comment]
1. The GCE setup was fixed in #2502.
2. AWS setup was merged.
