### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#826]
Add the following items to the [FAQ](../blob/master/FAQ.md):
- [ ] Discuss the entropy sources available to the guest, `rdrand`, and `rdseed`(#663)
- [ ] The location of the dev container Docker file.
- [ ] Discuss the minimum guest/host kernel. Point to the provided kernel config.
- [x] Reference the basic network configuration and disk image creation guides once they become available.
- [x] Mention some of the frequently encountered cryptic errors, such as `Kvm(Error(2))` meaning `/dev/kvm` cannot be found. Alternatively, have prettier error messages.

**Comment by acatangiu** [comment]
This issue is out of date, closing.
