### ISSUE TITLE
Small fix for getting-started doc

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#827]
Add renaming the Firecracker binary to `firecracker` and making it executable via `chmod +x` as additional steps at the end of **Getting the Firecracker Binary** from [getting-started.md](../blob/master/docs/getting-started.md).

**Comment by RobertDev** [comment]
The PR for addressing this one has been merged.

**Comment by acatangiu** [comment]
Fixed by https://github.com/firecracker-microvm/firecracker/pull/862.
