### ISSUE TITLE
Fix initial logger state

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#828]
There are a couple of issues related to the state of Firecracker logging right now:
- The jailer logs all of its messages to stdout/err, which is not really compatible with running daemonized. 
- We should encourage customers to make an explicit choice regarding the destination of logs/metrics, as opposed to having them off (or sent to `/dev/null`) by default.
One solution is to ensure the user specifies destinations for logs and metrics via Jailer parameters. These can be passed on to Firecracker either as file descriptors, or by name.

**Comment by jeromegn** [comment]
This would benefit us a lot. For now, we're going to have to run this through a different process to redirect stdout and stderr where we want them.

**Comment by lauralt** [comment]
I've picked this up.

**Comment by lauralt** [comment]
Closing this isssue since #1361 is merged and now we can configure the logger for Firecracker via command line parameter. At this moment we do not want this option for jailer, but if we change our mind, we'll reopen it.

**Comment by jayavanth** [comment]
I'm still getting it in the latest version

**Comment by a74731248** [comment]
> There are a couple of issues related to the state of Firecracker logging right now:
> 
> * The jailer logs all of its messages to stdout/err, which is not really compatible with running daemonized.
> * We should encourage customers to make an explicit choice regarding the destination of logs/metrics, as opposed to having them off (or sent to `/dev/null`) by default.
>   One solution is to ensure the user specifies destinations for logs and metrics via Jailer parameters. These can be passed on to Firecracker either as file descriptors, or by name.

when i use the follow api command, the error still occur:
```
curl --unix-socket /tmp/firecracker.socket -i \
    -X PUT "http://localhost/metrics" \
    -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -d "{
             \"metrics_path\": \"metrics.fifo\"
    }"
```
how can do solve this, I donot know how to specify the path of logs/metrics by using API command. Or how can I turn off the log
