### ISSUE TITLE
Documenting Out of memory: Cannot create VMM.: Vm(VmFd(Error(12)))

### ISSUE THREAD

**Issue by kennu** [firecracker-microvm/firecracker#835]
The [getting started document](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) is very nice but doesn't mention you need enough free memory to run Firecracker. In my case, I was running some other things on the computer and got *Cannot create VMM.: Vm(VmFd(Error(12)))*.

By releasing some memory, I was able to make Firecracker run. Perhaps this could be mentioned in the guide briefly? The error message requires you to know that error 12 is ENOMEM..

Before:

                  total        used        free      shared  buff/cache   available
    Mem:           3.8G        918M        107M        9.0M        2.8G        2.5G
    Swap:          4.0G        106M        3.9G

After:

                  total        used        free      shared  buff/cache   available
    Mem:           3.8G        188M        1.6G        2.9M        2.1G        3.3G
    Swap:          4.0G         79M        3.9G

**Comment by andreeaflorescu** [comment]
This looks like a good entry for the [FAQ.md](https://github.com/firecracker-microvm/firecracker/blob/master/FAQ.md). We can also specify that you need to have enough memory as part of the [Running Firecracker](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#running-firecracker) section.

**Comment by dhrgit** [comment]
Having enough memory seems like a pretty generic prerequisite for running any process. No need to clutter a guide with this info.

Agreed though, that we could use some more friendly error reporting. In the meantime, using the FAQ to untangle this kind of cryptic messages indeed sounds like a good idea.

**Comment by kennu** [comment]
Note that having free swap was not enough: you have to have free physical memory. That's what surprised me.

**Comment by xavinux** [comment]
Can I help with this issue?

**Comment by aghecenco** [comment]
@xavinux sure! #854 should have taken care of the error display format; the FAQ item still needs to be written :slightly_smiling_face:

**Comment by andreeaflorescu** [comment]
Fixed by #1450
