### ISSUE TITLE
Jailer lacks support for cgroups v2

### ISSUE THREAD

**Issue by acipu-aws** [firecracker-microvm/firecracker#841]
The regex in Cgroup::new only matches cgroups v1. Per the [man page](http://man7.org/linux/man-pages/man7/cgroups.7.html), cgroups v2 has a single hyerarchy, so specifying the type of controller in the options is no longer feasible. From the controllers used, cpu and pids are both supported in v2.

The jailer should be aware of both cgroups v1 and v2 and adapt the creation code accordingly.

**Comment by acipu-aws** [comment]
Extract from a /proc/mounts that fails:

`none /cgroups/cpu cgroup2 rw,relatime 0 0`
`none /cgroups/cpuset cgroup rw,relatime,cpuset 0 0`

**Comment by jdoss** [comment]
Are there any plans to support cgroups v2? I see there was a PR to add support for both v1 and v2 but it never got merged. :(

**Comment by jdoss** [comment]
@alindima I am looking to use Firecracker on Fedora CoreOS which is moving to cgroups v2 by default on the Stable channel.

https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/thread/V6OSIUOL5ICEP7WMXLJ2NI47EFNQ3MYF/

**Comment by alindima** [comment]
> @alindima I am looking to use Firecracker on Fedora CoreOS which is moving to cgroups v2 by default on the Stable channel.
> 
> https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/thread/V6OSIUOL5ICEP7WMXLJ2NI47EFNQ3MYF/

Thanks for the info! From what I quickly read in the link you pasted, it seems that Fedora CoreOS is enabling cgroups v2 by default, but preserves the v1 compatibility, is that right?

I'm trying to gauge if this would be a blocker for your use case or more of a nice to have.

**Comment by jdoss** [comment]
It is a blocker for my use case. Currently right now on FCOS next and testing streams which runs as cgroups v2 you cannot launch the jailer command with the below example: 

```
$ fgrep VERSION /etc/os-release
VERSION="34.20210518.1.0 (CoreOS)"
$ cat /proc/mounts |grep cgroup
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
$ grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
$ sudo ./jailer-v0.23.4-x86_64 --id 551e7604-e35c-42b3-b825-416853441234 --cgroup cpuset.mems=0 --cgroup cpuset.cpus=$(cat /sys/devices/system/node/node0/cpulist) --exec-file ./firecracker-v0.23.4-x86_64 --uid 123 --gid 100 --daemonize
thread 'main' panicked at 'Jailer error: cpuset configurations not found in /proc/mounts', src/jailer/src/main.rs:356:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

This works fine on the stable stream that is still on cgroups v1:

```
$ fgrep VERSION /etc/os-release
VERSION="34.20210427.3.0 (CoreOS)"
$ cat /proc/mounts |grep cgroup
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755,inode64 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
$ grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
$ sudo ./jailer-v0.23.4-x86_64 --id 551e7604-e35c-42b3-b825-416853441234 --cgroup cpuset.mems=0 --cgroup cpuset.cpus=$(cat /sys/devices/system/node/node0/cpulist) --exec-file ./firecracker-v0.23.4-x86_64 --uid 123 --gid 100 --daemonize
$ sudo ls -al /srv/jailer/firecracker-v0.23.4-x86_64/551e7604-e35c-42b3-b825-416853441234/root/
total 2000
drwx------. 4  123 users      62 May 27 19:46 .
drwxr-xr-x. 3 root root       18 May 27 19:46 ..
drwx------. 3  123 users      28 May 27 19:46 dev
-rwxr-xr-x. 1 root root  2046696 May 27 19:46 firecracker-v0.23.4-x86_64
drwx------. 2  123 users      32 May 27 19:46 run
```

**Comment by alindima** [comment]
Thanks for the detailed insight @jdoss. I've started looking into the issue and indeed it seems that the industry is slowly moving towards cgroupsv2 (and for good reason).
I think it's fair that Firecracker's jailer supports it.

We're going to need a little more time to figure out how we could test this behaviour in the CI pipelines. It doesn't seem so easy, especially since we're running under a docker container that uses cgroupsv1.
