### ISSUE TITLE
seccomp: move to crates.io

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#844]
Seccomp doesn't have any dependencies and can be easily moved to crates.io.

Before publishing it:
- [ ] we need a name (seccomp is already used on crates.io)
- [ ] add unit tests for `add_rules` and `setup_seccomp`. These methods are tested in Firecracker as part of the `default_syscalls.rs` module in the `vmm` crate. 
- [ ] advertise it as x86_64 specific (or add support for other platforms)

**Comment by aghecenco** [comment]
We should call it `seccomp_sys` as it's directly interface with the seccomp subsystem, but that name is unfortunately also taken even. How about `seccomp_bpf` since it also deals with bpf translations?

**Comment by alindima** [comment]
Closing, as this is now tracked by the seccompiler crate in rust-vmm: https://github.com/rust-vmm/seccompiler
