### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by amrragab8080** [firecracker-microvm/firecracker#849]
[Public facing api](https://github.com/firecracker-microvm/firecracker/blob/master/api_server/swagger/firecracker.yaml) doesnt seem to have support yet for passthrough pci devices, namely gpu is this technically feasible?

**Comment by gautamkmr** [comment]
That would be super helpful to have support for GPU.

**Comment by acatangiu** [comment]
GPU support in Firecracker is very hard/tricky at the moment. With current GPU hardware, there's two major problems:

1. To do device pass-through implies pinning physical memory which would remove our memory oversubscription capabilities.
1. We can only run 1 customer workload securely per physical GPU, and switching between customer workloads takes a long enough time to make it impractical.

As a result there is no known path to supporting GPUs in Firecracker.

**Comment by raduweiss** [comment]
@amrragab8080, we'll be looking at this as part of #1179.

**Comment by normtown** [comment]
> To do device pass-through implies pinning physical memory which would remove our memory oversubscription capabilities.

Why do you want to maintain the ability to oversubscribe memory?

**Comment by raduweiss** [comment]
Oversubscription is a core part of makes Firecracker a great way to isolate serverless workloads; that's why we took on a tenet around it [1].

[1] https://github.com/firecracker-microvm/firecracker/blob/master/CHARTER.md

**Comment by normtown** [comment]
Why is over-subscription a great way to isolate serverless workloads? I genuinely don't know, so the reasoning that led to the existence of the tenet is not self-evident to me.

**Comment by raduweiss** [comment]
Like all services, serverless compute providers want to keep their servers busy and to improve their overall utilization. Ideally, every CPU cycle on the service provider's servers is running user code, and every byte of RAM is filled with user data. If servers are sitting idle, that’s inefficient.

A part of solving this optimization problem is having the ability to oversubscribe a given server's hardware capacity with workloads who's hardware resource usage is statistically uncorrelated, or, even better, with workloads selected specifically to pack well together.

**Comment by normtown** [comment]
What you appear to be saying is that resource over-subscription helps the hosting service (e.g. AWS Lambda or Fargate) to lower their hardware costs. (Which, in turn, passes savings on to customers...presumably.)

That is not the same as being great for isolating workloads. It seems to be the opposite. Particularly, in the case that all workloads attempt to utilize their full resource reservations at the same time. It sounds like the design here is to bet on the workloads not calling in all their debts.

How ingrained into the Firecracker implementation is this resource-over-subscription tenet? Like, would it be remotely feasible to add a feature flag that turns over-subscription off?

P.S. As an aside, the Firecracker tenets don't seem to align with the Fargate project. Specifically the tenet that calls out favoring transient or stateless workloads over long-running or persistent workloads. The Fargate docs do not place similar restrictions on its workloads (AFAICT).

**Comment by raduweiss** [comment]
> That is not the same as being great for isolating workloads. It seems to be the opposite. Particularly, in the case that all workloads attempt to utilize their full resource reservations at the same time. It sounds like the design here is to bet on the workloads not calling in all their debts.

Great for isolating *serverless* workloads. Take a look at https://www.youtube.com/watch?v=QdzV04T_kec , there some more detail there around how Lambda multiplexes workloads.

> How ingrained into the Firecracker implementation is this resource-over-subscription tenet? Like, would it be remotely feasible to add a feature flag that turns over-subscription off?

Well, it's a tenet so we stick to it unless there's a very good reason to change it.

> P.S. As an aside, the Firecracker tenets don't seem to align with the Fargate project. Specifically the tenet that calls out favoring transient or stateless workloads over long-running or persistent workloads. The Fargate docs do not place similar restrictions on its workloads (AFAICT).

You're quite right here :) This tenet started out as a powerful simplifying assumption, but as you pointed out, it doesn't quite apply to all the serverless container workloads; we might let go of the "transient and stateless" part.

**Comment by DemiMarie** [comment]
> GPU support in Firecracker is very hard/tricky at the moment. With current GPU hardware, there's two major problems:
> 
> 1. To do device pass-through implies pinning physical memory which would remove our memory oversubscription capabilities.

In theory it is possible to do better by dynamically manipulating guest IOMMU mappings.

> 2. We can only run 1 customer workload securely per physical GPU, and switching between customer workloads takes a long enough time to make it impractical.

Does this also apply to SR-IOV capable GPUs?  What about e.g. attacks in which the guest overwrites the GPU’s vBIOS?

**Comment by Talador12** [comment]
> GPU support in Firecracker is very hard/tricky at the moment. With current GPU hardware, there's two major problems:
> 
> 1. To do device pass-through implies pinning physical memory which would remove our memory oversubscription capabilities.
> 2. We can only run 1 customer workload securely per physical GPU, and switching between customer workloads takes a long enough time to make it impractical.
> 
> As a result there is no known path to supporting GPUs in Firecracker.

This is becoming increasingly more important to support. It may be difficult, but we need to find a way to do this.
