### ISSUE TITLE
Refactor the cpuid crate 

### ISSUE THREAD

**Issue by serban300** [firecracker-microvm/firecracker#851]
Refactor the cpuid crate in order to make it easier to add support for new CPUs 

Make sure it doesn't affect the boot time

**Comment by serban300** [comment]
filter_cpuid execution time (cpu clock) before refactoring: 6-11 usec

**Comment by andreeaflorescu** [comment]
It looks like we should start the work on this with an integration test. It is rather tricky to catch regressions otherwise.

**Comment by serban300** [comment]
I will try to do this incrementally. The first iterations should be covered by the unit tests. I will add an integration test as soon as it is needed.
