### ISSUE TITLE
Implement Debug & Display for Errors that can generate panics

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#856]
We currently don't get a nice panic message as the errors on which we use unwrap or the `format!` macro do not have a custom implementation for Display and Debug.

The errors that I identified so far that should have Display/Debug implemented are the following:
- [ ] Error from vmm/src/lib.rs
- [ ] Error from api/src/lib.rs

For the API errors, instead of printing the `io::Error` with format we should do something like `io_err.kind().to_string()`. The nice thing it does is that instead of having a errno, we will get a nice string like: "permission denied" for errno=13.

**Comment by fristonio** [comment]
Ok, I will start working on this then. Will ping you on slack if I have some doubt :)

**Comment by 0xkelvin** [comment]
hello @andreeaflorescu is this still open ? if it doesnt move, please assign to me

**Comment by sarimaleem** [comment]
@JBYoshi and I would like to work on this. We're doing a class project for UT Austin's virtualization class, where we're supposed to work on issues in virtualization-related open source projects. Is this issue open for us to work on?

**Comment by JonathanWoollett-Light** [comment]
We have refactored the code to introduce error implementations to error types, these changes resolve this issue.
