### ISSUE TITLE
vritio-blk: Fix request handling

### ISSUE THREAD

**Issue by dhrgit** [firecracker-microvm/firecracker#865]
- [x] Add support for VIRTIO_BLK_T_FLUSH. Flush requests are currently:
  - not advertised during feature negotiation (VIRTIO_BLK_F_FLUSH)
  - incorrectly handled; i.e. the driver is (incorrectly) expected to pass a data descriptor, so the request fails with DescriptorChainTooShort, instead of Unsupported (see #857).
- [x] Look into request parsing: currently, exactly three descriptors are expected with each request: a request "header" descriptor, a data descriptor, and a status descriptor; the virtio spec doesn't appear to force this exact layout on the driver (what if the driver splits the data across multiple descriptors?).

**Comment by dianpopa** [comment]
Second issue was cleared up too. Closing this.
