### ISSUE TITLE
Get Dirty Pages Count for aarch64

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#866]
For the moment the ioctl for getting dirty pages used for firecracker is available only for x86 and x86_64. We need to implement the equivalent for arm64. See `get_and_reset_dirty_page_bitmap` function inside kvm/src/lib.rs

**Comment by andreeaflorescu** [comment]
Is there an ioctl on ARM supported by KVM that will give you the dirty pages? I failed to find something and I was considering disabling the LogDirtyPages functionality for ARM for now.

**Comment by aghecenco** [comment]
Nope. The [KVM API](https://www.kernel.org/doc/Documentation/virtual/kvm/api.txt) marks the `KVM_GET_DIRTY_LOG` ioctl as x86 specific. There seems to have been [an attempt](http://lists.infradead.org/pipermail/linux-arm-kernel/2014-November/300463.html) to add ARM support but I can't find any evidence of it having been merged, we need to ask around.

**Comment by andreeaflorescu** [comment]
FYI I made the LogDirtyPages options available only on x86 in this PR: https://github.com/firecracker-microvm/firecracker/pull/948

**Comment by xiaobo55x** [comment]
Hi @dianpopa &@andreeaflorescu, KVM_GET_DIRTY_LOG api is not supported on arm64 platform, it's a feature currently specific to x86 architecture.

**Comment by suzukikp** [comment]
> Hi @dianpopa &@andreeaflorescu, KVM_GET_DIRTY_LOG api is not supported on arm64 platform, it's a feature currently specific to x86 architecture.

It is supported on all major architectures, x86, arm64, mips, powerpc, s390x. The Documentation is outdated. What am I missing ?

**Comment by andreeaflorescu** [comment]
@suzukikp you are right. We were looking at the documentation though so that's where the confusion was from I believe.

**Comment by dianpopa** [comment]
Opened https://github.com/rust-vmm/kvm-ioctls/pull/62.

**Comment by dianpopa** [comment]
Support for getting dirty pages on aarch64 was added in kvm-ioctls.  Since we are planning on removing the metric that relies on that capability, no more work is needed in Firecracker.
