### ISSUE TITLE
Firecracker v0.13.0 /machine-config hangs

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#868]
Calling `GET` /machine-config hangs. To reproduce

```bash
firecracker --api-sock ./api.socket
```
```bash
sudo curl --unix-socket ./api.socket -i -X GET 'http://localhost/machine-config'
```

**Comment by dhrgit** [comment]
@xibz 
I couldn't reproduce this one. Can you please provide more details?
- Are you running the release binary, or are you building from the v0.13.0 tag? If building, are you using `devtool build`?
- Is `GET /machine-config` the only API call that fails, or are there others as well?
- What host machine/kernel can you reproduce this on?

Thanks!

**Comment by xibz** [comment]
1) I am building from tag with vsock, ie) `cargo build --release --features vsock`
2) Looks like it is all API calls that hang.
3) This is on Ubuntu 18.04.1 LTS

**Comment by andreeaflorescu** [comment]
There was a bug on v0.13.0 that was causing building with the vsock feature fail. This is fixed in v0.14.0 that was just released today. Let us know if the problem persists with the latest release.

**Comment by xibz** [comment]
Hello @andreeaflorescu, I checked out the `v0.14.0` tag and it is still persisting.

**Comment by raduweiss** [comment]
Actually, it looks we might have a different issue with v0.14.0 that causes the API to hang in general. We're focusing on this as soon as our workday starts tomorrow (we're on an EU time zone).

**Comment by xibz** [comment]
Awesome, thanks @raduweiss

**Comment by xiaoxubeii** [comment]
+1, CentOS Linux release 7.2.1511 (Core) with 4.14.10-1.el7.elrepo.x86_64. API hangs with both firecracker v0.14 and v0.13.

**Comment by andreeaflorescu** [comment]
Hey, I am not able to reproduce this locally. Are you using the container to build Firecracker?

What I've tried so far:
```bash
cargo build --release --features=vsock
./target/x86_64-unknown-linux-musl/release/firecracker
```
Then I am running a bash script with some of the supported API calls (I don't setup vsock at all). You can find the full list here: https://pastebin.com/Vz0ZWZrt
The output is here: https://pastebin.com/KTnPH7Rd

Did you recently updated your rust toolchain? We noticed that in rust-1.32.0 they introduced new syscalls that are causing Firecracker to crash. If you are building Firecracker using the `devtool`, that shouldn't be a problem.

On my local machine I have rust version 1.31.1.
```bash
$: rustc --version
rustc 1.31.1 (b6c32da9b 2018-12-18)
```

**Comment by xibz** [comment]
@dhrgit @andreeaflorescu - Yep, it was my `1.32` version for `v0.14.0` of Firecracker. After going running `devtool shell`, everything behaved normally. Going to go ahead and close.
