### ISSUE TITLE
CI Integration for aarch64

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#874]
- [x] Build specific tests pass
- [x] Functional specific tests pass
- [x] Performance specific tests pass
- [x] Security specific tests pass
- [x] Remove all aarch64 warnings
- [x] Add clippy test for aarch64 specific regions
- [x] Create dockerfile for x86_64 and aarch64
- [x] Create docker image for x86_64 and aarch64
- [x] Update our CI so that  it runs against aarch64 instances
- [x] Add CI specific tests for aarch64 (if needed).
- [x] Remove cross compilation related code

**Comment by andreeaflorescu** [comment]
This looks more like "Adding integration tests for ARM". We should probably also add an issue for updating our CI so that we can spawn ARM instances and run our integration tests there. What do you say?

**Comment by xiaobo55x** [comment]
Hi @dianpopa @andreeaflorescu,

Are there any user manual to boot a microVM on arm64 machine. It seems that the provided manual is for x86 machine.

Regards,

Haibo

**Comment by dianpopa** [comment]
hi! We do not yet have documentation for booting a microVM on arm64 machine even though firecracker now has support for that. I am currently working on PRs that fix issues #867 and #1066. Once those are merged, I will start working on setting up the CI, writing documentation and asses performance.

**Comment by dianpopa** [comment]
All checks are done.
