### ISSUE TITLE
Assess the performance of firecracker on aarch64 

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#875]
Create benchmarks for the aarch64 firecracker microVMs to extract performance metrics.

**Comment by xiaobo55x** [comment]
@dianpopa 
Hi,

Here is Haibo, from ARM open source software team.
We are very interested in this project, and have tried to launch the MicroVM on our x86_64 platform. Meanwhile, we noticed that firecracker is successfully built on aarch64 platform according to #756 . 
Very appreciate that if you could  share more status and road map about the firecracker support on aarch64. Also, please let us know if we can provide some help for this task.

Regards,

Haibo

**Comment by dianpopa** [comment]
Hi @xiaobo55x ,
I am really glad about your interest in this feature and really appreciate your support.
Indeed,  the project should compile on `aarch64`. However, we still do not have a CI test that makes sure the build does not get broken when a PR is merged but we are trying to get as close as possible to that point.
It is worth mentioning that up until now I encountered no major issue implementing the specific `aarch64` functionality since you have great documentation. Congrats on that!
We keep track of progress on enabling firecracker on `aarch64` by logging issues that are labeled with the [Feature: ARM Support](https://github.com/firecracker-microvm/firecracker/labels/Feature%3A%20ARM%20Support).  As far as the current status, I am currently working at implementing the FDT for the microVM and looking forward to pushing the "spawn" button in the near future.
Make sure you join our [slack channel](https://tinyurl.com/firecracker-microvm) so that it is easier to ping you in case I need help with this.

**Comment by xiaobo55x** [comment]
Hi @dianpopa ,

Thanks for sharing! I have joint your slack channel with the username "haibo xu".
Please ping me if we can do any help.

Regards,

Haibo

**Comment by dianpopa** [comment]
All performance related CI successfully pass on aarch64 without adjustments.
The block device I/O overhead is tracked in #1529 .

**Comment by dianpopa** [comment]
Nothing is left to be done on aarch64 here. Performance improvements will be treated equally on all architectures from now on.
