### ISSUE TITLE
Create a release pipeline

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#879]
Releasing Firecracker involves:

1. a set of manual steps which can be automated - see #821
1. a clean build
1. uploading the generated binaries to the release page
1. publishing a new version of the container image

To minimize the chances of polluting the build environment and generating corrupted binaries, we should enforce steps 2 and 3 to run on a dedicated machine (like the CI suite does). This would be accomplished by building a release pipeline, triggered manually when we decide to release, running all the now manual steps in a clean environment and publishing the binaries.

**Comment by aghecenco** [comment]
#901 tracks automating the tag creation - what I have in mind is the tedious tag description.

**Comment by raduweiss** [comment]
We are looking to build release automation in the second half of 2021.

**Comment by serban300** [comment]
We have scripts that we currently run manually. We're looking into automating beyond this point.
