### ISSUE TITLE
Support for other guest OS

### ISSUE THREAD

**Issue by guskovd** [firecracker-microvm/firecracker#883]
Virtualization via kvm compares favorably with the fact that it allows you to run windows, macos, etc.

Are there any plans to support guest operating systems other than Linux?

**Comment by dhrgit** [comment]
Support for other OS is not on the roadmap. Firecracker is a pretty specific tool, targeted towards running serverless/function workloads, with minimal overhead. It's not meant to be a general, do-it-all virtual machine manager.

That said, Firecracker expects the guest kernel to be an ELF binary. That doesn't necessarily mean Linux. There are people who got it working with unikernels - see #857.

**Comment by raduweiss** [comment]
Indeed, our Kernel loading process is very much tied into the ELF format; but I guess the background reason is that to achieve our [specification](https://github.com/firecracker-microvm/firecracker/blob/master/SPECIFICATION.md) targets, we really need a high degree of control over how the guest OS behaves. If you diff our [kernel config](https://github.com/firecracker-microvm/firecracker/blob/master/resources/microvm-kernel-config) and command line to others out there, you'll see that we turn off a bunch of stuff, and pass very specific parameters. These all work in tandem with Firecracker to actually achieve those specs.

That being said, having a Firecracker-like VMM that also runs Windows guests, or that runs on Windows hosts is something that may indeed have it's use cases (for one, the minimal attack surface). 

However, I think the best place to do that is of doing this is [rust-vmm](https://github.com/rust-vmm). a new drive to build some common virtualization components in Rust. Eventually, most of Firecracker will be made up of rust-vmm crates, and then groups that to run, e.g., Windows guests or on Windows hosts could create / consume all appropriate rust-vmm crates and roll their own. There's been some interest in the community for working towards this, but it will take some time to come to fruition.

I'm closing this now, feel free to re-open if you want to continue the conversation.
