### ISSUE TITLE
Create RW disk snapshots of running Firecracker microVMs

### ISSUE THREAD

**Issue by s3rj1k** [firecracker-microvm/firecracker#886]
A way to do disk snapshoting on a runnig VM

**Comment by ad-m** [comment]
Let's do that. It's just file.

**Comment by raduweiss** [comment]
I assume you're thinking of snapshots while the guest is still running?

**Comment by s3rj1k** [comment]
@raduweiss yes, while VM is running

**Comment by acatangiu** [comment]
What's the usecase for this?

Please always bear in mind that Firecracker is designed for short-lived specialized tasks and not a general-purpose VM.

**Comment by s3rj1k** [comment]
being able to make point in time backup is always a good thing

**Comment by raduweiss** [comment]
@s3rj1k , I thought about this for a bit, and indeed a proper backup image can't be achieved without changes in Firecracker. This is something we've also talked about in the team, and we're going to continue looking at. I'll leave the issue open so we have it on our radar (we're going to organize ourselves with some milestones in the near future).

**Comment by s3rj1k** [comment]
@raduweiss cool, sounds great :)

**Comment by raduweiss** [comment]
@s3rj1k, @ad-m, we've added something like this to the roadmap, see #1184. Figuring out exactly how this will work (e.g., if/how you rw disk snapshots) will probably be discussed as part of that issue.

**Comment by acatangiu** [comment]
@s3rj1k we've released dev-preview snapshotting functionality in v0.23 with full support coming up in v0.24.

Does that cover this issue?

**Comment by s3rj1k** [comment]
@acatangiu Yea, that's great news, thanks!
https://github.com/firecracker-microvm/firecracker/blob/v0.23.0/docs/snapshotting/snapshot-support.md
