### ISSUE TITLE
Running clippy with firecracker fails

### ISSUE THREAD

**Issue by acipu-aws** [firecracker-microvm/firecracker#890]
Running `cargo clippy` yields 6 error lints, as well as several dozens of warnings. The errors are:

- [unsafe_vector_initialization](https://rust-lang.github.io/rust-clippy/master/#unsafe_vector_initialization)
- [mut_from_ref](https://rust-lang.github.io/rust-clippy/master/#mut_from_ref)
- [into_iter_on_array](https://rust-lang.github.io/rust-clippy/master/#into_iter_on_array)
- [cast_ptr_alignment](https://rust-lang.github.io/rust-clippy/master/#cast_ptr_alignment)
- [unused_io_amount](https://rust-lang.github.io/rust-clippy/master/#unused_io_amount)
- [absurd_extreme_comparison](https://rust-lang.github.io/rust-clippy/master/#absurd_extreme_comparison)

**Comment by fristonio** [comment]
@andreeaflorescu Can I take up this issue?

**Comment by andreeaflorescu** [comment]
Sure!

**Comment by dianpopa** [comment]
Running clippy with firecracker does not fail anymore, we even have an integration test in place that makes sure no errors are thrown. Indeed, we still have some warnings to get rid of, but there are separate issues opened for those.

**Comment by andreeaflorescu** [comment]
The PR that fixes this is not yet merged.
