### ISSUE TITLE
Logger integration tests randomly fail

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#906]
Some of the tests from `test_logging.py` fail every now and then for no apparent reason, even for already merged code. So far, the only reliable way to observe this is to go on an `i3.metal`, run something like `while :; do tools/devtool test -- integration_tests/functional/test_logging.py ; done`, and wait for the inevitable failure to eventually manifest (shouldn't take too many runs).

**Comment by aghecenco** [comment]
related: #899
