### ISSUE TITLE
Add VM address space abstraction to memory_model

### ISSUE THREAD

**Issue by jiangliu** [firecracker-microvm/firecracker#913]
Currently memory_model::GuestMemory is used to present VM memory, which actually has two responsibilities:
1) describe VM memory structure
2) map VM memory into current process

It would be better to separate this two responsibilities into two abstractions:
1) AddressSpace to describe VM address space structure. It maintain information about physical memory, MMIO and backend file descriptor.
2) GuestMemory to map partial or all of guest memory into current process

The AddressSpace abstraction may be used to:
1) support vhost-user protocol by sharing memfd based guest memory
2) protect guest kernel code/data/rodata from virtual devices
3) apply special access permission in EPT for kernel code/data/rodata
4) enable hugetlbfs based guest memory allocation

**Comment by raduweiss** [comment]
Thanks Liu, this looks interesting. We'll take a look over the next couple of days.

**Comment by andreeaflorescu** [comment]
Closing this since the code is change is going to happen in the rust-vmm repository.
