### ISSUE TITLE
Generate whitelisted syscall list for simple-mode seccomp

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#920]
When running Firecracker with `seccomp_level=1`, the seccomp filters will only match the syscall numbers, and not the arguments. The list of whitelisted syscall numbers should be autogenerated from the (much more complex) list of complex rules so that they stay in sync with new modifications.

**Comment by andreeaflorescu** [comment]
This sounds like removing duplicated code, my favourite kind of commit <3
