### ISSUE TITLE
seccomp: integration tests

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#921]
Add integration tests with the following configurations:
- [ ] no seccomp test => this could be something like starting firecracker with seccomp-level=0 and check that a syscall we do not whitelist doesn't cause a crash.
- [ ] seccomp-level = 1

**Comment by aghecenco** [comment]
I don't think we get extra value out of testing that Firecracker works fine without seccomp filters - if it works OK with them (which is tested by the whole CI suite as they're enabled in strict mode by default), surely it works without them.

As for seccomp level = 1, there is an integration test - [`test_seccomp_ls`](https://github.com/firecracker-microvm/firecracker/blob/9cdb5b248ec80b6a742805490c0438add4f358fc/tests/integration_tests/security/test_seccomp.py#L112) - that installs basic seccomp filters and runs `/bin/ls`, which violates them. The purpose of this test is to test the seccomp functionality, not Firecracker; it would be overkill IMO to build a custom Firecracker that issues an offending syscall just to test the filters, when we can do that with any binary.

**Comment by andreeaflorescu** [comment]
I added this issue after we had a bug introduced by https://github.com/firecracker-microvm/firecracker/pull/919 which was caught during the review (by you). I still see value in having tests with different values of seccomp-level in Firecracker. I will re-open this if we ever have a similar bug.

**Comment by aghecenco** [comment]
Aaah, verifying that Firecracker works fine with seccomp=1 (I really do have the memory span of a goldfish) - I hope that this is taken care of by no longer keeping 2 separate structs for the rules, and building the 'basic' set as a simplification of the 'advanced' set. True, to be super thorough we'd need basic seccomp'ed Firecracker to jump through the same hoops as advanced seccomp'ed Firecracker. But super thoroughness would mean double the time to test, as every single functionality would need to be verified by the 2 binaries with their different filters. Without parallel tests, I don't really want to go there :worried:
