### ISSUE TITLE
Move KVM fd allocation from jailer to firecracker

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#930]
The Jailer<->FIrecracker handover via `exec` relies on getting some predefined fd numbers (e.g. 3 when opening `/dev/kvm`). It would be nice to have a definite answer to the following question: if we close all fd numbers greater than 2, will the next functions which are supposed to provide file descriptors return 3,4, ... etc?

**Comment by acatangiu** [comment]
Definite answer based on research and testing: **YES** (on Linux).

The smallest available/free FD in the process' fd table is returned by the kernel - holes are plugged, FDs are not necessarily incremental.

**Comment by raduweiss** [comment]
So, can we close this then?

**Comment by alexandruag** [comment]
Is there some document/weg page/man page/source code we can quote?

**Comment by acatangiu** [comment]
Fixed by https://github.com/firecracker-microvm/firecracker/pull/966
