### ISSUE TITLE
Enhance supported KVM ioctls 

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#933]
Add wrappers for the following ioctls:
- [ ] KVM_GET_MP_STATE
- [ ] KVM_GET_XSAVE
- [ ] KVM_GET_XCRS
- [ ] KVM_GET_DEBUGREGS
- [ ] KVM_GET_VCPU_EVENTS
- [ ] KVM_GET_CPUID2
- [ ] KVM_GET_EMULATED_CPUID
- [ ] KVM_GET_CLOCK

Others?

**Comment by raduweiss** [comment]
This code is now in rust-vmm.
