### ISSUE TITLE
Clippy: Fix cast_ptr_alignment clippy errors

### ISSUE THREAD

**Issue by fristonio** [firecracker-microvm/firecracker#934]
Use `git grep cast_ptr_alignment` to find the affected code blocks.
Ref: #922

**Comment by dtolnay** [comment]
This lint caught 4 instances of undefined behavior in crosvm, some of which are present in Firecracker too.
https://chromium-review.googlesource.com/c/chromiumos/platform/crosvm/+/1566736

**Comment by aghecenco** [comment]
#922
