### ISSUE TITLE
Clippy: Fix mut_from_ref clippy errors

### ISSUE THREAD

**Issue by fristonio** [firecracker-microvm/firecracker#935]
`git grep mut_from_ref` for affected code blocks.
https://rust-lang.github.io/rust-clippy/master/#mut_from_ref

Ref: #922

**Comment by serban300** [comment]
Command for finding the errors:

```
cargo clippy --all-targets --all-features -- -A clippy::all -W clippy::mut_from_ref
```

**Comment by serban300** [comment]
Draft commit: https://github.com/serban300/firecracker/commit/e45d1f5d68799a72ff500549548167fd2fcc6f90

**Comment by serban300** [comment]
Will revisit this task after having an final version of the rust-vmm memory-model crate: https://github.com/jiangliu/memory-model

**Comment by serban300** [comment]
The rust-vmm memmory-model crate uses `#[allow(clippy::mut_from_ref)]`

Closing this issue
