### ISSUE TITLE
Workspace and email missing from slack invite

### ISSUE THREAD

**Issue by arun-gupta** [firecracker-microvm/firecracker#938]
I tried signing up for firecracker slack channel. The invitation email does not include the workspace URL. This is particularly true if the registered user is already subscribed to it. 

Here is a image capture from the email:

<img width="631" alt="screen shot 2019-02-15 at 2 47 51 pm" src="https://user-images.githubusercontent.com/113947/52889099-545d3b00-3133-11e9-934d-cb30444967fd.png">

**Comment by dianpopa** [comment]
Hi @arun-gupta,
This issue does not seem to replicate anymore.
![slack-invite](https://user-images.githubusercontent.com/4263668/65425527-da9ed580-de16-11e9-8189-d5d21961cfd8.png)
Closing this. Feel free to reopen with detailed replication steps if it still happens to you.
