### ISSUE TITLE
Faq.md error: Firecracker can't be used with Kata containers.

### ISSUE THREAD

**Issue by xavinux** [firecracker-microvm/firecracker#941]
The  [FAQ.md](https://github.com/firecracker-microvm/firecracker/blob/master/FAQ.md) says that Firecracker can't be used with Kata containers yet. But since the last [1.5.0](https://github.com/kata-containers/runtime/releases/tag/1.5.0) release of Kata Containers, support for the Firecracker hypervisor has been included.

**Comment by acatangiu** [comment]
Fixed by #942
