### ISSUE TITLE
Download an empty Firecracker file from Github.

### ISSUE THREAD

**Issue by xavinux** [firecracker-microvm/firecracker#945]
Following the Getting Started guide to install Firecracker on a bare metal Linux Ubuntu 18.04, after running the following command an empty file with a Not Found text is downloaded:

curl -LOJ https://github.com/firecracker-microvm/firecracker/releases/download/v${latest}/firecracker-v${latest}

**Comment by andreeaflorescu** [comment]
${latest} is not defined. You will have to replace it manually with the latest version of Firecracker. Currently that is v0.14.0

**Comment by xavinux** [comment]
You're right, thanks.
