### ISSUE TITLE
vsock failure does not cause firecracker to exit with non-zero exit code

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#946]
Using firecracker v0.12.0 and I noticed that if there is a vsock error, firecracker still behaves as if there was no error and continues to run. The desired behavior would be for the firecracker process to panic and exit with a non-zero exit code if an error was to occur.

<details>
<pre>
[    0.000000] Linux version 4.14.55-84.37.amzn2.x86_64 (mockbuild@ip-10-0-1-79) (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Wed Jul 25 18:47:15 UTC 2018
[    0.000000] Command line: console=ttyS0 noapic reboot=k panic=1 pci=off nomodules rw  root=/dev/vda virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6 virtio_mmio.device=4K@0xd0002000:7
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000000fffffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] DMI not present or invalid.
[    0.000000] Hypervisor detected: KVM
[    0.000000] tsc: Fast TSC calibration using PIT
[    0.000000] e820: last_pfn = 0x10000 max_arch_pfn = 0x400000000
[    0.000000] MTRR: Disabled
[    0.000000] x86/PAT: MTRRs disabled, skipping PAT initialization too.
[    0.000000] CPU MTRRs all blank - virtualized system.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC  
[    0.000000] found SMP MP-table at [mem 0x0009fc00-0x0009fc0f] mapped at [ffffffffff200c00]
[    0.000000] Scanning 1 areas for low memory corruption
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000] NODE_DATA(0) allocated [mem 0x0ffde000-0x0fffffff]
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 0:ffdc001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 74352171 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x000000000fffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x000000000fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x000000000fffffff]
[    0.000000] Intel MultiProcessor Specification v1.4
[    0.000000] MPTABLE: OEM ID: FC      
[    0.000000] MPTABLE: Product ID: 000000000000
[    0.000000] MPTABLE: APIC at: 0xFEE00000
[    0.000000] Processor #0 (Bootup-CPU)
[    0.000000] IOAPIC[0]: apic_id 2, version 17, address 0xfec00000, GSI 0-23
[    0.000000] Processors: 1
[    0.000000] smpboot: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x000fffff]
[    0.000000] e820: [mem 0x10000000-0xffffffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.000000] random: get_random_bytes called from start_kernel+0x94/0x486 with crng_init=0
[    0.000000] setup_percpu: NR_CPUS:128 nr_cpumask_bits:128 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] percpu: Embedded 41 pages/cpu @ffff88000fc00000 s128728 r8192 d31016 u2097152
[    0.000000] KVM setup async PF for cpu 0
[    0.000000] kvm-stealtime: cpu 0, msr fc15040
[    0.000000] PV qspinlock hash table entries: 256 (order: 0, 4096 bytes)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 64393
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: console=ttyS0 noapic reboot=k panic=1 pci=off nomodules rw  root=/dev/vda virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6 virtio_mmio.device=4K@0xd0002000:7
[    0.000000] PID hash table entries: 1024 (order: 1, 8192 bytes)
[    0.000000] Memory: 240080K/261752K available (8204K kernel code, 622K rwdata, 1464K rodata, 1268K init, 2820K bss, 21672K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Kernel/User page tables isolation: enabled
[    0.004000] Hierarchical RCU implementation.
[    0.004000] 	RCU restricting CPUs from NR_CPUS=128 to nr_cpu_ids=1.
[    0.004000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.004000] NR_IRQS: 4352, nr_irqs: 48, preallocated irqs: 16
[    0.004000] Console: colour dummy device 80x25
[    0.004000] console [ttyS0] enabled
[    0.004000] tsc: Detected 3591.682 MHz processor
[    0.004000] Calibrating delay loop (skipped) preset value.. 7183.36 BogoMIPS (lpj=14366728)
[    0.004000] pid_max: default: 32768 minimum: 301
[    0.004000] Security Framework initialized
[    0.004000] SELinux:  Initializing.
[    0.004000] Dentry cache hash table entries: 32768 (order: 6, 262144 bytes)
[    0.004000] Inode-cache hash table entries: 16384 (order: 5, 131072 bytes)
[    0.004000] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.004011] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.004860] Last level iTLB entries: 4KB 1024, 2MB 1024, 4MB 1024
[    0.005346] Last level dTLB entries: 4KB 1024, 2MB 1024, 4MB 1024, 1GB 4
[    0.005906] Spectre V2 : Mitigation: Full generic retpoline
[    0.006355] Spectre V2 : Spectre v2 mitigation: Enabling Indirect Branch Prediction Barrier
[    0.007016] Spectre V2 : Enabling Restricted Speculation for firmware calls
[    0.007568] Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled via prctl and seccomp
[    0.017853] Freeing SMP alternatives memory: 28K
[    0.019070] smpboot: Max logical packages: 1
[    0.019423] Not enabling interrupt remapping due to skipped IO-APIC setup
[    0.020057] smpboot: CPU0: Intel(R) Xeon(R) Processor @ 3.60GHz (family: 0x6, model: 0x3f, stepping: 0x2)
[    0.020933] Performance Events: unsupported p6 CPU model 63 no PMU driver, software events only.
[    0.021698] Hierarchical SRCU implementation.
[    0.022321] smp: Bringing up secondary CPUs ...
[    0.022693] smp: Brought up 1 node, 1 CPU
[    0.023019] smpboot: Total of 1 processors activated (7183.36 BogoMIPS)
[    0.023634] devtmpfs: initialized
[    0.023949] x86/mm: Memory block size: 128MB
[    0.024156] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.024931] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.025584] NET: Registered protocol family 16
[    0.026049] cpuidle: using governor ladder
[    0.026388] cpuidle: using governor menu
[    0.029318] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.030098] dmi: Firmware registration failed.
[    0.030546] NetLabel: Initializing
[    0.030851] NetLabel:  domain hash size = 128
[    0.031228] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
[    0.031697] NetLabel:  unlabeled traffic allowed by default
[    0.032095] clocksource: Switched to clocksource kvm-clock
[    0.032554] VFS: Disk quotas dquot_6.6.0
[    0.032882] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.035088] NET: Registered protocol family 2
[    0.035555] TCP established hash table entries: 2048 (order: 2, 16384 bytes)
[    0.036112] TCP bind hash table entries: 2048 (order: 3, 32768 bytes)
[    0.036641] TCP: Hash tables configured (established 2048 bind 2048)
[    0.037210] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.037697] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.038229] NET: Registered protocol family 1
[    0.039226] virtio-mmio: Registering device virtio-mmio.0 at 0xd0000000-0xd0000fff, IRQ 5.
[    0.039910] virtio-mmio: Registering device virtio-mmio.1 at 0xd0001000-0xd0001fff, IRQ 6.
[    0.040681] virtio-mmio: Registering device virtio-mmio.2 at 0xd0002000-0xd0002fff, IRQ 7.
[    0.041404] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    0.042325] Scanning for low memory corruption every 60 seconds
[    0.042938] audit: initializing netlink subsys (disabled)
[    0.043549] Initialise system trusted keyrings
[    0.043944] Key type blacklist registered
[    0.044418] audit: type=2000 audit(1550601303.232:1): state=initialized audit_enabled=0 res=1
[    0.045135] workingset: timestamp_bits=36 max_order=16 bucket_order=0
[    0.046558] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.048747] Key type asymmetric registered
[    0.049097] Asymmetric key parser 'x509' registered
[    0.049539] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
[    0.050192] io scheduler noop registered (default)
[    0.050630] io scheduler cfq registered
[    0.051040] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.052110] virtio-mmio virtio-mmio.1: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.053060] virtio-mmio virtio-mmio.2: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.054143] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.075870] serial8250: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a U6_16550A
[    0.077951] loop: module loaded
[    0.078963] tun: Universal TUN/TAP device driver, 1.6
[    0.079446] hidraw: raw HID events driver (C) Jiri Kosina
[    0.079935] nf_conntrack version 0.5.0 (2048 buckets, 8192 max)
[    0.080542] ip_tables: (C) 2000-2006 Netfilter Core Team
[    0.081021] Initializing XFRM netlink socket
[    0.081473] NET: Registered protocol family 10
[    0.082197] Segment Routing with IPv6
[    0.082507] NET: Registered protocol family 17
[    0.082872] Bridge firewalling registered
[    0.083421] NET: Registered protocol family 40
2019-02-19T10:35:03.345723036 [anonymous-instance:ERROR:src/main.rs:49] Panic occurred: PanicInfo { payload: Any, message: Some(Failed to activate device: BadVhostActivate(VhostVsockSetCid(IoctlError(Os { code: 98, kind: AddrInUse, message: "Address in use" })))), location: Location { file: "src/libcore/result.rs", line: 1009, col: 5 } }
2019-02-19T10:35:03.353877878 [anonymous-instance:ERROR:src/main.rs:53] stack backtrace:
   0:           0x55df9d - backtrace::backtrace::trace::h669c73b43cac085a
   1:           0x588288 - firecracker::main::{{closure}}::hd933f1dec0b02f46
   2:           0x560e92 - std::panicking::rust_panic_with_hook::h28b9ce6fa7a5033b
                        at src/libstd/panicking.rs:495
   3:           0x560c1d - std::panicking::continue_panic_fmt::h4c221b9431554bc2
                        at src/libstd/panicking.rs:398
   4:           0x56e445 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   5:           0x5709db - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   6:           0x46c85d - core::result::unwrap_failed::h9e884a20ae090d0d
   7:           0x477e78 - <devices::virtio::mmio::MmioDevice as devices::bus::BusDevice>::write::ha8412f125ebfd81d
   8:           0x472897 - devices::bus::Bus::write::h5174aba9064356b2
   9:           0x45b3f9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd185ab1a6224be29
  10:           0x458180 - <F as alloc::boxed::FnBox<A>>::call_box::hf908fa6d54f73f34
  11:           0x56f004 - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Out * Remounting devtmpfs on /dev
<br>
Welcome to Alpine Linux 3.8
Kernel 4.14.55-84.37.amzn2.x86_64 on an x86_64 (ttyS0)
</pre>
</details>

**Comment by raduweiss** [comment]
Made obsolete by #650.

**Comment by andreeaflorescu** [comment]
@raduweiss this is not directly related to vsock. This looks like a bug in our VMM loop that was discovered through a vsock failure. We still need to fix it.

**Comment by dianpopa** [comment]
I am not able to replicate this with latest Firecracker [release](https://github.com/firecracker-microvm/firecracker/releases/tag/v0.18.0). When activation fails for vsock device, the following occurs now:
```
[    0.000000] Linux version 4.14.55-84.37.amzn2.x86_64 (mockbuild@ip-10-0-1-79) (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Wed Jul 25 18:47:15 UTC 2018
[    0.000000] Command line: console=ttyS0 noapic reboot=k panic=1 pci=off nomodules ip=192.168.241.2::192.168.241.1:255.255.255.0::eth0:off root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
[    0.000000] x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
[    0.000000] x86/fpu: Enabled xstate features 0x1f, context size is 960 bytes, using 'compacted' format.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x0000000007ffffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] DMI not present or invalid.
[    0.000000] Hypervisor detected: KVM
[    0.000000] tsc: Using PIT calibration value
[    0.000000] e820: last_pfn = 0x8000 max_arch_pfn = 0x400000000
[    0.000000] MTRR: Disabled
[    0.000000] x86/PAT: MTRRs disabled, skipping PAT initialization too.
[    0.000000] CPU MTRRs all blank - virtualized system.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC  
[    0.000000] found SMP MP-table at [mem 0x0009fc00-0x0009fc0f] mapped at [ffffffffff200c00]
[    0.000000] Scanning 1 areas for low memory corruption
[    0.000000] Using GB pages for direct mapping
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] NODE_DATA(0) allocated [mem 0x07fde000-0x07ffffff]
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 0:7fdc001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 13421738945 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x0000000007ffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x0000000007ffffff]
[    0.000000] Intel MultiProcessor Specification v1.4
[    0.000000] MPTABLE: OEM ID: FC      
[    0.000000] MPTABLE: Product ID: 000000000000
[    0.000000] MPTABLE: APIC at: 0xFEE00000
[    0.000000] Processor #0 (Bootup-CPU)
[    0.000000] IOAPIC[0]: apic_id 2, version 17, address 0xfec00000, GSI 0-23
[    0.000000] Processors: 1
[    0.000000] smpboot: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x000fffff]
[    0.000000] e820: [mem 0x08000000-0xffffffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.000000] random: get_random_bytes called from start_kernel+0x94/0x486 with crng_init=0
[    0.000000] setup_percpu: NR_CPUS:128 nr_cpumask_bits:128 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] percpu: Embedded 41 pages/cpu @ffff880007c00000 s128728 r8192 d31016 u2097152
[    0.000000] KVM setup async PF for cpu 0
[    0.000000] kvm-stealtime: cpu 0, msr 7c15040
[    0.000000] PV qspinlock hash table entries: 256 (order: 0, 4096 bytes)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32137
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: console=ttyS0 noapic reboot=k panic=1 pci=off nomodules ip=192.168.241.2::192.168.241.1:255.255.255.0::eth0:off root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6
[    0.000000] PID hash table entries: 512 (order: 0, 4096 bytes)
[    0.000000] Memory: 111064K/130680K available (8204K kernel code, 622K rwdata, 1464K rodata, 1268K init, 2820K bss, 19616K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Kernel/User page tables isolation: enabled
[    0.004000] Hierarchical RCU implementation.
[    0.004000] 	RCU restricting CPUs from NR_CPUS=128 to nr_cpu_ids=1.
[    0.004000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.004000] NR_IRQS: 4352, nr_irqs: 48, preallocated irqs: 16
[    0.004000] Console: colour dummy device 80x25
[    0.004000] console [ttyS0] enabled
[    0.004000] tsc: Detected 3408.000 MHz processor
[    0.004000] Calibrating delay loop (skipped) preset value.. 6816.00 BogoMIPS (lpj=13632000)
[    0.004000] pid_max: default: 32768 minimum: 301
[    0.004000] Security Framework initialized
[    0.004000] SELinux:  Initializing.
[    0.004000] Dentry cache hash table entries: 16384 (order: 5, 131072 bytes)
[    0.004060] Inode-cache hash table entries: 8192 (order: 4, 65536 bytes)
[    0.004947] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.005753] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.006987] Last level iTLB entries: 4KB 64, 2MB 8, 4MB 8
[    0.007656] Last level dTLB entries: 4KB 64, 2MB 0, 4MB 0, 1GB 4
[    0.008008] Spectre V2 : Mitigation: Full generic retpoline
[    0.009015] Spectre V2 : Spectre v2 mitigation: Filling RSB on context switch
[    0.010495] Spectre V2 : Spectre v2 mitigation: Enabling Indirect Branch Prediction Barrier
[    0.012020] Spectre V2 : Enabling Restricted Speculation for firmware calls
[    0.013924] Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled via prctl and seccomp
[    0.025544] Freeing SMP alternatives memory: 28K
[    0.026915] smpboot: Max logical packages: 1
[    0.027454] Not enabling interrupt remapping due to skipped IO-APIC setup
[    0.028123] smpboot: CPU0: Intel(R) Xeon(R) Processor @ 3.40GHz (family: 0x6, model: 0x5e, stepping: 0x3)
[    0.029342] Performance Events: unsupported p6 CPU model 94 no PMU driver, software events only.
[    0.030442] Hierarchical SRCU implementation.
[    0.031231] smp: Bringing up secondary CPUs ...
[    0.031780] smp: Brought up 1 node, 1 CPU
[    0.032004] smpboot: Total of 1 processors activated (6816.00 BogoMIPS)
[    0.032905] devtmpfs: initialized
[    0.033346] x86/mm: Memory block size: 128MB
[    0.033999] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.035185] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.036081] NET: Registered protocol family 16
[    0.036735] cpuidle: using governor ladder
[    0.037273] cpuidle: using governor menu
[    0.041104] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    0.042191] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.043487] dmi: Firmware registration failed.
[    0.044298] NetLabel: Initializing
[    0.045056] NetLabel:  domain hash size = 128
[    0.045891] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
[    0.046967] NetLabel:  unlabeled traffic allowed by default
[    0.048000] clocksource: Switched to clocksource kvm-clock
[    0.048000] VFS: Disk quotas dquot_6.6.0
[    0.048000] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.048080] NET: Registered protocol family 2
[    0.048080] TCP established hash table entries: 1024 (order: 1, 8192 bytes)
[    0.048080] TCP bind hash table entries: 1024 (order: 2, 16384 bytes)
[    0.048080] TCP: Hash tables configured (established 1024 bind 1024)
[    0.048080] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.052068] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.052835] NET: Registered protocol family 1
[    0.053928] virtio-mmio: Registering device virtio-mmio.0 at 0xd0000000-0xd0000fff, IRQ 5.
[    0.054936] virtio-mmio: Registering device virtio-mmio.1 at 0xd0001000-0xd0001fff, IRQ 6.
[    0.055936] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    0.057149] Scanning for low memory corruption every 60 seconds
[    0.057974] audit: initializing netlink subsys (disabled)
[    0.058786] Initialise system trusted keyrings
[    0.059330] Key type blacklist registered
[    0.059834] audit: type=2000 audit(1569239692.668:1): state=initialized audit_enabled=0 res=1
[    0.060963] workingset: timestamp_bits=36 max_order=15 bucket_order=0
[    0.062624] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.064906] Key type asymmetric registered
[    0.065415] Asymmetric key parser 'x509' registered
[    0.066014] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
[    0.066919] io scheduler noop registered (default)
[    0.067576] io scheduler cfq registered
[    0.068142] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.069931] virtio-mmio virtio-mmio.1: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.071690] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.095183] serial8250: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a U6_16550A
[    0.097670] loop: module loaded
[    0.098489] tun: Universal TUN/TAP device driver, 1.6
[    0.099169] hidraw: raw HID events driver (C) Jiri Kosina
[    0.099870] nf_conntrack version 0.5.0 (1024 buckets, 4096 max)
[    0.100745] ip_tables: (C) 2000-2006 Netfilter Core Team
[    0.101470] Initializing XFRM netlink socket
[    0.102542] NET: Registered protocol family 10
[    0.103714] Segment Routing with IPv6
[    0.104683] NET: Registered protocol family 17
[    0.105590] Bridge firewalling registered
[    0.107149] NET: Registered protocol family 40
2019-09-23T14:54:52.786949091 [anonymous-instance:ERROR:src/main.rs:54] Firecracker panicked at 'Failed to activate device: BadActivate', src/libcore/result.rs:997:5
2019-09-23T14:54:52.793703108 [anonymous-instance:ERROR:src/main.rs:57] stack backtrace:
   0: firecracker::main::{{closure}}::h4beb370db1a7e928 (0x40404e)
   1: rust_panic_with_hook (0x558926)
             at src/libstd/panicking.rs:478
   2: continue_panic_fmt (0x5586be)
             at src/libstd/panicking.rs:381
   3: rust_begin_unwind (0x565656)
   4: panic_fmt (0x5695ec)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h1f2bb488396497ab (0x49d2e2)
   6: <devices::virtio::mmio::MmioDevice as devices::bus::BusDevice>::write::hde6ed55f6b570748 (0x49fe3f)
   7: devices::bus::Bus::write::h137b18f4fd19a876 (0x4a3a5d)
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::hcdba08b84faa93ce (0x481fe1)
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}::hba3484d8d597bb0e (0x48a1f2)
  10: call_once<(),FnBox<()>> (0x564d3e)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
  11: call_once<(),alloc::boxed::Box<FnBox<()>>> (0x566258)
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:80

```
Closing this for now. @xibz  feel free to reopen if issue still replicates for you.
