### ISSUE TITLE
Delete 'foobar' tag

### ISSUE THREAD

**Issue by blitz** [firecracker-microvm/firecracker#953]
The repository contains a bogus tag called 'foobar': https://github.com/firecracker-microvm/firecracker/tree/foobar

This should probably be deleted.

**Comment by aghecenco** [comment]
That's mine :smile: I'm using it to test the release pipeline (#879), I'll clean it up when everything is in place. Will leave this issue open so I don't forget. Thanks!

**Comment by aghecenco** [comment]
The release pipeline does not need this tag. Removed.
