### ISSUE TITLE
code: 19, kind: Other, message: No such device

### ISSUE THREAD

**Issue by notesness** [firecracker-microvm/firecracker#954]
I installed vsock 

curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
apt install cargo
rustup target add x86_64-unknown-linux-musl
cargo build --features vsock

and run MicroVM for firectl

firectl \
--kernel=$KERNEL \
--root-drive=$ROOTFS \
--kernel-opts="console=ttyS0 reboot=k panic=1 pci=off " \
--vsock-device=root:3

but failed error, I cannot run MicroVM

[anonymous-instance:ERROR:api_server/src/http_service.rs:586] Received Error on synchronous Put request on "/actions" with body "{\"action_type\":\"InstanceStart\"}\n". Status code: 500 Internal Server Error.
ERRO[0000] Starting instance: [PUT /actions][500] createSyncAction default  &{FaultMessage:Cannot create vsock device. VhostOpen(VhostOpen(Os { code: 19, kind: Other, message: No such device }))}
FATA[0000] Failed to start machine: [PUT /actions][500] createSyncAction default  &{FaultMessage:Cannot create vsock device. VhostOpen(VhostOpen(Os { code: 19, kind: Other, message: No such device }))}

Is it due to running ubuntu on VMwarePlayer?

Please help

**Comment by dhrgit** [comment]
Looks like there is no support for vhost-vsock on your host. I.e. Firecracker cannot find/open `/dev/vhost-vsock`.

In order to use the experimental vsock support, you need a host kernel with support for vhost and vsock (compiled with `CONFIG_VHOST_VSOCK`).

**Comment by notesness** [comment]
Thank you for response!
I solved, 
Is it due to running ubuntu on VMwarePlayer

run commands

systemctl stop open-vm-tools
modprobe -r vmw_vsock_vmci_transport
modprobe -i vhost_vsock
