### ISSUE TITLE
API call durations sometimes exceed the maximum 100 ms with vsock

### ISSUE THREAD

**Issue by aghecenco** [firecracker-microvm/firecracker#976]
Integration tests fail sporadically with:

```
E   framework.decorators.timed_request.<locals>.ApiTimeoutException: API call exceeded maximum duration: 195.22 ms.
```

for vsock tests, where it takes longer to start the instance because of the new device.

As a workaround we could increase the timeout to 200 ms.

**Comment by andreeaflorescu** [comment]
We should be able to configure default timeouts depending on the feature being tested. We can use pytest markers: https://docs.pytest.org/en/latest/example/markers.html

**Comment by aghecenco** [comment]
TBH I don't understand most of what's on that page. To me it looks like a way of telling pytest what to run (which would be useful if `devtool` could pass it along so that testing in devenv no longer take the better part of the day) but not applicable to a decorator. Meanwhile PRs get marked as failed because of a completely unrelated known vsock issue. I think it would be best to increase the timeout or remove timing altogether to unblock the CI. We can deal with pytest meta decorating later.

**Comment by aghecenco** [comment]
#977 increased the timeout to 300 ms.
