### ISSUE TITLE
Immutable rootfs? 

### ISSUE THREAD

**Issue by ashish235** [firecracker-microvm/firecracker#987]
Hi,

I am trying the docker analogy here forgive me if that is totally wrong thing to do. 

I am using a Ubuntu rootfs which is used to spin up a vm using firectl. Now inside the vm I did some stuff (created some files, added some packages) and then I did a reboot, which shut down the vm. Now when I use the same rootfs I have the files and packages inside already? I thought it would be immutable and I get a fresh Ubuntu next time. So I did something wrong there to make the rootfs persist? Or it's supposed to behave that way and I need different rootfs for different vm(which I dont feel is correct). 

I wanted a way to persist some data but I planned it in doing by some other method but not persisting the data in rootfs itself. 

Regards
Ashish

**Comment by iggy** [comment]
What you experienced was correct. There is some ongoing work to integrate with devmapper (via containerd iirc) to have the layered style filesystems we're so used to seeing with existing tools like docker.

You will need a separate filesystem image for each VM instance for now.

**Comment by samuelkarp** [comment]
Firecracker itself does not provide filesystem immutability.  We're working integration with Docker- or OCI-style containers in the [firecracker-containerd project](https://github.com/firecracker-microvm/firecracker-containerd/), and providing an immutable (or copy-on-write) filesystem is part of that.  The approach we're using right now is a devicemapper thin-pool; you can see our implementation [here](https://github.com/firecracker-microvm/firecracker-containerd/tree/master/snapshotter/cmd/devmapper) as well as a pull request into the upstream containerd project here: https://github.com/containerd/containerd/pull/3022.

We don't currently have anything like that implemented in firectl, but I don't think it would be unreasonable to provide a little bit of tooling (if we could figure out how we'd want it to work).
