### ISSUE TITLE
Unable to ssh into the microVM

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker#988]
I want to ssh into the microVM by using its ip. Currently, I was switching terminals and entering the username and password to login to the VM. I want to run more than one instance and would like to automate the creation via a script and it would really help if i can do ssh instead of switching terminals.

Also, how to generate the id_rsa key for the VMs to enable ssh.

**Comment by acatangiu** [comment]
@Anjali05 You can definitely SSH into microVMs as long as you correctly configure your network topology and the SSH server(s) on the microVM(s).

You can find some example scripts that set up many microVMs at https://github.com/firecracker-microvm/firecracker-demo

A tutorial on how to create SSH keys can be found here: https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2

This is how you can mount a `disk image file` on the host to set things up on the `guest disk` without doing it directly in the guest: https://www.cyberciti.biz/tips/how-to-mount-iso-image-under-linux.html

**Comment by Anjali05** [comment]
@acatangiu  I was able to get up networking by doing the following steps:

On Host:
sudo ip tuntap add tap0 mode tap # user $(id -u) group $(id -g)
sudo ip addr add 172.17.100.1/24 dev tap0
sudo ip link set tap0 up
sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
sudo iptables -t nat -A POSTROUTING -o $WIRELESS_DEVICE_NAME -j MASQUERADE
sudo iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i tap0 -o $WIRELESS_DEVICE_NAME -j ACCEPT


curl -X PUT \
  --unix-socket /tmp/firecracker.socket \
  http://localhost/network-interfaces/enp1s0f0 \
  -H accept:application/json \
  -H content-type:application/json \
  -d '{
      "iface_id": "enp1s0f0",
      "guest_mac": "AA:FC:00:00:00:01",
      "host_dev_name": "tap0"
    }'

On the microVM
ip addr add 172.17.100.10/24 dev eth0
ifconfig eth0 up
ip route add default via 172.17.100.1 dev eth0
ping 1.1.1.1 -c 3

After that I logged into the VM and generated the private/public key using ssh-keygen and copied it on the host. I rebooted the microVM and re-launched. I tried getting the ip using:

root@node-0:~# ifconfig tap0 | grep "inet"
        inet 172.17.100.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::7847:c5ff:feb6:544b  prefixlen 64  scopeid 0x20<link>

I tried logging into the microVM using the key I generated earlier  but I am getting permission denied.
root@node-0:~# ssh -i hello-rootfs.id_rsa root@172.17.100.1
root@172.17.100.1: Permission denied (publickey).

My future goal is to launch multiple microVMs and do some measurement for my research work so according to my understanding the same key should work on all the microVMs as the filesystem image is the same. I do not know if I am missing something here.

Thanks,
Anjali

**Comment by acatangiu** [comment]
@Anjali05 
> I tried logging into the microVM using the key I generated earlier but I am getting permission denied.
root@node-0:~# ssh -i hello-rootfs.id_rsa root@172.17.100.1
root@172.17.100.1: Permission denied (publickey).

You need to ssh connect to the *guest ip* and not the *host tap ip*. Try running:
```
ssh -i hello-rootfs.id_rsa root@172.17.100.10
```
for your particular config.

**Comment by Anjali05** [comment]
@acatangiu Its giving me, connection refused error:

root@node-0:~# ssh -i hello-rootfs.id_rsa root@172.17.100.10
ssh: connect to host 172.17.100.10 port 22: Connection refused

**Comment by Anjali05** [comment]
@acatangiu Also, it would really help if you could add a documentation for ssh-ing into the microVM for one as well as multiple instances as a follow up in the networking guide. I tried getting up networking using the guide but my host's ip was not static and could not get it up immediately. So adding that as well to the network setup guide would help.

**Comment by ustiugov** [comment]
@acatangiu I am also trying to setup ssh access to a microVM. I configure the host and the guest according to the provided manual and I can ping the guest from the host and vice versa. However, I cannot start `sshd` service because `networking` service can't be (re)started. I have the following error:
```
localhost:~# /etc/init.d/networking restart                                                                                                 
 * Starting networking ...
 *   eth0 ...
sh: invalid number ''                                                                                                                       
sh: invalid number ''                  
sh: invalid number ''                                                                                                                       
sh: invalid number ''     
ifconfig: SIOCSIFNETMASK: Address not available
run-parts: /etc/network/if-up.d/firecracker-tap: exit status 1            [ !! ]
 * ERROR: networking failed to start    
```
Then, I added loopback configuration in /etc/network/interfaces but still can't restart networking
```localhost:~# /etc/init.d/networking restart                                     
 * Starting networking ...                                                                                                                     
 *   eth0 ...           
RTNETLINK answers: File exists
RTNETLINK answers: File exists                                            [ !! ]
 * ERROR: networking failed to start            
```

I think the hello-world image is broken.

**Comment by Anjali05** [comment]
@ustiugov How did you setup networking? I am not able to ping also.

**Comment by ustiugov** [comment]
@Anjali05 
> The microVM is able to ping the host but not vice versa.
I would suggest checking the IP addresses you ping from the host and guest, and make sure they are different from the tap IP (as it was pointed in one of the comments above).
In your setting (according to what you wrote above), guest should be able to ping host by 172.17.100.1 and host to ping guest by 172.17.100.10
Hope it helps.

**Comment by ustiugov** [comment]
@Anjali05 
Before the hello-world image will get updated, it seems to me that the best way to set up networking is described and suggested [issue#711](https://github.com/firecracker-microvm/firecracker/issues/711).

In brief, use firecracker-demo's rootfs with the following steps:
* Set up DNS in `/etc/resolv.conf` in guest. (don't forget to change the scripts to boot rootfs in the read-write mode)
* Set up IP forwarding in host.

As a result, you will be able to ssh both ways, just need to install ssh on guest.

**Comment by Anjali05** [comment]
@ustiugov Did you use the xenial.rootfs.id_rsa which is there in the demo-repository?

**Comment by Anjali05** [comment]
@ustiugov Thanks! I am able to ssh. My only concern is since it is a demo image, I do not know if its good enough(or stable enough) for running the tests.

**Comment by ustiugov** [comment]
Glad that it helped 👍

**Comment by acatangiu** [comment]
@Anjali05 The demo image is stable enough to run the demo tests, if you plan to run things in production you should definitely build your own rootfs image.

Another thing specific to the demo is that the main disk (rootfs) is used in read-only mode to be shared across multiple instances, thus some of your errors were coming from the fact that you were trying to write configurations on the read-only drive and of course those failed.

I'm glad that you managed to get SSH connectivity in the end. Closing this issue now, please reopen if you run into further problems.

**Comment by ustiugov** [comment]
@acatangiu Just one more question. What would be the tool of choice to build custom images? Would QEMU-related tools (e.g., guestfs-tools) work? for example, if I need to resize the disk image.

**Comment by acatangiu** [comment]
I'm not familiar with the QEMU-related tools, but I'm expecting they should work fine. We haven't seen the need to use tooling yet since we didn't have to build heavy rootfs. They can be built manually or using a simple script. Example: http://www.hotmcu.com/wiki/How_to_make_a_customize_ubuntu_rootfs_image

**Comment by Anjali05** [comment]
@acatangiu Is there a way to bring up networking without logging into the guest VM without running these steps:
ip addr add 172.17.100.10/24 dev eth0
ifconfig eth0 up
ip route add default via 172.17.100.1 dev eth0

I mean is it possible to bring up networking via the init.d/networking by specifying to run these steps on startup. So instead of going into the VM and initializing it, I can directly ssh.

**Comment by ustiugov** [comment]
@Anjali05 I suggest you take a look at the following script
https://github.com/firecracker-microvm/firecracker-demo/blob/master/start-firecracker.sh

**Comment by aghecenco** [comment]
@Anjali05 see https://github.com/firecracker-microvm/firecracker/issues/711#issuecomment-472958512

**Comment by Anjali05** [comment]
@ustiugov @aghecenco Thanks, I will try it.

**Comment by Anjali05** [comment]
@ustiugov 
Have you tried re-sizing the image?

**Comment by ustiugov** [comment]
Hi, I used this tool for the demo firecracker image.
https://linux.die.net/man/8/resize2fs


On Mar 22, 2019, at 8:06 PM, Anjali <notifications@github.com<mailto:notifications@github.com>> wrote:


@ustiugov<https://github.com/ustiugov>
Have you tried re-sizing the image?

**Comment by Anjali05** [comment]
> @Anjali05
> Before the hello-world image will get updated, it seems to me that the best way to set up networking is described and suggested [issue#711](https://github.com/firecracker-microvm/firecracker/issues/711).
> 
> In brief, use firecracker-demo's rootfs with the following steps:
> 
>     * Set up DNS in `/etc/resolv.conf` in guest. (don't forget to change the scripts to boot rootfs in the read-write mode)
> 
>     * Set up IP forwarding in host.
> 
> 
> As a result, you will be able to ssh both ways, just need to install ssh on guest.

Can you share the content of your `/etc/resolv.conf` in the guest? When I try to ping google.com, I get bad address.

Thanks
